force-app/main/default/objects/Account_Portfolio_Assignment__c/Account_Portfolio_Assignment__c.object-meta.xml
<CustomObject>
    <label>Account Portfolio Assignment</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Account Portfolio Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPortfolioAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Portfolio_Assignment__c/fields/BSF_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>BSF_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BSF Portfolio</label>
    <referenceTo>BSF_Portfolio__c</referenceTo>
    <relationshipLabel>AccountPortfolioAssignments</relationshipLabel>
    <relationshipName>AccountPortfolioAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Portfolio_Assignment__c/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <formula>IF( ISPICKVAL( BSF_Portfolio__r.Portfolio_Type__c , &#39;DSVP&#39;) ,  BSF_Portfolio__r.Portfolio_Name__c ,IF( ISPICKVAL(  BSF_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c , &#39;DSVP&#39;),  BSF_Portfolio__r.Parent_Portfolio__r.Portfolio_Name__c 
,IF( ISPICKVAL( BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c , &#39;DSVP&#39;),  BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Name__c , 
IF(  ISPICKVAL( BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c , &#39;DSVP&#39;), BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Name__c , 
IF(  ISPICKVAL( BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c , &#39;DSVP&#39;), BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Name__c , &#39;&#39; )) ) ))</formula>
    <label>Division Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Portfolio_Assignment__c/fields/Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Type__c</fullName>
    <formula>IF( ISPICKVAL(BSF_Portfolio__r.Taxonomy_Type__c, &#39;Bio Recruitment CD&#39;),&#39;Territory Based&#39;, &#39;Account Based&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio_Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Portfolio_Assignment__c/fields/Taxonomy_Type__c.field-meta.xml
<CustomField>
    <fullName>Taxonomy_Type__c</fullName>
    <formula>TEXT(BSF_Portfolio__r.Taxonomy_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxonomy Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Portfolio_Assignment__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <formula>IF(ISPICKVAL(BSF_Portfolio__r.Portfolio_Type__c ,&#39;District Manager&#39;), BSF_Portfolio__r.Portfolio_Name__c ,
IF( ISPICKVAL( BSF_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c , &#39;District Manager&#39;), BSF_Portfolio__r.Parent_Portfolio__r.Portfolio_Name__c, 
IF( ISPICKVAL( BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c , &#39;District Manager&#39;), BSF_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__r.Portfolio_Name__c , &#39;&#39; )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/BSF_Portfolio__c.object-meta.xml
<CustomObject>
    <label>BSF Portfolio</label>
    <nameField>
        <label>BSF Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSFPortfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Account_Based_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Account_Based_Portfolio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Based Portfolio</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <description>This field holds the unique key of each portfolio that includes parent keys appended.</description>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Parent_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Parent_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Portfolio</label>
    <referenceTo>BSF_Portfolio__c</referenceTo>
    <relationshipLabel>BSFPortfolios</relationshipLabel>
    <relationshipName>BSFPortfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/fields/Portfolio_Name__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Name__c</fullName>
    <label>Portfolio Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/fields/Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Type__c</fullName>
    <label>Portfolio Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Portfolio_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Taxonomy_Type__c.field-meta.xml
<CustomField>
    <fullName>Taxonomy_Type__c</fullName>
    <label>Taxonomy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bio Recruitment CD</fullName>
            </value>
            <value>
                <fullName>Bio Collection BSF</fullName>
            </value>
            <value>
                <fullName>Bio Account Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Fixed Sites</fullName>
            </value>
            <value>
                <fullName>Bio Sickle Cell Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Relationship Manager Portfolio</fullName>
            </value>
            <value>
                <fullName>National Account Manager Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Recruitment Supervisor</fullName>
            </value>
            <value>
                <fullName>Bio Booking Support</fullName>
            </value>
            <value>
                <fullName>Account Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/fields/Territory_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Territory_Portfolio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Territory Portfolio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portfolio_Assignment__c/Portfolio_Assignment__c.object-meta.xml
<CustomObject>
    <label>Portfolio Assignment</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Portfolio Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PortfolioAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Assignment__c/fields/BSF_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>BSF_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BSF Portfolio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BSF_Portfolio__c.Portfolio_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assignment_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BSF_Portfolio__c</referenceTo>
    <relationshipLabel>PortfolioAssignments</relationshipLabel>
    <relationshipName>PortfolioAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Portfolio_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PortfolioAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/Taxonomy__c.object-meta.xml
<CustomObject>
    <description>Taxonomy data from GOATS is imported in this object</description>
    <label>Taxonomy</label>
    <nameField>
        <displayFormat>TAX-{0000000000}</displayFormat>
        <label>Taxonomy</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxonomies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy__c/fields/ABM_Code__c.field-meta.xml
<CustomField>
    <fullName>ABM_Code__c</fullName>
    <label>ABM Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/ABM_Name__c.field-meta.xml
<CustomField>
    <fullName>ABM_Name__c</fullName>
    <label>ABM Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Collection_Operation_Code__c.field-meta.xml
<CustomField>
    <fullName>Collection_Operation_Code__c</fullName>
    <label>Collection Operation Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Collection_Operation_Name__c.field-meta.xml
<CustomField>
    <fullName>Collection_Operation_Name__c</fullName>
    <label>Collection Operation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/District_Code__c.field-meta.xml
<CustomField>
    <fullName>District_Code__c</fullName>
    <label>District Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/District_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Name__c</fullName>
    <label>District Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Code__c.field-meta.xml
<CustomField>
    <fullName>Division_Code__c</fullName>
    <label>Division Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Key__c.field-meta.xml
<CustomField>
    <fullName>Division_Key__c</fullName>
    <label>Division Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <label>Division Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DRD_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Code__c</fullName>
    <label>DRD Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DRD_Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Key__c</fullName>
    <label>DRD Territory Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/DRD_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Name__c</fullName>
    <label>DRD Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/DS_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Code__c</fullName>
    <label>DS Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DS_Region_Key__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Key__c</fullName>
    <label>DS Region Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DS_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Name__c</fullName>
    <label>DS Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <label>Portfolio Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Supervisor_Code__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Code__c</fullName>
    <label>Supervisor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Supervisor_Name__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Name__c</fullName>
    <label>Supervisor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Code__c.field-meta.xml
<CustomField>
    <fullName>Team_Code__c</fullName>
    <label>Team Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Key__c.field-meta.xml
<CustomField>
    <fullName>Team_Key__c</fullName>
    <label>Team Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Type_Key__c.field-meta.xml
<CustomField>
    <fullName>Type_Key__c</fullName>
    <label>Type Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Portfolio_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Account Portfolio</fullName>
    </customValue>
    <customValue>
        <fullName>Account Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Area Booking Manager</fullName>
        <label>Strategic Business Planning Manager</label>
    </customValue>
    <customValue>
        <fullName>Collection Operation</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRICT</fullName>
    </customValue>
    <customValue>
        <fullName>District Manager</fullName>
    </customValue>
    <customValue>
        <fullName>DSVP</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>National Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Power Booker</fullName>
    </customValue>
    <customValue>
        <fullName>RDSE</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sickle Cell Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Support</fullName>
    </customValue>
    <masterLabel>Portfolio Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/UpdateRMLookUpOnAccountDailyBatch_Test.cls
@isTest
public class UpdateRMLookUpOnAccountDailyBatch_Test 
{
    @testSetup
    public static void testSetup()
    {
        List<Taxonomy__c> taxonomies = PortfolioTestDataFactory.createTaxonomies('48420','48421');
        insert taxonomies;
        
        String firstName = 'User';
        String LastName = '1';
        
        Profile drdProfile = [SELECT Id FROM Profile WHERE Name='DRD Profile']; 
        
        
        User user1 = new User(Alias = firstName, FirstName = firstName, Email=firstName+'.'+lastName+'@test.com',EmailEncodingKey='UTF-8', LastName=lastName, LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = drdProfile.id, TimeZoneSidKey='America/Los_Angeles', UserName=firstName+'.'+lastName+'@test.com.tst1');
        
        
        insert user1;
        
        User u =[select id from user limit 1];
        
        List<Taxonomy__c> taxoList = [SELECT Division_Code__c,Division_Key__c,Division_Name__c,DRD_Territory_Code__c,DRD_Territory_Key__c,DRD_Territory_Name__c,DS_Region_Code__c,DS_Region_Key__c,DS_Region_Name__c,
                                      Team_Code__c,Team_Key__c,Team_Name__c,ABM_Code__c,ABM_Name__c,Type_Key__c,Type__c,Start_Date__c,End_Date__c,
                                      RecordType.Name,District_Code__c,District_Name__c,Collection_Operation_Code__c,Collection_Operation_Name__c,Supervisor_Code__c,Supervisor_Name__c,Portfolio_Code__c,Portfolio_Name__c
                                      FROM Taxonomy__c WHERE RecordType.Name != :BSF_Constants.BIO_COLLECTION_RECORD_TYPE]; 
        TriggerHandler.bypass('BsfPortfolioTriggerHandler');
        BSFPortfolioHelper portfolioHelper = new BSFPortfolioHelper();
        portfolioHelper.createOrUpdatePortfolio(taxoList);
        TriggerHandler.clearBypass('BsfPortfolioTriggerHandler');
        
        List<BSF_Portfolio__c> portfolios = [Select Id,Name,Portfolio_Code__c , Portfolio_Name__c ,Taxonomy_Type__c,Portfolio_Type__c,External_Key__c,Parent_Portfolio__c,Parent_Portfolio__r.Portfolio_Type__c,Account_Based_Portfolio__c,Territory_Portfolio__c  FROM BSF_Portfolio__c];
        
        Portfolio_assignment__c portfolioAssign = new Portfolio_assignment__c();
        for(BSF_Portfolio__c portfolio:portfolios)
        {
            if(portfolio.Portfolio_Type__c == BSF_Constants.RELATIONSHIP_MANAGER)
            {
                portfolioAssign.BSF_Portfolio__c=portfolio.id;
                portfolioAssign.User__c=u.Id;
                portfolioAssign.Assignment_Type__c=portfolio.Portfolio_Type__c;
                portfolioAssign.Start_Date__c=system.today();
                portfolioAssign.End_Date__c=system.today()+365;
            }
        }
        insert portfolioAssign;
        
        Map <String,Schema.RecordTypeInfo> recordTypesAccount = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        Id mobileRecTypeId = recordTypesAccount.get('Mobile Account').getRecordTypeId();    
        List<Account> accList = new List<Account>();        
        Account acc = new Account(
            name = 'Test Account 1',
            RecordTypeId = MobileRecTypeId,
            BillingStreet = '2204 Westcrt ln, Apt 213', 
            BillingCity = 'Herndon',
            BillingStateCode = 'MI',
            BillingPostalCode = '48421'
        );
        
        Account acc1 = new Account(
            name = 'Test Account 2',
            RecordTypeId = MobileRecTypeId,
            BillingStreet = '2204 Westcrt ln, Apt 213', 
            BillingCity = 'Herndon',
            BillingStateCode = 'MI',
            BillingPostalCode = '48421'
        );
        
        accList.add(acc);
        accList.add(acc1);
        insert accList;
    }
    
    @isTest
    public static void ScheduleClass_Test()
    {
        Test.StartTest();
		UpdateRMOnAccountDailyBatchScheduler testsche = new UpdateRMOnAccountDailyBatchScheduler(200);
		String sch = '0 0 23 * * ?';
		system.schedule('Test schedule class', sch, testsche );
		Test.stopTest();
        
        CronTrigger contrg = [select Id,CronJobDetailId,CronJobDetail.Name from CronTrigger where CronJobDetail.Name = 'Test schedule class'];
        system.assert(contrg.CronJobDetail.Name == 'Test schedule class');
    }
    @isTest
    public static void testMethod1()
    {
        Test.startTest();
        
        BSF_Portfolio__c bsfPortfolio = [Select Id  FROM BSF_Portfolio__c where Portfolio_Type__c =:BSF_Constants.RELATIONSHIP_MANAGER];
        List<Account> acountsList =[select id from account];
        
        List<Account_Portfolio_Assignment__c> apaList = new List<Account_Portfolio_Assignment__c>();
        for(account ac:acountsList)
        {
            Account_Portfolio_Assignment__c apa = new Account_Portfolio_Assignment__c();
            apa.Account__c = ac.id;
            apa.BSF_Portfolio__c = bsfPortfolio.id;
            apa.Start_Date__c = system.today();
            apa.End_Date__c = system.today()+365;
            apaList.add(apa);    
        }
        
        insert apaList;
        
        
        UpdateRMLookUpOnAccountDailyBatch batch = new UpdateRMLookUpOnAccountDailyBatch();
        Database.executeBatch(batch);
        Test.stopTest();            
        
        List<Account> updatedAccount = [Select Relationship_Manager__c from account where Relationship_Manager__c != null];
        system.debug('updatedAccount: '+updatedAccount);
        system.assertNotEquals(null,updatedAccount[0].Relationship_Manager__c);
    }
}