force-app/main/default/objects/Account_Portfolio_Assignment__c/Account_Portfolio_Assignment__c.object-meta.xml
<CustomObject>
    <label>Account Portfolio Assignment</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Account Portfolio Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPortfolioAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Portfolio_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountPortfolioAssignments</relationshipLabel>
    <relationshipName>AccountPortfolioAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Portfolio_Assignment__c/fields/BSF_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>BSF_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BSF Portfolio</label>
    <referenceTo>BSF_Portfolio__c</referenceTo>
    <relationshipLabel>AccountPortfolioAssignments</relationshipLabel>
    <relationshipName>AccountPortfolioAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Portfolio_Assignment__c/fields/Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Type__c</fullName>
    <formula>IF( ISPICKVAL(BSF_Portfolio__r.Taxonomy_Type__c, &#39;Bio Recruitment CD&#39;),&#39;Territory Based&#39;, &#39;Account Based&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portfolio_Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Portfolio_Assignment__c/fields/Taxonomy_Type__c.field-meta.xml
<CustomField>
    <fullName>Taxonomy_Type__c</fullName>
    <formula>TEXT(BSF_Portfolio__r.Taxonomy_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxonomy Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/BSF_Portfolio__c.object-meta.xml
<CustomObject>
    <label>BSF Portfolio</label>
    <nameField>
        <label>BSF Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSFPortfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Account_Based_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Account_Based_Portfolio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Based Portfolio</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Parent_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Parent_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Portfolio</label>
    <referenceTo>BSF_Portfolio__c</referenceTo>
    <relationshipLabel>BSFPortfolios</relationshipLabel>
    <relationshipName>BSFPortfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/fields/Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Type__c</fullName>
    <label>Portfolio Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Portfolio_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Taxonomy_Type__c.field-meta.xml
<CustomField>
    <fullName>Taxonomy_Type__c</fullName>
    <label>Taxonomy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bio Recruitment CD</fullName>
            </value>
            <value>
                <fullName>Bio Collection BSF</fullName>
            </value>
            <value>
                <fullName>Bio Account Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Fixed Sites</fullName>
            </value>
            <value>
                <fullName>Bio Sickle Cell Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Relationship Manager Portfolio</fullName>
            </value>
            <value>
                <fullName>National Account Manager Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Recruitment Supervisor</fullName>
            </value>
            <value>
                <fullName>Bio Booking Support</fullName>
            </value>
            <value>
                <fullName>Account Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/fields/Territory_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Territory_Portfolio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Territory Portfolio</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Portfolio_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Account Portfolio</fullName>
    </customValue>
    <customValue>
        <fullName>Account Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Area Booking Manager</fullName>
        <label>Strategic Business Planning Manager</label>
    </customValue>
    <customValue>
        <fullName>Collection Operation</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRICT</fullName>
    </customValue>
    <customValue>
        <fullName>District Manager</fullName>
    </customValue>
    <customValue>
        <fullName>DSVP</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>National Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Power Booker</fullName>
    </customValue>
    <customValue>
        <fullName>RDSE</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sickle Cell Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Support</fullName>
    </customValue>
    <masterLabel>Portfolio Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CreateDefaultTerritoryPortfolioBatch.cls
//This batch is created as part of HRP-4619
global class CreateDefaultTerritoryPortfolioBatch implements Database.Batchable<sObject>,Database.Stateful{
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String AMRole = 'Account Manager'; 
        Date today = Date.today();
        Date yesterday = today.addDays(-1);
        List<String> reqTaxonomyList = new List<String>{BSF_Constants.BIO_RECRUITMENT_RECORD_TYPE,BSF_Constants.TAXO_ACCOUNT_RECORD_TYPE};
        String query = 'SELECT Id,Account__c,Start_Date__c,End_Date__c,Portfolio_Type__c,BSF_Portfolio__c,BSF_Portfolio__r.Account_Based_Portfolio__c,'+
                       'BSF_Portfolio__r.Territory_Portfolio__c,BSF_Portfolio__r.Portfolio_Type__c,Bsf_Portfolio__r.Parent_Portfolio__c,'+
                       'Bsf_Portfolio__r.Parent_Portfolio__r.Parent_Portfolio__c,Bsf_Portfolio__r.Parent_Portfolio__r.Portfolio_Type__c,'+
                       'Bsf_Portfolio__r.Portfolio_Code__c,BSF_Portfolio__r.Taxonomy_Type__c'+
                       ' FROM Account_Portfolio_Assignment__c WHERE (start_Date__c =:today OR start_Date__c =:yesterday OR End_date__c =:today)'+
                       ' AND BSF_Portfolio__r.Portfolio_Type__c =:AMRole AND (BSF_Portfolio__r.Account_Based_Portfolio__c = TRUE OR BSF_Portfolio__r.Territory_Portfolio__c = true)'+
                       ' AND BSF_Portfolio__r.Taxonomy_Type__c IN:reqTaxonomyList';
    	return Database.getQueryLocator(query);	
    }
    global void execute(Database.BatchableContext BC,List<Account_Portfolio_Assignment__c> accPortfolioList){
        DefaultTerritoryPortfolioBatchHelper.createDefaultTerritoryPortfolioRecords(accPortfolioList);
    }
    global void finish(Database.BatchableContext bc){
        
    }
}