unpackaged/main/default/objects/BSF_Error_Log__c/BSF_Error_Log__c.object-meta.xml
<CustomObject>
    <label>BSF Error Log</label>
    <nameField>
        <displayFormat>BEL-{0000000000}</displayFormat>
        <label>BSF Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSF Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Quantity__c.field-meta.xml
<CustomField>
    <fullName>sked__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_VPHH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>sked_VPHH_Quantity__c</fullName>
    <label>VPHH Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/Average_Staff_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Average_Staff_Capacity__c</fullName>
    <label>Average Staff Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/Excess_Staff_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Excess_Staff_Capacity__c</fullName>
    <label>Excess Staff Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Operation_Type__c</fullName>
    <formula>TEXT(sked_Drive_Site__r.Operation_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Operation Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Projected_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>sked_Projected_Registered_Donors__c</fullName>
    <label>Projected Registered Donors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Staff_Capacity__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Capacity__c</fullName>
    <label>Staff Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>System Generated</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Pending Action</fullName>
                <isActive>false</isActive>
                <label>Pending Action</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_APT_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_APT_Setup__c</fullName>
    <label>APT Setup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Staff_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Setup__c</fullName>
    <label>Staff Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/sked_Resource_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC Sign-off</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - 2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Charge Mentor</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Competent Driver</fullName>
    </customValue>
    <customValue>
        <fullName>CT1</fullName>
    </customValue>
    <customValue>
        <fullName>Drive Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL B</fullName>
    </customValue>
    <customValue>
        <fullName>Driver - DOT</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Prestaff</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Tech Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>FS Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>HH</fullName>
    </customValue>
    <customValue>
        <fullName>Licensed Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Limited HH</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Ship</fullName>
    </customValue>
    <customValue>
        <fullName>NCE Staff</fullName>
    </customValue>
    <customValue>
        <fullName>OJI</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <customValue>
        <fullName>Post Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screeners</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - RNOR</fullName>
    </customValue>
    <customValue>
        <fullName>Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>VP/HH</fullName>
    </customValue>
    <masterLabel>Resource Roles</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AverageStaffCapAndExcesSCCorrectionBatch.cls
Global class AverageStaffCapAndExcesSCCorrectionBatch implements Database.Batchable<sObject>, Database.Stateful{
    /*

	AverageStaffCapAndExcesSCCorrectionBatch batchObject = new AverageStaffCapAndExcesSCCorrectionBatch();
    Database.executeBatch(batchObject,200);

    Set<Id> driveId = new Set<Id>{''};
    AverageStaffCapAndExcesSCCorrectionBatch batchObject = new AverageStaffCapAndExcesSCCorrectionBatch(driveId);
    Database.executeBatch(batchObject,200);

    
    Date toDate = Date.newInstance(2024,01,01);
    Date fromDate = Date.newInstance(2024,09,23);
    
    AverageStaffCapAndExcesSCCorrectionBatch batchObject = new AverageStaffCapAndExcesSCCorrectionBatch(toDate, fromDate);
    Database.executeBatch(batchObject,200);

   */
    String query;
    Set<Id> driveId;
    Date toDate; 
    Date fromDate;
    
    public AverageStaffCapAndExcesSCCorrectionBatch(){
        this.query = 'Select Id, sked_Drive_Date__c, Average_Staff_Capacity__c,  Excess_Staff_Capacity__c, sked_Staff_Capacity__c, sked_Projected_Registered_Donors__c from sked_Drive__c where sked_Drive_Date__c >= Today AND sked_Status__c Not IN (\'Cancel\',\'Complete\') AND (sked_Operation_Type__c = \'Non Integrated WB\' or sked_Type_of_Drive__c = \'Mobile\')';
    }

    public AverageStaffCapAndExcesSCCorrectionBatch(Set<Id> driveId){
        this.driveId = driveId;
        this.query = 'Select Id, sked_Drive_Date__c, Average_Staff_Capacity__c,  Excess_Staff_Capacity__c, sked_Staff_Capacity__c, sked_Projected_Registered_Donors__c from sked_Drive__c where sked_Drive_Date__c >= Today AND sked_Status__c Not IN (\'Cancel\',\'Complete\') AND (sked_Operation_Type__c = \'Non Integrated WB\' or sked_Type_of_Drive__c = \'Mobile\') AND Id IN: driveId';
    }

    public AverageStaffCapAndExcesSCCorrectionBatch(Date toDate, Date fromDate){
        this.toDate = toDate;
        this.fromDate = fromDate;
        
        this.query = 'Select Id, sked_Drive_Date__c, Average_Staff_Capacity__c,  Excess_Staff_Capacity__c, sked_Staff_Capacity__c, sked_Projected_Registered_Donors__c from sked_Drive__c where sked_Drive_Date__c >= :toDate AND sked_Drive_Date__c <= :fromDate AND sked_Drive_Date__c >= Today AND sked_Status__c Not IN (\'Cancel\',\'Complete\') AND (sked_Operation_Type__c = \'Non Integrated WB\' or sked_Type_of_Drive__c = \'Mobile\')';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {   
        return Database.getQueryLocator(this.query);        
    }
    global void execute(Database.BatchableContext BC, List<sked_Drive__c> driveList){
        Set<Id> toGetDriveAgain = new Set<Id>();
        
        for(sked_Drive__c drive : driveList){
            toGetDriveAgain.add(drive.Id);
        }
        
        List<sked_Drive_Shift__c> driveShiftList = [Select Id, sked_Staff_Setup__c, sked_APT_Setup__c, sked_Drive__c, sked_Drive_Date__c, sked_Drive__r.Average_Staff_Capacity__c, sked_Drive__r.Excess_Staff_Capacity__c, sked_Drive__r.sked_Staff_Capacity__c, sked_Drive__r.sked_Projected_Registered_Donors__c from sked_Drive_Shift__c where sked_Drive__c IN: toGetDriveAgain];

        Map<Id,List<sked_Drive_Shift__c>> driveIdVsDriveShiftListMap = new Map<Id, List<sked_Drive_Shift__c>>();
        Set<Id> driveShiftIdSet = new Set<Id>();
        List<sked_Drive__c> driveToUpdate = new List<sked_Drive__c>();
        Boolean isUpdate = false;
        Set<String> staffQuantityNeededFor = new Set<String>{'Driver', 'Driver Support', '2RBC', 'VP/HH', 'Charge'};

        for(sked_Drive_Shift__c driveShift : driveShiftList){
            driveShiftIdSet.add(driveShift.Id);
            if(!driveIdVsDriveShiftListMap.containskey(driveShift.sked_Drive__c)){
                driveIdVsDriveShiftListMap.put(driveShift.sked_Drive__c, new List<sked_Drive_Shift__c>());
            }
            driveIdVsDriveShiftListMap.get(driveShift.sked_Drive__c).add(driveShift);
        }

        List<sked__Job__c> jobs = [SELECT Id, sked_Resource_Role__c, sked__Quantity__c, sked_VPHH_Quantity__c, sked_Drive_Shift__c FROM sked__Job__c where sked_Drive_Shift__c IN : driveShiftIdSet AND sked_Resource_Role__c IN: staffQuantityNeededFor];
        
        Map<Id,List<sked__Job__c>> driveShiftIdVsJobsListMap = new Map<Id, List<sked__Job__c>>();

        for(sked__Job__c job : jobs){
            if(!driveShiftIdVsJobsListMap.containskey(job.sked_Drive_Shift__c)){
                driveShiftIdVsJobsListMap.put(job.sked_Drive_Shift__c, new List<sked__Job__c>());
            }
            driveShiftIdVsJobsListMap.get(job.sked_Drive_Shift__c).add(job);
        }

        for(Id driveId : driveIdVsDriveShiftListMap.keySet()){
            isUpdate = false;
            Decimal curruntAverageStaffCapacity = 0;
            Decimal curruntExcessStaffCapacity = 0;
            Decimal updatedAverageStaffCapacity = 0;
            Decimal updatedExcessStaffCapacity = 0;
            Decimal driveStaffCapacity = 0;
            Decimal totalStaffRequested = 0;
            Decimal projectedRegisteredDonors = 0;
            if(driveIdVsDriveShiftListMap.get(driveId) != NULL){
                for(sked_Drive_Shift__c driveShift : driveIdVsDriveShiftListMap.get(driveId)){
                    driveStaffCapacity = driveShift.sked_Drive__r.sked_Staff_Capacity__c;
                    curruntAverageStaffCapacity = driveShift.sked_Drive__r.Average_Staff_Capacity__c;
                    curruntExcessStaffCapacity = driveShift.sked_Drive__r.Excess_Staff_Capacity__c;
                    projectedRegisteredDonors = driveShift.sked_Drive__r.sked_Projected_Registered_Donors__c;
                    Decimal driveShiftStaffCount = 0;
                    if(driveShiftIdVsJobsListMap.get(driveShift.Id) != NULL){
                        for(sked__Job__c job : driveShiftIdVsJobsListMap.get(driveShift.Id)){
                            if (!string.isBlank(job.sked_Resource_Role__c) && (staffQuantityNeededFor.contains(job.sked_Resource_Role__c))) {
                                if (job.sked_Resource_Role__c == 'VP/HH') {
                                    driveShiftStaffCount += job.sked_VPHH_Quantity__c;
                                } else {
                                    driveShiftStaffCount += job.sked__Quantity__c;
                                }
                            }
                        }
                    }
                    
                    totalStaffRequested = totalStaffRequested + driveShiftStaffCount;
                }
            }
            

            updatedAverageStaffCapacity = (totalStaffRequested == NULL || totalStaffRequested == 0) ? 0 : (driveStaffCapacity / totalStaffRequested).setScale(1, System.RoundingMode.HALF_UP);
            updatedExcessStaffCapacity = (updatedAverageStaffCapacity == NULL || updatedAverageStaffCapacity == 0) ? 0 : ((driveStaffCapacity - projectedRegisteredDonors) / updatedAverageStaffCapacity).setScale(1, System.RoundingMode.HALF_UP);
            sked_Drive__c drive = new sked_Drive__c();
            if(curruntAverageStaffCapacity != updatedAverageStaffCapacity){
                isUpdate = true;
                drive.Id = driveId;
                drive.Average_Staff_Capacity__c = updatedAverageStaffCapacity;
            }
            if(curruntExcessStaffCapacity != updatedExcessStaffCapacity){
                isUpdate = true;
                drive.Id = driveId;
                drive.Excess_Staff_Capacity__c = updatedExcessStaffCapacity;
            }
            if(isUpdate){
                driveToUpdate.add(drive);
                isUpdate = false;
            }
        }
        
        List<BSF_Error_Log__c> errorList = new List<BSF_Error_Log__c>();
        if(driveToUpdate.size()>0){
            // datebase.update(driveToUpdate,false);
            Database.SaveResult[] driveToUpdateList = Database.update(driveToUpdate,false);
            errorList.addAll(BSF_Utilities.createErrorLog(driveToUpdateList,'AverageStaffCapAndExcesSCCorrectionBatch','AverageStaffCapAndExcesSCCorrectionBatch','execute','Error','Update Failed'));
        }
        
    }
    global void finish(Database.BatchableContext bc){
        
    }
}