unpackaged/main/default/objects/BSF_Error_Log__c/BSF_Error_Log__c.object-meta.xml
<CustomObject>
    <label>BSF Error Log</label>
    <nameField>
        <displayFormat>BEL-{0000000000}</displayFormat>
        <label>BSF Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSF Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BSF_Error_Log__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>ApexClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Error_Log__c/fields/Error_Description_Long__c.field-meta.xml
<CustomField>
    <fullName>Error_Description_Long__c</fullName>
    <label>Error Description Long</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BSF_Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create Portfolio</fullName>
            </value>
            <value>
                <fullName>Assign Account to Portfolio</fullName>
            </value>
            <value>
                <fullName>Populate Account Team</fullName>
            </value>
            <value>
                <fullName>Create Oppty Team</fullName>
            </value>
            <value>
                <fullName>Run Logs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Debug Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job_Tag__c/sked__Job_Tag__c.object-meta.xml
<CustomObject>
    <label>Job Tag</label>
    <nameField>
        <displayFormat>JT_{0}</displayFormat>
        <label>JobTag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Tag__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipName>JobTags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Tag__c/fields/sked__Required__c.field-meta.xml
<CustomField>
    <fullName>sked__Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Job_Tag__c/fields/sked__Tag__c.field-meta.xml
<CustomField>
    <fullName>sked__Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>sked__Tag__c</referenceTo>
    <relationshipName>JobTags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Tag__c/sked__Tag__c.object-meta.xml
<CustomObject>
    <description>string metadata to be associated  with any other object</description>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Account__c.field-meta.xml
<CustomField>
    <fullName>sked_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RemoveDuplicateTagFromJob.cls
global class RemoveDuplicateTagFromJob implements Database.Batchable<sObject>,Database.Stateful{
    Date startDate;
    Date endDate;
    Integer limitOfRecord;
    Set<Id> jobIdSet = new Set<Id>();
    global RemoveDuplicateTagFromJob(Date startDate, Date endDate, Set<Id> jobIdSet, integer limitOfRecord){
        this.startDate = startDate;
    	this.endDate = endDate;
    	this.jobIdSet = jobIdSet;
    	this.limitOfRecord = limitOfRecord;
    }  
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = '';
        if(this.startDate != null && this.endDate != null){
            query = createJobQueryConditionDriveDate();
        }
        if(jobIdSet != null && !jobIdSet.isEmpty()){
            query = createJobQueryConditionJobIdSet();
        }
       return Database.getQueryLocator(query);
        
    }
    global void execute(Database.BatchableContext BC, List<sked__Job__c> jobss){
        set<Id> jobIdSets = new set<Id>();
        for(sked__Job__c job : jobss){
            jobIdSets.add(job.Id);
        }
        List<sked__Job__c> jobs = [Select id, sked_Drive__c, sked_Drive__r.sked_Account__c , sked_Drive__r.sked_Drive_Site__c , (Select Id, sked__Job__c,sked__Job__r.sked_Drive__c, sked__Tag__c, sked__Tag__r.Name, sked__Required__c, Name from sked__JobTags__r) from sked__Job__c where Id in: jobIdSets];
        Map<String,List<sked__Job_Tag__c>> jobVsJobTagList = new Map<String,List<sked__Job_Tag__c>>();
        
        For(sked__Job__c job : jobs){
            
            Map<String,List<sked__Job_Tag__c>> duplicateTagNameVsTagIds = new Map<String,List<sked__Job_Tag__c>>();
            
            for (sked__Job_Tag__c jobTag : job.sked__jobTags__r) {
                if(jobTag != null){
                    if(!duplicateTagNameVsTagIds.containsKey(jobTag.sked__Tag__r.Name)){
                        duplicateTagNameVsTagIds.put(jobTag.sked__Tag__r.Name,new List<sked__Job_Tag__c>());
                    }
                    duplicateTagNameVsTagIds.get(jobTag.sked__Tag__r.Name).add(jobTag);
                }
            }
            for (String tagName : duplicateTagNameVsTagIds.keySet()) {
                if(duplicateTagNameVsTagIds.get(tagName).size() > 1){
                    //jobVsJobTagList.put(job.Id,duplicateTagNameVsTagIds.get(tagName));
                    if(jobVsJobTagList.get(job.Id) != null){
                        jobVsJobTagList.get(job.Id).addAll(duplicateTagNameVsTagIds.get(tagName));
                    } else {
                        jobVsJobTagList.put(job.Id,duplicateTagNameVsTagIds.get(tagName));
                    }
                }
            }
        }
        
        Map<Id,sked__Job_Tag__c> tagToBeDeleted = new Map<Id,sked__Job_Tag__c>();
        for (Id jobId : jobVsJobTagList.keySet()) {
            Map<Id,sked__Job_Tag__c> uniqueTag = new Map<Id,sked__Job_Tag__c>();
            for(sked__Job_Tag__c jobTag : jobVsJobTagList.get(jobId)){
                if(uniqueTag.containsKey(jobTag.sked__Tag__c)){
                    tagToBeDeleted.put(jobTag.Id,jobTag);
                } else{
                    uniqueTag.put(jobTag.sked__Tag__c,jobTag);
                }
            }
        }
        if(!tagToBeDeleted.isEmpty()){
            system.debug('tagToBeDeleted :: '+tagToBeDeleted);
            Database.delete(tagToBeDeleted.values(),false);
            BSF_Error_Log__c errorLog = new BSF_Error_Log__c(Process_Name__c = '', ApexClass__c = 'RemoveDuplicateTag', Method__c ='Batch Execute', Type__c='', Error_Description__c = 'error',Error_Description_Long__c = String.join(new List<Id>(tagToBeDeleted.keySet()),';'));
            Insert errorLog;
        }
    }
    global void finish(Database.BatchableContext bc){
        System.debug('duplicate job tag is deleted');
    }
    
    private static String createJobQueryConditionDriveDate () {
        string jobQuery = 'Select id, sked_Drive__c, sked_Drive__r.sked_Account__c , sked_Drive__r.sked_Drive_Site__c from sked__Job__c where sked_Drive__r.sked_drive_date__c >=: startDate AND sked_Drive__r.sked_drive_date__c <=: endDate';
    	return jobQuery;
    }
    private static String createJobQueryConditionJobIdSet () {
        string jobQuery = 'Select id, sked_Drive__c, sked_Drive__r.sked_Account__c , sked_Drive__r.sked_Drive_Site__c from sked__Job__c where Id in : jobIdSet';
    	return jobQuery;
    }
}