unpackaged/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Manager of the related Account</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blood_Drive_Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_End_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_End_Time_Field__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_Start_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_Start_Time_Field__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 6 AND (3 OR 4 OR 5)</booleanFilter>
        <errorMessage>Only Templates related to the same Account are eligible and related site must be active.</errorMessage>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Is_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Drive_Site__r.sked_End_Date__c</field>
            <operation>greaterThan</operation>
            <valueField>$Source.Drive_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Cancelled</value>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Withdrawn</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Template_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select the Template for this Opportunity. Only Templates related to the same Account are eligible to be selected.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Mobile_Opp.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Opp</fullName>
    <active>true</active>
    <businessProcess>Blood Drive Sales Process</businessProcess>
    <label>Mobile Opp</label>
</RecordType>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestOneTimeFlowTimeFieldUpdateBatch.cls
@isTest(SeeAllData = false)
private class TestOneTimeFlowTimeFieldUpdateBatch {

    @testSetup
    static void prepateTestData() {
        skedHubBase.BypassInsertTriggers = true;
        skedHubBase.BypassUpdateTriggers = true;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('ContactTriggerHandler');
        TriggerHandler.bypass('UserTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        //insert DRD User
        User testDrdUser = (User)mapTestData.get('DRD_USER');
        testDrdUser.Email = 'DRDUser@test.com.invalid';
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert testDrdUser;
        }
        
        //insert account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c =  'Test Account';
        testMobileAccount.BillingPostalCode = '30146';
        testMobileAccount.Phone = '1234567890' ;
        testMobileAccount.Type = 'Business';
        testMobileAccount.Account_Manager__c = testDrdUser.Id;
        insert testMobileAccount;
        
        //insert contact
        Contact testContact = (Contact)mapTestData.get('CONTACT');
        testContact.AccountId = testMobileAccount.Id ;
        insert testContact;
        
        // insert Mobile Site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite;
        
        // insert templates
        Opportunity testTemplate = (Opportunity)mapTestData.get('MOBILE_TEMPLATE_OPP');
        testTemplate.AccountId = testMobileAccount.Id;
        testTemplate.Drive_Site__c = testMobileSite.Id;
        insert testTemplate;
        
        //insert mobile opportunity
        Opportunity testMobileOpp = (Opportunity)mapTestData.get('MOBILE_OPP');
        testMobileOpp.AccountId = testMobileAccount.Id;
        testMobileOpp.Drive_Site__c = testMobileSite.Id;
        testMobileOpp.Parent_Template_Id__c = testTemplate.Id;
        insert testMobileOpp;
    }
    
    @isTest static void testFlowStartTime() {
        Test.startTest();
        
        Opportunity testOpp = [SELECT Id, Flow_End_Time_Field__c FROM Opportunity WHERE Is_Template__c = false LIMIT 1];
        testOpp.Flow_Start_Time_Field__c = null;
        testOpp.Flow_End_Time_Field__c = null;
        
        TriggerHandler.bypass('OpportunityTriggerHandler');
        update testOpp;
        TriggerHandler.clearBypass('OpportunityTriggerHandler');
        
        OneTimeFlowTimeFieldUpdateBatch oneTimeFlowTimeFieldUpdateBatch = new oneTimeFlowTimeFieldUpdateBatch();
        Database.executeBatch(oneTimeFlowTimeFieldUpdateBatch);
        
        Test.stopTest();
        Opportunity testUpdatedOpp = [SELECT Id, Flow_End_Time_Field__c FROM Opportunity WHERE Id = :testOpp.Id LIMIT 1];
        Assert.isTrue(testUpdatedOpp.Flow_End_Time_Field__c != null);
        
    }
    
    @isTest static void testOneTimeEmailBatch() {
        Test.startTest();
        
        OneTimeEmailUpdateBatch OneTimeEmailUpdateBatch = new OneTimeEmailUpdateBatch();
        Database.executeBatch(OneTimeEmailUpdateBatch, 1);

        Test.stopTest();
        
        User testUser = [SELECT Id, Email FROM User WHERE Profile.Name = 'DRD Profile' AND Email LIKE 'DRDUser@test%' LIMIT 1];
        Assert.isTrue(String.valueOf(testUser.email).contains('invalid') == false); 
    }
}