unpackaged/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Accept_56_Day_Rule_Violation__c.field-meta.xml
<CustomField>
    <fullName>Accept_56_Day_Rule_Violation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate if a user has elected to create an opportunity even though it violates the 56 days rule</description>
    <label>Accept 56 Day Rule Violation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Manager of the related Account</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blood_Drive_Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Registered_Donors__c</fullName>
    <description>Numeric value that reflects the # of donors expected to be at the drive. Current based on historical drive data (like drive, how many people).</description>
    <label>Anticipated Registered Donors</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date_Change_Reason__c</fullName>
    <label>Drive Date Change Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 6 AND (3 OR 4 OR 5)</booleanFilter>
        <errorMessage>Only Templates related to the same Account are eligible and related site must be active.</errorMessage>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Is_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Drive_Site__r.sked_End_Date__c</field>
            <operation>greaterThan</operation>
            <valueField>$Source.Drive_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Cancelled</value>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Withdrawn</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Template_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select the Template for this Opportunity. Only Templates related to the same Account are eligible to be selected.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/OpportunityTeamMember/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <formula>Opportunity.Account_Manager__r.FirstName + &#39; &#39;+ Opportunity.Account_Manager__r.LastName</formula>
    <label>Account Manager</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <formula>Opportunity.Drive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Publicity_Approved__c.field-meta.xml
<CustomField>
    <fullName>Publicity_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicity Approved &amp; Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Reassignment_Matrix__mdt/Task_Reassignment_Matrix__mdt.object-meta.xml
<CustomObject>
    <label>Task Reassignment Matrix</label>
    <pluralLabel>Task Reassignment Matrixs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Task_Reassignment_Matrix__mdt/fields/Creation_Date_Offset__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date_Offset__c</fullName>
    <label>Creation Date Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BSF_Batch_CreatePublicityTasksTest.cls
/* The following class covers the below mentioned batch classes
 * BSF_Batch_CreatePublicityTasksOnOrders (Not needed)
 * BSF_Batch_CreatePublicityTasks (100%)
  
 * Modification Log 
 * Date					     Developer Name			     Comments
 * ****************************************************************************************
 * 11/01/2024				  Priti Jana				Modified for HRP-12583
 ******************************************************************************************
 */

@isTest(SeeAllData = false)
public class BSF_Batch_CreatePublicityTasksTest
{
    public static String mobileOppRecType = 'Mobile Opp';
    public static Map<String,Id> recordTypeMap  = new Map<String,Id>();
    
    @testSetup
    public static void prepareDataSetup()
    {
        TriggerHandler.Bypass('AccountTriggerHandler');
        TriggerHandler.Bypass('OpportunityTriggerHandler');
        TriggerHandler.Bypass('SiteTriggerHandler');
        
        Task_Reassignment_Matrix__mdt publicityOrder = Task_Reassignment_Matrix__mdt.getInstance('Publicity_Order_Not_Created');
    	Date dateUntil = system.today() + Integer.valueof(publicityOrder.Creation_Date_Offset__c);
        
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        // insert DRD User
        User drdUser = (User)mapTestData.get('DRD_USER');
        System.runAs( new User(Id = UserInfo.getUserId()))
        {
            insert drdUser;
        }
               
        //insert mobile account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c = 'Test Account';
        insert testMobileAccount;
        
        // insert mobile site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
    	insert testMobileSite;
        
        // insert template
        Opportunity testTemplate = (Opportunity)mapTestData.get('MOBILE_TEMPLATE_OPP');
        testTemplate.AccountId = testMobileAccount.Id;
        testTemplate.Drive_Site__c = testMobileSite.Id;
        insert testTemplate;
        
        //insert opportunity
        recordTypeMap = recordTypeMap( 'Opportunity' );
		Id optyRecTypeId = recordTypeMap.get(mobileOppRecType);
		opportunity testMobileOpp =new opportunity();
		testMobileOpp.RecordTypeId = optyRecTypeId;        
        testMobileOpp.AccountId=testMobileAccount.Id;
        testMobileOpp.name='testOpp1';
        testMobileOpp.StageName= 'Closed';
        testMobileOpp.Parent_Template_Id__c=testTemplate.id;
        testMobileOpp.CloseDate= system.today().addDays(1); 
        testMobileOpp.Drive_Date__c = dateUntil;
        testMobileOpp.Accept_56_Day_Rule_Violation__c = true;
        testMobileOpp.Account_Manager__c = UserInfo.getUserId();
        testMobileOpp.Start_Time__c = System.now().Time();
		testMobileOpp.End_Time__c = System.now().Time()+1;
		testMobileOpp.Anticipated_Registered_Donors__c = 1;	
        insert testMobileOpp;
        
        // insert team member
        OpportunityTeamMember oppTeammember = new OpportunityTeamMember(OpportunityId = testMobileOpp.Id, 
                                                                        Start_Date__c = system.today(), 
                                                                        TeamMemberRole = 'District Manager',
                                                                        OpportunityAccessLevel = 'Edit',
                                                                        UserId = drdUser.Id);
        insert oppTeammember;
        
    }
    
    static testMethod void testBatchToCreateTasksForNoOrders() {
        Test.startTest();
        //BSF_Batch_CreatePublicityTasksOnOrders batchable = new BSF_Batch_CreatePublicityTasksOnOrders();
        
        BSF_Batch_CreatePublicityTasks batchable = new BSF_Batch_CreatePublicityTasks();
        Database.executeBatch(batchable);
        Test.stopTest();
        
        Integer createdTasksCount = [SELECT count() FROM Task WHERE Subject = 'Publicity Order Not Created'];
        Assert.isTrue(createdTasksCount == 1);
    }
    
    static testMethod void testBatchToCreateTasksForReview() {
        Test.startTest();
        Task_Reassignment_Matrix__mdt publicityReview = Task_Reassignment_Matrix__mdt.getInstance('Publicity_Review_Needed');
        
        Account testMobileAccount = [SELECT Id FROM Account LIMIT 1];
        Opportunity testMobileOpp = [SELECT Id, Drive_Date__c, Drive_Date_Change_Reason__c FROM Opportunity WHERE Is_Template__c = FALSE LIMIT 1];
        testMobileOpp.Drive_Date__c = system.today().addDays(Integer.valueof(publicityReview.Creation_Date_Offset__c));
        testMobileOpp.Drive_Date_Change_Reason__c = 'TEST';
        TriggerHandler.bypass('OpportunityTriggerHandler');
        update testMobileOpp;
        TriggerHandler.clearAllBypasses();
        
         //insert orders
        List<Order> orderList = new List<Order>();
        
        Order testOrder;
        testOrder = new Order(EffectiveDate = system.today() , 
                                    Description = 'Test Order 1', 
                                    Publicity_Approved__c = false , 
                                    Status = 'Draft',
                                   	AccountId = testMobileAccount.Id,
                                   	OpportunityId = testMobileOpp.Id);
        
        orderList.add(testOrder);
        
        testOrder = new Order(EffectiveDate = system.today() , 
                                    Description = 'Test Order 2', 
                                    Publicity_Approved__c = false , 
                                    Status = 'Draft',
                                   	AccountId = testMobileAccount.Id,
                                   	OpportunityId = testMobileOpp.Id);
        
        orderList.add(testOrder);        
        insert orderList;
        
        //BSF_Batch_CreatePublicityTasksOnOrders batchable = new BSF_Batch_CreatePublicityTasksOnOrders();
        
        BSF_Batch_CreatePublicityTasks batchable = new BSF_Batch_CreatePublicityTasks();
        Database.executeBatch(batchable);
        Test.stopTest();
        
        Integer createdTasksCount = [SELECT count() FROM Task WHERE Subject = 'Publicity Review Needed'];
        Assert.isTrue(createdTasksCount == 2);
    }
    
    static testMethod void testBatchNotToCreateDuplicateTasks() {
        Test.startTest();
        Opportunity testMobileOpp = [SELECT Id, Drive_Date__c, Drive_Date_Change_Reason__c FROM Opportunity WHERE Is_Template__c = FALSE LIMIT 1];
        
        //insert Tasks
        List<Task> oppTasks = new List<Task>();
        Task t;
        t = new Task(
            subject = 'Publicity Review Needed', 
            Status = 'Not Started',
            Priority = 'High',
            WhatId = testMobileOpp.Id, 
            OwnerId = userInfo.getUserId()
        );
        oppTasks.add(t);
        
        t = new Task(
            subject = 'Publicity Order Not Created', 
            Status = 'Not Started',
            Priority = 'High',
            WhatId = testMobileOpp.Id, 
            OwnerId = userInfo.getUserId()
        );
        oppTasks.add(t);
        
        insert oppTasks;
        
        //BSF_Batch_CreatePublicityTasksOnOrders batchable = new BSF_Batch_CreatePublicityTasksOnOrders();
        BSF_Batch_CreatePublicityTasks batchable = new BSF_Batch_CreatePublicityTasks();
        Database.executeBatch(batchable);
        
        Integer taskCount = [SELECT Count() FROM Task];
        Assert.isTrue(taskCount == 2); // duplicate tasks didn't get created
        Test.stopTest();
    }
    
    static testMethod void testScheduleBatch() {
        Test.startTest();
        BSF_Batch_CreatePublicityTasks batchable = new BSF_Batch_CreatePublicityTasks();
        SchedulableContext scon;
        batchable.execute(scon);
        Test.stopTest();
    }

    //Method to get the map of recordType Name as key and recordTypeId as value 
    public static Map<String,Id> recordTypeMap(string obj) {
        Map<String,Id> recTypeNameWithIdMap = new Map<String,Id>();
        if(obj!= null)
        {
            for(Schema.RecordTypeInfo recInfo : Schema.getGlobalDescribe().get(obj).getDescribe().getRecordTypeInfosByName().values()){
                recTypeNameWithIdMap.put(recInfo.getName(),recInfo.getRecordTypeId());
            }
        }
        return recTypeNameWithIdMap;
    }

}