unpackaged/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Manager of the related Account</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blood_Drive_Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Registered_Donors__c</fullName>
    <description>Numeric value that reflects the # of donors expected to be at the drive. Current based on historical drive data (like drive, how many people).</description>
    <label>Anticipated Registered Donors</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_End_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_End_Time_Field__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>1530</fullName>
                <label>3:30 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_Start_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_Start_Time_Field__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>1530</fullName>
                <label>3:30 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Online_Scheduling_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Online_Scheduling_Enabled__c</fullName>
    <label>Online Scheduling Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Whole Blood Procedures Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>X2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Double Red Procedures Projected</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Reassignment_Matrix__mdt/Task_Reassignment_Matrix__mdt.object-meta.xml
<CustomObject>
    <label>Task Reassignment Matrix</label>
    <pluralLabel>Task Reassignment Matrixs</pluralLabel>
</CustomObject>

force-app/main/default/classes/BSF_BatchTaskSyncTest.cls
@isTest
public class BSF_BatchTaskSyncTest {
    @isTest static void Test(){
        
User AdminUser = new User(
             ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
             LastName = 'last',
             Email = 'puser000@amamama.com',
             Username = 'adminuser000@amamama.com' + System.currentTimeMillis(),
             CompanyName = 'TEST',
             Title = 'title',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US'
             
        );    
        insert AdminUser;
        //List<Account> mobileAccList = new List<Account>();       
        Account accobj = new Account();
        accobj.Name = 'Exavalu';
        accobj.Type = 'Business';
        accobj.Internal_Name__c='test';
        insert accobj;
        //List<Opportunity> opplist = new List<Opportunity>();
        Opportunity optyObj = new Opportunity();
        optyObj.Name = 'Test Drive 1';
        optyObj.StageName = 'Discovery';
        optyObj.Drive_Date__c = System.Today()-1;
        optyObj.CloseDate= System.Today()-2;
        optyObj.AccountId=accobj.id;
        optyObj.Account_Manager__c=AdminUser.Id;
        optyObj.Start_Time__c = Time.newInstance(10, 0, 0, 0);
        optyObj.End_Time__c = Time.newInstance(15, 30, 0, 0);
        optyObj.Flow_Start_Time_Field__c = '1000';
        optyObj.Flow_End_Time_Field__c = '1530';
        optyObj.WB_Projected_Procedures__c = 4;
        optyObj.X2RBC_Projected_Procedures__c = 2;
        optyObj.Anticipated_Registered_Donors__c = 25;
        optyObj.Online_Scheduling_Enabled__c = 'No';
            
            insert optyObj;
        
        
        OpportunityTeamMember testoppteammem= new OpportunityTeamMember();
        testoppteammem.OpportunityId=optyObj.id;
        testoppteammem.UserId=AdminUser.Id;
        testoppteammem.TeamMemberRole=BSF_Constants.DISTRICT_MANAGER ;
        insert testoppteammem;
        Task testtsk = new Task();
        testtsk.WhatId=optyObj.Id;
        testtsk.Status='Not Started';
        testtsk.Subject='Recruitment Planning Meeting';//HRP-7123
        insert testtsk;
        Task testtaskDM = new Task();
        testtaskDM.WhatId=optyObj.Id;
        testtaskDM.Status='Not Started';
        testtaskDM.Subject='Request for Marketing Exception';
        insert testtaskDM;
        /*Task_Reassignment_Matrix__mdt testreassign = new Task_Reassignment_Matrix__mdt();
        testreassign.Assigned_To__c='AM'; 
        testreassign.Task_Subject__c='72 Hour Check in - Sytem Generated';
        testreassign.Label='72 Hour Check In';*/
        Test.startTest();
        BSF_BatchTaskSync taskbatch = new BSF_BatchTaskSync();
        DataBase.executeBatch(taskbatch); 
        
        Test.stopTest();
    }
    @isTest static void executeTest(){
        
        SchedulableContext sc = null;
        BSF_BatchTaskSync taskbatch = new BSF_BatchTaskSync();
        taskbatch.execute(sc);
        
    }  
}