unpackaged/main/default/objects/Account/fields/Account_AM_Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_AM_Portfolio_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account AM Portfolio Type</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/Taxonomy__c.object-meta.xml
<CustomObject>
    <description>Taxonomy data from GOATS is imported in this object</description>
    <label>Taxonomy</label>
    <nameField>
        <displayFormat>TAX-{0000000000}</displayFormat>
        <label>Taxonomy</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxonomies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy__c/fields/ABM_Code__c.field-meta.xml
<CustomField>
    <fullName>ABM_Code__c</fullName>
    <label>ABM Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/ABM_Name__c.field-meta.xml
<CustomField>
    <fullName>ABM_Name__c</fullName>
    <label>ABM Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Collection_Operation_Code__c.field-meta.xml
<CustomField>
    <fullName>Collection_Operation_Code__c</fullName>
    <label>Collection Operation Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Collection_Operation_Name__c.field-meta.xml
<CustomField>
    <fullName>Collection_Operation_Name__c</fullName>
    <label>Collection Operation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/District_Code__c.field-meta.xml
<CustomField>
    <fullName>District_Code__c</fullName>
    <label>District Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/District_Name__c.field-meta.xml
<CustomField>
    <fullName>District_Name__c</fullName>
    <label>District Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Code__c.field-meta.xml
<CustomField>
    <fullName>Division_Code__c</fullName>
    <label>Division Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Key__c.field-meta.xml
<CustomField>
    <fullName>Division_Key__c</fullName>
    <label>Division Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <label>Division Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DRD_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Code__c</fullName>
    <label>DRD Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DRD_Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Key__c</fullName>
    <label>DRD Territory Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/DRD_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Name__c</fullName>
    <label>DRD Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/DS_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Code__c</fullName>
    <label>DS Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DS_Region_Key__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Key__c</fullName>
    <label>DS Region Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DS_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Name__c</fullName>
    <label>DS Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Portfolio_Code__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Code__c</fullName>
    <label>Portfolio Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Supervisor_Code__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Code__c</fullName>
    <label>Supervisor Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Supervisor_Name__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Name__c</fullName>
    <label>Supervisor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Code__c.field-meta.xml
<CustomField>
    <fullName>Team_Code__c</fullName>
    <label>Team Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Key__c.field-meta.xml
<CustomField>
    <fullName>Team_Key__c</fullName>
    <label>Team Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Type_Key__c.field-meta.xml
<CustomField>
    <fullName>Type_Key__c</fullName>
    <label>Type Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Version_Key__c.field-meta.xml
<CustomField>
    <fullName>Version_Key__c</fullName>
    <label>Version Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BSF_Batch_AccountPortfolioAssignment_V2.cls
global class BSF_Batch_AccountPortfolioAssignment_V2 implements Database.Batchable<sObject>{
	global String bioRecruitmentRecordType;
    global Decimal taxoVerKey;
    global List<String> postalcodeList;
    
    global BSF_Batch_AccountPortfolioAssignment_V2(Decimal taxoVerKey){
      this.bioRecruitmentRecordType = BSF_Constants.BIO_RECRUITMENT_RECORD_TYPE;
      this.taxoVerKey = taxoVerKey;  
      this.postalcodeList = new List<String>(); 
   }
    
  global Database.QueryLocator start(Database.BatchableContext BC)
  {
        
     String accountQuery = 'Select Id,Name,BillingPostalCode FROM Account WHERE Account_AM_Portfolio_Type__c = FALSE';
  	
    return Database.getQueryLocator(accountQuery);
  }
 
  global void execute(Database.BatchableContext bc, List<Account> accountList)
  {
        postalcodeList.clear();
        for(Account acc:accountList){
        	postalcodeList.add(acc.BillingPostalCode);      
        }
      
        String taxonomyQuery = 'SELECT Zip_Code__c ,Start_Date__c,End_Date__c,Division_Code__c,Division_Key__c,Division_Name__c,DRD_Territory_Code__c,DRD_Territory_Key__c,DRD_Territory_Name__c,DS_Region_Code__c,DS_Region_Key__c,DS_Region_Name__c,'+
                                             ' Team_Code__c,Team_Key__c,Team_Name__c,ABM_Code__c,ABM_Name__c,Type_Key__c,Type__c,'+
                                             ' RecordType.Name,District_Code__c,District_Name__c,Collection_Operation_Code__c,Collection_Operation_Name__c,Supervisor_Code__c,Supervisor_Name__c,Portfolio_Code__c,Portfolio_Name__c '+
                                             ' FROM Taxonomy__c WHERE RecordType.Name = :bioRecruitmentRecordType  AND Version_Key__c = :taxoVerKey AND Zip_Code__c IN :postalcodeList'; 
       
        List<Taxonomy__c> taxoList = Database.query(taxonomyQuery);
        
        System.debug(' postalcodeList '+postalcodeList);
        System.debug(' taxoList '+taxoList.size());
      
		AccountPortfolioAssignmentHelper protfolioAssignmentHelper = new AccountPortfolioAssignmentHelper();
        protfolioAssignmentHelper.assignAccountToPortfolio(taxoList,accountList);
  }
    
  global void finish(Database.BatchableContext BC)
  {
       //Capture finish method entry in Error Log
  }
}