unpackaged/main/default/objects/Account/fields/District_Manager__c.field-meta.xml
<CustomField>
    <fullName>District_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/Coverage_Reason__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Reason__c</fullName>
    <description>Field to capture the vacancy reason on Account Team Member level.</description>
    <label>Coverage Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leave of Absence (LOA)</fullName>
            </value>
            <value>
                <fullName>Vacant Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Original_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Service_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Original Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DMBellNotificationATMBatchHelperTest.cls
@isTest
public class DMBellNotificationATMBatchHelperTest {
    
    static testMethod void test(){
        
        customNotificationType cn=[select id from CustomNotificationType where developername='Account_Custom_Notification'];
        
        Account a=new Account();
        a.name='account';
        a.District_Manager__c=[select id , name from user limit 1].id;
        insert a;
        
        contact c=new contact();
        c.AccountId=a.Id;
        c.FirstName='contact1';
        c.Email='abcd@gmail.com';
        c.Primary_Phone__c='Mobile Phone';
        c.Original_Service_Date__c=system.today();
        c.LastName='contact2';
        c.Phone='7474749';
        insert c;
        
        List<User> userList=new List<User>();
        User u=new User();
        u.LastName='user123';
        u.FirstName='user222';
        u.Username='john@acme5.com';
        u.Email='abc@gmail34.com';
        u.Alias='alias';
        u.TimeZoneSidKey='America/New_York';
        u.LocaleSidKey='en_US';
        u.EmailEncodingKey='ISO-8859-1';
        u.ProfileId='00eo0000000rmqFAAQ';
        u.LanguageLocaleKey ='en_US';
        userList.add(u);
        insert u;
        List<User> ListUser=[select id,name from user limit 1];
        
       List<AccountTeamMember> atmList=new List<AccountTeamMember>();
        AccountTeamMember atm =new AccountTeamMember(AccountAccessLevel = 'Edit',
            CaseAccessLevel = 'Edit',
            OpportunityAccessLevel = 'Edit',
            TeamMemberRole = 'Account Manager',
            Start_Date__c = System.today(),
            End_Date__c = System.today()+3,
            Coverage_Reason__c = '');
        	atm.UserId = u.Id;
            atm.AccountId = a.Id;
        	atmList.add(atm);
        	 BSF_Constants.isTeamMemberCreatedFromBackend = true;
        	insert atmList;
            BSF_Constants.isTeamMemberCreatedFromBackend = false;
        Test.startTest();
        DMBellNotificationATMExpiryBatchSchedule amExpBellNotificationSch = new DMBellNotificationATMExpiryBatchSchedule(100);
		System.schedule('Notify DM 4 AM Expiry Batch1', '0 30 0 * * ?', amExpBellNotificationSch );
        
        
        DMBellNotificationForATMExpiryBatch ba= new DMBellNotificationForATMExpiryBatch();
        Id jobid= Database.executeBatch(ba,5);
        DMBellNotificationATMExpiryBatchHelper.SendBellNotificationToDM(atmList);
        Test.stopTest();
    }
}