unpackaged/main/default/objects/Account/fields/District_Manager__c.field-meta.xml
<CustomField>
    <fullName>District_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/sked_Fixed_Site_Procedure_Projection__c.object-meta.xml
<CustomObject>
    <label>Fixed Site Procedure Projection</label>
    <nameField>
        <displayFormat>FSPP-{000000}</displayFormat>
        <label>Fixed Site Procedure Projection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fixed Site Procedure Projections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Account__c.field-meta.xml
<CustomField>
    <fullName>sked_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fixed Site Procedure Projections</relationshipLabel>
    <relationshipName>sked_Fixed_Site_Procedure_Projections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Deferral__c.field-meta.xml
<CustomField>
    <fullName>sked_Deferral__c</fullName>
    <label>Deferral %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Procedure_Type__c</fullName>
    <label>Procedure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Fixed_Site_Procedure_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Productive_Procedure_Goal__c.field-meta.xml
<CustomField>
    <fullName>sked_Productive_Procedure_Goal__c</fullName>
    <label>Productive Procedure Goal</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_QNS__c.field-meta.xml
<CustomField>
    <fullName>sked_QNS__c</fullName>
    <label>QNS %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Fixed_Site_Procedure_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>WB</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Platelet</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <masterLabel>Fixed Site Procedure Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/skedFsppHandler_Test.cls
@isTest
private class skedFsppHandler_Test {
    
    static testmethod void mainTest() {
        Account testAccount1 = new Account(
            Name = 'Test Account',
            Internal_Name__c = 'Test Internal Name',
            District_Manager__c = UserInfo.getUserId()
        );
        insert testAccount1;
        
        sked_Fixed_Site_Procedure_Projection__c fspp = new sked_Fixed_Site_Procedure_Projection__c(
            sked_Account__c = testAccount1.Id,
            sked_Deferral__c = 5,
            sked_QNS__c = 5,
            sked_Productive_Procedure_Goal__c = 10,
            sked_Procedure_Type__c = '2RBC',
            sked_Effective_Start_Date__c = system.today().addDays(-14),
            sked_Effective_End_Date__c = system.today().addDays(14)
        );
        insert fspp;
        
        Test.startTest();
        
        fspp.sked_Productive_Procedure_Goal__c = fspp.sked_Productive_Procedure_Goal__c + 1;
        update fspp;
        
        Test.stopTest();
    }

}