unpackaged/main/default/objects/Account/fields/IsPremierCurrent__c.field-meta.xml
<CustomField>
    <fullName>IsPremierCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Premier Current</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IsPumpedItUpCurrent__c.field-meta.xml
<CustomField>
    <fullName>IsPumpedItUpCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Pumped It Up Current</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Marketing_Program__c/Account_Marketing_Program__c.object-meta.xml
<CustomObject>
    <label>Account Affiliation</label>
    <nameField>
        <displayFormat>AMP-{000000}</displayFormat>
        <label>Account Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Marketing_Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Marketing_Program</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Marketing_Program__c/fields/Account_Affiliation_External_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Affiliation_External_Key__c</fullName>
    <externalId>true</externalId>
    <label>Account Affiliation External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account_Marketing_Program__c/fields/Date_Removed__c.field-meta.xml
<CustomField>
    <fullName>Date_Removed__c</fullName>
    <label>Date Removed</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account_Marketing_Program__c/fields/Marketing_Program__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Program__c</fullName>
    <label>Marketing Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Marketing_Program__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Marketing_Program__c</referenceTo>
    <relationshipLabel>Account Affiliations</relationshipLabel>
    <relationshipName>Account_Marketing_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Marketing_Program__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Marketing_Program__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Program__c/Marketing_Program__c.object-meta.xml
<CustomObject>
    <description>replaces Hemasphere marketing affiliations for drives</description>
    <label>Affiliation</label>
    <nameField>
        <label>Affiliation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Marketing_Program__c/fields/Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>Drive_Type__c</fullName>
    <label>Drive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
                <default>true</default>
                <label>Mobile</label>
            </value>
            <value>
                <fullName>Fixed Site</fullName>
                <isActive>false</isActive>
                <label>Fixed Site</label>
            </value>
            <value>
                <fullName>RSMO</fullName>
                <isActive>false</isActive>
                <label>RSMO</label>
            </value>
            <value>
                <fullName>Site Only</fullName>
                <isActive>false</isActive>
                <label>Site Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Program__c/fields/External_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Name__c</fullName>
    <label>External Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Marketing_Program__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>was Hemasphere Type</description>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountBatchOnRecognitionTest.cls
/***********************************************************************************************************
 * Modification Log:    
 * --------------------------------------------------------------------------------------------------------
 * Date         Author                 Description                              Covering Class Name
 * 10/17/23     Ankit Kundu         The batch implemented based on HRP-11077.   AccountBatchOnRecognition
 *
 **********************************************************************************************************/
@isTest
private class AccountBatchOnRecognitionTest {
    static testMethod void testBatch(){
           
        
        List<Account> accList = new List<Account>();
        Account acc = new account(name='testAccount',IsPumpedItUpCurrent__c = true);
        Account acc1 = new account(name='testAccount1',IsPremierCurrent__c = true);
        accList.add(acc);
        accList.add(acc1);
        insert accList; 
        
        Id RccognitionId = Schema.SObjectType.Marketing_Program__c.getRecordTypeInfosByName().get('Sponsor Recognition').getRecordTypeId();
        list<Marketing_Program__c> mpclist = new list<Marketing_Program__c>();
        //HRP-11077 Start->
        Marketing_Program__c mp = new Marketing_Program__c(Name = label.Premier_Bonus_Prior, Start_Date__c=system.today(),End_Date__c=system.today()+5,
                            Scope__c = 'account' ,
                            RecordTypeId=RccognitionId,Drive_Type__c = 'N/A',External_Name__c = 'Test Account Marketing Program');
        mpclist.add(mp);
        Marketing_Program__c mp1 = new Marketing_Program__c(Name = label.PremierPrior, Start_Date__c=system.today(),End_Date__c=system.today()+5,
                                    Scope__c = 'account',
                                    RecordTypeId=RccognitionId,Drive_Type__c = 'N/A',External_Name__c = 'Test Account Marketing Program1');
        mpclist.add(mp1);
        Marketing_Program__c mp2 = new Marketing_Program__c(Name = label.Premier_Bonus_Current, 
                                            Scope__c = 'account' ,Start_Date__c=system.today(),End_Date__c=system.today()+5,
                                            RecordTypeId=RccognitionId,Drive_Type__c = 'N/A',External_Name__c = 'Test Account Marketing Program');
        mpclist.add(mp2);
        Marketing_Program__c mp3 = new Marketing_Program__c(Name = label.PremierCurrent, 
                                    Scope__c = 'account',Start_Date__c=system.today(),End_Date__c=system.today()+5,
                                    RecordTypeId=RccognitionId,Drive_Type__c = 'N/A',External_Name__c = 'Test Account Marketing Program1');
        mpclist.add(mp3);
        
        
        Marketing_Program__c mp4 = new Marketing_Program__c(Name = label.PremierPrior, 
                                    Scope__c = 'account',Start_Date__c=system.today(),End_Date__c=system.today()+5,
                                    RecordTypeId=RccognitionId,Drive_Type__c = 'N/A',External_Name__c = 'Test Account Marketing Program1');
        mpclist.add(mp4);
        
        insert mpclist;
       // <-End [HRP-11077]
        
        List<Account_Marketing_Program__c> newAmpList = new List<Account_Marketing_Program__c>();
       Account_Marketing_Program__c amp = new Account_Marketing_Program__c();
        amp.Account__c =acc.Id;
        amp.Date_Assigned__c=system.today().adddays(-50);
        amp.Date_Removed__c=system.today()+5;
        amp.Account_Affiliation_External_Key__c=String.valueOf(System.now()+100);
        amp.Marketing_Program__c = mp2.Id;
        newAmpList.add(amp);
        Account_Marketing_Program__c amp1 = new Account_Marketing_Program__c();
        amp1.Account__c =acc1.Id;
        amp1.Date_Assigned__c=system.today();
        amp.Date_Removed__c=system.today()+5;
        amp.Account_Affiliation_External_Key__c=String.valueOf(System.now()+200);   
        amp1.Marketing_Program__c = mp3.Id;
        newAmpList.add(amp1);
        /*Account_Marketing_Program__c amp2 = new Account_Marketing_Program__c();
        amp2.Account__c=acc.Id;
        amp2.Marketing_Program__c=mp.Id;
        newAmpList.add(amp2);
        Account_Marketing_Program__c amp3 = new Account_Marketing_Program__c();
        amp2.Account__c=acc1.Id;
        amp2.Marketing_Program__c=mp1.Id;
        newAmpList.add(amp3);*/
        insert newAmpList;
        
      
        AccountBatchOnRecognitionScheduler acctSponsorRecognSch = new AccountBatchOnRecognitionScheduler(100);
		System.schedule('Update Account Sponsor Recognition Batch1', '0 0 21 * * ?', acctSponsorRecognSch );
        
        AccountBatchOnRecognition test = new AccountBatchOnRecognition();
        Id jobid=Database.executeBatch(test,5);
        
         List<Account_Marketing_Program__c> updatedRecords = [SELECT Id FROM Account_Marketing_Program__c WHERE Account__c = :acc.Id];
        Assert.areEqual(1, updatedRecords.size(), 'Record should be updated/deleted/inserted');
        
        
    }
}