force-app/main/default/objects/sked_Drive_Shift_Trade__c/sked_Drive_Shift_Trade__c.object-meta.xml
<CustomObject>
    <label>Drive Shift Trade</label>
    <nameField>
        <displayFormat>DST-{000000}</displayFormat>
        <label>Drive Shift Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drive Shift Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive_Shift_Trade__c/fields/sked_Requesting_Staff_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Requesting_Staff_Drive_Date__c</fullName>
    <label>Requesting Staff Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift_Trade__c/fields/sked_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Trading Staff Acknowledge</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Waiting for Requesting Staff Acknowledge</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/skedExpireStaffTradeEvents_Test.cls
@isTest
private class skedExpireStaffTradeEvents_Test {
    @isTest
    private static void skedExpireStaffTradeEvents_Test() {
        sked_Drive_Shift_Trade__c dst1 = new sked_Drive_Shift_Trade__c(
            sked_Status__c = 'Submitted',
            sked_Requesting_Staff_Drive_Date__c = System.today().addDays(5)
        );
        
        sked_Drive_Shift_Trade__c dst2 = new sked_Drive_Shift_Trade__c(
            sked_Status__c = 'Submitted',
            sked_Requesting_Staff_Drive_Date__c = System.today().addDays(-5)
        );
        insert new List<SObject>{dst1, dst2};
            
        Test.startTest();
        
        skedExpireStaffTradeEventsSchedulable schedulable = new skedExpireStaffTradeEventsSchedulable();
        String chron = '0 0 23 * * ?'; 
        System.schedule('Test schedulable' + Math.random(), chron, schedulable);
        
        Test.stopTest();
    }
}