force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Collection_Op_Staging_Location__c/sked_Collection_Op_Staging_Location__c.object-meta.xml
<CustomObject>
    <label>Collection Operation Staging Location</label>
    <nameField>
        <displayFormat>COSL-{0000}</displayFormat>
        <label>Collection Operation Staging Location Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Operation Staging Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Collection_Op_Staging_Location__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Collection Operation Staging Locations</relationshipLabel>
    <relationshipName>sked_Collection_Op_Staging_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Collection_Op_Staging_Location__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Collection_Op_Staging_Location__c/fields/sked_Staging_Location__c.field-meta.xml
<CustomField>
    <fullName>sked_Staging_Location__c</fullName>
    <label>Staging Location</label>
    <referenceTo>sked_Staging_Location__c</referenceTo>
    <relationshipLabel>Collection Operation Staging Locations</relationshipLabel>
    <relationshipName>sked_Collection_Op_Staging_Locations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Staging_Location__c.field-meta.xml
<CustomField>
    <fullName>sked_Staging_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Location</label>
    <referenceTo>sked_Staging_Location__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>Drives_on_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Staging_Location__c/sked_Staging_Location__c.object-meta.xml
<CustomObject>
    <label>Staging Location</label>
    <nameField>
        <label>Staging Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/skedPopulateStagingLocForDrivesBatch.cls
public class skedPopulateStagingLocForDrivesBatch implements Database.Batchable<SObject> {

    public skedPopulateStagingLocForDrivesBatch() {}

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([
            SELECT Id, sked_Collection_Operation__c, sked_Drive_Date__c
            FROM sked_Drive__c
            WHERE sked_Staging_Location__c = NULL
            AND sked_Collection_Operation__c != NULL
        ]);
     }
  
    public void execute(Database.BatchableContext BC, List<SObject> scope){
        List<sked_Drive__c> drives = (List<sked_Drive__c>) scope;
        
        Set<Id> coIds = new Set<Id>();
        for (sked_Drive__c drive : drives) {
            coIds.add(drive.sked_Collection_Operation__c);
        }

        Map<Id, Biomed_Collection_Op_Center__c> coById = new Map<Id, Biomed_Collection_Op_Center__c>([
            SELECT Id, Name,
            (SELECT Id, sked_Start_Date__c, sked_End_Date__c, sked_Staging_Location__c FROM sked_Collection_Op_Staging_Locations__r)
            FROM Biomed_Collection_Op_Center__c
            WHERE Id IN :coIds
        ]);

        for (sked_Drive__c drive : drives) { 
            Biomed_Collection_Op_Center__c co = coById.get(drive.sked_Collection_Operation__c);

            if (co != null && co.sked_Collection_Op_Staging_Locations__r != null && !co.sked_Collection_Op_Staging_Locations__r.isEmpty()) {
                for (sked_Collection_Op_Staging_Location__c cosl : co.sked_Collection_Op_Staging_Locations__r) {
                    if (drive.sked_Drive_Date__c >= cosl.sked_Start_Date__c && drive.sked_Drive_Date__c <= cosl.sked_End_Date__c) {
                        drive.sked_Staging_Location__c = cosl.sked_Staging_Location__c;
                    }
                }
            }
        }

        skedHubBase.BypassUpdateTriggers = true;
        update drives;
        skedHubBase.BypassUpdateTriggers = false;
    }
  
    public void finish(Database.BatchableContext BC) {}
}