force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_MigrationID__c.field-meta.xml
<CustomField>
    <fullName>sked_MigrationID__c</fullName>
    <externalId>true</externalId>
    <label>MigrationID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Travel_Time2__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time2__c</fullName>
    <label>Travel Time 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time__c</fullName>
    <label>Travel Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>sked_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <defaultValue>IF(
AND(MONTH(TODAY()) = 2, DAY(TODAY()) = 29),
DATE(YEAR(TODAY())+ 50, 3, 1),
DATE(YEAR(TODAY()) + 50, MONTH(TODAY()), DAY(TODAY()))
)</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Travel_Time_Breakdown_JSON_2__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_Breakdown_JSON_2__c</fullName>
    <description>Site to CO</description>
    <label>Travel Time Breakdown JSON 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Travel_Time_Breakdown_JSON__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_Breakdown_JSON__c</fullName>
    <description>CO to Site</description>
    <label>Travel Time Breakdown JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <label>Location</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Site_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>.</description>
    <label>Site Collection Operation</label>
    <referenceTo>sked_Site_Collection_Operation__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Resource_Role_Group__c/sked_Resource_Role_Group__c.object-meta.xml
<CustomObject>
    <label>Resource Role Group</label>
    <nameField>
        <displayFormat>RRGS-{0000}</displayFormat>
        <label>Resource Role Group Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Role Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Resource_Role_Group__c/fields/sked_Resource_Role_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role_Group__c</fullName>
    <label>Resource Role Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Role_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/sked_Role_Time_Detail__c.object-meta.xml
<CustomObject>
    <label>Role Time Detail</label>
    <nameField>
        <displayFormat>RTD-{000000}</displayFormat>
        <label>Role Time Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Time Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Role Time Details</relationshipLabel>
    <relationshipName>sked_Role_Time_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Type__c</fullName>
    <label>Drive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Mobile_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Mobile_Type__c</fullName>
    <label>Mobile Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked_Drive_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
            <value>
                <fullName>Inside/Outside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Resource_Role_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role_Group__c</fullName>
    <label>Resource Role Group</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Role_Group</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Collection Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/sked_Site_Collection_Operation__c.object-meta.xml
<CustomObject>
    <label>Site Collection Operation</label>
    <nameField>
        <displayFormat>SCO-{000000}</displayFormat>
        <label>Site Collection Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Collection Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Site Collection Operations</relationshipLabel>
    <relationshipName>sked_Site_Collection_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Site__c</fullName>
    <label>Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Site Collection Operations</relationshipLabel>
    <relationshipName>sked_Site_Collection_Operations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Travel_Time_Breakdown_JSON_2__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_Breakdown_JSON_2__c</fullName>
    <inlineHelpText>Travel Time from Site</inlineHelpText>
    <label>Travel Time Breakdown JSON 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Travel_Time_Breakdown_JSON__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_Breakdown_JSON__c</fullName>
    <inlineHelpText>Travel Time to Site</inlineHelpText>
    <label>Travel Time Breakdown JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Resource_Role_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Driving roles</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisory roles</fullName>
    </customValue>
    <customValue>
        <fullName>Staff roles</fullName>
    </customValue>
    <masterLabel>Resource Role Group</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Resource_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC Sign-off</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - 2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Charge Mentor</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Competent Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Drive Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL A</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL B</fullName>
    </customValue>
    <customValue>
        <fullName>Driver - DOT</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Prestaff</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Tech Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Float</fullName>
    </customValue>
    <customValue>
        <fullName>FS Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>HH</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Donor Ambassador</fullName>
    </customValue>
    <customValue>
        <fullName>Licensed Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Limited HH</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Ship</fullName>
    </customValue>
    <customValue>
        <fullName>NCE Staff</fullName>
    </customValue>
    <customValue>
        <fullName>OJI</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <customValue>
        <fullName>Post Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screeners</fullName>
    </customValue>
    <masterLabel>Resource Roles</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/skedPostJobMigrationBatch_Test.cls
@isTest
private class skedPostJobMigrationBatch_Test {
    @isTest
    static void skedPostJobMigrationBatch_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Biomed_Collection_Op_Center__c testCollectionOp = (Biomed_Collection_Op_Center__c) mapTestData.get('testCollectionOperation1');
        sked__Region__c testRegion = (sked__Region__c) mapTestData.get('testRegion1');
        sked__Location__c testLocation = (sked__Location__c) mapTestData.get('testLocation1');
        
        List<string> weekdays = new List<string>();
        weekdays.add('sunday');
        weekdays.add('monday');
        weekdays.add('tuesday');
        weekdays.add('wednesday');
        weekdays.add('thursday');
        weekdays.add('friday');
        weekdays.add('saturday');
        
        List<string> directions = new List<string>();
        directions.add('CO to Site');
        directions.add('Site to CO');
        
        List<skedAsyncJobHandler.travelTimeBreakdownModel> models = new List<skedAsyncJobHandler.travelTimeBreakdownModel>();
        for (string direction : directions) {
            for (string weekday : weekdays) {
                skedAsyncJobHandler.travelTimeBreakdownModel model = new skedAsyncJobHandler.travelTimeBreakdownModel();
                model.siteId = testLocation.Id;
                model.weekday = weekday;
                model.endOfWindow = Time.newInstance(23, 59, 0, 0);
                model.startOfWindow = Time.newInstance(0, 0, 0, 0);
                model.direction = direction;
                model.travelDistance = 5;
                model.travelTime = 30;
                models.add(model);
            }
        }

        Test.startTest();
        sked_Site_Collection_Operation__c testSco = new sked_Site_Collection_Operation__c(
            sked_Site__c = testLocation.Id,
            sked_Collection_Operation__c = testCollectionOp.Id,
            sked_Start_Date__c = testDataFactory.summary.startDate,
            sked_End_Date__c = testDataFactory.summary.endDate,
            sked_Travel_Time_Breakdown_JSON__c = JSON.serialize(models),
            sked_Travel_Time_Breakdown_JSON_2__c = JSON.serialize(models)
        );
        insert testSco;

        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        sked__Job__c testDriveJob = new sked__Job__c(
            sked_Drive__c = testDrive.Id,
            sked__Region__c = testRegion.Id,
            sked__Start__c = System.today().addDays(5),
            sked__Finish__c = System.today().addDays(6),
            sked__Location__c = testLocation.Id,
            sked_Resource_Role__c = '2RBC',
            sked_MigrationID__c = 'migration-id',
            sked_Travel_Time__c = 45,
            sked_Travel_Time2__c = 45
        );
        sked__Job__c testDriveJob2 = new sked__Job__c(
            sked_Drive__c = testDrive.Id,
            sked__Region__c = testRegion.Id,
            sked__Start__c = System.today().addDays(5),
            sked__Finish__c = System.today().addDays(6),
            sked__Location__c = testLocation.Id,
            sked_Resource_Role__c = 'Apheresis',
            sked_MigrationID__c = 'migration-id-2',
            sked_Travel_Time__c = 45,
            sked_Travel_Time2__c = 45
        );
        insert new List<sked__Job__c>{testDriveJob, testDriveJob2};

        sked_Role_Time_Detail__c testRtd = new sked_Role_Time_Detail__c(
            sked_Effective_Start_Date__c = System.today().addDays(-100),
            sked_Effective_End_Date__c = System.today().addDays(100), 
            sked_Drive_Type__c = 'Mobile',
            sked_Mobile_Type__c = 'Outside',
            sked_Resource_Role_Group__c = 'Staff roles',
            sked_Collection_Operation__c = testCollectionOp.Id
        );

        sked_Role_Time_Detail__c testRtdGlobal = new sked_Role_Time_Detail__c(
            sked_Effective_Start_Date__c = System.today().addDays(-100),
            sked_Effective_End_Date__c = System.today().addDays(100), 
            sked_Drive_Type__c = 'Mobile',
            sked_Mobile_Type__c = 'Outside',
            sked_Resource_Role_Group__c = 'Staff roles',
            sked_Type__c = 'Global'
        );
        insert new List<sked_Role_Time_Detail__c>{testRtd, testRtdGlobal};

            Database.executeBatch(new skedPostJobMigrationBatch());
        Test.stopTest();
    }
}