force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Resource_Role_Group__c/sked_Resource_Role_Group__c.object-meta.xml
<CustomObject>
    <label>Resource Role Group</label>
    <nameField>
        <displayFormat>RRGS-{0000}</displayFormat>
        <label>Resource Role Group Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Role Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Resource_Role_Group__c/fields/sked_Resource_Role_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role_Group__c</fullName>
    <label>Resource Role Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Role_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/sked_Role_Time_Detail__c.object-meta.xml
<CustomObject>
    <label>Role Time Detail</label>
    <nameField>
        <displayFormat>RTD-{000000}</displayFormat>
        <label>Role Time Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Time Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Breakdown_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Breakdown_Time__c</fullName>
    <label>Breakdown Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Role Time Details</relationshipLabel>
    <relationshipName>sked_Role_Time_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>sked_Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_Week</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Type__c</fullName>
    <label>Drive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lead_Time__c</fullName>
    <label>Lead Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Mobile_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Mobile_Type__c</fullName>
    <label>Mobile Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked_Drive_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
            <value>
                <fullName>Inside/Outside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Resource_Role_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role_Group__c</fullName>
    <label>Resource Role Group</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Role_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Setup_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Setup_Time__c</fullName>
    <label>Setup Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Wrap_up_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Wrap_up_Time__c</fullName>
    <label>Wrap-up Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Days_of_Week.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Days of Week</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Resource_Role_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Driving roles</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisory roles</fullName>
    </customValue>
    <customValue>
        <fullName>Staff roles</fullName>
    </customValue>
    <masterLabel>Resource Role Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/skedRoleTimeDetailTrigger_Test.cls
@isTest
private class skedRoleTimeDetailTrigger_Test {

    static testmethod void mainTest() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();
        
        Biomed_Collection_Op_Center__c testCollectionOp = (Biomed_Collection_Op_Center__c) mapTestData.get('testCollectionOperation1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');

        Test.startTest();
        
        sked_Role_Time_Detail__c roleTimeDetail = new sked_Role_Time_Detail__c(
            sked_Collection_Operation__c = testCollectionOp.Id,
            sked_Effective_Start_Date__c = System.today().addDays(-10),
            sked_Effective_End_Date__c = System.today().addDays(10),
            sked_Breakdown_Time__c = 25,
            sked_Days_of_Week__c = 'Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',
            sked_Drive_Type__c = testDrive.sked_Type_of_Drive__c,
            sked_Lead_Time__c = 15,
            sked_Setup_Time__c = 15,
            sked_Wrap_up_Time__c = 15,
            sked_Mobile_Type__c = 'Inside/Outside',
            sked_Resource_Role_Group__c = 'Driving roles;Supervisory roles;Staff roles'
        );
        insert roleTimeDetail;
        
        roleTimeDetail.sked_Lead_Time__c = 30;
        update roleTimeDetail;
        
        delete roleTimeDetail;
        
        Test.stopTest();
    }
    
}