force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Regulated_Medi_Screener_Drive_Types__c.field-meta.xml
<CustomField>
    <fullName>sked_Regulated_Medi_Screener_Drive_Types__c</fullName>
    <label>Regulated Medical Screener Drive Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Fixed Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Address__c.field-meta.xml
<CustomField>
    <fullName>sked__Address__c</fullName>
    <description>Address of the job</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Job_Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Pending Allocation</fullName>
            </value>
            <value>
                <fullName>Pending Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Volunteer_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Volunteer_Role__c</fullName>
    <label>Volunteer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Volunteer_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Address__c.field-meta.xml
<CustomField>
    <fullName>sked__Address__c</fullName>
    <description>The address of the location</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>sked_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Physical_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Physical_Location_Type__c</fullName>
    <label>Physical Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
            <value>
                <fullName>Inside/Outside</fullName>
                <isActive>false</isActive>
                <label>Inside/Outside</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>sked_Industry_Code__c</fullName>
    <formula>TEXT(sked_Account__r.Industry_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Max_Shift_End__c.field-meta.xml
<CustomField>
    <fullName>sked_Max_Shift_End__c</fullName>
    <label>Max Shift End</label>
    <summarizedField>sked_Drive_Shift__c.sked_Finish__c</summarizedField>
    <summaryForeignKey>sked_Drive_Shift__c.sked_Drive__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Min_Shift_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Min_Shift_Start__c</fullName>
    <label>Min Shift Start</label>
    <summarizedField>sked_Drive_Shift__c.sked_Start__c</summarizedField>
    <summaryForeignKey>sked_Drive_Shift__c.sked_Drive__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sked_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Projected_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>sked_Projected_Registered_Donors__c</fullName>
    <label>Projected Registered Donors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Total_Products_Projected__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Products_Projected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Products Projected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Site__c</fullName>
    <formula>CASESAFEID(sked_Drive__r.sked_Drive_Site__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>Draw End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Start__c</fullName>
    <label>Min Shift Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Draw Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Total_Products_Projected__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Products_Projected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Products Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/sked_Site_Collection_Operation__c.object-meta.xml
<CustomObject>
    <label>Site Collection Operation</label>
    <nameField>
        <displayFormat>SCO-{000000}</displayFormat>
        <label>Site Collection Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Collection Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Site Collection Operations</relationshipLabel>
    <relationshipName>sked_Site_Collection_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Resource_Volunteer_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Donor Ambassador</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Donor Ambassador</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screener</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - RNOR</fullName>
    </customValue>
    <customValue>
        <fullName>Translator</fullName>
    </customValue>
    <masterLabel>Resource Volunteer Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/skedRegulatedMedicalScreenerGenBatch.cls
global class skedRegulatedMedicalScreenerGenBatch implements System.Schedulable, Database.Batchable<sObject> {
    
    private final Decimal TOTAL_PRODUCTS_PROJECTED_MOBILE = 30;
    private final Decimal TOTAL_PRODUCTS_PROJECTED_FIXED_SITE = 20;
    private final String DRIVE_INDUSTRY_SCHOOL = 'High School';
    private final String DRIVE_INDUSTRY_COLLEGE = 'College';
    private final String ACC_MARKETING_PREMIER_CURRENT = 'Premier Current';
    private final String ACC_MARKETING_PREMIER_PRIOR = 'Premier Prior';
    private final String ACC_MARKETING_PREMIER_BONUS_CURRENT = 'Premier Bonus Current';
    private final String ACC_MARKETING_PREMIER_BONUS_PRIOR = 'Premier Bonus Prior';
    private final String OPP_MARKETING_HONOR_MEMORY = 'In Honor/In Memory Of';
    
    global void execute(SchedulableContext SC) {
        Database.executeBatch(new skedRegulatedMedicalScreenerGenBatch(), 200);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date dateThreshold = system.today().addDays(56); //8 weeks
        
        Set<Id> driveIdsHaveMedical = new Set<Id>();
        for (sked__Job__c medicalJob : [SELECT Id, sked_Drive__c
                                        FROM sked__Job__c
                                        WHERE sked_Volunteer_Role__c = :skedConstants.JOB_VOLUNTEER_ROLE_MEDICAL_SCREENER
                                        AND sked_Drive__r.sked_Drive_Date__c >= TODAY
                                        AND sked_Drive__r.sked_Drive_Date__c <= :dateThreshold
                                        AND 
                                        (
                                            (sked_Drive__r.sked_Type_Of_Drive__c = :skedConstants.DRIVE_TYPE_MOBILE AND sked_Drive__r.sked_Total_Products_Projected__c >= :TOTAL_PRODUCTS_PROJECTED_MOBILE)
                                            OR
                                            (sked_Drive__r.sked_Type_Of_Drive__c = :skedConstants.DRIVE_TYPE_FIXED_SITE AND sked_Drive__r.sked_Total_Products_Projected__c >= :TOTAL_PRODUCTS_PROJECTED_FIXED_SITE)
                                        )
                                        AND sked_Drive__r.sked_Drive_Site__r.sked_Physical_Location_Type__c != :skedConstants.LOCATION_TYPE_OUTSIDE
                                        AND sked__Job_Status__c != :skedConstants.JOB_STATUS_CANCELLED]) {
                                            driveIdsHaveMedical.add(medicalJob.sked_Drive__c);
                                        }
        
        List<string> excludedDriveStatuses = new List<string> {skedConstants.DRIVE_STATUS_CANCEL, skedConstants.DRIVE_STATUS_COMPLETE};
        return Database.getQueryLocator([SELECT Id, sked_Industry_Code__c, sked_Opportunity__r.AccountId, sked_Opportunity__c,
                sked_Projected_Registered_Donors__c, sked_Drive_Date__c, sked_Start_Time__c, sked_End_Time__c,
                sked_Drive_Site__c, sked_Collection_Operation__c, sked_Min_Shift_Start__c, sked_Max_Shift_End__c,
                sked_Collection_Operation__r.sked_Regulated_Medi_Screener_Drive_Types__c, sked_Type_Of_Drive__c,
                sked_Drive_Site__r.sked__GeoLocation__Latitude__s, sked_Drive_Site__r.sked__GeoLocation__Longitude__s, sked_Drive_Site__r.sked__Address__c,
                (
                    SELECT Id
                    FROM sked_Drive_Shifts__r
                    ORDER BY sked_Start__c ASC
                    LIMIT 1
                )
                FROM sked_Drive__c
                WHERE Id NOT IN :driveIdsHaveMedical
                AND sked_Drive_Shift_Count__c > 0
                //AND sked_Projected_Registered_Donors__c != NULL
                AND sked_Min_Shift_Start__c != NULL
                AND sked_Max_Shift_End__c != NULL
                AND sked_Drive_Date__c >= TODAY 
                AND sked_Drive_Date__c <= :dateThreshold 
                AND
                (
                    (sked_Type_Of_Drive__c = :skedConstants.DRIVE_TYPE_MOBILE AND sked_Total_Products_Projected__c >= :TOTAL_PRODUCTS_PROJECTED_MOBILE)
                    OR
                    (sked_Type_Of_Drive__c = :skedConstants.DRIVE_TYPE_FIXED_SITE AND sked_Total_Products_Projected__c >= :TOTAL_PRODUCTS_PROJECTED_FIXED_SITE)
                )
                AND sked_Drive_Site__r.sked_Physical_Location_Type__c != :skedConstants.LOCATION_TYPE_OUTSIDE
                AND sked_Status__c NOT IN :excludedDriveStatuses]);
    }
    
    global void execute(Database.BatchableContext BC, List<sked_Drive__c> lsDriveRecs) {
        if (lsDriveRecs.isEmpty()) return;
        
        // get drive accounts & opps without specific 'Marketing programs'
        Set<Id> setAccIds = new Set<Id>();
        Set<Id> setOppIds = new Set<Id>();
        getMarketingAccOpp(lsDriveRecs, setAccIds, setOppIds);
        
        Map<Id, Id> mapDriveToRegion = getMapDriveToRegion(lsDriveRecs);

        Map<Id, Decimal> mapDriveShiftToVolunteerQuantity = getMapDriveShiftToVolunteerQuantity(lsDriveRecs);
        
        // loop through each drive & when specific condition is met, create 'volunteer job'
        List<sked_Drive_Shift__c> lsDriveShiftsToUpdate = new List<sked_Drive_Shift__c>();
        List<sked__Job__c> lsJobsToCreate = new List<sked__Job__c>();
        for (sked_Drive__c driveRec : lsDriveRecs) {
            Boolean isRegulatedMediScreenerNeeded = driveRec.sked_Collection_Operation__r.sked_Regulated_Medi_Screener_Drive_Types__c != NULL &&
                driveRec.sked_Collection_Operation__r.sked_Regulated_Medi_Screener_Drive_Types__c.contains(driveRec.sked_Type_Of_Drive__c);
            Boolean hasValidMarketingRecognition = setAccIds.contains(driveRec.sked_Opportunity__r.AccountId);
            Boolean isAssociatedWithAllowedIndustryCode = !String.isBlank(driveRec.sked_Industry_Code__c) && (driveRec.sked_Industry_Code__c == DRIVE_INDUSTRY_SCHOOL || driveRec.sked_Industry_Code__c.containsIgnoreCase(DRIVE_INDUSTRY_COLLEGE));
            Boolean hasInHonoredMemoryMarketingProgram = setOppIds.contains(driveRec.sked_Opportunity__c);
            Boolean isFixedDriveType = driveRec.sked_Type_Of_Drive__c == skedConstants.DRIVE_TYPE_FIXED_SITE;
            if ((isRegulatedMediScreenerNeeded && isFixedDriveType) || (isRegulatedMediScreenerNeeded && (hasValidMarketingRecognition || isAssociatedWithAllowedIndustryCode || hasInHonoredMemoryMarketingProgram))) {
                    Decimal calculatedQty = 1; //getCalculatedQuantity(driveRec);
                    Id regionId = mapDriveToRegion.get(driveRec.Id);
                    Decimal duration = skedDateTimeUtils.getDifferentMinutes(driveRec.sked_Min_Shift_Start__c, driveRec.sked_Max_Shift_End__c);
                    
                    if (calculatedQty != NULL && !String.isBlank(regionId) && duration != NULL) {
                        sked__Job__c newSkedJob = new sked__Job__c(
                            sked_Drive__c = driveRec.Id,
                            sked_Drive_Shift__c = driveRec.sked_Drive_Shifts__r[0].Id,
                            sked__Location__c = driveRec.sked_Drive_Site__c,
                            sked__Region__c = regionId,
                            sked_Volunteer_Role__c = skedConstants.JOB_VOLUNTEER_ROLE_MEDICAL_SCREENER,
                            sked_Redcross_Volunteer_Quantity__c = calculatedQty,
                            sked_Sponsor_Volunteer_Quantity__c = 0,
                            sked__Quantity__c = calculatedQty,
                            sked__Start__c = driveRec.sked_Min_Shift_Start__c,
                            sked__Finish__c = driveRec.sked_Max_Shift_End__c,
                            sked__Duration__c = duration,
                            sked__GeoLocation__Latitude__s = driveRec.sked_Drive_Site__r.sked__GeoLocation__Latitude__s,
                            sked__GeoLocation__Longitude__s = driveRec.sked_Drive_Site__r.sked__GeoLocation__Longitude__s,
                            sked__Address__c = driveRec.sked_Drive_Site__r.sked__Address__c
                        );
                        lsJobsToCreate.add(newSkedJob);

                        sked_Drive_Shift__c driveShiftToUpdate = driveRec.sked_Drive_Shifts__r[0];
                        Decimal existingVolunteerQuantity = mapDriveShiftToVolunteerQuantity.containsKey(driveShiftToUpdate.Id) ? mapDriveShiftToVolunteerQuantity.get(driveShiftToUpdate.Id) : 0;
                        driveShiftToUpdate.sked_Volunteer_Setup__c = existingVolunteerQuantity + calculatedQty;
                        lsDriveShiftsToUpdate.add(driveShiftToUpdate);
                    }
            }
        }
        
        if (!lsJobsToCreate.isEmpty()) {
            insert lsJobsToCreate;
        }

        if (!lsDriveShiftsToUpdate.isEmpty()) {
            skedHubBase.setBypassAllTriggers(true);
            update lsDriveShiftsToUpdate;
            skedHubBase.setBypassAllTriggers(false);
        }
    }
    
    private Map<Id, Id> getMapDriveToRegion(List<sked_Drive__c> lsDriveRecs) {
        Map<Id, Id> mapDriveToRegion = new Map<Id, Id>();
        
        if (lsDriveRecs.isEmpty()) {
            return mapDriveToRegion;
        }
        
        // get siteIds , collOperIds from drive
        Set<Id> setSiteIds = new Set<Id>();
        Set<Id> setColOperIds = new Set<Id>();
        for (sked_Drive__c driveRec : lsDriveRecs) {
            if (String.isBlank(driveRec.sked_Drive_Site__c) || String.isBlank(driveRec.sked_Collection_Operation__c)) {
                continue;
            }
            
            setSiteIds.add(driveRec.sked_Drive_Site__c);
            setColOperIds.add(driveRec.sked_Collection_Operation__c);
        }
        
        // get 'site collection operation' records & add in a map for lookup in next step
        Map<String, List<sked_Site_Collection_Operation__c>> mapSiteColOperToDates = new Map<String, List<sked_Site_Collection_Operation__c>>();
        for (sked_Site_Collection_Operation__c siteColOperRec :
             [SELECT Id, sked_Site__c, sked_Collection_Operation__c, sked_Region__c, sked_Start_Date__c, sked_End_Date__c 
              FROM sked_Site_Collection_Operation__c 
              WHERE sked_Site__c IN :setSiteIds AND sked_Collection_Operation__c IN :setColOperIds]) {
                  String key = siteColOperRec.sked_Site__c + ':' + siteColOperRec.sked_Collection_Operation__c;
                  List<sked_Site_Collection_Operation__c> lsCollOpers = mapSiteColOperToDates.get(key);
                  if (lsCollOpers == null) {
                      lsCollOpers = new List<sked_Site_Collection_Operation__c>();
                  }
                  lsCollOpers.add(siteColOperRec);
                  mapSiteColOperToDates.put(key, lsCollOpers);
              }
        
        // loop through each drive & find the right 'site collection operation' matching the drive date
        for (sked_Drive__c driveRec : lsDriveRecs) {
            String key = driveRec.sked_Drive_Site__c + ':' + driveRec.sked_Collection_Operation__c;
            List<sked_Site_Collection_Operation__c> lsCollOpers = mapSiteColOperToDates.get(key);
            Date driveDate = driveRec.sked_Drive_Date__c;
            if (lsCollOpers != null && driveDate != null) {
                for (sked_Site_Collection_Operation__c siteColOperRec : lsCollOpers) {
                    if (driveDate >= siteColOperRec.sked_Start_Date__c &&  driveDate <= siteColOperRec.sked_End_Date__c) {
                        if (siteColOperRec.sked_Region__c == null) {
                            continue;
                        }
                        mapDriveToRegion.put(driveRec.Id, siteColOperRec.sked_Region__c);
                        break;
                    }
                }
            }
        }
        return mapDriveToRegion;
    }
    
    private void getMarketingAccOpp(List<sked_Drive__c> lsDriveRecs, Set<Id> setAccIds, Set<Id> setOppIds) {
        Set<Id> driveAccountIds = new Set<Id>();
        Set<Id> driveOppIds = new Set<Id>();
        for (sked_Drive__c driveRec : lsDriveRecs) {
            driveAccountIds.add(driveRec.sked_Opportunity__r.AccountId);
            driveOppIds.add(driveRec.sked_Opportunity__c);
        }
        
        List<String> lsPremierPrgms = new List<String> {ACC_MARKETING_PREMIER_CURRENT, ACC_MARKETING_PREMIER_PRIOR, ACC_MARKETING_PREMIER_BONUS_CURRENT, ACC_MARKETING_PREMIER_BONUS_PRIOR};
            for (Account_Marketing_Program__c accMarkPgm : 
                 [SELECT Account__c 
                  FROM Account_Marketing_Program__c 
                  WHERE Marketing_Program__r.Name IN :lsPremierPrgms AND Account__c IN :driveAccountIds]) {
                      setAccIds.add(accMarkPgm.Account__c);
                  }
        
        for (Drive_Marketing_Programs__c oppMarkPgm : 
             [SELECT Id, Blood_Drive_Opportunity__c
              FROM Drive_Marketing_Programs__c 
              WHERE Marketing_Program__r.Name = :OPP_MARKETING_HONOR_MEMORY AND Blood_Drive_Opportunity__c IN :driveOppIds]) {
                  setOppIds.add(oppMarkPgm.Blood_Drive_Opportunity__c);
              }
    }

    private Map<Id, Decimal> getMapDriveShiftToVolunteerQuantity(List<sked_Drive__c> lsDriveRecs) {
        Map<Id, Decimal> mapDriveShiftToVolunteerQuantity = new Map<Id, Decimal>();
        
        Map<Id, sked_Drive__c> mapDrive = new Map<Id, sked_Drive__c>(lsDriveRecs);
        for (sked__Job__c job : [
            SELECT Id, sked_Drive_Shift__c, sked__Quantity__c
            FROM sked__Job__c
            WHERE sked__Job_Status__c != :skedConstants.JOB_STATUS_CANCELLED
            AND (sked_Is_Manually_Created__c = FALSE OR sked_Manually_Created_From__c != 'Staffing Modal')
            AND sked_Volunteer_Role__c != NULL
            AND sked__Quantity__c != NULL
            AND sked_Drive__c IN :mapDrive.keySet()
        ]) {
            if (!mapDriveShiftToVolunteerQuantity.containsKey(job.sked_Drive_Shift__c)) {
                mapDriveShiftToVolunteerQuantity.put(job.sked_Drive_Shift__c, 0);
            }
            mapDriveShiftToVolunteerQuantity.put(job.sked_Drive_Shift__c, mapDriveShiftToVolunteerQuantity.get(job.sked_Drive_Shift__c) + job.sked__Quantity__c);
        }

        return mapDriveShiftToVolunteerQuantity;
    }
    
    private Decimal getCalculatedQuantity(sked_Drive__c driveRec) {
        Decimal noOfVolunteerDonorAmbassadors;
        
        try {
            if (driveRec.sked_Projected_Registered_Donors__c <= 70) {
                noOfVolunteerDonorAmbassadors = 1;
            } 
            else {
                noOfVolunteerDonorAmbassadors = 1 + Math.ceil((driveRec.sked_Projected_Registered_Donors__c - 70) / 60);
            }
            
            DateTime driveStartTime = DateTime.newInstance(driveRec.sked_Drive_Date__c, driveRec.sked_Start_Time__c);
            DateTime driveEndTime = DateTime.newInstance(driveRec.sked_Drive_Date__c, driveRec.sked_End_Time__c);
            Decimal driveLength = skedDateTimeUtils.getDifferentMinutes(driveStartTime, driveEndTime) / 60;
            if (driveLength > 6.5) {
                noOfVolunteerDonorAmbassadors = Math.ceil(noOfVolunteerDonorAmbassadors * 0.5);
            }
        } 
        catch (Exception e) {
            System.debug('Exception caught - ' + e.getMessage());
            noOfVolunteerDonorAmbassadors = null;
        }
        
        return noOfVolunteerDonorAmbassadors;
    }
    
    global void finish(Database.BatchableContext BC) {}
}