force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_RTD_Change_DCR_Required__c.field-meta.xml
<CustomField>
    <fullName>sked_RTD_Change_DCR_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RTD Change DCR Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>System Generated</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Pending Action</fullName>
                <isActive>false</isActive>
                <label>Pending Action</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Drive_Change_Request__c/sked_Drive_Change_Request__c.object-meta.xml
<CustomObject>
    <label>Drive Change Request</label>
    <nameField>
        <displayFormat>DCR-{000000}</displayFormat>
        <label>Drive Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drive Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive_Change_Request__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Change Requests</relationshipLabel>
    <relationshipName>sked_Drive_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Change_Request__c/fields/sked_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waiting for DM Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for APS Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for DRD Feedback</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved by System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Drive_Change_Request__c/fields/sked_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Change</fullName>
                <default>true</default>
                <label>User Change</label>
            </value>
            <value>
                <fullName>Collection Operation Change</fullName>
            </value>
            <value>
                <fullName>Role Time Detail Change</fullName>
            </value>
            <value>
                <fullName>Role Time Variance Change</fullName>
            </value>
            <value>
                <fullName>Site Address Change</fullName>
            </value>
            <value>
                <fullName>Travel Time Change</fullName>
            </value>
            <value>
                <fullName>Regenerate Drive</fullName>
            </value>
            <value>
                <fullName>Slot Configuration Change</fullName>
            </value>
            <value>
                <fullName>Vehicle Requirement Change</fullName>
            </value>
            <value>
                <fullName>SDM Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Change_Request_Item__c/sked_Drive_Change_Request_Item__c.object-meta.xml
<CustomObject>
    <label>Drive Change Request Item</label>
    <nameField>
        <displayFormat>DCRI-{000000}</displayFormat>
        <label>Drive Change Request Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drive Change Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive_Change_Request_Item__c/fields/sked_Drive_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Change_Request__c</fullName>
    <label>Drive Change Request</label>
    <referenceTo>sked_Drive_Change_Request__c</referenceTo>
    <relationshipLabel>Drive Change Request Items</relationshipLabel>
    <relationshipName>sked_Drive_Change_Request_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Change_Request_Item__c/fields/sked_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Impact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Resource_Role_Group__c/sked_Resource_Role_Group__c.object-meta.xml
<CustomObject>
    <label>Resource Role Group</label>
    <nameField>
        <displayFormat>RRGS-{0000}</displayFormat>
        <label>Resource Role Group Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Role Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Resource_Role_Group__c/fields/sked_Resource_Role_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role_Group__c</fullName>
    <label>Resource Role Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Role_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/sked_Role_Time_Detail__c.object-meta.xml
<CustomObject>
    <label>Role Time Detail</label>
    <nameField>
        <displayFormat>RTD-{000000}</displayFormat>
        <label>Role Time Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Time Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Breakdown_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Breakdown_Time__c</fullName>
    <label>Breakdown Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Role Time Details</relationshipLabel>
    <relationshipName>sked_Role_Time_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>sked_Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_Week</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Type__c</fullName>
    <label>Drive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Fixed_Site_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Fixed_Site_Operation_Type__c</fullName>
    <label>Fixed Site Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked_Drive_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Non Integrated WB</fullName>
            </value>
            <value>
                <fullName>Non Integrated APH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lead_Time__c</fullName>
    <label>Lead Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Mobile_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Mobile_Type__c</fullName>
    <label>Mobile Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked_Drive_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
            <value>
                <fullName>Inside/Outside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Resource_Role_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role_Group__c</fullName>
    <label>Resource Role Group</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Role_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Setup_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Setup_Time__c</fullName>
    <label>Setup Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Collection Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Role_Time_Detail__c/fields/sked_Wrap_up_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Wrap_up_Time__c</fullName>
    <label>Wrap-up Time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Days_of_Week.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Days of Week</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Resource_Role_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Driving roles</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisory roles</fullName>
    </customValue>
    <customValue>
        <fullName>Staff roles</fullName>
    </customValue>
    <masterLabel>Resource Role Group</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/skedCreateDCRForRTDBatch_Test.cls
@isTest
private class skedCreateDCRForRTDBatch_Test {
    @isTest
    static void skedCreateDCRForRTDBatch_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Biomed_Collection_Op_Center__c testCollectionOp = (Biomed_Collection_Op_Center__c) mapTestData.get('testCollectionOperation1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');

        sked_Role_Time_Detail__c testRtd = new sked_Role_Time_Detail__c(
            sked_Collection_Operation__c = testCollectionOp.Id,
            sked_Effective_Start_Date__c = System.today().addDays(-10),
            sked_Effective_End_Date__c = System.today().addDays(10),
            sked_Breakdown_Time__c = 25,
            sked_Days_of_Week__c = 'Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',
            sked_Drive_Type__c = testDrive.sked_Type_of_Drive__c,
            sked_Lead_Time__c = 15,
            sked_Setup_Time__c = 15,
            sked_Wrap_up_Time__c = 15,
            sked_Mobile_Type__c = 'Inside/Outside',
            sked_Resource_Role_Group__c = 'Driving roles;Supervisory roles;Staff roles'
        );

        insert testRtd;

        Test.startTest();
            Database.executeBatch(new skedCreateDCRForRTDBatch(new List<sked_Role_Time_Detail__c>{testRtd}), 1);
        Test.stopTest();

        Integer testDCRCount = [SELECT COUNT() FROM sked_Drive__c WHERE sked_RTD_Change_DCR_Required__c = TRUE];
        System.assertEquals(1, testDCRCount);
    }

    @isTest
    static void skedCreateDCRForRTDBatch_NoWeekdaysSelected_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Biomed_Collection_Op_Center__c testCollectionOp = (Biomed_Collection_Op_Center__c) mapTestData.get('testCollectionOperation1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');

        sked_Role_Time_Detail__c testRtd = new sked_Role_Time_Detail__c(
            sked_Collection_Operation__c = testCollectionOp.Id,
            sked_Effective_Start_Date__c = System.today().addDays(-10),
            sked_Effective_End_Date__c = System.today().addDays(10),
            sked_Breakdown_Time__c = 25,
            sked_Days_of_Week__c = '',
            sked_Drive_Type__c = testDrive.sked_Type_of_Drive__c,
            sked_Lead_Time__c = 15,
            sked_Setup_Time__c = 15,
            sked_Wrap_up_Time__c = 15,
            sked_Mobile_Type__c = 'Inside/Outside',
            sked_Resource_Role_Group__c = 'Driving roles;Supervisory roles;Staff roles'
        );

        insert testRtd;

        Test.startTest();
            Database.executeBatch(new skedCreateDCRForRTDBatch(new List<sked_Role_Time_Detail__c>{testRtd}), 1);
        Test.stopTest();

        Integer testDCRCount = [SELECT COUNT() FROM sked_Drive__c WHERE sked_RTD_Change_DCR_Required__c = TRUE];
        System.assertEquals(0, testDCRCount);
    }

    @isTest
    static void skedCreateDCRForRTDBatch_FixedSiteWD_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Test.startTest();
        Biomed_Collection_Op_Center__c testCollectionOp = (Biomed_Collection_Op_Center__c) mapTestData.get('testCollectionOperation1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        testDrive.sked_Type_Of_Drive__c = 'Fixed Site';
        update testDrive;

        sked_Role_Time_Detail__c testRtd = new sked_Role_Time_Detail__c(
            sked_Collection_Operation__c = testCollectionOp.Id,
            sked_Effective_Start_Date__c = System.today().addDays(-10),
            sked_Effective_End_Date__c = System.today().addDays(10),
            sked_Breakdown_Time__c = 25,
            sked_Days_of_Week__c = 'Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',
            sked_Drive_Type__c = 'Fixed Site',
            sked_Lead_Time__c = 15,
            sked_Setup_Time__c = 15,
            sked_Wrap_up_Time__c = 15,
            sked_Fixed_Site_Operation_Type__c = 'Non Integrated WB',
            sked_Mobile_Type__c = 'Inside',
            sked_Resource_Role_Group__c = 'Driving roles;Supervisory roles;Staff roles'
        );

        insert testRtd;
        Database.executeBatch(new skedCreateDCRForRTDBatch(new List<sked_Role_Time_Detail__c>{testRtd}), 1);
        Test.stopTest();

        Integer testDCRCount = [SELECT COUNT() FROM sked_Drive__c WHERE sked_RTD_Change_DCR_Required__c = TRUE];
        System.assertEquals(0, testDCRCount);
    }

    @isTest
    static void skedCreateDCRForRTDBatch_Test_NoDuplicateDCR() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Biomed_Collection_Op_Center__c testCollectionOp = (Biomed_Collection_Op_Center__c) mapTestData.get('testCollectionOperation1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');

        sked_Role_Time_Detail__c testRtd = new sked_Role_Time_Detail__c(
            sked_Collection_Operation__c = testCollectionOp.Id,
            sked_Effective_Start_Date__c = System.today().addDays(-10),
            sked_Effective_End_Date__c = System.today().addDays(10),
            sked_Breakdown_Time__c = 25,
            sked_Days_of_Week__c = 'Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',
            sked_Drive_Type__c = testDrive.sked_Type_of_Drive__c,
            sked_Lead_Time__c = 15,
            sked_Setup_Time__c = 15,
            sked_Wrap_up_Time__c = 15,
            sked_Mobile_Type__c = 'Inside/Outside',
            sked_Resource_Role_Group__c = 'Driving roles;Supervisory roles;Staff roles'
        );
        insert testRtd;

        sked_Drive_Change_Request__c testDcr = new sked_Drive_Change_Request__c(
            sked_Drive__c = testDrive.Id,
            sked_Type__c = skedConstants.DRIVE_CHANGE_REQUEST_TYPE_RTD_CHANGE,
            sked_Status__c = skedConstants.DRIVE_CHANGE_REQUEST_STATUS_PENDING
        );
        insert testDcr;
        sked_Drive_Change_Request_Item__c testDcri = new sked_Drive_Change_Request_Item__c(
            sked_Drive_Change_Request__c = testDcr.Id,
            sked_Object_API_Name__c = 'sked_Drive__c',
            sked_Field_API_Name__c = 'sked_Role_Time_Detail_Changed__c',
            sked_Field_Label__c = 'Role Time Detail Changed',
            sked_Field_Type__c = 'Boolean',
            sked_Type__c = 'Change'
        );
        insert testDcri;

        Test.startTest();
            Database.executeBatch(new skedCreateDCRForRTDBatch(new List<sked_Role_Time_Detail__c>{testRtd}), 1);
        Test.stopTest();

        Integer testDCRCount = [SELECT COUNT() FROM sked_Drive__c WHERE sked_RTD_Change_DCR_Required__c = TRUE];
        System.assertEquals(1, testDCRCount);
    }
}