force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Operation_Availability__c/Collection_Operation_Availability__c.object-meta.xml
<CustomObject>
    <description>Junction object between Collection Operation and Availability Pattern</description>
    <label>Collection Operation Availability</label>
    <nameField>
        <label>CO AP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operation Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Operation_Availability__c/fields/Availability_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Availability_Pattern__c</fullName>
    <description>Created as part of HRP-1522</description>
    <label>Availability Pattern</label>
    <referenceTo>sked__Availability_Pattern__c</referenceTo>
    <relationshipLabel>Collection Operation Availabilities</relationshipLabel>
    <relationshipName>Collection_Operation_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collection_Operation_Availability__c/fields/Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>Collection_Operation__c</fullName>
    <description>Created as part of HRP-1522</description>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Collection Operation Availabilities</relationshipLabel>
    <relationshipName>Collection_Operation_Availabilities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collection_Operation_Availability__c/fields/Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_End_Date__c</fullName>
    <description>Created as part of HRP-1522</description>
    <label>Effective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collection_Operation_Availability__c/fields/Effective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Start_Date__c</fullName>
    <description>Created as part of HRP-1522</description>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collection_Operation_Availability__c/fields/Total_Target__c.field-meta.xml
<CustomField>
    <fullName>Total_Target__c</fullName>
    <description>Created as part of HRP-1522</description>
    <label>Total Target (AP)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Availability_Pattern__c/sked__Availability_Pattern__c.object-meta.xml
<CustomObject>
    <description>Table to store availability patterns</description>
    <label>Availability Pattern</label>
    <nameField>
        <label>Availability Pattern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Availability Patterns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Availability_Pattern_Resource__c/sked__Availability_Pattern_Resource__c.object-meta.xml
<CustomObject>
    <label>Availability Pattern Resource</label>
    <nameField>
        <displayFormat>APR-{0000}</displayFormat>
        <label>Availability Pattern Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availability Pattern Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Availability_Pattern_Resource__c/fields/sked__Availability_Pattern__c.field-meta.xml
<CustomField>
    <fullName>sked__Availability_Pattern__c</fullName>
    <label>Availability Pattern</label>
    <referenceTo>sked__Availability_Pattern__c</referenceTo>
    <relationshipLabel>Availability Pattern Resources</relationshipLabel>
    <relationshipName>Availability_Pattern_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Availability_Pattern_Resource__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Availability Pattern Resources</relationshipLabel>
    <relationshipName>Availability_Pattern_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Availability_Pattern_Resource__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/CO_AP_Status__c.field-meta.xml
<CustomField>
    <fullName>CO_AP_Status__c</fullName>
    <description>Created as part of HRP-1522</description>
    <label>CO AP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Yet to process CO</fullName>
            </value>
            <value>
                <fullName>Yet to Process Totals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/skedAPResourceTrigger_Test.cls
@isTest(SeeAllData = false)
private class skedAPResourceTrigger_Test {
    
    @testSetup
    static void prepareTestData() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        
        Biomed_Collection_Op_Center__c testCollectionOperation1 = (Biomed_Collection_Op_Center__c)mapTestData.get('testCollectionOperation1');
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Availability_Pattern__c testWeeklyPattern1 = (sked__Availability_Pattern__c)mapTestData.get('testWeeklyPattern1');
        sked__Resource__c testResource1 = (sked__Resource__c)mapTestData.get('testResource1');
        sked__Resource__c testResource2 = (sked__Resource__c)mapTestData.get('testResource2');
        
        Collection_Operation_Availability__c testCoAp = new Collection_Operation_Availability__c(
        	Name = testCollectionOperation1.Name + ' ' + testWeeklyPattern1.Name,
        	Collection_Operation__c = testCollectionOperation1.Id,
        	Availability_Pattern__c = testWeeklyPattern1.Id,
        	Effective_Start_Date__c = system.today(),
        	Effective_End_Date__c = Date.newInstance(4000, 12, 30),
        	Total_Target__c = 5
        );
        insert testCoAp;
        
        sked__Availability_Pattern_Resource__c testPatternResource1 = new sked__Availability_Pattern_Resource__c(
            sked__Availability_Pattern__c = testWeeklyPattern1.Id,
            sked__Resource__c = testResource1.Id, 
            sked__Start__c = testDataFactory.summary.startTime.addDays(1)
        );
        sked__Availability_Pattern_Resource__c testPatternResource2 = new sked__Availability_Pattern_Resource__c(
            sked__Availability_Pattern__c = testWeeklyPattern1.Id,
            sked__Resource__c = testResource2.Id, 
            sked__Start__c = testDataFactory.summary.startTime.addDays(1)
        );
        insert new List<sked__Availability_Pattern_Resource__c>{testPatternResource1, testPatternResource2};
    }
    
    static testMethod void testEndApResourceFunctionality() {
        Test.startTest();
        
        List<sked__Availability_Pattern_Resource__c> testApResources = [SELECT Id, sked__Start__c, sked_End_Date__c FROM sked__Availability_Pattern_Resource__c];
        testApResources[0].sked_End_Date__c = testApResources[0].sked__Start__c.date().addDays(2);
        update testApResources[0];
        
        Test.stopTest();
        sked__Resource__c testResource = [SELECT Id, CO_AP_Status__c FROM sked__Resource__c LIMIT 1];
        Assert.isTrue(testResource.CO_AP_Status__c != null);
    }
}