force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Lunch_Break__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the lunch break durations are populated by default for drives in this Collection Operation</inlineHelpText>
    <label>Lunch Break</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Lunch_Break_Before_Draw_Hours__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Before_Draw_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break Before Draw Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <description>duration (in minutes) of the job</description>
    <label>Duration</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <label>Location</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/sked__Slot__c/sked__Slot__c.object-meta.xml
<CustomObject>
    <label>Slot</label>
    <nameField>
        <label>Slot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slots</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Slot__c/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <formula>sked_Drive__r.sked_Drive_Date__c</formula>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Slot__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Slot__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>sked_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Slot__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>sked_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Slot__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Slot__c/fields/sked_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Donors_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>sked_Donors_Scheduled__c</fullName>
    <label>Donors Scheduled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>Draw End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Equipment__c.field-meta.xml
<CustomField>
    <fullName>sked_Equipment__c</fullName>
    <label>Equipment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Finish__c.field-meta.xml
<CustomField>
    <fullName>sked_Finish__c</fullName>
    <label>Max Shift End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Before_Draw_Hours__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Before_Draw_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break Before Draw Hours?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Duration__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Duration__c</fullName>
    <label>Lunch Break Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_End_Time__c</fullName>
    <label>Lunch Break End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Start_Time__c</fullName>
    <label>Lunch Break Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Order__c.field-meta.xml
<CustomField>
    <fullName>sked_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Sign_Up_Reduction__c.field-meta.xml
<CustomField>
    <fullName>sked_Sign_Up_Reduction__c</fullName>
    <label>Sign-Up Reduction %</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Staff_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Setup__c</fullName>
    <label>Staff Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Start__c</fullName>
    <label>Min Shift Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Draw Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Vehicles_Needed__c.field-meta.xml
<CustomField>
    <fullName>sked_Vehicles_Needed__c</fullName>
    <label>Vehicles Needed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Volunteer_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Volunteer_Setup__c</fullName>
    <label>Volunteer Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/slwcOpportunityService_Test.cls
@isTest
private class slwcOpportunityService_Test {

    static testmethod void testCloneOpportunity() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Biomed_Collection_Op_Center__c testCollectionOperation1 = (Biomed_Collection_Op_Center__c)mapTestData.get('testCollectionOperation1');
        Opportunity testOpportunity = (Opportunity)mapTestData.get('testOpportunity');
        sked_Drive__c testDrive1 = (sked_Drive__c)mapTestData.get('testDrive1');
        sked__Resource__c testResource1 = (sked__Resource__c)mapTestData.get('testResource1');
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Location__c testLocation1 = (sked__Location__c)mapTestData.get('testLocation1');
        
        Test.startTest();

        sked_Drive_Shift__c driveShift = new sked_Drive_Shift__c(
            sked_Donors_Scheduled__c = 1,
            sked_End_Time__c = Time.newInstance(20,0,0,0),
            sked_Start_Time__c = Time.newInstance(14,0,0,0),
            sked_Drive__c = testDrive1.Id,
            sked_Drive_Date__c = testDrive1.sked_Drive_Date__c,
            sked_Equipment__c = 1,
            sked_Lunch_Break__c = FALSE,
            sked_Lunch_Break_Before_Draw_Hours__c = FALSE,
            sked_Lunch_Break_Duration__c = 0,
            sked_Lunch_Break_End_Time__c = NULL,
            sked_Lunch_Break_Start_Time__c = NULL,
            sked_Finish__c = DateTime.newInstance(System.today(), Time.newInstance(20,0,0,0)),
            sked_Start__c = DateTime.newInstance(System.today(), Time.newInstance(14,0,0,0)),
            sked_Order__c = 1,
            sked_Sign_Up_Reduction__c = 0,
            sked_Staff_Setup__c = 1,
            sked_Vehicles_Needed__c = 1,
            sked_Volunteer_Setup__c = 1
        );
        insert driveShift;
        
        List<sked__Job__c> jobs = new List<sked__Job__c>();
        sked__Job__c job = new sked__Job__c(
            sked__Region__c = testRegion1.Id,
            sked__Start__c = testDataFactory.summary.startTime.addHours(11),
            sked__Finish__c = testDataFactory.summary.startTime.addHours(12),
            sked__Duration__c = 60,
            sked__Job_Status__c = skedConstants.JOB_STATUS_PENDING_ALLOCATION,
            sked__GeoLocation__Latitude__s = 37.7450046,
            sked__GeoLocation__Longitude__s = -122.4816244,
            sked_Drive__c = testDrive1.Id,
            sked_Drive_Shift__c = driveShift.Id,
            sked_Resource_Role__c = 'Driver'
        );
        jobs.add(job);
        
        sked__Job__c equipmentJob = new sked__Job__c(
            sked__Region__c = testRegion1.Id,
            sked__Start__c = testDataFactory.summary.startTime.addHours(11),
            sked__Finish__c = testDataFactory.summary.startTime.addHours(12),
            sked__Duration__c = 60,
            sked__Job_Status__c = skedConstants.JOB_STATUS_PENDING_ALLOCATION,
            sked__GeoLocation__Latitude__s = 37.7450046,
            sked__GeoLocation__Longitude__s = -122.4816244,
            sked_Drive__c = testDrive1.Id,
            sked_Drive_Shift__c = driveShift.Id,
            sked_Asset_Type__c = 'Equipment'
        );
        jobs.add(equipmentJob);
        
        insert jobs;
        
        sked__Slot__c slot = new sked__Slot__c(
        	sked_Drive__c = testDrive1.Id,
            sked_Drive_Shift__c = driveShift.Id,
            sked_Type__c = '2RBC',
            sked_Status__c = slwcConstants.SLOT_STATUS_OPEN,
            sked_Start__c = testDataFactory.summary.startTime.addHours(11),
            sked_End__c = testDataFactory.summary.startTime.addHours(11).addMinutes(15)
        );
        insert slot;
        
        string newDriveDateIso = Json.serialize(testOpportunity.Drive_Date__c.addDays(1)).replace('"', '');
        slwcOpportunityService.cloneOpportunity(testOpportunity.Id, newDriveDateIso, true);
        
        Test.stopTest();
    }
    
}