force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Accept_56_Day_Rule_Violation__c.field-meta.xml
<CustomField>
    <fullName>Accept_56_Day_Rule_Violation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate if a user has elected to create an opportunity even though it violates the 56 days rule</description>
    <label>Accept 56 Day Rule Violation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Online_Scheduling_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Online_Scheduling_Enabled__c</fullName>
    <label>Online Scheduling Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Slot_Generator__c.field-meta.xml
<CustomField>
    <fullName>Slot_Generator__c</fullName>
    <description>Field has been added as part of HRP-12011</description>
    <label>Slot Generator</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/sked_Fixed_Site_Procedure_Projection__c.object-meta.xml
<CustomObject>
    <label>Fixed Site Procedure Projection</label>
    <nameField>
        <displayFormat>FSPP-{000000}</displayFormat>
        <label>Fixed Site Procedure Projection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fixed Site Procedure Projections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Account__c.field-meta.xml
<CustomField>
    <fullName>sked_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fixed Site Procedure Projections</relationshipLabel>
    <relationshipName>sked_Fixed_Site_Procedure_Projections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Deferral__c.field-meta.xml
<CustomField>
    <fullName>sked_Deferral__c</fullName>
    <label>Deferral %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Impact_Drives__c.field-meta.xml
<CustomField>
    <fullName>sked_Impact_Drives__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Impact Drives</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Procedure_Type__c</fullName>
    <label>Procedure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Fixed_Site_Procedure_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_Productive_Procedure_Goal__c.field-meta.xml
<CustomField>
    <fullName>sked_Productive_Procedure_Goal__c</fullName>
    <label>Productive Procedure Goal</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Fixed_Site_Procedure_Projection__c/fields/sked_QNS__c.field-meta.xml
<CustomField>
    <fullName>sked_QNS__c</fullName>
    <label>QNS %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Fixed_Site_Procedure_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>WB</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Platelet</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <masterLabel>Fixed Site Procedure Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/skedFsppHandler_Test.cls
@isTest
private class skedFsppHandler_Test {
    
    @testSetup
    static void prepareTestData() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();

        Biomed_Collection_Op_Center__c testCollectionOperation1 = (Biomed_Collection_Op_Center__c)mapTestData.get('testCollectionOperation1');
        sked__Location__c testLocation1 = (sked__Location__c)mapTestData.get('testLocation1');
        Account testAccount1 = (Account)mapTestData.get('testAccount1');
          
        Opportunity testOpp1 = new Opportunity(
            Name = 'Test Drive',
            AccountId = testAccount1.Id,
            Drive_Date__c = system.today().addDays(10),
            Start_Time__c = Time.newInstance(7, 0, 0, 0),
            End_Time__c = Time.newInstance(17, 0, 0, 0),
            Drive_Site__c = testLocation1.Id,
            StageName = 'Solicitation',
            CloseDate = system.today(),
            Online_Scheduling_Enabled__c = 'No',
            Accept_56_Day_Rule_Violation__c = true,
            Slot_Generator__c = 130
        );
        TriggerHandler.bypass('OpportunityTriggerHandler');
        insert testOpp1;
    }
    
    static testmethod void mainTest_insert() {
        Test.startTest();
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        
        List<sked_Fixed_Site_Procedure_Projection__c> testFsppList = new List<sked_Fixed_Site_Procedure_Projection__c>();
        
        sked_Fixed_Site_Procedure_Projection__c fspp;
        fspp = new sked_Fixed_Site_Procedure_Projection__c(
            sked_Account__c = testAccount.Id,
            sked_Deferral__c = 5,
            sked_QNS__c = 5,
            sked_Productive_Procedure_Goal__c = 10,
            sked_Procedure_Type__c = '2RBC',
            sked_Effective_Start_Date__c = system.today().addDays(-14),
            sked_Effective_End_Date__c = system.today().addDays(14)
        );
        testFsppList.add(fspp);
        
        fspp = new sked_Fixed_Site_Procedure_Projection__c(
            sked_Account__c = testAccount.Id,
            sked_Deferral__c = 5,
            sked_QNS__c = 5,
            sked_Productive_Procedure_Goal__c = 10,
            sked_Procedure_Type__c = '2RBC'
        );
        testFsppList.add(fspp);
        
        fspp = new sked_Fixed_Site_Procedure_Projection__c(
            sked_Account__c = testAccount.Id,
            sked_Deferral__c = 5,
            sked_QNS__c = 5,
            sked_Productive_Procedure_Goal__c = 10,
            sked_Procedure_Type__c = '2RBC',
            sked_Effective_End_Date__c = system.today().addDays(14)
        );
        testFsppList.add(fspp);
        
        fspp = new sked_Fixed_Site_Procedure_Projection__c(
            sked_Account__c = testAccount.Id,
            sked_Deferral__c = 5,
            sked_QNS__c = 5,
            sked_Productive_Procedure_Goal__c = 10,
            sked_Procedure_Type__c = '2RBC',
            sked_Effective_Start_Date__c = system.today().addDays(-14)
        );
        testFsppList.add(fspp);
        
        insert testFsppList;
        
        List<sked_Fixed_Site_Procedure_Projection__c> testUpdatedFspps = [SELECT Id,
                                                                          sked_Impact_Drives__c 
                                                                          FROM sked_Fixed_Site_Procedure_Projection__c];
        Assert.isTrue(testUpdatedFspps[testUpdatedFspps.size() - 1].sked_Impact_Drives__c == true);

        Test.stopTest();
    }
    
    static testmethod void mainTest_update() {
        Test.startTest();
        Account testAccount1 = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        
        sked_Fixed_Site_Procedure_Projection__c fspp = new sked_Fixed_Site_Procedure_Projection__c(
            sked_Account__c = testAccount1.Id,
            sked_Deferral__c = 5,
            sked_QNS__c = 5,
            sked_Productive_Procedure_Goal__c = 10,
            sked_Procedure_Type__c = '2RBC',
            sked_Effective_Start_Date__c = system.today().addDays(-14),
            sked_Effective_End_Date__c = system.today().addDays(14)
        );
        skedHubBase.BypassInsertTriggers = true;
        insert fspp;
        skedHubBase.BypassInsertTriggers = false;
        
        Assert.isTrue(fspp.sked_Impact_Drives__c == false);
        
        fspp.sked_Productive_Procedure_Goal__c = fspp.sked_Productive_Procedure_Goal__c + 10;
        update fspp;
        
        sked_Fixed_Site_Procedure_Projection__c testUpdatedFspp = [SELECT Id, 
                                                                   sked_Impact_Drives__c 
                                                                   FROM sked_Fixed_Site_Procedure_Projection__c
                                                                   WHERE Id =:fspp.Id];
		Assert.isTrue(testUpdatedFspp.sked_Impact_Drives__c == true);
        
        Test.stopTest();
    }

}