force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <description>duration (in minutes) of the job</description>
    <label>Duration</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Job_Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Pending Allocation</fullName>
            </value>
            <value>
                <fullName>Pending Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>2RBC</fullName>
            </value>
            <value>
                <fullName>2RBC Sign-off</fullName>
            </value>
            <value>
                <fullName>Apheresis</fullName>
            </value>
            <value>
                <fullName>Apheresis Charge</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Charge - 2RBC</fullName>
            </value>
            <value>
                <fullName>Charge Mentor</fullName>
            </value>
            <value>
                <fullName>Charge - Special Collections</fullName>
            </value>
            <value>
                <fullName>Competent Driver</fullName>
            </value>
            <value>
                <fullName>Drive Lead</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Driver CDL A</fullName>
            </value>
            <value>
                <fullName>Driver CDL B</fullName>
            </value>
            <value>
                <fullName>Driver - DOT</fullName>
            </value>
            <value>
                <fullName>Driver Prestaff</fullName>
            </value>
            <value>
                <fullName>Driver Support</fullName>
            </value>
            <value>
                <fullName>Driver Tech Trainee</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>Lead Donor Ambassador</fullName>
            </value>
            <value>
                <fullName>Licensed Nurse</fullName>
            </value>
            <value>
                <fullName>Limited HH</fullName>
            </value>
            <value>
                <fullName>Limited Ship</fullName>
            </value>
            <value>
                <fullName>NCE Staff</fullName>
            </value>
            <value>
                <fullName>OJI</fullName>
            </value>
            <value>
                <fullName>Pickup Driver</fullName>
            </value>
            <value>
                <fullName>Plasma</fullName>
            </value>
            <value>
                <fullName>Post Collections</fullName>
            </value>
            <value>
                <fullName>Regulated - Medical Screeners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Dispatch</fullName>
                <default>true</default>
                <label>Pending Dispatch</label>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <formula>TEXT(sked__Job__r.sked_Resource_Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Tag__c/sked__Resource_Tag__c.object-meta.xml
<CustomObject>
    <label>Resource Tag</label>
    <nameField>
        <displayFormat>RT-{0}</displayFormat>
        <label>ResourceTag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Tag__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipName>ResourceTags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Tag__c/fields/sked__Tag__c.field-meta.xml
<CustomField>
    <fullName>sked__Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>sked__Tag__c</referenceTo>
    <relationshipName>ResourceTags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Tag__c/fields/sked_Role_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Role_Status__c</fullName>
    <label>Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Tag__c/sked__Tag__c.object-meta.xml
<CustomObject>
    <description>string metadata to be associated  with any other object</description>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Tag__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Asset Type</fullName>
            </value>
            <value>
                <fullName>Physical Location Type</fullName>
            </value>
            <value>
                <fullName>Drive Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/sked_Resource_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC Sign-off</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - 2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Charge Mentor</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Competent Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Drive Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL A</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL B</fullName>
    </customValue>
    <customValue>
        <fullName>Driver - DOT</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Prestaff</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Tech Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Float</fullName>
    </customValue>
    <customValue>
        <fullName>FS Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>HH</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Donor Ambassador</fullName>
    </customValue>
    <customValue>
        <fullName>Licensed Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Limited HH</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Ship</fullName>
    </customValue>
    <customValue>
        <fullName>NCE Staff</fullName>
    </customValue>
    <customValue>
        <fullName>OJI</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <customValue>
        <fullName>Post Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screeners</fullName>
    </customValue>
    <masterLabel>Resource Roles</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/skedResourceTagTrigger_ExceptionTest.cls
@isTest
private class skedResourceTagTrigger_ExceptionTest {

    static testmethod void roleStatusException() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        
        mapTestData = testDataFactory.setupDriveData();
        
        Biomed_Collection_Op_Center__c testCollectionOperation1 = (Biomed_Collection_Op_Center__c)mapTestData.get('testCollectionOperation1');
        sked_Drive__c testDrive1 = (sked_Drive__c)mapTestData.get('testDrive1');
        sked__Resource__c testResource1 = (sked__Resource__c)mapTestData.get('testResource1');
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        
        Test.startTest();
        
        sked__Tag__c x2rbcTag = [SELECT Id
                                 FROM sked__Tag__c
                                 WHERE Name = '2RBC'
                                 AND sked__Type__c = :skedConstants.TAG_TYPE_ROLE];
        sked__Resource_Tag__c testResource1_2rbc = new sked__Resource_Tag__c(
            sked__Resource__c = testResource1.Id,
            sked__Tag__c = x2rbcTag.Id,
            sked_Start_Date__c = testDataFactory.summary.startDate,
            sked_Role_Status__c = skedConstants.TAG_ROLE_STATUS_ACTIVE
        );
        insert testResource1_2rbc;
        
        List<sObject> secondList = new List<sObject>();
        
        sked__Job__c job1 = new sked__Job__c(
            sked__Region__c = testRegion1.Id,
            sked__Start__c = testDataFactory.summary.startTime.addHours(9),
            sked__Finish__c = testDataFactory.summary.startTime.addHours(10),
            sked__Duration__c = 60,
            sked__Job_Status__c = skedConstants.JOB_STATUS_PENDING_ALLOCATION,
            sked_Drive__c = testDrive1.Id,
            sked_Resource_Role__c = '2RBC',
            sked__GeoLocation__Latitude__s = 51.508105,
            sked__GeoLocation__Longitude__s = -0.132901
        );
        secondList.add(job1);
        insert secondList;

        List<sObject> thirdList = new List<sObject>();
        sked__Job_Allocation__c testResource1_job1 = new sked__Job_Allocation__c(
            sked__Job__c = job1.Id,
            sked__Resource__c = testResource1.Id,
            sked__Status__c = skedConstants.JOB_ALLOCATION_STATUS_PENDING_DISPATCH
        );
        thirdList.add(testResource1_job1);
        insert thirdList;
        
        testResource1_2rbc.sked_Role_Status__c = skedConstants.TAG_ROLE_STATUS_INACTIVE;
        update testResource1_2rbc;
        
        Test.stopTest();
    }
    
}