force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Is_Deactivated__c.field-meta.xml
<CustomField>
    <fullName>sked_Is_Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Territory__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipName>sked_Biomed_Collection_Ops_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Territory__c/sked_Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Territory_Collection_Operation__c/sked_Territory_Collection_Operation__c.object-meta.xml
<CustomObject>
    <label>Territory Collection Operation</label>
    <nameField>
        <displayFormat>TCO-{000000}</displayFormat>
        <label>Territory Collection Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Collection Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Territory_Collection_Operation__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Territory Collection Operations</relationshipLabel>
    <relationshipName>sked_Territory_Collection_Operations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Territory_Collection_Operation__c/fields/sked_Territory__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory__c</fullName>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipLabel>Territory Collection Operations</relationshipLabel>
    <relationshipName>sked_Territory_Collection_Operations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/skedTerritoryService.cls
global class skedTerritoryService extends skedDataService {
    
    protected override void initialize() {
        this.sObjectApiName = 'sked_Territory__c';
        this.objectTYpe = 'territory';
        this.domainType = Type.forName('skedModels.territory');
    }
    
    protected override void getQueryConditions(skedQueryBuilder queryBuilder, queryModelBase inputModel) {
        queryModel query = (queryModel)inputModel;
        Date startDate, endDate;
        if (!string.isBlank(query.startDate)) {
            startDate = skedDateTimeUtils.getDateFromIsoString(query.startDate);
        }
        if (!string.isBlank(query.endDate)) {
            endDate = skedDateTimeUtils.getDateFromIsoString(query.endDate);
        }
        
        List<String> excludedCONames = new List<String>{skedConstants.NON_COLLECTION_AREA_CO};
        skedQueryBuilder territoryCollectionOperationBuilder = query.getQueryBuilder('sked_Territory_Collection_Operation__c');
        if (startDate != NULL && endDate != NULL) {
            territoryCollectionOperationBuilder.addCondition('(sked_Start_Date__c = NULL OR sked_Start_Date__c <= {0})', endDate);
            territoryCollectionOperationBuilder.addCondition('(sked_End_Date__c = NULL OR sked_End_Date__c >= {0})', startDate);
        }
        territoryCollectionOperationBuilder.addCondition('sked_Collection_Operation__r.sked_Is_Deactivated__c = FALSE');
        territoryCollectionOperationBuilder.addCondition('sked_Collection_Operation__r.Name NOT IN {0}', excludedCONames);
        
        queryBuilder.addCondition('Name NOT IN {0}', excludedCONames);
    }
    
    /*********************************************************** Nested class ***********************************************************/
    public class queryModel extends skedDataService.queryModelBase {
        public string endDate;
        public string startDate;
    }

}