force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Waitlist_Enabled__c.field-meta.xml
<CustomField>
    <fullName>sked_Waitlist_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether or not PTO waitlist is enabled for this CO</description>
    <label>Waitlist Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/skedBiomedCollectionOpUtils.cls
public class skedBiomedCollectionOpUtils {
    public static String getBiomedCollectionOpWaitlistStatus(Id collectionOpId) {
        Biomed_Collection_Op_Center__c collectionOp = [
            SELECT Id, sked_Waitlist_Enabled__c
            FROM Biomed_Collection_Op_Center__c
            WHERE Id = :collectionOpId
        ];

        return collectionOp.sked_Waitlist_Enabled__c ? skedConstants.AVAILABILITY_STATUS_WAITLIST : skedConstants.AVAILABILITY_STATUS_DECLINED;
    }
}