force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Quantity__c.field-meta.xml
<CustomField>
    <fullName>sked__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>2RBC</fullName>
            </value>
            <value>
                <fullName>2RBC Sign-off</fullName>
            </value>
            <value>
                <fullName>Apheresis</fullName>
            </value>
            <value>
                <fullName>Apheresis Charge</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Charge - 2RBC</fullName>
            </value>
            <value>
                <fullName>Charge Mentor</fullName>
            </value>
            <value>
                <fullName>Charge - Special Collections</fullName>
            </value>
            <value>
                <fullName>Competent Driver</fullName>
            </value>
            <value>
                <fullName>Drive Lead</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Driver CDL A</fullName>
            </value>
            <value>
                <fullName>Driver CDL B</fullName>
            </value>
            <value>
                <fullName>Driver - DOT</fullName>
            </value>
            <value>
                <fullName>Driver Prestaff</fullName>
            </value>
            <value>
                <fullName>Driver Support</fullName>
            </value>
            <value>
                <fullName>Driver Tech Trainee</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>Lead Donor Ambassador</fullName>
            </value>
            <value>
                <fullName>Licensed Nurse</fullName>
            </value>
            <value>
                <fullName>Limited HH</fullName>
            </value>
            <value>
                <fullName>Limited Ship</fullName>
            </value>
            <value>
                <fullName>NCE Staff</fullName>
            </value>
            <value>
                <fullName>OJI</fullName>
            </value>
            <value>
                <fullName>Pickup Driver</fullName>
            </value>
            <value>
                <fullName>Plasma</fullName>
            </value>
            <value>
                <fullName>Post Collections</fullName>
            </value>
            <value>
                <fullName>Regulated - Medical Screeners</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Asset_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_CDL__c.field-meta.xml
<CustomField>
    <fullName>sked_CDL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_DOT__c.field-meta.xml
<CustomField>
    <fullName>sked_DOT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <formula>sked__Job__r.sked_Drive__r.sked_Drive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <formula>TEXT(sked__Job__r.sked_Resource_Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Category__c.field-meta.xml
<CustomField>
    <fullName>sked__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked__Resource_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Cargo Van</fullName>
            </value>
            <value>
                <fullName>ProMaster</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>sked__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Primary_Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Primary_Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource_Type__c</fullName>
    <description>Is the resource a human or otherwise</description>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Asset_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Pres_Donor_Capacity__c.field-meta.xml
<CustomField>
    <fullName>sked_Pres_Donor_Capacity__c</fullName>
    <label>Pres Donor Capacity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_No_of_Allocated_Buses__c.field-meta.xml
<CustomField>
    <fullName>sked_No_of_Allocated_Buses__c</fullName>
    <label># of Allocated Buses</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_No_of_Allocated_CDL__c.field-meta.xml
<CustomField>
    <fullName>sked_No_of_Allocated_CDL__c</fullName>
    <label># of Allocated CDL</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_No_of_Allocated_DOT__c.field-meta.xml
<CustomField>
    <fullName>sked_No_of_Allocated_DOT__c</fullName>
    <label># of Allocated DOT</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sked_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Vehicle_Capacity__c.field-meta.xml
<CustomField>
    <fullName>sked_Vehicle_Capacity__c</fullName>
    <label>Vehicle Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Vehicle_Types__c.field-meta.xml
<CustomField>
    <fullName>sked_Vehicle_Types__c</fullName>
    <label>Vehicle Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Cargo Van</fullName>
            </value>
            <value>
                <fullName>ProMaster</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/sked_Asset_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/sked_Resource_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC Sign-off</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - 2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Charge Mentor</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Competent Driver</fullName>
    </customValue>
    <customValue>
        <fullName>CT1</fullName>
    </customValue>
    <customValue>
        <fullName>Drive Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL B</fullName>
    </customValue>
    <customValue>
        <fullName>Driver - DOT</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Prestaff</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Tech Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>FS Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>HH</fullName>
    </customValue>
    <customValue>
        <fullName>Licensed Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Limited HH</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Ship</fullName>
    </customValue>
    <customValue>
        <fullName>NCE Staff</fullName>
    </customValue>
    <customValue>
        <fullName>OJI</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <customValue>
        <fullName>Post Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screeners</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - RNOR</fullName>
    </customValue>
    <customValue>
        <fullName>Special Collections</fullName>
    </customValue>
    <masterLabel>Resource Roles</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/UpdateDrivesVehicleAllocationFieldsTest.cls
@isTest
public class UpdateDrivesVehicleAllocationFieldsTest {
	@istest
    public static void updateDriveFieldsTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.testSetupForMobileDriveV2();
        Opportunity mobileOpportunity = (Opportunity)mapTestData.get('mobileOpportunity');
        
        MobileDriveGeneratorDMLService.driveGeneratorConfig config = new MobileDriveGeneratorDMLService.driveGeneratorConfig();
        config.oppIds = new Set<Id>();
        config.oppIds.add(mobileOpportunity.Id);

        AccountTeamMemberHelper.skipAccountTrigger = true;
        skedHubBase.BypassUpdateTriggers = TRUE;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('DriveTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('BSFTaskChecklistTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        Test.startTest();
        GenerateMobileDrive.generateDrives(config);
        
        List<sked_Drive__c> driveList = [SELECT Id, sked_Drive_Date__c, sked_Type_of_Drive__c, sked_No_of_Allocated_Buses__c, sked_No_of_Allocated_CDL__c, sked_No_of_Allocated_DOT__c, sked_Vehicle_Types__c, sked_Vehicle_Capacity__c, (SELECT Id, sked_Drive__c,sked__Type__c,sked__Quantity__c, sked_Resource_Role__c, sked_Asset_Type__c FROM sked_Jobs__r where sked__Type__c = 'Vehicle') FROM sked_Drive__c WHERE sked_Opportunity__c IN: config.oppIds];
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Resource__c testVehicle = new sked__Resource__c(
                Name = 'Test Vehicle ',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 50,
                sked__Is_Active__c = TRUE,
            	sked_DOT__c = TRUE,
            	sked__Category__c = 'Bus'
            );
        insert testVehicle;
        List<sked__Job__c> Jobs = driveList[0].sked_Jobs__r;
        sked__Job_Allocation__c jobAllocation = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c =   testVehicle.Id          
        );
        insert jobAllocation;
        
        UpdateDrivesVehicleAllocationFieldsBatch batch1 = new UpdateDrivesVehicleAllocationFieldsBatch('Mobile');
        Database.executeBatch(batch1, 100);
        
        skedSetting.instance.Admin.migrationMode = FALSE;

        skedHubBase.BypassInsertTriggers = FALSE;
        skedHubBase.BypassUpdateTriggers = FALSE;
        Test.stopTest();
    }
    
    @istest
    public static void unitTestToUpdateDriveMultipleVehicleAllocationTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.testSetupForMobileDriveV2();
        Opportunity mobileOpportunity = (Opportunity)mapTestData.get('mobileOpportunity');
        
        MobileDriveGeneratorDMLService.driveGeneratorConfig config = new MobileDriveGeneratorDMLService.driveGeneratorConfig();
        config.oppIds = new Set<Id>();
        config.oppIds.add(mobileOpportunity.Id);

        AccountTeamMemberHelper.skipAccountTrigger = true;
        skedHubBase.BypassUpdateTriggers = TRUE;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('DriveTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('BSFTaskChecklistTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        Test.startTest();
        GenerateMobileDrive.generateDrives(config);
        
        
        List<sked_Drive__c> driveList = [SELECT Id, sked_Drive_Date__c, sked_Type_of_Drive__c, sked_No_of_Allocated_Buses__c, sked_No_of_Allocated_CDL__c, sked_No_of_Allocated_DOT__c, sked_Vehicle_Types__c, sked_Vehicle_Capacity__c, (SELECT Id, sked_Drive__c,sked__Type__c,sked__Quantity__c, sked_Resource_Role__c, sked_Asset_Type__c FROM sked_Jobs__r where sked__Type__c = 'Vehicle') FROM sked_Drive__c WHERE sked_Opportunity__c IN: config.oppIds];
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Resource__c testVehicle = new sked__Resource__c(
                Name = 'Test Vehicle ',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 50,
                sked__Is_Active__c = TRUE,
            	sked_DOT__c = TRUE,
            	sked__Category__c = 'Bus'
            );
        insert testVehicle;
        
        sked__Resource__c testVehicle1 = new sked__Resource__c(
                Name = 'Test Vehicle 1',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 25,
                sked__Is_Active__c = TRUE,
            	sked_CDL__c = TRUE,
            	sked__Category__c = 'Truck'
            );
        insert testVehicle1;
        
        List<sked__Job__c> Jobs = driveList[0].sked_Jobs__r;
        List<sked__Job_Allocation__c> jobAllocationList = new List<sked__Job_Allocation__c>();
        sked__Job_Allocation__c jobAllocation = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle.Id          
        );
        jobAllocationList.add(jobAllocation);
        
        sked__Job_Allocation__c jobAllocation1 = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle1.Id          
        );
        jobAllocationList.add(jobAllocation1);
        
        insert jobAllocationList;
        
        UpdateDrivesVehicleAllocationFieldsBatch batch1 = new UpdateDrivesVehicleAllocationFieldsBatch('Mobile');
        Database.executeBatch(batch1, 100);
        
        skedSetting.instance.Admin.migrationMode = FALSE;

        skedHubBase.BypassInsertTriggers = FALSE;
        skedHubBase.BypassUpdateTriggers = FALSE;
        Test.stopTest();
    }
    
    @istest
    public static void unitTestForCustomDateConstructorTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.testSetupForMobileDriveV2();
        Opportunity mobileOpportunity = (Opportunity)mapTestData.get('mobileOpportunity');
        
        MobileDriveGeneratorDMLService.driveGeneratorConfig config = new MobileDriveGeneratorDMLService.driveGeneratorConfig();
        config.oppIds = new Set<Id>();
        config.oppIds.add(mobileOpportunity.Id);

        AccountTeamMemberHelper.skipAccountTrigger = true;
        skedHubBase.BypassUpdateTriggers = TRUE;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('DriveTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('BSFTaskChecklistTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        Test.startTest();
        GenerateMobileDrive.generateDrives(config);
        List<sked_Drive__c> driveList = [SELECT Id, sked_Drive_Date__c, sked_Type_of_Drive__c, sked_No_of_Allocated_Buses__c, sked_No_of_Allocated_CDL__c, sked_No_of_Allocated_DOT__c, sked_Vehicle_Types__c, sked_Vehicle_Capacity__c, (SELECT Id, sked_Drive__c,sked__Type__c,sked__Quantity__c, sked_Resource_Role__c, sked_Asset_Type__c FROM sked_Jobs__r where sked__Type__c = 'Vehicle') FROM sked_Drive__c WHERE sked_Opportunity__c IN: config.oppIds];
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Resource__c testVehicle = new sked__Resource__c(
                Name = 'Test Vehicle ',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 50,
                sked__Is_Active__c = TRUE,
            	sked_DOT__c = TRUE,
            	sked__Category__c = 'Bus'
            );
        insert testVehicle;
        List<sked__Job__c> Jobs = driveList[0].sked_Jobs__r;
        List<sked__Job_Allocation__c> jobAllocationList = new List<sked__Job_Allocation__c>();
        sked__Job_Allocation__c jobAllocation = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle.Id          
        );
        jobAllocationList.add(jobAllocation);
        
        insert jobAllocationList;
        
        Integer month = Date.today().month(); 
        Integer year = Date.today().year(); 
        Integer todayDate = Date.today().day(); 
        
        Date date1 = Date.newInstance(year,month,todayDate);
    	Date date2 = Date.newInstance(year,month,todayDate);
    	String typeOfDrive = 'Mobile';
    
    	UpdateDrivesVehicleAllocationFieldsBatch batchObject = new UpdateDrivesVehicleAllocationFieldsBatch(date1, date2, typeOfDrive);
    	Database.executeBatch(batchObject,100);
        
        skedSetting.instance.Admin.migrationMode = FALSE;

        skedHubBase.BypassInsertTriggers = FALSE;
        skedHubBase.BypassUpdateTriggers = FALSE;
        Test.stopTest();
    }
    
    @istest
    public static void unitTestForScheduledBatchRunwithFirstconstructorTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.testSetupForMobileDriveV2();
        Opportunity mobileOpportunity = (Opportunity)mapTestData.get('mobileOpportunity');
        
        MobileDriveGeneratorDMLService.driveGeneratorConfig config = new MobileDriveGeneratorDMLService.driveGeneratorConfig();
        config.oppIds = new Set<Id>();
        config.oppIds.add(mobileOpportunity.Id);

        AccountTeamMemberHelper.skipAccountTrigger = true;
        skedHubBase.BypassUpdateTriggers = TRUE;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('DriveTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('BSFTaskChecklistTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        Test.startTest();
        GenerateMobileDrive.generateDrives(config);
        List<sked_Drive__c> driveList = [SELECT Id, sked_Drive_Date__c, sked_Type_of_Drive__c, sked_No_of_Allocated_Buses__c, sked_No_of_Allocated_CDL__c, sked_No_of_Allocated_DOT__c, sked_Vehicle_Types__c, sked_Vehicle_Capacity__c, (SELECT Id, sked_Drive__c,sked__Type__c,sked__Quantity__c, sked_Resource_Role__c, sked_Asset_Type__c FROM sked_Jobs__r where sked__Type__c = 'Vehicle') FROM sked_Drive__c WHERE sked_Opportunity__c IN: config.oppIds];
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Resource__c testVehicle = new sked__Resource__c(
                Name = 'Test Vehicle ',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 50,
                sked__Is_Active__c = TRUE,
            	sked_DOT__c = TRUE,
            	sked__Category__c = 'Bus'
            );
        insert testVehicle;
        
        sked__Resource__c testVehicle1 = new sked__Resource__c(
                Name = 'Test Vehicle 1',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 25,
                sked__Is_Active__c = TRUE,
            	sked_CDL__c = TRUE,
            	sked__Category__c = 'Truck'
            );
        insert testVehicle1;
        
        List<sked__Job__c> Jobs = driveList[0].sked_Jobs__r;
        List<sked__Job_Allocation__c> jobAllocationList = new List<sked__Job_Allocation__c>();
        sked__Job_Allocation__c jobAllocation = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle.Id          
        );
        jobAllocationList.add(jobAllocation);
        
        sked__Job_Allocation__c jobAllocation1 = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle1.Id          
        );
        jobAllocationList.add(jobAllocation1);
        
        insert jobAllocationList;
        
        Datetime now = Datetime.now().addMinutes(1); // Get the time 1 minute from now
        Integer second = now.second();
        Integer minute = now.minute();
        Integer hour = now.hour();
        
        String cronExp = second + ' ' + minute + ' ' + hour + ' * * ?'; // Repeats daily at the same time
        
        String typeOfDrive = 'Mobile';
        UpdateDrivesVehicleAllocationSchedulable schedulerJob = new UpdateDrivesVehicleAllocationSchedulable(typeOfDrive);
        System.schedule('Test Schedule UpdateDrivesVehicleAllocationSchedulable', cronExp, schedulerJob);
        
        skedSetting.instance.Admin.migrationMode = FALSE;

        skedHubBase.BypassInsertTriggers = FALSE;
        skedHubBase.BypassUpdateTriggers = FALSE;
        Test.stopTest();
    }
    
    @istest
    public static void unitTestForScheduledBatchRunwithSecondconstructorTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.testSetupForMobileDriveV2();
        Opportunity mobileOpportunity = (Opportunity)mapTestData.get('mobileOpportunity');
        
        MobileDriveGeneratorDMLService.driveGeneratorConfig config = new MobileDriveGeneratorDMLService.driveGeneratorConfig();
        config.oppIds = new Set<Id>();
        config.oppIds.add(mobileOpportunity.Id);

        AccountTeamMemberHelper.skipAccountTrigger = true;
        skedHubBase.BypassUpdateTriggers = TRUE;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('DriveTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('BSFTaskChecklistTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        Test.startTest();
        GenerateMobileDrive.generateDrives(config);
        List<sked_Drive__c> driveList = [SELECT Id, sked_Drive_Date__c, sked_Type_of_Drive__c, sked_No_of_Allocated_Buses__c, sked_No_of_Allocated_CDL__c, sked_No_of_Allocated_DOT__c, sked_Vehicle_Types__c, sked_Vehicle_Capacity__c, (SELECT Id, sked_Drive__c,sked__Type__c,sked__Quantity__c, sked_Resource_Role__c, sked_Asset_Type__c FROM sked_Jobs__r where sked__Type__c = 'Vehicle') FROM sked_Drive__c WHERE sked_Opportunity__c IN: config.oppIds];
        sked__Region__c testRegion1 = (sked__Region__c)mapTestData.get('testRegion1');
        sked__Resource__c testVehicle = new sked__Resource__c(
                Name = 'Test Vehicle ',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 50,
                sked__Is_Active__c = TRUE,
            	sked_DOT__c = TRUE,
            	sked__Category__c = 'Bus'
            );
        insert testVehicle;
        
        sked__Resource__c testVehicle1 = new sked__Resource__c(
                Name = 'Test Vehicle 1',
                sked__Primary_Region__c = testRegion1.Id,
                sked__Resource_Type__c = 'Asset',
                sked_Asset_Type__c = 'Vehicle',
                sked_Pres_Donor_Capacity__c = 25,
                sked__Is_Active__c = TRUE,
            	sked_CDL__c = TRUE,
            	sked__Category__c = 'Truck'
            );
        insert testVehicle1;
        
        List<sked__Job__c> Jobs = driveList[0].sked_Jobs__r;
        List<sked__Job_Allocation__c> jobAllocationList = new List<sked__Job_Allocation__c>();
        sked__Job_Allocation__c jobAllocation = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle.Id          
        );
        jobAllocationList.add(jobAllocation);
        
        sked__Job_Allocation__c jobAllocation1 = new sked__Job_Allocation__c (
        	sked__Job__c = Jobs[0].Id,
			sked__Resource__c = testVehicle1.Id          
        );
        jobAllocationList.add(jobAllocation1);
        
        insert jobAllocationList;
        
        Datetime now = Datetime.now().addMinutes(1); // Get the time 1 minute from now
        Integer second = now.second();
        Integer minute = now.minute();
        Integer hour = now.hour();
        
        String cronExp = second + ' ' + minute + ' ' + hour + ' * * ?'; // Repeats daily at the same time

		Integer month = Date.today().month(); 
        Integer year = Date.today().year(); 
        Integer todayDate = Date.today().day(); 
        
        Date toDate = Date.newInstance(year,month,todayDate);
    	Date fromDate = Date.newInstance(year,month,todayDate);
    	String typeOfDrive = 'Mobile';
    
    	UpdateDrivesVehicleAllocationSchedulable schedulerJob = new UpdateDrivesVehicleAllocationSchedulable(toDate, fromDate, typeOfDrive);
        System.schedule('update Drives Vehicle Allocation for custom drive date', cronExp, schedulerJob);
        
        skedSetting.instance.Admin.migrationMode = FALSE;

        skedHubBase.BypassInsertTriggers = FALSE;
        skedHubBase.BypassUpdateTriggers = FALSE;
        Test.stopTest();
    }
}