force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Job_Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Pending Allocation</fullName>
            </value>
            <value>
                <fullName>Pending Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <label>Location</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Category__c.field-meta.xml
<CustomField>
    <fullName>sked__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked__Resource_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Cargo Van</fullName>
            </value>
            <value>
                <fullName>ProMaster</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Email__c.field-meta.xml
<CustomField>
    <fullName>sked__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__User__c.field-meta.xml
<CustomField>
    <fullName>sked__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>sked_Employee_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Workday External ID</inlineHelpText>
    <label>Employee ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_First_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_ULID__c.field-meta.xml
<CustomField>
    <fullName>sked_ULID__c</fullName>
    <externalId>true</externalId>
    <label>ULID (A #)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Donors_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>sked_Donors_Scheduled__c</fullName>
    <label>Donors Scheduled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>Draw End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Equipment__c.field-meta.xml
<CustomField>
    <fullName>sked_Equipment__c</fullName>
    <label>Equipment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Order__c.field-meta.xml
<CustomField>
    <fullName>sked_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Staff_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Setup__c</fullName>
    <label>Staff Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Draw Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Vehicles_Needed__c.field-meta.xml
<CustomField>
    <fullName>sked_Vehicles_Needed__c</fullName>
    <label>Vehicles Needed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Volunteer_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Volunteer_Setup__c</fullName>
    <label>Volunteer Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/sked_Operation_Record__c.object-meta.xml
<CustomObject>
    <label>Operation Record</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Operation Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Operation Records</relationshipLabel>
    <relationshipName>sked_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <formula>sked_Drive__r.sked_Drive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Operation Records</relationshipLabel>
    <relationshipName>sked_Operation_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <formula>sked_Drive__r.sked_End_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <formula>sked_Drive__r.sked_Start_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/BSF_DeleteVolunteerOpRecordsJob_Test.cls
@IsTest
private class BSF_DeleteVolunteerOpRecordsJob_Test {

    @IsTest
    static void execute_deletesYesterdayVolunteerStaff_leavesOthers() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<String, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        sked__Location__c testLocation1 = (sked__Location__c) mapTestData.get('testLocation1');
        sked__Region__c testRegion1 = (sked__Region__c) mapTestData.get('testRegion1');
        sked__Resource__c employeeResource = (sked__Resource__c) mapTestData.get('testResource1');

        sked__Resource__c volunteerResource = employeeResource.clone(false, true, false, false);
        volunteerResource.Name = 'Volunteer Delete Job Resource';
        volunteerResource.sked__Category__c = BSF_WorkdayDirectSubmissionConfig.RESOURCE_CATEGORY_VOLUNTEER;
        volunteerResource.sked_Employee_ID__c = 'VOLDEL1';
        volunteerResource.sked_ULID__c = 'ULIDVOLDEL1';
        volunteerResource.sked_First_Name__c = 'Volunteer';
        volunteerResource.sked_Last_Name__c = 'Delete';
        volunteerResource.sked__User__c = null;
        volunteerResource.sked__Email__c = 'volunteer.delete@example.test';
        insert volunteerResource;

        sked_Drive_Shift__c testDriveShift = new sked_Drive_Shift__c(
            sked_Donors_Scheduled__c = 1, sked_End_Time__c = Time.newInstance(20, 0, 0, 0),
            sked_Start_Time__c = Time.newInstance(14, 0, 0, 0), sked_Drive__c = testDrive.Id,
            sked_Drive_Date__c = testDrive.sked_Drive_Date__c, sked_Equipment__c = 1,
            sked_Lunch_Break__c = false, sked_Order__c = 1, sked_Staff_Setup__c = 1,
            sked_Vehicles_Needed__c = 1, sked_Volunteer_Setup__c = 1
        );
        insert testDriveShift;

        sked__Job__c testJob = new sked__Job__c(
            sked__Region__c = testRegion1.Id, sked_Drive__c = testDrive.Id,
            sked_Drive_Shift__c = testDriveShift.Id, sked__Location__c = testLocation1.Id,
            sked__Job_Status__c = skedConstants.JOB_STATUS_PENDING_ALLOCATION,
            sked_Resource_Role__c = 'VP/HH', sked_VPHH_Quantity__c = 1,
            sked_APT_Quantity__c = 0, sked__Quantity__c = 1,
            sked__Duration__c = 60, sked__Start__c = System.now(), sked__Finish__c = System.now().addHours(1),
            sked__Actual_Start__c = System.now(), sked__Actual_End__c = System.now().addHours(1)
        );
        insert testJob;

        sked_Operation_Record__c op = new sked_Operation_Record__c(
            sked_Drive__c = testDrive.Id, sked_Drive_Shift__c = testDriveShift.Id,
            sked_Status__c = 'Not Submitted', sked_Locked__c = true,
            sked_Workday_Submission_Status__c = BSF_WorkdayDirectSubmissionConfig.STATUS_DRAFT,
            sked_Power_Red_Machines_Sent__c = 1, sked_Power_Red_Machines_Used__c = 1,
            sked_Submitted_By__c = employeeResource.Id, sked_Donor_Ambassadors_Actual__c = 0
        );
        insert op;

        sked_Operation_Record_Staff__c volunteerStaffYesterday = new sked_Operation_Record_Staff__c(
            sked_Operation_Record__c = op.Id, sked_Job__c = testJob.Id,
            sked_Resource__c = volunteerResource.Id, sked_Absent__c = false,
            sked_Actual_Roles__c = 'Driver'
        );
        insert volunteerStaffYesterday;
        Test.setCreatedDate(volunteerStaffYesterday.Id, System.now().addDays(-1));

        sked_Operation_Record_Staff__c volunteerStaffToday = new sked_Operation_Record_Staff__c(
            sked_Operation_Record__c = op.Id, sked_Job__c = testJob.Id,
            sked_Resource__c = volunteerResource.Id, sked_Absent__c = false,
            sked_Actual_Roles__c = 'Driver'
        );
        insert volunteerStaffToday;

        sked_Operation_Record_Staff__c employeeStaffYesterday = new sked_Operation_Record_Staff__c(
            sked_Operation_Record__c = op.Id, sked_Job__c = testJob.Id,
            sked_Resource__c = employeeResource.Id, sked_Absent__c = false,
            sked_Actual_Roles__c = 'Driver'
        );
        insert employeeStaffYesterday;
        Test.setCreatedDate(employeeStaffYesterday.Id, System.now().addDays(-1));

        Test.startTest();
        Database.executeBatch(new BSF_DeleteVolunteerOpRecordsJob(), 50);
        Test.stopTest();

        System.assertEquals(
            0,
            [SELECT COUNT() FROM sked_Operation_Record_Staff__c WHERE Id = :volunteerStaffYesterday.Id],
            'Yesterday volunteer staff should be deleted'
        );
      
    }

   
}