force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>2RBC</fullName>
            </value>
            <value>
                <fullName>2RBC Sign-off</fullName>
            </value>
            <value>
                <fullName>Apheresis</fullName>
            </value>
            <value>
                <fullName>Apheresis Charge</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Charge - 2RBC</fullName>
            </value>
            <value>
                <fullName>Charge Mentor</fullName>
            </value>
            <value>
                <fullName>Charge - Special Collections</fullName>
            </value>
            <value>
                <fullName>Competent Driver</fullName>
            </value>
            <value>
                <fullName>Drive Lead</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Driver CDL A</fullName>
            </value>
            <value>
                <fullName>Driver CDL B</fullName>
            </value>
            <value>
                <fullName>Driver - DOT</fullName>
            </value>
            <value>
                <fullName>Driver Prestaff</fullName>
            </value>
            <value>
                <fullName>Driver Support</fullName>
            </value>
            <value>
                <fullName>Driver Tech Trainee</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>Lead Donor Ambassador</fullName>
            </value>
            <value>
                <fullName>Licensed Nurse</fullName>
            </value>
            <value>
                <fullName>Limited HH</fullName>
            </value>
            <value>
                <fullName>Limited Ship</fullName>
            </value>
            <value>
                <fullName>NCE Staff</fullName>
            </value>
            <value>
                <fullName>OJI</fullName>
            </value>
            <value>
                <fullName>Pickup Driver</fullName>
            </value>
            <value>
                <fullName>Plasma</fullName>
            </value>
            <value>
                <fullName>Post Collections</fullName>
            </value>
            <value>
                <fullName>Regulated - Medical Screeners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Dual_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Dual_Role__c</fullName>
    <label>Dual Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Additional_Roles__c.field-meta.xml
<CustomField>
    <fullName>sked_Additional_Roles__c</fullName>
    <label>Additional Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Dual_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Dual_Role__c</fullName>
    <formula>TEXT(sked__Job__r.sked_Dual_Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dual Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <formula>TEXT(sked__Job__r.sked_Resource_Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/sked_Resource_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC Sign-off</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - 2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Charge Mentor</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Competent Driver</fullName>
    </customValue>
    <customValue>
        <fullName>CT1</fullName>
    </customValue>
    <customValue>
        <fullName>Drive Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL B</fullName>
    </customValue>
    <customValue>
        <fullName>Driver - DOT</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Prestaff</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Tech Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>FS Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>HH</fullName>
    </customValue>
    <customValue>
        <fullName>Licensed Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Limited HH</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Ship</fullName>
    </customValue>
    <customValue>
        <fullName>NCE Staff</fullName>
    </customValue>
    <customValue>
        <fullName>OJI</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <customValue>
        <fullName>Post Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screeners</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - RNOR</fullName>
    </customValue>
    <customValue>
        <fullName>Special Collections</fullName>
    </customValue>
    <masterLabel>Resource Roles</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/JobTriggerHandler.cls
/* Modification Log 
 *    Date					     Developer Name			     Comments
 * **********************************************************************************
 *  09/26/2024				      Priti Jana		        Logic for HRP-13522
 *  08/06/2025				      Krapy Tuli		        Logic for HRP-15160
 * **********************************************************************************
 */

public class JobTriggerHandler extends TriggerHandler implements Callable {
    
    public override void beforeUpdate() {}
    
    public override void afterUpdate() {
       if(super.getTriggerMethodsToBypass().indexOf('jobPopulateDriveSupervisoryRole') == -1) { 
        	jobPopulateDriveSupervisoryRole((List<sked__Job__c>)trigger.new, (Map<Id,sked__Job__c>)trigger.oldMap);
        }
        //HRP-15160
        if(super.getTriggerMethodsToBypass().indexOf('jobPopulateDriveSupervisoryRole') == -1) { 
        	populateAdditionalRole((List<sked__Job__c>)trigger.new, (Map<Id,sked__Job__c>)trigger.oldMap);
        }
    }
    
    public override void beforeInsert() {}
    
    public override void afterInsert() {
        if(super.getTriggerMethodsToBypass().indexOf('jobPopulateDriveSupervisoryRole') == -1) { 
        	jobPopulateDriveSupervisoryRole((List<sked__Job__c>)trigger.new, null);
        }
    }
    
    public override void afterDelete(){
         if(super.getTriggerMethodsToBypass().indexOf('jobPopulateDriveSupervisoryRole') == -1) {
             BSF_Constants.After_Delete = True;
        	 jobPopulateDriveSupervisoryRole((List<sked__Job__c>)trigger.old, null);
             BSF_Constants.After_Delete = False;
        }
    }
    
    /**************************************** CALLABLE INTERFACE  ***************************************/
    public static Object call(String methodName, Map<String, Object> params) {
        skedProcessEventResult result = new skedProcessEventResult();
        try {
            switch on methodName {
                when 'populateDriveSupervisoryRole' {
                    populateDriveSupervisoryRole((Set<Id>) JSON.deserialize((String) params.get('param1'), Set<Id>.class));
                }
                //HRP-15160
                when 'updateAdditionalRole' {
                    updateAdditionalRole((List<sked__Job_Allocation__c>) JSON.deserialize((String) params.get('param1'), List<sked__Job_Allocation__c>.class));
                }
                when else {
                    throw new skedException('Unable to locate Method: ' + methodName + ' in Class: ' + JobTriggerHandler.class.getName());
                }
            }
        } catch (skedException ex) {
            result.addError(ex);
        }
        return result;
    }
    
    /************************************************************************************************************************************************************/
    
    public static void jobPopulateDriveSupervisoryRole(List<sked__Job__c> newJobsList, Map<Id, sked__Job__c> oldJobsMap) {
        if(newJobsList == null || newJobsList.isEmpty()) {
            return;
        }
        Set<Id> driveIdsToUpdate = new Set<Id>();
        for (sked__Job__c newJob : newJobsList) {
            if(oldJobsMap != null && newJob.Id != null) {
                sked__Job__c oldJob = oldJobsMap.get(newJob.Id);           
        		if (newJob.sked_Resource_Role__c != oldJob.sked_Resource_Role__c ||
            		newJob.sked_Dual_Role__c != oldJob.sked_Dual_Role__c ||
            		newJob.sked__Type__c != oldJob.sked__Type__c) {
            		Id driveId = newJob.sked_Drive__c;
           			 if (driveId != null) {
               		 	driveIdsToUpdate.add(driveId);
             		}
            	}
           }
            else if(oldJobsMap == null && newJob.Id != null){
                	Id driveId = newJob.sked_Drive__c;
           			 if (driveId != null) {
               		 	driveIdsToUpdate.add(driveId);
             		}
            }
        }
        // Running the following process asynchronously - HRP-13522
		if (!System.isBatch()) {
            if(driveIdsToUpdate != NULL && !driveIdsToUpdate.isEmpty()) {
                skedFutureCallEventHandler.publishFutureCallEvent(
                    JobTriggerHandler.class.getName(),
                    'populateDriveSupervisoryRole',
                    driveIdsToUpdate
                );
            }
        } else {
            populateDriveSupervisoryRole(driveIdsToUpdate);
        }
    }
    
    private static void populateDriveSupervisoryRole(Set<Id> driveIdsToUpdate) {
        DriveTriggerService.populateDriveSupervisoryRole(driveIdsToUpdate);
    }
    // HRP-13522

    //HRP-15160 starts
    public static void populateAdditionalRole(List<sked__Job__c> newRecords, Map<Id, sked__Job__c> oldMap) {
        Set<Id> jobIds = new Set<Id>(); 
        for (sked__Job__c newRecord : newRecords) {
            sked__Job__c oldData = oldMap.get(newRecord.Id);
            if (newRecord.sked_Dual_Role__c != oldData.sked_Dual_Role__c) {
                jobIds.add(newRecord.id);
            }
        }
        if (!jobIds.isEmpty()) {
            List<sked__Job_Allocation__c> allocations = [Select Id , sked_Additional_Roles__c , sked_Dual_Role__c from sked__Job_Allocation__c where sked__Job__c in : jobIds ];
            if(!allocations.isEmpty()){
            if (!System.isBatch()) {
                skedFutureCallEventHandler.publishFutureCallEvent(
                    'JobTriggerHandler',
                    'updateAdditionalRole',
                    new List<sked__Job_Allocation__c>(allocations)
                );
            } else {
                JobTriggerHandler.updateAdditionalRole(new List<sked__Job_Allocation__c>(allocations));
            }
        }
        }
    }

    public static void updateAdditionalRole(List<sked__Job_Allocation__c> allocationList) {
        List<sked__Job_Allocation__c> updatedJA = new List<sked__Job_Allocation__c>();
        for(sked__Job_Allocation__c allocation : allocationList){
                List<string> additionalRoles = new List<string>();
                if(!string.isBlank(allocation.sked_Dual_Role__c)){
                    additionalRoles = allocation.sked_Dual_Role__c.split(';');
                    allocation.sked_Additional_Roles__c = string.join(additionalRoles, ';');
                }
                else{
                    allocation.sked_Additional_Roles__c = '';
                }
                    updatedJA.add(allocation);
            }
        if (!updatedJA.isEmpty()) {
            update updatedJA ;
        }
    }
    //HRP-15160 ends
}