force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Address__c.field-meta.xml
<CustomField>
    <fullName>sked__Address__c</fullName>
    <description>Address of the job</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Job_Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Pending Allocation</fullName>
            </value>
            <value>
                <fullName>Pending Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Address__c.field-meta.xml
<CustomField>
    <fullName>sked__Address__c</fullName>
    <description>The address of the location</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/skedUpdateJobAddressBatch.cls
public class skedUpdateJobAddressBatch implements Database.Batchable<sked__Job__c> {

    protected Set<Id> siteIds; 
    
    public skedUpdateJobAddressBatch(Set<Id> inputSiteIds) {
        this.siteIds = inputSiteIds;
    }
    
    public List<sked__Job__c> start(Database.BatchableContext BC) {
        return [SELECT Id, sked__Location__r.sked__Address__c, 
                sked__Location__r.sked__GeoLocation__Latitude__s, sked__Location__r.sked__GeoLocation__Longitude__s, 
                sked__Address__c, sked__GeoLocation__Latitude__s, sked__GeoLocation__Longitude__s
                FROM sked__Job__c
                WHERE sked__Location__c IN :this.siteIds
                AND sked_Drive__r.sked_Drive_Date__c >= TODAY
                AND sked__Job_Status__c != :skedConstants.JOB_STATUS_CANCELLED];   
    }
    
    public void execute(Database.BatchableContext BC, List<sked__Job__c> impactedJobs) {
        List<sked__Job__c> jobsToUpdate = new List<sked__Job__c>();
        for (sked__Job__c impactedJob : impactedJobs) {
            Boolean hasChange = false;
            if(impactedJob.sked__Address__c != impactedJob.sked__Location__r.sked__Address__c) {
                impactedJob.sked__Address__c = impactedJob.sked__Location__r.sked__Address__c;   
                hasChange = true;
            }
            if (impactedJob.sked__GeoLocation__Latitude__s != impactedJob.sked__Location__r.sked__GeoLocation__Latitude__s || 
                    impactedJob.sked__GeoLocation__Longitude__s != impactedJob.sked__Location__r.sked__GeoLocation__Longitude__s) {
                impactedJob.sked__GeoLocation__Latitude__s = impactedJob.sked__Location__r.sked__GeoLocation__Latitude__s;   
                impactedJob.sked__GeoLocation__Longitude__s = impactedJob.sked__Location__r.sked__GeoLocation__Longitude__s; 
                hasChange = true;
            }
            if (hasChange) {
                jobsToUpdate.add(impactedJob);
            } 
        }
        if (jobsToUpdate.size() > 0) {
            skedHubBase.BypassUpdateTriggers = TRUE;
            update jobsToUpdate;
            skedHubBase.BypassUpdateTriggers = FALSE;
        }
    }
    
    public void finish(Database.BatchableContext BC) {}
    
}