force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <description>duration (in minutes) of the job</description>
    <label>Duration</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Job_Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Pending Allocation</fullName>
            </value>
            <value>
                <fullName>Pending Dispatch</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>On Site</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Resource_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Dispatch</fullName>
                <default>true</default>
                <label>Pending Dispatch</label>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Role__c</fullName>
    <formula>TEXT(sked__Job__r.sked_Resource_Role__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Travel_Time_Back__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_Back__c</fullName>
    <label>Travel Time Back</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Travel_Time_To__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_To__c</fullName>
    <label>Travel Time  To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/sked_Resource_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>2RBC Sign-off</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis</fullName>
    </customValue>
    <customValue>
        <fullName>Apheresis Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - 2RBC</fullName>
    </customValue>
    <customValue>
        <fullName>Charge Mentor</fullName>
    </customValue>
    <customValue>
        <fullName>Charge - Special Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Competent Driver</fullName>
    </customValue>
    <customValue>
        <fullName>CT1</fullName>
    </customValue>
    <customValue>
        <fullName>Drive Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Driver CDL B</fullName>
    </customValue>
    <customValue>
        <fullName>Driver - DOT</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Prestaff</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Driver Tech Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>FS Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>HH</fullName>
    </customValue>
    <customValue>
        <fullName>Licensed Nurse</fullName>
    </customValue>
    <customValue>
        <fullName>Limited HH</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Ship</fullName>
    </customValue>
    <customValue>
        <fullName>NCE Staff</fullName>
    </customValue>
    <customValue>
        <fullName>OJI</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup Driver</fullName>
    </customValue>
    <customValue>
        <fullName>Plasma</fullName>
    </customValue>
    <customValue>
        <fullName>Post Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - Medical Screeners</fullName>
    </customValue>
    <customValue>
        <fullName>Regulated - RNOR</fullName>
    </customValue>
    <customValue>
        <fullName>Special Collections</fullName>
    </customValue>
    <masterLabel>Resource Roles</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/skedResourceAverageTravelTimeBatch_Test.cls
@isTest
private class skedResourceAverageTravelTimeBatch_Test {

    static testmethod void mainTest() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();
        
        skedMockTest mockTest = new skedMockTest();
        Test.setMock(HttpCalloutMock.class, mockTest);
        Test.startTest();
        sked__Region__c testRegion = (sked__Region__c) mapTestData.get('testRegion1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        sked__Resource__c testResource = (sked__Resource__c) mapTestData.get('testResource1');
        
        sked__Job__c testJob = new sked__Job__c(
            sked__Region__c = testRegion.Id,
            sked__Start__c = testDataFactory.summary.startTime.addHours(11).addMinutes(15),
            sked__Finish__c = testDataFactory.summary.startTime.addHours(11).addMInutes(30),
            sked__Duration__c = 15,
            sked__Job_Status__c = skedConstants.JOB_STATUS_PENDING_ALLOCATION,
            sked_Drive__c = testDrive.Id,
            sked_Resource_Role__c = '2RBC',
            sked__GeoLocation__Latitude__s = 51.508105,
            sked__GeoLocation__Longitude__s = -0.132901
        );
        insert testJob;
        
        sked__Job_Allocation__c testJobAllocation = new sked__Job_Allocation__c(
            sked__Job__c = testJob.Id,
            sked__Resource__c = testResource.Id,
            sked__Status__c = skedConstants.JOB_ALLOCATION_STATUS_PENDING_DISPATCH,
            sked_Travel_Time_To__c = 10,
            sked_Travel_Time_Back__c = 10
        );
        insert testJobAllocation;
        
        Database.executeBatch(new skedResourceAverageTravelTimeBatch());
        
        Test.stopTest();
    }
    
}