force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked_Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Type__c</fullName>
    <description>HRP-12864</description>
    <label>Drive Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Fixed Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/sked__Resource_Override__c.object-meta.xml
<CustomObject>
    <label>Resource Override</label>
    <nameField>
        <displayFormat>RO-{000}</displayFormat>
        <label>Resource Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked__End__c.field-meta.xml
<CustomField>
    <fullName>sked__End__c</fullName>
    <description>End date for when these overrides apply</description>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Resource Overrides</relationshipLabel>
    <relationshipName>Resource_Overrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <description>Start date for when these overrides apply</description>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Resource Overrides</relationshipLabel>
    <relationshipName>sked_Resource_Overrides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Is_Travel_Required__c.field-meta.xml
<CustomField>
    <fullName>sked_Is_Travel_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Travel Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_Back_End__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Back_End__c</fullName>
    <label>Travel Back End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_Back_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Back_End_Date__c</fullName>
    <label>Travel Back End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_Back_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Back_End_Time__c</fullName>
    <label>Travel Back End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_Back_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Back_Start__c</fullName>
    <label>Travel Back Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_Back_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Back_Start_Date__c</fullName>
    <label>Travel Back Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_Back_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Back_Start_Time__c</fullName>
    <label>Travel Back Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_To_End__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_To_End__c</fullName>
    <label>Travel To End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_To_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_To_End_Date__c</fullName>
    <label>Travel To End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_To_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_To_End_Time__c</fullName>
    <label>Travel To End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_To_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_To_Start__c</fullName>
    <label>Travel To Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_To_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_To_Start_Date__c</fullName>
    <label>Travel To Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Travel_To_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_To_Start_Time__c</fullName>
    <label>Travel To Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Tag__c/sked__Resource_Tag__c.object-meta.xml
<CustomObject>
    <label>Resource Tag</label>
    <nameField>
        <displayFormat>RT-{0}</displayFormat>
        <label>ResourceTag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Tag__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipName>ResourceTags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Tag__c/fields/sked__Tag__c.field-meta.xml
<CustomField>
    <fullName>sked__Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>sked__Tag__c</referenceTo>
    <relationshipName>ResourceTags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Staffing_Constraint__c/sked_Staffing_Constraint__c.object-meta.xml
<CustomObject>
    <label>Staffing Constraint</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Staffing Constraint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Constraints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Staffing_Constraint__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Staffing Constraints</relationshipLabel>
    <relationshipName>sked_Staffing_Constraints</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Staffing_Constraint__c/fields/sked_Date_of_Constraint__c.field-meta.xml
<CustomField>
    <fullName>sked_Date_of_Constraint__c</fullName>
    <label>Date of Constraint</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Staffing_Constraint__c/fields/sked_Total_Staff_Constraints__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Staff_Constraints__c</fullName>
    <label>Total Staff Constraints</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/skedResourceOverrideTrigger_Test.cls
@isTest
private class skedResourceOverrideTrigger_Test {
    @isTest
    static void skedResourceOverrideTrigger_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Test.startTest();
        Biomed_Collection_Op_Center__c testCollectionOperation1 = (Biomed_Collection_Op_Center__c)mapTestData.get('testCollectionOperation1');
        sked__Region__c testRegion = (sked__Region__c) mapTestData.get('testRegion1');
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        sked__Resource__c testResource = (sked__Resource__c) mapTestData.get('testResource1');
        sked__Tag__c mobileTag = [SELECT Id FROM sked__Tag__c WHERE Name = 'Mobile' LIMIT 1][0];
        
        skedHubBase.setBypassAllTriggers(true);
        insert new sked__Resource_Tag__c(
            sked_Start_Date__c = System.today().addYears(-1),
            sked__Resource__c = testResource.Id,
            sked__Tag__c = mobileTag.Id
        );

        sked_Staffing_Constraint__c testStaffingConstraintFS = new sked_Staffing_Constraint__c(
            sked_Collection_Operation__c = testCollectionOperation1.Id,
            sked_Date_of_Constraint__c = testDataFactory.summary.startDate,
            sked_Drive_Type__c = 'Fixed Site',
            sked_Total_Staff_Constraints__c = 20
        );
        sked_Staffing_Constraint__c testStaffingConstraintM = new sked_Staffing_Constraint__c(
            sked_Collection_Operation__c = testCollectionOperation1.Id,
            sked_Date_of_Constraint__c = testDataFactory.summary.startDate,
            sked_Drive_Type__c = 'Mobile',
            sked_Total_Staff_Constraints__c = 20
        );
        insert new List<sked_Staffing_Constraint__c>{testStaffingConstraintFS, testStaffingConstraintM};
        
        sked__Resource_Override__c testResourceOverride = new sked__Resource_Override__c(
            sked__Resource__c = testResource.Id,
            sked__Geolocation__Latitude__s = 30.7575256,
            sked__Geolocation__Longitude__s = -125.4730585,
            sked__End__c = System.now().addHours(6),
            sked__Start__c = System.now().addHours(6),
            sked_Collection_Operation__c = testCollectionOperation1.Id,
            sked_Travel_To_Start__c = System.now().addMinutes(5),
            sked_Travel_To_End__c = System.now().addMinutes(5),
            sked_Travel_Back_Start__c = System.now().addMinutes(5),
            sked_Travel_Back_End__c = System.now().addMinutes(5),
            sked_End_Date__c = System.today().addDays(5),
            sked_Start_Date__c = System.today().addDays(-5),
            sked_Travel_Back_End_Date__c = System.today().addDays(5),
            sked_Travel_Back_Start_Date__c = System.today(),
            sked_Travel_To_End_Date__c = System.today(),
            sked_Travel_To_Start_Date__c = System.today(),
            sked_End_Time__c = System.now().time(),
            sked_Travel_Back_End_Time__c = System.now().addMinutes(5).time(),
            sked_Travel_Back_Start_Time__c = System.now().time(),
            sked_Travel_To_End_Time__c = System.now().addMinutes(5).time(),
            sked_Start_Time__c = System.now().time(),
            sked_Travel_To_Start_Time__c = System.now().addMinutes(5).time(),
            sked_Is_Travel_Required__c = true
        );
        insert testResourceOverride;
        
        sked__Job__c testJob = new sked__Job__c(
            sked__Region__c = testRegion.Id,
            sked__Start__c = testDataFactory.summary.startTime.addHours(11).addMinutes(15),
            sked__Finish__c = testDataFactory.summary.startTime.addHours(11).addMInutes(30),
            sked__Duration__c = 15,
            sked__Job_Status__c = skedConstants.JOB_STATUS_PENDING_ALLOCATION,
            sked_Drive__c = testDrive.Id,
            sked_Resource_Role__c = '2RBC',
            sked__GeoLocation__Latitude__s = 51.508105,
            sked__GeoLocation__Longitude__s = -0.132901
        );
        insert testJob;
        
        sked__Job_Allocation__c testJobAllocation = new sked__Job_Allocation__c(
            sked__Job__c = testJob.Id,
            sked__Resource__c = testResource.Id,
            sked__Status__c = skedConstants.JOB_ALLOCATION_STATUS_PENDING_DISPATCH,
            sked_Roles_Assignment_Str__c = '2RBC',
            sked_Additional_Roles__c = '2RBC Sign-off'
        );
        insert testJobAllocation;
        skedHubBase.setBypassAllTriggers(false);

        Set<Id> jaIds = new Set<Id>();
        jaIds.add(testJobAllocation.Id);
        
        skedMockTest mockTest = new skedMockTest();
        Test.setMock(HttpCalloutMock.class, mockTest);
        
        testResourceOverride.sked_Start_Date__c = System.today();
        update testResourceOverride;
        delete testResourceOverride;
        
        Test.stopTest();
    }
}