force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <description>duration (in minutes) of the job</description>
    <label>Duration</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Job_Allocation_Time_Source__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Allocation_Time_Source__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Job Allocation Time Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Duration__c.field-meta.xml
<CustomField>
    <fullName>sked__Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Set_End__c.field-meta.xml
<CustomField>
    <fullName>sked__Set_End__c</fullName>
    <description>An editable version of the End field. This may be null for historical records. For new records, there are triggers in place to ensure that this will always have the same value as the formula End field.</description>
    <label>Set End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Dispatch</fullName>
                <default>true</default>
                <label>Pending Dispatch</label>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource_Type__c</fullName>
    <description>Is the resource a human or otherwise</description>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Max_Shift_End__c.field-meta.xml
<CustomField>
    <fullName>sked_Max_Shift_End__c</fullName>
    <label>Max Shift End</label>
    <summarizedField>sked_Drive_Shift__c.sked_Finish__c</summarizedField>
    <summaryForeignKey>sked_Drive_Shift__c.sked_Drive__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Min_Shift_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Min_Shift_Start__c</fullName>
    <label>Min Shift Start</label>
    <summarizedField>sked_Drive_Shift__c.sked_Start__c</summarizedField>
    <summaryForeignKey>sked_Drive_Shift__c.sked_Drive__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/skedJAAssetCorrectionBatch.cls
global class skedJAAssetCorrectionBatch implements Database.Batchable<sked__Job_Allocation__c>, Database.AllowsCallouts, Database.Stateful {
    
    protected string lastId = '';
    
    public skedJAAssetCorrectionBatch() { 
        this.lastId = '';
    }
    
    public skedJAAssetCorrectionBatch(string lastId) { 
        this.lastId = lastId;
    }
    
    global List<sked__Job_Allocation__c> start(Database.BatchableContext BC) {
        return [SELECT Id, sked__Start__c, sked__Set_End__c,
                sked__Job__r.sked_Drive__r.sked_Min_Shift_Start__c,
                sked__Job__r.sked_Drive__r.sked_Max_Shift_End__c
                FROM sked__Job_Allocation__c
                WHERE sked__Resource__r.sked__Resource_Type__c = :skedConstants.RESOURCE_TYPE_ASSET
                AND sked__Job__r.sked__Job_Allocation_Time_Source__c = FALSE
                AND sked__Status__c != :skedConstants.JOB_ALLOCATION_STATUS_DELETED
                AND sked__Job__r.sked_Drive__c != NULL
                AND sked__Job__r.sked_Drive__r.sked_Min_Shift_Start__c != NULL
                AND sked__Job__r.sked_Drive__r.sked_Max_Shift_End__c != NULL
                AND Id > :this.lastId
                ORDER BY Id ASC
                LIMIT 50000];
    }
    
    global void execute(Database.BatchableContext BC, List<sked__Job_Allocation__c> records) {
        for (sked__Job_Allocation__c record : records) {
            record.sked__Start__c = record.sked__Job__r.sked_Drive__r.sked_Min_Shift_Start__c;
            record.sked__Set_End__c = record.sked__Job__r.sked_Drive__r.sked_Max_Shift_End__c;
            record.sked__Duration__c = skedDateTimeUtils.getDifferentMinutes(record.sked__Start__c, record.sked__Set_End__c);
        }
        
        skedSetting.instance.Admin.migrationMode = TRUE;
        update records;
        skedSetting.instance.Admin.migrationMode = FALSE;
        
        this.lastId = records.get(records.size() - 1).Id;
    }
    
    global void finish(Database.BatchableContext BC) {
        List<sked__Job_Allocation__c> remainRecordQuery = [
            SELECT Id
            FROM sked__Job_Allocation__c
            WHERE sked__Resource__r.sked__Resource_Type__c = :skedConstants.RESOURCE_TYPE_ASSET
            AND sked__Job__r.sked__Job_Allocation_Time_Source__c = FALSE
            AND sked__Status__c != :skedConstants.JOB_ALLOCATION_STATUS_DELETED
            AND sked__Job__r.sked_Drive__c != NULL
            AND sked__Job__r.sked_Drive__r.sked_Min_Shift_Start__c != NULL
            AND sked__Job__r.sked_Drive__r.sked_Max_Shift_End__c != NULL
            AND Id > :this.lastId
            ORDER BY Id ASC
            LIMIT 1
        ];
        
        if (!remainRecordQuery.isEmpty()) {
            if (!Test.isRunningTest()) {
                Database.executeBatch(new skedJAAssetCorrectionBatch(this.lastId), 200);
            }
        }
    }
    
}