force-app/main/default/objects/sked__Availability__c/sked__Availability__c.object-meta.xml
<CustomObject>
    <description>Exceptions to the standard availability template for this user</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Availability__c/fields/sked__Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Recurring_Schedule__c.field-meta.xml
<CustomField>
    <fullName>sked_Recurring_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Schedule</label>
    <referenceTo>sked__Recurring_Schedule__c</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>sked_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Related_Call_Out__c.field-meta.xml
<CustomField>
    <fullName>sked_Related_Call_Out__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Call Out</label>
    <referenceTo>sked__Availability__c</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>sked_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Recurring_Schedule__c/sked__Recurring_Schedule__c.object-meta.xml
<CustomObject>
    <description>header for recurring schedules</description>
    <label>Recurring Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Recurring_Schedule__c/fields/sked_Availability_Count__c.field-meta.xml
<CustomField>
    <fullName>sked_Availability_Count__c</fullName>
    <label>Availability Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/skedRecurringScheduleUtils.cls
public class skedRecurringScheduleUtils implements callable {

    public static void publishUpdateAvailabilityCountEvent(List<sked__Availability__c> availabilities) {
        Set<Id> recurringScheduleIds = new Set<Id>();

        for (sked__Availability__c avail : availabilities) {
            if (avail.sked_Recurring_Schedule__c != null) {
                recurringScheduleIds.add(avail.sked_Recurring_Schedule__c);
            }
        }

        if (!recurringScheduleIds.isEmpty()) {
            skedFutureCallEventHandler.publishFutureCallEvent('skedRecurringScheduleUtils', 'updateAvailabilityCount', recurringScheduleIds);   
        }
    }
    public static Object call(String methodName, Map<String, Object> params) {
        skedProcessEventResult result = new skedProcessEventResult();
        try {
            switch on methodName {
                when 'updateAvailabilityCount' {
                    updateAvailabilityCount((Set<Id>) JSON.deserialize((String) params.get('param1'), Set<Id>.class));
                }
                when else {
                    throw new skedException('Unable to locate Method: ' + methodName + ' in Class: ' + skedAvailabilityHandler.class.getName());
                }
            }
        } catch (skedException ex) {
            result.addError(ex);
        }
        return result;
    }

    public static void updateAvailabilityCount(Set<Id> recurringScheduleIds) {
        List<sked__Recurring_Schedule__c> recurringSchedules = [
            SELECT Id, sked_Availability_Count__c,
            (SELECT Id, sked__Status__c FROM sked_Availabilities__r)
            FROM sked__Recurring_Schedule__c
            WHERE Id IN :recurringScheduleIds
        ];

        Set<String> cancelledStatuses = new Set<String>{skedConstants.AVAILABILITY_STATUS_DECLINED, skedConstants.AVAILABILITY_STATUS_CANCELLED};
        for (sked__Recurring_Schedule__c recurringSchedule : recurringSchedules) {
            Integer availabilityCount = 0;
            for (sked__Availability__c availability : recurringSchedule.sked_Availabilities__r) {
                if (!cancelledStatuses.contains(availability.sked__Status__c)) {
                    availabilityCount++;
                }
            }
            recurringSchedule.sked_Availability_Count__c = availabilityCount;
        }

        update recurringSchedules;
    }


}