force-app/main/default/objects/sked__Availability__c/sked__Availability__c.object-meta.xml
<CustomObject>
    <description>Exceptions to the standard availability template for this user</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Availability__c/fields/sked_Custom_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Custom_Status__c</fullName>
    <label>Custom Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Expired</fullName>
                <label>Pending - Expired</label>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
                <label>Waitlist - Expired</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved From Waitlist</fullName>
            </value>
            <value>
                <fullName>Approved From Pending</fullName>
            </value>
            <value>
                <fullName>Processing Approval</fullName>
            </value>
            <value>
                <fullName>Processing Adjustment</fullName>
            </value>
            <value>
                <fullName>Processing Cancellation</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
                <isActive>false</isActive>
                <label>Processing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Recurring_Schedule__c.field-meta.xml
<CustomField>
    <fullName>sked_Recurring_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Schedule</label>
    <referenceTo>sked__Recurring_Schedule__c</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>sked_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Staffing_Budget__c.field-meta.xml
<CustomField>
    <fullName>sked_Staffing_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staffing Budget</label>
    <referenceTo>sked_Staffing_Budget__c</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>sked_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Staffing_Budget__c/sked_Staffing_Budget__c.object-meta.xml
<CustomObject>
    <label>Staffing Budget</label>
    <nameField>
        <displayFormat>SB-{000000}</displayFormat>
        <label>Staffing Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Staffing_Budget__c/fields/sked_Recurring_Schedule__c.field-meta.xml
<CustomField>
    <fullName>sked_Recurring_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Schedule</label>
    <referenceTo>sked__Recurring_Schedule__c</referenceTo>
    <relationshipLabel>Staffing Budgets</relationshipLabel>
    <relationshipName>sked_Staffing_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Staffing_Budget_Availability__c/sked_Staffing_Budget_Availability__c.object-meta.xml
<CustomObject>
    <description>Junction Object for Staffing Budgets/Availabilities</description>
    <label>Staffing Budget Availability</label>
    <nameField>
        <label>Staffing Budget Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staffing Budget Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Staffing_Budget_Availability__c/fields/sked_Availability__c.field-meta.xml
<CustomField>
    <fullName>sked_Availability__c</fullName>
    <label>Availability</label>
    <referenceTo>sked__Availability__c</referenceTo>
    <relationshipLabel>Staffing Budget Availabilities</relationshipLabel>
    <relationshipName>sked_Staffing_Budget_Availabilities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Staffing_Budget_Availability__c/fields/sked_Created_Inside_Bidding_Period__c.field-meta.xml
<CustomField>
    <fullName>sked_Created_Inside_Bidding_Period__c</fullName>
    <formula>sked_Staffing_Budget__r.sked_Bidding_Start_Date__c &lt;= DATEVALUE(CreatedDate) &amp;&amp; DATEVALUE(CreatedDate) &lt;= sked_Staffing_Budget__r.sked_Bidding_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Inside Bidding Period</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Staffing_Budget_Availability__c/fields/sked_Staffing_Budget__c.field-meta.xml
<CustomField>
    <fullName>sked_Staffing_Budget__c</fullName>
    <label>Staffing Budget</label>
    <referenceTo>sked_Staffing_Budget__c</referenceTo>
    <relationshipLabel>Staffing Budget Availabilities</relationshipLabel>
    <relationshipName>sked_Staffing_Budget_Availabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/skedStaffingBudgetAvailabilityService.cls
public with sharing class skedStaffingBudgetAvailabilityService extends skedDataService {

    protected override void initialize() {
        this.sObjectApiName = 'sked_Staffing_Budget_Availability__c';
        this.objectType = 'staffingBudgetAvailability';
        this.domainType = Type.forName('skedModels.staffingBudgetAvailability');
    }

    protected override void getQueryConditions(skedQueryBuilder queryBuilder, queryModelBase inputModel) {
        queryModel query = (queryModel)inputModel;

        if (query.availabilityStatuses != NULL && !query.availabilityStatuses.isEmpty()) {
            queryBuilder.addCondition('sked_Availability__r.sked_Custom_Status__c IN {0}', query.availabilityStatuses);
        }

        if (query.recurringScheduleIds != NULL && !query.recurringScheduleIds.isEmpty()) {
            queryBuilder.addCondition('sked_Availability__r.sked_Recurring_Schedule__c IN {0}', query.recurringScheduleIds);
        }

        if (query.availabilityIds != NULL && !query.availabilityIds.isEmpty()) {
            queryBuilder.addCondition('sked_Availability__c IN {0}', query.availabilityIds);
        }

        if (query.staffingBudgetIds != NULL && !query.staffingBudgetIds.isEmpty()) {
            queryBuilder.addCondition('sked_Staffing_Budget__c IN {0}', query.staffingBudgetIds);
        }

        if (query.hideRecordsOutsideBiddingPeriod) {
            queryBuilder.addCondition('sked_Created_Inside_Bidding_Period__c = TRUE');
        }
    }

    public class queryModel extends skedEventService.queryModel {
        public List<string> availabilityStatuses;
        public List<String> availabilityIds;
        public List<String> staffingBudgetIds;
        public List<String> recurringScheduleIds;
        public Boolean hideRecordsOutsideBiddingPeriod = false;
    }

}