force-app/main/default/objects/sked__Account_Tag__c/sked__Account_Tag__c.object-meta.xml
<CustomObject>
    <label>Account Tag</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>AT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Account_Tag__c/fields/sked__Tag__c.field-meta.xml
<CustomField>
    <fullName>sked__Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>sked__Tag__c</referenceTo>
    <relationshipLabel>Account Tags</relationshipLabel>
    <relationshipName>Account_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>2RBC</fullName>
            </value>
            <value>
                <fullName>2RBC Sign-off</fullName>
            </value>
            <value>
                <fullName>Apheresis</fullName>
            </value>
            <value>
                <fullName>Apheresis Charge</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Charge - 2RBC</fullName>
            </value>
            <value>
                <fullName>Charge Mentor</fullName>
            </value>
            <value>
                <fullName>Charge - Special Collections</fullName>
            </value>
            <value>
                <fullName>Competent Driver</fullName>
            </value>
            <value>
                <fullName>Drive Lead</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Driver CDL A</fullName>
            </value>
            <value>
                <fullName>Driver CDL B</fullName>
            </value>
            <value>
                <fullName>Driver - DOT</fullName>
            </value>
            <value>
                <fullName>Driver Prestaff</fullName>
            </value>
            <value>
                <fullName>Driver Support</fullName>
            </value>
            <value>
                <fullName>Driver Tech Trainee</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>Lead Donor Ambassador</fullName>
            </value>
            <value>
                <fullName>Licensed Nurse</fullName>
            </value>
            <value>
                <fullName>Limited HH</fullName>
            </value>
            <value>
                <fullName>Limited Ship</fullName>
            </value>
            <value>
                <fullName>NCE Staff</fullName>
            </value>
            <value>
                <fullName>OJI</fullName>
            </value>
            <value>
                <fullName>Pickup Driver</fullName>
            </value>
            <value>
                <fullName>Plasma</fullName>
            </value>
            <value>
                <fullName>Post Collections</fullName>
            </value>
            <value>
                <fullName>Regulated - Medical Screeners</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Job_Tag__c/sked__Job_Tag__c.object-meta.xml
<CustomObject>
    <label>Job Tag</label>
    <nameField>
        <displayFormat>JT_{0}</displayFormat>
        <label>JobTag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Tag__c/fields/sked__Tag__c.field-meta.xml
<CustomField>
    <fullName>sked__Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>sked__Tag__c</referenceTo>
    <relationshipName>JobTags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Tag__c/sked__Tag__c.object-meta.xml
<CustomObject>
    <description>string metadata to be associated  with any other object</description>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Tag__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Asset Type</fullName>
            </value>
            <value>
                <fullName>Physical Location Type</fullName>
            </value>
            <value>
                <fullName>Drive Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Tag__c/fields/sked_Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Account__c.field-meta.xml
<CustomField>
    <fullName>sked_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Donors_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>sked_Donors_Scheduled__c</fullName>
    <label>Donors Scheduled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Site__c</fullName>
    <formula>CASESAFEID(sked_Drive__r.sked_Drive_Site__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>Draw End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Equipment__c.field-meta.xml
<CustomField>
    <fullName>sked_Equipment__c</fullName>
    <label>Equipment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Finish__c.field-meta.xml
<CustomField>
    <fullName>sked_Finish__c</fullName>
    <label>Max Shift End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Before_Draw_Hours__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Before_Draw_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break Before Draw Hours?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Duration__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Duration__c</fullName>
    <label>Lunch Break Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_End_Time__c</fullName>
    <label>Lunch Break End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Start_Time__c</fullName>
    <label>Lunch Break Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Start__c</fullName>
    <label>Min Shift Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Draw Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift_Tag__c/sked_Drive_Shift_Tag__c.object-meta.xml
<CustomObject>
    <label>Drive Shift Tag</label>
    <nameField>
        <displayFormat>DST-{000000}</displayFormat>
        <label>Drive Shift Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drive Shift Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive_Shift_Tag__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Drive Shift Tags</relationshipLabel>
    <relationshipName>sked_Drive_Shift_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RemoveDuplicateTagBatchTest.cls
@istest
private class RemoveDuplicateTagBatchTest {
    @testSetup
    static void prepareTestData() {
        TriggerHandler.bypass('DriveTriggerHandler');
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();
    }
    
    @istest
    public static void removeDuplicateTagFromDriveShiftTest() { 
        Test.startTest();
        skedHubBase.BypassInsertTriggers = true;
        
        List<sked_Drive__c> drive = [SELECT Id, sked_Account__c, sked_Drive_Site__c, sked_Drive_Date__c FROM sked_Drive__c limit 1];
        sked__Tag__c usCitizenTag = new sked__Tag__c(
            Name = 'US Citizen',
            sked__Type__c = 'Certification',
            sked_Resource_Type__c = 'Person'
        );
        sked__Tag__c liftGateTag = new sked__Tag__c(
            Name = 'Lift Gate',
            sked__Type__c = 'Certification',
            sked_Resource_Type__c = 'Vehicle'
        );
        insert new List<sked__Tag__c>{usCitizenTag, liftGateTag};
        
        List<sObject> sObjectList = new List<sObject>();
                sked_Drive_Shift__c testDriveShift = new sked_Drive_Shift__c(
            sked_Donors_Scheduled__c = 1,
            sked_End_Time__c = Time.newInstance(20,0,0,0),
            sked_Start_Time__c = Time.newInstance(14,0,0,0),
            sked_Drive__c = drive[0].Id,
            sked_Drive_Date__c = drive[0].sked_Drive_Date__c,
            sked_Equipment__c = 1,
            sked_Lunch_Break__c = FALSE,
            sked_Lunch_Break_Before_Draw_Hours__c = FALSE,
            sked_Lunch_Break_Duration__c = 0,
            sked_Lunch_Break_End_Time__c = NULL,
            sked_Lunch_Break_Start_Time__c = NULL,
            sked_Finish__c = DateTime.newInstance(System.today(), Time.newInstance(20,0,0,0)),
            sked_Start__c = DateTime.newInstance(System.today(), Time.newInstance(14,0,0,0)),
            sked_Order__c = 1,
            sked_Sign_Up_Reduction__c = 0,
            sked_Staff_Setup__c = 1,
            sked_Vehicles_Needed__c = 1,
            sked_Volunteer_Setup__c = 1
        );
        sObjectList.add(testDriveShift);
        
        sked__Account_Tag__c mobileAccountTag_usCitizen = new sked__Account_Tag__c(
            sked__Account__c = drive[0].sked_Account__c,
            sked__Tag__c = usCitizenTag.Id,
            sked__Required__c = TRUE
        );
        sObjectList.add(mobileAccountTag_usCitizen);
        
        sked__Account_Tag__c mobileAccountTag_liftGate = new sked__Account_Tag__c(
            sked__Account__c = drive[0].sked_Account__c,
            sked__Tag__c = liftGateTag.Id,
            sked__Required__c = FALSE,
            sked__Weighting__c = 1,
            sked_Minimum_Quantity__c = 1
        );
        sObjectList.add(mobileAccountTag_liftGate);
        
        sked_Location_Tag__c driveSiteUSCitizenTag = new sked_Location_Tag__c(
            sked_Location__c = drive[0].sked_Drive_Site__c,
            sked_Tag__c = usCitizenTag.Id,
            sked_Required__c = TRUE
        );
        sObjectList.add(driveSiteUSCitizenTag);
        insert sObjectList;
        
        sked_Drive_Shift_Tag__c testDriveShiftTag_liftGate = new sked_Drive_Shift_Tag__c(
        	sked_Drive_Shift__c = testDriveShift.Id,
        	sked_Tag__c = liftGateTag.Id,
            sked_Minimum_Quantity__c = 2
        );
        insert testDriveShiftTag_liftGate;
        
        Map<Id,sked__Account_Tag__c> accountMap = new Map<Id,sked__Account_Tag__c> ([SELECT Id, sked__Tag__c, sked__Tag__r.Name, sked__Account__c, sked__Required__c, sked_Minimum_Quantity__c FROM sked__Account_Tag__c Where sked__Account__c =: drive[0].sked_Account__c]);
        Id tagIdToCreateDuplicateJobTag = null;
        Id tagIdToCreateDuplicateDriveShiftTag = null;
        for(sked__Account_Tag__c accTag : accountMap.values()) {
            if(accTag.sked__Tag__r.Name == 'Lift Gate') {
                tagIdToCreateDuplicateDriveShiftTag = accTag.sked__Tag__c;
            }
        }
        Map<Id,sked_Location_Tag__c> locationMap = new Map<Id,sked_Location_Tag__c> ([SELECT Id, sked_Location__c, sked_Tag__c,sked_Tag__r.Name, sked_Minimum_Quantity__c, sked_Required__c FROM sked_Location_Tag__c Where sked_Location__c =: drive[0].sked_Drive_Site__c]);
        for(sked_Location_Tag__c locTag : locationMap.values()){
            if(locTag.sked_Tag__r.Name == 'US Citizen') {
                tagIdToCreateDuplicateJobTag = locTag.sked_Tag__c;
            }
        }
       
        sked_Drive_Shift_Tag__c driveShiftTagClone = new sked_Drive_Shift_Tag__c();
        driveShiftTagClone = testDriveShiftTag_liftGate.clone();
        driveShiftTagClone.sked_Minimum_Quantity__c = 1;
        insert driveShiftTagClone; //duplicate tag

        RemoveDuplicateTagFromDriveShift batch = new RemoveDuplicateTagFromDriveShift(null, null, new Set<Id>{testDriveShift.Id}, 0);
        database.executebatch(batch, 200);
        
        Test.stopTest();
        Assert.isTrue([SELECT count() FROM sked_Drive_Shift_Tag__c] == 1);
    }
    
    @istest
    public static void removeDuplicateTagFromJobTest() { 
        Test.startTest();
        skedHubBase.BypassInsertTriggers = true;
        
        List<sked_Drive__c> drive = [SELECT Id, sked_Account__c, sked_Drive_Site__c, sked_Drive_Date__c FROM sked_Drive__c LIMIT 1];
        
        sked__Tag__c usCitizenTag = new sked__Tag__c(
            Name = 'US Citizen',
            sked__Type__c = 'Certification',
            sked_Resource_Type__c = 'Person'
        );
        sked__Tag__c spanishTag = new sked__Tag__c(
            Name = 'Spanish',
            sked__Type__c = 'Certification',
            sked_Resource_Type__c = 'Person'
        );
        insert new List<sked__Tag__c>{usCitizenTag, spanishTag};
        
        List<sObject> sObjectList = new List<sObject>();
        sked_Drive_Shift__c testDriveShift = new sked_Drive_Shift__c(
            sked_Donors_Scheduled__c = 1,
            sked_End_Time__c = Time.newInstance(20,0,0,0),
            sked_Start_Time__c = Time.newInstance(14,0,0,0),
            sked_Drive__c = drive[0].Id,
            sked_Drive_Date__c = drive[0].sked_Drive_Date__c,
            sked_Equipment__c = 1,
            sked_Lunch_Break__c = FALSE,
            sked_Lunch_Break_Before_Draw_Hours__c = FALSE,
            sked_Lunch_Break_Duration__c = 0,
            sked_Lunch_Break_End_Time__c = NULL,
            sked_Lunch_Break_Start_Time__c = NULL,
            sked_Finish__c = DateTime.newInstance(System.today(), Time.newInstance(20,0,0,0)),
            sked_Start__c = DateTime.newInstance(System.today(), Time.newInstance(14,0,0,0)),
            sked_Order__c = 1,
            sked_Sign_Up_Reduction__c = 0,
            sked_Staff_Setup__c = 1,
            sked_Vehicles_Needed__c = 1,
            sked_Volunteer_Setup__c = 1
        );
        sObjectList.add(testDriveShift);
        
        sked__Account_Tag__c mobileAccountTag_usCitizen = new sked__Account_Tag__c(
            sked__Account__c = drive[0].sked_Account__c,
            sked__Tag__c = usCitizenTag.Id,
            sked__Required__c = TRUE
        );
        sObjectList.add(mobileAccountTag_usCitizen);
        
        sked__Account_Tag__c mobileAccountTag_liftGate = new sked__Account_Tag__c(
            sked__Account__c = drive[0].sked_Account__c,
            sked__Tag__c = spanishTag.Id,
            sked__Required__c = FALSE,
            sked__Weighting__c = 1,
            sked_Minimum_Quantity__c = 1
        );
        sObjectList.add(mobileAccountTag_liftGate);
        
        sked_Location_Tag__c driveSiteUSCitizenTag = new sked_Location_Tag__c(
            sked_Location__c = drive[0].sked_Drive_Site__c,
            sked_Tag__c = usCitizenTag.Id,
            sked_Required__c = TRUE
        );
        sObjectList.add(driveSiteUSCitizenTag);
        insert sObjectList;
        
        Map<Id,sked__Account_Tag__c> accountMap = new Map<Id,sked__Account_Tag__c> ([SELECT Id, sked__Tag__c, sked__Tag__r.Name, sked__Account__c, sked__Required__c, sked_Minimum_Quantity__c FROM sked__Account_Tag__c Where sked__Account__c =: drive[0].sked_Account__c]);
        Id tagIdToCreateDuplicateJobTag = null;
        Id tagIdToCreateDuplicateDriveShiftTag = null;
        for(sked__Account_Tag__c accTag : accountMap.values()){
            if(accTag.sked__Tag__r.Name == 'Spanish') {
                tagIdToCreateDuplicateDriveShiftTag = accTag.sked__Tag__c;
            }
        }
        
        Map<Id,sked_Location_Tag__c> locationMap = new Map<Id,sked_Location_Tag__c> ([SELECT Id, sked_Location__c, sked_Tag__c,sked_Tag__r.Name, sked_Minimum_Quantity__c, sked_Required__c FROM sked_Location_Tag__c Where sked_Location__c =: drive[0].sked_Drive_Site__c]);
        for(sked_Location_Tag__c locTag : locationMap.values()){
            if(locTag.sked_Tag__r.Name == 'US Citizen') {
                tagIdToCreateDuplicateJobTag = locTag.sked_Tag__c;
            }
        }
        
        sked__Region__c skdRegion = [SELECT Id, sked__Timezone__c FROM sked__Region__c LIMIT 1];
        sked__Job__c job1 = new sked__Job__c(
            sked__Region__c = skdRegion.Id,
            sked__Duration__c = 10,
            sked__Quantity__c = 2,
            sked_Drive__c = drive[0].Id,
            sked_Asset_Type__c = Constants.JOB_TYPE_VEHICLE,
            sked_Drive_Shift__c = testDriveShift.Id,
            sked__Job_Status__c = 'Pending Allocation'
        );
        insert job1;
		
        List<sked__Job_Tag__c> testJobTags = new List<sked__Job_Tag__c>();
        sked__Job_Tag__c skedJobTag;
        skedJobTag = new sked__Job_Tag__c(
            sked__Job__c = job1.Id,
            sked__Tag__c = tagIdToCreateDuplicateJobTag
        );
        testJobTags.add(skedJobTag);
        skedJobTag = new sked__Job_Tag__c(
            sked__Job__c = job1.Id,
            sked__Tag__c = tagIdToCreateDuplicateJobTag
        );
        testJobTags.add(skedJobTag);
        insert testJobTags;

        RemoveDuplicateTagFromJob batch = new RemoveDuplicateTagFromJob(null, null, new Set<Id>{job1.Id}, 0);
        database.executebatch(batch, 200);
        
        Test.stopTest();
        Assert.isTrue([SELECT count() FROM sked__Job_Tag__c] == 1);
    }
}