force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Service_Role__c/Account_Service_Role__c.object-meta.xml
<CustomObject>
    <label>Account Service Role</label>
    <nameField>
        <displayFormat>ACR-{0000000}</displayFormat>
        <label>Account Service History Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Service Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Service_Role__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Service_Role__c/fields/Account_Service_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Service_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Contact</fullName>
            </value>
            <value>
                <fullName>Blood Program Leader</fullName>
            </value>
            <value>
                <fullName>Executive Account Leader</fullName>
            </value>
            <value>
                <fullName>Stewardship Communication</fullName>
            </value>
            <value>
                <fullName>Call List Recipient</fullName>
                <isActive>false</isActive>
                <label>Call List Recipient</label>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
                <isActive>false</isActive>
                <label>Primary Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Service_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can&#39;t add inactive contact</errorMessage>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Service Roles</relationshipLabel>
    <relationshipName>Account_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A flag that captures if a contact record is active. If unchecked, system should assume that record is inactive.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Name_Change__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Name Change</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Original_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Service_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Original Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Mobile_Opp.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Opp</fullName>
    <active>true</active>
    <businessProcess>Blood Drive Sales Process</businessProcess>
    <label>Mobile Opp</label>
</RecordType>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked_Active__c.field-meta.xml
<CustomField>
    <fullName>sked_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <defaultValue>IF(
AND(MONTH(TODAY()) = 2, DAY(TODAY()) = 29),
DATE(YEAR(TODAY())+ 50, 3, 1),
DATE(YEAR(TODAY()) + 50, MONTH(TODAY()), DAY(TODAY()))
)</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/contactService_Test.cls
@isTest(SeeAllData = False)
public class contactService_Test 
{
 @testSetup
    public static void testDataSetup()
    {
        
        Account acc1 = new Account(name='Test Account 2');
        acc1.BillingStreet = '2205 Westcrt ln, Apt 215'; 
        acc1.BillingCity = 'Herndon';
        acc1.BillingStateCode = 'MI';
        acc1.BillingPostalCode = '48093';
        insert acc1;
        
        list<contact> cList = new list<Contact>();
        Contact contact1 = new Contact (firstname='Test Contact First 1',lastname='Test Contact Last 1');
        contact1.Active__c = TRUE;
        contact1.MailingStreet = '2204 Westcrt ln, Apt 213'; 
        contact1.MailingCity = 'Herndon';
        contact1.MailingStateCode = 'MI';
        contact1.MailingPostalCode = '48093';
        contact1.AccountId = acc1.id;
        contact1.Primary_Phone__c='Mobile Phone';
        contact1.Email='avs1@dfh.com';
        contact1.Original_Service_Date__c=Date.newInstance(2022, 09, 01);
        cList.add( contact1);
        
        Contact contact2 = new Contact (firstname='Test Contact First 2',lastname='Test Contact Last 2');
        contact2.Active__c = TRUE;
        contact2.MailingStreet = '2204 Westcrt ln, Apt 213'; 
        contact2.MailingCity = 'Herndon';
        contact2.MailingStateCode = 'MI';
        contact2.MailingPostalCode = '48093';
        contact2.AccountId = acc1.id;
        contact2.Primary_Phone__c='Mobile Phone';
        contact2.Email='avs1@dfh.com';
        contact2.Original_Service_Date__c=Date.newInstance(2022, 09, 01);
        cList.add( contact2);
		insert cList;
        
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        // insert mobile site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        testMobileSite.sked_Active__c = true;
        testMobileSite.sked_Start_Date__c = system.today().addDays(-30);
        testMobileSite.sked_End_Date__c = system.today().addDays(30);
        insert testMobileSite;
        
        // insert mobile opportunity
        Opportunity testMobileOpp = (Opportunity)mapTestData.get('MOBILE_OPP');
        testMobileOpp.accountId = acc1.Id;
        testMobileOpp.Drive_Site__c = testMobileSite.Id;
        testMobileOpp.Drive_Date__c = system.today().addDays(-1);
        testMobileOpp.CloseDate = system.today().addDays(-20);
        insert testMobileOpp;
    }
    public static void testContactService()
    {
        Contact contact1 = new Contact (firstname='Test Contact First 3',lastname='Test Contact Last 3');
        contact1.Active__c = TRUE;
        contact1.MailingStreet = '2204 Westcrt ln, Apt 213'; 
        contact1.MailingCity = 'Herndon';
        contact1.MailingStateCode = 'MI';
        contact1.MailingPostalCode = '48093';
        contact1.AccountId = [select id from Account where Name ='Test Account 2'].id;
        contact1.Primary_Phone__c='Mobile Phone';
        contact1.Email='avs2@dfh.com';
        contact1.Original_Service_Date__c=Date.newInstance(2022, 09, 01);
        
        insert contact1;
        
        
        system.assertEquals(1, [select count() from contact where Email='avs2@dfh.com']);
        
       
    }
    
    @isTest
     public static void testContactServiceUpdate()
    {
        contact c = [select id,MailingPostalCode from contact limit 1];
        c.MailingPostalCode='48092';
            
            update c;
     }
    
    @isTest
     public static void testContactServiceUpdate2()
    {
        List<contact> cList = [select id,MailingPostalCode,Primary_Phone__c,Phone,OtherPhone,MobilePhone from contact];
        cList[0].MailingPostalCode='48092';
        cList[0].Primary_Phone__c='Work Phone';
        cList[0].Phone='242343242';
        cList[0].OtherPhone=null;
        
        
        //cList[0].MailingPostalCode='48092';
        cList[1].Primary_Phone__c='Mobile Phone';
        cList[1].Phone='242343242';
        
        try{
            update cList;
        }
        catch(exception e)
        {
            system.debug('exception'+e);
        }
        
        contact c =[select id,OtherPhone from contact where Primary_Phone__c='Work Phone'];
        system.assertequals('242343242',c.OtherPhone);
        
     }
    
    @isTest
    static void testUpdateNameChangeFlag()
    {
        List<contact> cList = [select id, firstname, lastname, Contact_Name_Change__c from Contact];
        
        cList[0].firstname = 'Test Contact Update 1';
        try
        {
            update cList[0];
        }catch(Exception ex)
        { }
        
        list<id> idList = new list<id>{cList[0].id,cList[1].id};
            
        test.startTest();
        ContactTriggerHandler.updateNameChangeFlag(idList);
        test.stopTest();
       
        system.assertEquals(cList[0].Contact_Name_Change__c, FALSE); 
        
    }
    
    @isTest
    static void testRestrictInactiveContact()
    {
        Account accObj = [Select Id from Account limit 1];
        Contact conObj = [select Id , Active__c from Contact limit 1];
        Opportunity oppObj = [Select Id, AccountId from Opportunity where AccountId =: accobj.Id];
        
        // insert Account Service Role
        Account_Service_Role__c accServiceRoleObj = new Account_Service_Role__c();
        accServiceRoleObj.Account__c = accObj.Id;
        accServiceRoleObj.Contact__c = conObj.Id;
        insert accServiceRoleObj;
        
        // insert Drive Service Role
        OpportunityContactRole driveServiceRoleObj = new OpportunityContactRole();
        driveServiceRoleObj.ContactId = conObj.Id;
        driveServiceRoleObj.OpportunityId = oppObj.Id;
        driveServiceRoleObj.Role = 'Primary Contact';
        insert driveServiceRoleObj;
        
        conObj.Active__c = false;
        
        try{
            update conObj;
        }Catch(Exception ex)
        {
            String errormsg = ex.getMessage();
            //system.debug('errormsg '+errormsg);
            System.assert(errormsg.contains('Contact is associated with Active Template, Future Opportunities or Account. Please remove the association before inactivating the contact'));
        }
        
    }
    
    @isTest
    public static void testOnlyAdminsCanDeleteContact()
    {
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        // insert DRD User
         User testDRDUser = (User)mapTestData.get('DRD_USER');
         system.runAs(new User(Id = UserInfo.getUserId()))
         {
        	insert testDRDUser;
         }
        
         Contact conObj = [select Id , Active__c from Contact limit 1];
        
         system.runAs(testDRDUser)
         {
         	Test.startTest();
         	try
         	{
         		Delete conObj;        
         	}catch(Exception ex){
         		String errormsg = ex.getMessage();
         		System.assertEquals(0, conObj.getErrors().size());        
    		}
        	Test.stopTest();
        
    	}
    }
}