force-app/main/default/objects/Account/fields/Collections_Territory__c.field-meta.xml
<CustomField>
    <fullName>Collections_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>used to show the Blood Collections Territory</description>
    <label>Collections Zip Code</label>
    <referenceTo>Collections_Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Collections_Territory__c/Collections_Territory__c.object-meta.xml
<CustomObject>
    <description>***API name is different because of reference in code.  Please do not change API name without update to code</description>
    <label>Collections Zipcode</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections Zipcodes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Collections_Territory__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Business Development Manager.</description>
    <inlineHelpText>The Business Development Manager.</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zip_Territory_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Collections_Territory__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Updated field label for Oct 2019 geographic realignment</description>
    <label>Donor Services Region</label>
    <referenceTo>Collections_Region__c</referenceTo>
    <relationshipLabel>Collections Zip Codes (Region)</relationshipLabel>
    <relationshipName>Collections_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collections_Territory__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <description>The zip code.</description>
    <externalId>true</externalId>
    <inlineHelpText>The zip code.</inlineHelpText>
    <label>Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Original_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Service_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Original Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Opportunity Owner Region.</description>
    <formula>Owner.Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Opportunity Owner Region.</inlineHelpText>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Calendar Build</fullName>
            </value>
            <value>
                <fullName>Business Planning</fullName>
            </value>
            <value>
                <fullName>Adhoc Calendar Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked_Address_1__c.field-meta.xml
<CustomField>
    <fullName>sked_Address_1__c</fullName>
    <label>Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_ARC_Vehicle_Parking_Directions__c.field-meta.xml
<CustomField>
    <fullName>sked_ARC_Vehicle_Parking_Directions__c</fullName>
    <label>ARC Vehicle Parking Directions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Automation_Suitability__c.field-meta.xml
<CustomField>
    <fullName>sked_Automation_Suitability__c</fullName>
    <inlineHelpText>Indicates if the Site is Suitable or Unsuitable for Double Red Blood Cells.</inlineHelpText>
    <label>Automation Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Suitable</fullName>
            </value>
            <value>
                <fullName>Unsuitable</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Base_Description__c.field-meta.xml
<CustomField>
    <fullName>sked_Base_Description__c</fullName>
    <label>Base Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_City__c.field-meta.xml
<CustomField>
    <fullName>sked_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_County__c.field-meta.xml
<CustomField>
    <fullName>sked_County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Directions_From_CollectionOperation__c.field-meta.xml
<CustomField>
    <fullName>sked_Directions_From_CollectionOperation__c</fullName>
    <label>Directions From Collection Operation</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <defaultValue>IF(
AND(MONTH(TODAY()) = 2, DAY(TODAY()) = 29),
DATE(YEAR(TODAY())+ 50, 3, 1),
DATE(YEAR(TODAY()) + 50, MONTH(TODAY()), DAY(TODAY()))
)</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Floor_Description__c.field-meta.xml
<CustomField>
    <fullName>sked_Floor_Description__c</fullName>
    <label>Floor Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_National_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_National_Name__c</fullName>
    <label>National Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Outside_stairs__c.field-meta.xml
<CustomField>
    <fullName>sked_Outside_stairs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outside Stairs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Physical_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Physical_Location_Type__c</fullName>
    <label>Physical Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
            <value>
                <fullName>Inside/Outside</fullName>
                <isActive>false</isActive>
                <label>Inside/Outside</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Room_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Room_Name__c</fullName>
    <label>Room Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Room_Size__c.field-meta.xml
<CustomField>
    <fullName>sked_Room_Size__c</fullName>
    <label>Room Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;800 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>801-1200 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>1201-1600 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>1601-2000 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>2001-2400 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>2401-2800 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>2801-3200 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>3201-3600 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>3601-4000 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>4001-4500 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>4501-5000 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>&gt;5000 Sq. Ft.</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Building_Name__c</fullName>
    <label>Site/Building Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Locations (Site Contact)</relationshipLabel>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Inspection_Completed_By__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Inspection_Completed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site is deemed suitable and as applicable concerns are documented and approved.</inlineHelpText>
    <label>Site Inspection Completed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Main_Phone__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Main_Phone__c</fullName>
    <label>Site Main Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Staff_Personal_Parking_Directions__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Personal_Parking_Directions__c</fullName>
    <label>Staff Personal Parking Directions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_State__c.field-meta.xml
<CustomField>
    <fullName>sked_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Wireless_Policy__c.field-meta.xml
<CustomField>
    <fullName>sked_Wireless_Policy__c</fullName>
    <inlineHelpText>Accepted  
Connectivity Wired Only: allowed but not functional 
Sponsor Wired Only: wireless not allowed to be used  
Prohibited: not allowed on site</inlineHelpText>
    <label>Wireless Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Prohibited</fullName>
            </value>
            <value>
                <fullName>Connectivity Wired Only</fullName>
            </value>
            <value>
                <fullName>Sponsor Wired Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&quot;Standard New Form&quot;</defaultValue>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard New Form</fullName>
            </value>
            <value>
                <fullName>Custom New Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchAccoutsOpptyUpdateOnCZipCodeTest.cls
@isTest
public class BatchAccoutsOpptyUpdateOnCZipCodeTest {
    @isTest
    Public static void Test_Schedule_Class()
    {
        Test.StartTest();
		BatchAcctsOpptyUpdateOnCZipCodeSchedule testsche = new BatchAcctsOpptyUpdateOnCZipCodeSchedule(200);
		String sch = '0 0 23 * * ?';
		system.schedule('Test schedule class', sch, testsche );
		Test.stopTest();
        
        CronTrigger contrg = [select Id,CronJobDetailId,CronJobDetail.Name from CronTrigger where CronJobDetail.Name = 'Test schedule class'];
        system.assert(contrg.CronJobDetail.Name == 'Test schedule class');
    }
    static testMethod void test(){
        account a1=new account();
        a1.name='acc1';
        insert a1;
        
        contact c=new contact();
        c.AccountId=a1.Id;
        c.FirstName='contact1';
        c.LastName='contact2';
        c.Email = 'testContact@gmail.com';
		c.Original_Service_Date__c = system.today().addDays(3);
		c.Primary_Phone__c = 'Mobile Phone';
        c.MobilePhone = '752-781-0090';
        c.Phone='7474749';
        insert c;
        
        User u=new User();
        u.LastName='user12';
        u.FirstName='user22';
        u.Username='john@acme5.com';
        u.Email='abc@gmail34.com';
        u.Alias='alias';
        u.TimeZoneSidKey='America/New_York';
        u.LocaleSidKey='en_US';
        u.EmailEncodingKey='ISO-8859-1';
        u.ProfileId='00eo0000000rmqFAAQ';
        u.LanguageLocaleKey ='en_US';
        insert u;
            
        sked__Location__c lc=new sked__Location__c();
        lc.sked_National_Name__c='national2';
        lc.sked_Physical_Location_Type__c='inside';
        lc.sked_Site_Contact__c=c.Id;
        lc.sked_Site_Main_Phone__c='838-438-4367';
        lc.sked_Start_Date__c=system.today();
        lc.sked_End_Date__c=system.today()+1;
        lc.sked_Address_1__c='kolkata';
        lc.sked_City__c='kolkata';
        lc.sked_County__c='India';
        lc.sked_Zip_Code__c='70456';
        lc.sked_State__c='WB';
        lc.sked_Site_Inspection_Completed_By__c=u.Id;
        lc.sked_Site_Building_Name__c='new site building';
        lc.sked_Floor_Description__c='desc';
        lc.sked_Room_Name__c='room name';
        lc.sked_Room_Size__c='Bus';
        lc.sked_Automation_Suitability__c='Suitable';
        lc.sked_Wireless_Policy__c='Accepted';
        lc.sked_Outside_stairs__c=3;
        lc.sked_Base_Description__c='base desc';
        lc.sked_Directions_From_CollectionOperation__c='sked_Directions_From_CollectionOperation__c';
        lc.sked_ARC_Vehicle_Parking_Directions__c='sked_ARC_Vehicle_Parking_Directions__c';
        lc.sked_Staff_Personal_Parking_Directions__c='sked_Staff_Personal_Parking_Directions__c';
        lc.Source__c = 'Custom New Form';
        lc.Name='site name';
        insert lc;
        
       
       Collections_Region__c donorServicesRegion = new Collections_Region__c(name = 'Test Donor Services Region' );
       
            insert donorServicesRegion;
        
        Collections_Territory__c regionTerritory = new Collections_Territory__c(
            Name = 'Test Territory',
            Zip__c = '70456',
            BDM__c = u.id,
            sked_Start_Date__c=system.today(),
            sked_End_Date__c=system.today()+5
        );
       
            regionTerritory.Region__c = donorServicesRegion.Id;
            insert regionTerritory;
        
        
        Account a=new Account();
        a.name='account1';
        //a.CreatedDate=system.today();
        a.Collections_Territory__c=regionTerritory.id;
        a.BillingPostalCode='70456';
        insert a;
       
        
        Opportunity mobileOpp = new Opportunity(
            Name = 'Test Opportunity1',
        	StageName = 'Draft',
           	Type_of_Drive__c = 'Mobile',
        	RecordTypeId =  Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId(),
        	Drive_Name__c = 'Test Drive',
        	Drive_Date__c = System.today(),
        	CloseDate = System.today(),
        	Start_Time__c = Time.newInstance(10, 0, 0, 0),
      		End_Time__c = Time.newInstance(15, 30, 0, 0),
        	Flow_Start_Time_Field__c = '1000',
        	Flow_End_Time_Field__c = '1530',
        	WB_Projected_Procedures__c = 4,
        	X2RBC_Projected_Procedures__c = 2,
        	Anticipated_Registered_Donors__c = 25,
            Online_Scheduling_Enabled__c = 'No'
		);
            mobileOpp.AccountId = a.Id;
            mobileOpp.Drive_Site__c = lc.id;
			insert mobileOpp;  
        
        
        Test.startTest();
        BatchAccoutsOpptyUpdateOnCZipCode ba= new BatchAccoutsOpptyUpdateOnCZipCode();
        Id jobid= Database.executeBatch(ba,5);
        Test.stopTest();
    }
}