force-app/main/default/objects/Account/fields/Contact_BPL__c.field-meta.xml
<CustomField>
    <fullName>Contact_BPL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this will be populated as soon Account Service role is created for this account with the account service role of BPL</description>
    <label>Blood Program Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Mobile_Opp.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Opp</fullName>
    <active>true</active>
    <businessProcess>Blood Drive Sales Process</businessProcess>
    <label>Mobile Opp</label>
</RecordType>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked_Pre_Drive_Security_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Pre_Drive_Security_Due_Date__c</fullName>
    <inlineHelpText>Date which Security Information, Staff List or Sponsor Security Form is required by.  If required pre-drive, the form/list will be sent to the Security Contact on the Blood Drive Opportunity record.</inlineHelpText>
    <label>Pre-Drive Security Due Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/Sponsor_Security_Form_Required__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Security_Form_Required__c</fullName>
    <inlineHelpText>Sponsor provided form to be completed. Sponsor form should be uploaded to Site Files for AP&amp;S to access for completion.</inlineHelpText>
    <label>Sponsor Security Form Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Drive</fullName>
            </value>
            <value>
                <fullName>Day of Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/createdPreDriveTaskScheduleTest.cls
@isTest
private class createdPreDriveTaskScheduleTest {
    @testSetup
    static void prepareTestData() {
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('ContactTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects();
     
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        insert testMobileAccount;
        
        Contact testContact = (Contact)mapTestData.get('CONTACT');
        testContact.AccountId = testMobileAccount.Id;
        insert testContact;
        
        testMobileAccount.Contact_BPL__c = testContact.Id;
        update testMobileAccount;
        
       	sked__Location__c testLocation = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        testLocation.Sponsor_Security_Form_Required__c = 'Pre-Drive';
        testLocation.sked_Pre_Drive_Security_Due_Date__c='14';
        insert testLocation;
        
        Opportunity testMobileOpp = (Opportunity)mapTestData.get('MOBILE_OPP');
        testMobileOpp.accountId = testMobileAccount.Id;
        testMobileOpp.Drive_Site__c = testLocation.Id;
        testMobileOpp.Drive_Date__c = System.Today().addDays(4);
        insert testMobileOpp;
    }
    
    static testMethod void testBatch() {
        Test.startTest();
        
        Opportunity testMobileOpp = [SELECT Id, StageName FROM Opportunity WHERE Is_Template__c = false LIMIT 1];
        testMobileOpp.StageName = 'Closed';
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('TaskTriggerHandler');
        skedHubBase.BypassUpdateTriggers = true;
        update testMobileOpp;
 
        createdPreDriveTaskSchedule b = new createdPreDriveTaskSchedule();
        string sch = '0 0 2 * * ?';
        System.Schedule('TEST',sch,b);
        
        TriggerHandler.clearAllBypasses();
        Test.stopTest();
        Assert.isTrue([SELECT count() FROM CronTrigger WHERE CronJobDetail.Name = 'TEST' AND CronJobDetail.JobType = '7'] == 1);
    }
}