force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fixed_Site_Account.recordType-meta.xml
<RecordType>
    <fullName>Fixed_Site_Account</fullName>
    <active>true</active>
    <label>Fixed Site Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/AccountTeamMember/fields/BSF_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>BSF_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field is added to capture the Portfolio related to the Current Team Member</description>
    <label>BSF Portfolio</label>
    <referenceTo>BSF_Portfolio__c</referenceTo>
    <relationshipLabel>Account Team</relationshipLabel>
    <relationshipName>Account_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/Is_Covering_Recruiter__c.field-meta.xml
<CustomField>
    <fullName>Is_Covering_Recruiter__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check this checkbox if any user is selected as Covering Recruiter.</description>
    <label>Is Covering Recruiter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Name__c.field-meta.xml
<CustomField>
    <fullName>Drive_Name__c</fullName>
    <label>Blood Drive Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_Start_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_Start_Time_Field__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>1530</fullName>
                <label>3:30 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Fixed Site</fullName>
            </value>
            <value>
                <fullName>RSMO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Portfolio_Accounts_Processing__c/Portfolio_Accounts_Processing__c.object-meta.xml
<CustomObject>
    <label>Portfolio Accounts Processing</label>
    <nameField>
        <label>Portfolio Accounts Processing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Accounts Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Accounts_Processing__c/fields/Records_Processed__c.field-meta.xml
<CustomField>
    <fullName>Records_Processed__c</fullName>
    <label>Records Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/Taxonomy__c.object-meta.xml
<CustomObject>
    <description>Taxonomy data from GOATS is imported in this object</description>
    <label>Taxonomy</label>
    <nameField>
        <displayFormat>TAX-{0000000000}</displayFormat>
        <label>Taxonomy</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxonomies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Taxonomy__c/fields/Version_Key__c.field-meta.xml
<CustomField>
    <fullName>Version_Key__c</fullName>
    <label>Version Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Run__c/Taxonomy_Run__c.object-meta.xml
<CustomObject>
    <description>The Taxo run object will be populated with New Taxo Data for any of the record types that become available in Taxonomy__c. The Taxo Run Control Batch will run daily and identify if new Taxo data has been received for any of the Taxo Record Types and insert in this object.</description>
    <label>Taxonomy Run</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxonomy Run</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy_Run__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This will be a combination of the Taxo Record Type and Future Version Number. Format &lt;Taxo Record Type&gt;_&lt;Future_Version_No&gt;.</description>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Taxonomy_Run__c/fields/Future_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Future_Version_Number__c</fullName>
    <description>Version number of the Future Taxo for the Taxo Record type as received in Taxonomy__c.</description>
    <label>Future Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Run__c/fields/Run_Date__c.field-meta.xml
<CustomField>
    <fullName>Run_Date__c</fullName>
    <description>Run Date will be calculated by the Taxo Run Control Batch when inserting data in this object. The Run Date will be calculated as the date of the first Saturday of the next month for all situations, except if the current date is the first of the month. In the later case, it will be set as the current date.</description>
    <label>Run Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Taxonomy_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This will be populated with the value of Pending when the entry is made. On the run date, Taxo Run Control Batch will change the Status to Processing for the Record with the Lowest Sequence Number for that date and Chain BSF_Batch_BSFPortfolio. When the portfolio creation and subsequent enddating is completed by BSF_Batch_TaxonomyEndDateHandler, it will update the status to Completed and then pick the next &apos;Pending&apos; taxo record type for that run date based on sequence, update it to &apos;Processing&apos; and again Chain BSF_Batch_BSFPortfolio. This will continue till all the Taxo Record Types are processed for the run date. Finally, when a Future Version becomes history because of New Taxo Data being pushed and the end date on the Version becomes &lt; Current Date + 1 month, the Data for that verson is deleted in Taxonomy__c and the subsequent status on this record is set to &apos;Deleted.&apos;</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy_Run__c/fields/Taxo_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Taxo_Record_Type__c</fullName>
    <description>Taxo Record Type Name for which Taxo Data has been received.</description>
    <label>Taxo Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BSF_Batch_OpportunityTeamSyncTest.cls
// The following test class covers BSF_Batch_OpportunityTeamSync

@istest(SeeAllData = false)
public class BSF_Batch_OpportunityTeamSyncTest
{
    @testSetup
    static void prepareDataset()
    {
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
            
        // insert DRD Users
        List<User> drdUsersList = new List<User>();
        
        User drdUser = (User)mapTestData.get('DRD_USER');
        User drdUser2 = (User)mapTestData.get('DRD_MANAGER_USER');
        
        drdUsersList.add(drdUser);
        drdUsersList.add(drdUser2);
        
        system.runAs(new User(Id = UserInfo.getUserId()))
        {
            insert drdUsersList;
        }
        
        // insert Fixed Site Account
        Account testFixedSiteAccount = (Account)mapTestData.get('FIXED_SITE_ACCOUNT');
        insert testFixedSiteAccount;
                        
        // insert AccountTeamMembers - Fixed Site
        
        List<AccountTeamMember> accTeamList = new  List<AccountTeamMember>();
        AccountTeamMember accTeamMember1 = (AccountTeamMember)mapTestData.get('ACCOUNT_TEAM_MEMBER_FIXED');
        accTeamMember1.AccountId = testFixedSiteAccount.Id;
        accTeamMember1.UserId = drdUsersList[0].Id;
        accTeamList.add(accTeamMember1);
        
       	AccountTeamMember accTeamMember2 = (AccountTeamMember)mapTestData.get('ACCOUNT_TEAM_MEMBER_FIXED2');
       	accTeamMember2.AccountId = testFixedSiteAccount.Id;
       	accTeamMember2.UserId = drdUsersList[1].Id;
       	accTeamList.add(accTeamMember2);
        
        insert accTeamList;
        
        // insert site
        sked__Location__c fixedSite = (sked__Location__c)mapTestdata.get('FIXED_SITE');
        insert fixedSite;
        
        // insert fixed site opportunity
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity fixedSiteOpp = (Opportunity)mapTestData.get('FIXED_OPP');
        fixedSiteOpp.Drive_Site__c = fixedSite.Id;
        fixedSiteOpp.AccountId = testFixedSiteAccount.Id;
        oppList.add(fixedSiteOpp);
        Triggerhandler.bypass('OpportunityTriggerhandler');
        insert oppList;
    }
    
    static testMethod void testBatchV1()
    {
        Test.startTest();
        List<Account> acc = [select Id from Account];
        
        Map<Id,List<AccountTeamMember>> mapOfAcctsWithTeamMembers = new Map<Id,List<AccountTeamMember>>();
        for(Account obj: acc)
        {
            mapOfAcctsWithTeamMembers.put(obj.Id,new List<AccountTeamMember>([select Id, accountId, start_date__c, end_date__c, TeammemberRole,Is_Covering_Recruiter__c, userId, BSF_Portfolio__c from AccountTeamMember where accountId =: obj.Id]));            
        }
        

        
        List<AccountTeamMember> accTeam2 = [select Id, accountId, start_date__c, end_date__c, TeammemberRole,Is_Covering_Recruiter__c, userId,BSF_Portfolio__c from AccountTeamMember limit 2];
        accTeam2[0].start_date__c = system.today().adddays(10);
        
        update accTeam2[0];
        
      Portfolio_Accounts_Processing__c pap = new Portfolio_Accounts_Processing__c();
        pap.Records_Processed__c = 1;
        insert pap;
        
           
        RecordType rt = [SELECT Id,Name FROM RecordType WHERE SObjectType = 'Taxonomy__c' and Name =: BSF_Constants.BIO_RECRUITMENT_RECORD_TYPE LIMIT 1];
        // Create corresponding taxonomy run
        Taxonomy_Run__c taxoRun = new Taxonomy_Run__c(
            //  External_Id__c = rt.Name + '_' + taxn.Version_Key__c,
            Status__c = 'pending',
            Taxo_Record_Type__c = rt.Name,
             Future_Version_Number__c =296,
            Run_Date__c = System.today()
        );
        insert taxoRun;
        
        Database.executeBatch(new BSF_Batch_OpportunityTeamSync(system.today().adddays(-1),system.today().addDays(2)));
        
        BSF_Batch_OpportunityTeamSync batch = new BSF_Batch_OpportunityTeamSync(mapOfAcctsWithTeamMembers,0,system.today().adddays(-1),system.today().addDays(2));
        database.executeBatch(batch, 50);
        
             //    Database.executeBatch(new BSF_Batch_OpportunityTeamSync(system.today().adddays(-1),system.today().addDays(2)),143);

  BSF_Batch_OpportunityTeamSync batch1 = new BSF_Batch_OpportunityTeamSync(system.today().adddays(-1),system.today().addDays(2),296);
        database.executeBatch(batch1, 50);
                
        
        Test.stopTest();
        
    }
    
    
     public static List<User> populateUserFields(String firstName,String lastName,Id profileId,Integer count){
        List<User> users = new List<User>();
        for(Integer index=1;index<=count;index++){
            User user1 = new User(Alias = firstName+index, FirstName = firstName+index, Email=firstName+index+'.'+lastName+index+'@test.com',EmailEncodingKey='UTF-8', LastName=lastName+index, LanguageLocaleKey='en_US', 
            	LocaleSidKey='en_US', ProfileId = profileId, TimeZoneSidKey='America/Los_Angeles', UserName=firstName+index+'.'+lastName+index+'@test.com.tst1',CommunityNickname=firstName+index+'.'+lastName+index+'@test.com.tst1');
        	users.add(user1);
        }
        return users;
    }
      @isTest
    public static void testMethodAccTeam()
    {
        skedHubBase.BypassInsertTriggers=true;
        skedHubBase.BypassUpdateTriggers=true;
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
                
        // insert Mobile Account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c =  'TEST ACCOUNT 1';
        triggerHandler.bypass('AccountTriggerHandler');
        insert testMobileAccount;
        
        
        // insert Mobile Site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite;
        
        // insert templates
        Opportunity testTemplate = (Opportunity)mapTestData.get('MOBILE_TEMPLATE_OPP');
        testTemplate.AccountId = testMobileAccount.Id;
        testTemplate.Drive_Site__c = testMobileSite.Id;
        insert testTemplate;
        
        list<opportunity> opportunityList = new list<opportunity>();
        
        
       Opportunity testMobileOpp1 = new Opportunity(
            Name = 'Test Opportunity 2',
        	StageName = 'Draft',
           	Type_of_Drive__c = 'Mobile',
        	RecordTypeId =  Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId(),
        	Drive_Name__c = 'Test Drive',
        	Drive_Date__c = system.today().addDays(55),
        	CloseDate = system.today(),
        	Start_Time__c = Time.newInstance(10, 0, 0, 0),
      		End_Time__c = Time.newInstance(15, 30, 0, 0),
        	Flow_Start_Time_Field__c = '1000',
        	Flow_End_Time_Field__c = '1530',
        	WB_Projected_Procedures__c = 4,
        	X2RBC_Projected_Procedures__c = 2,
        	Anticipated_Registered_Donors__c = 25,
            Online_Scheduling_Enabled__c = 'No'
		);
        testMobileOpp1.AccountId = testMobileAccount.Id;
        testMobileOpp1.Drive_Site__c = testMobileSite.Id;
        testMobileOpp1.Parent_Template_Id__c = testTemplate.Id;
       opportunityList.add(testMobileOpp1);
        TriggerHandler.bypass('OpportunityTriggerHandler');
        insert opportunityList;
        List<User> users = new List<User>();
        Profile drdProfile = [SELECT Id FROM Profile WHERE Name='DRD Profile']; //Keep this in Label
        Profile drdManagerProfile = [SELECT Id FROM Profile WHERE Name='DRD Manager'];
        
        List<User> drdUsers = populateUserFields('DRD','User',drdProfile.Id,60);
        List<User> dmUsers = populateUserFields('DM','User',drdManagerProfile.Id,60);
        
        List<User> allUsers = new List<User>();
        allUsers.addAll(drdUsers);
        allUsers.addAll(dmUsers);
        insert allUsers;
        List<AccountTeamMember> coveringRecruiterList = new List<AccountTeamMember>();
        AccountTeamMember coveringRecruiter1 = new AccountTeamMember(AccountId=testMobileAccount.Id,Coverage_Reason__c='Leave of Absence (LOA)',TeamMemberRole='Account Manager',UserId=drdUsers[drdUsers.size()-1].Id);
        coveringRecruiter1.Is_Covering_Recruiter__c = true;
        coveringRecruiter1.Start_Date__c = System.today()-2;
        coveringRecruiter1.End_Date__c = System.today()+30;
        AccountTeamMember coveringRecruiter2 = new AccountTeamMember(AccountId=testMobileAccount.Id,Coverage_Reason__c='Vacant Territory',TeamMemberRole='Account Manager',UserId=drdUsers[drdUsers.size()-2].Id);
        coveringRecruiter2.Is_Covering_Recruiter__c = true;
        coveringRecruiter2.Start_Date__c = System.today()+50;
        coveringRecruiter2.End_Date__c = System.today()+100;
        
        BSF_Constants.isTeamMemberCreatedFromBackend = false;
        
        coveringRecruiterList.add(coveringRecruiter1);
        coveringRecruiterList.add(coveringRecruiter2);
        test.startTest();
        insert coveringRecruiterList;
        test.stopTest();
     BSF_Batch_OpportunityTeamSync batch1 = new BSF_Batch_OpportunityTeamSync(system.today().adddays(-1),system.today().addDays(2),296);
        database.executeBatch(batch1, 50);
     
    
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
}