force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SitePlanForTemplatesHelper_Test.cls
@isTest
private class SitePlanForTemplatesHelper_Test {
    
    @testSetup 
    static void prepareDataset() {
        skedHubBase.BypassInsertTriggers = true;
        skedHubBase.BypassUpdateTriggers = true;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        //insert Account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c =  'Test Account';
        testMobileAccount.BillingPostalCode = '30146';
        insert testMobileAccount;
        
        // insert Mobile Site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite;
        
        // insert templates
        Opportunity testTemplate = (Opportunity)mapTestData.get('MOBILE_TEMPLATE_OPP');
        testTemplate.AccountId = testMobileAccount.Id;
        testTemplate.Drive_Site__c = testMobileSite.Id;
        insert testTemplate;  
        TriggerHandler.clearAllBypasses();
    }
    
    @isTest static void validateSitePlan() {
        Test.startTest();
        
        sked__Location__c testSite = [SELECT Id FROM sked__Location__c LIMIT 1];
        List<Opportunity> testResults = SitePlanForTemplatesHelper.SitePlanForTemplatesHelper(testSite.Id);
        
        Test.stopTest();
        Assert.isTrue(!testResults.isEmpty());
    }
}