force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fixed_Site_Account.recordType-meta.xml
<RecordType>
    <fullName>Fixed_Site_Account</fullName>
    <active>true</active>
    <label>Fixed Site Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/Account_Service_Role__c/Account_Service_Role__c.object-meta.xml
<CustomObject>
    <label>Account Service Role</label>
    <nameField>
        <displayFormat>ACR-{0000000}</displayFormat>
        <label>Account Service History Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Service Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Service_Role__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Service_Role__c/fields/Account_Service_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Service_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Contact</fullName>
            </value>
            <value>
                <fullName>Blood Program Leader</fullName>
            </value>
            <value>
                <fullName>Executive Account Leader</fullName>
            </value>
            <value>
                <fullName>Stewardship Communication</fullName>
            </value>
            <value>
                <fullName>Call List Recipient</fullName>
                <isActive>false</isActive>
                <label>Call List Recipient</label>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
                <isActive>false</isActive>
                <label>Primary Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Service_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can&#39;t add inactive contact</errorMessage>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Service Roles</relationshipLabel>
    <relationshipName>Account_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Original_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Service_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Original Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Registered_Donors__c</fullName>
    <description>Numeric value that reflects the # of donors expected to be at the drive. Current based on historical drive data (like drive, how many people).</description>
    <label>Anticipated Registered Donors</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Drive_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Drive_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created as part of HRP-7470
This field will be used in &apos;Create New Template&apos; flow to capture primary contact (default/user selected) and drive service role will be created based on the output value</description>
    <label>Primary Drive Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Blood Drive Opportunities</relationshipLabel>
    <relationshipName>Blood_Drive_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Red_Cross_Volunteer_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Red_Cross_Volunteer_Quantity__c</fullName>
    <description>Created as part of HRP-14653</description>
    <label>Red Cross Volunteer Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Red_Cross_Volunteer_Required__c.field-meta.xml
<CustomField>
    <fullName>Red_Cross_Volunteer_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of HRP-14653</description>
    <label>Red Cross Volunteer Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Whole Blood Procedures Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>X2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Double Red Procedures Projected</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TemplateService_Test.cls
/* This test class is coving the following classes -
 * TemplateService (93%)
 * ***************************************************************************/

@isTest
private class TemplateService_Test {

    @testSetup
    private static void prepareTestData() {
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('ContactTriggerHandler');
        TriggerHandler.bypass('SiteTriggerHandler');
        skedHubBase.BypassInsertTriggers = true;
        
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
                
        // insert Mobile Account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c =  'TEST ACCOUNT 1';
        insert testMobileAccount;
        
        // insert Fixed Site Account
        Account testFixedSiteAccount = (Account)mapTestData.get('FIXED_SITE_ACCOUNT');
        testFixedSiteAccount.Internal_Name__c =  'TEST ACCOUNT 2';
        insert testFixedSiteAccount;
        
        // insert Contact
        List<Contact> testContacts = new List<Contact>();
        Contact testContact;
        testContact = (Contact)mapTestData.get('CONTACT');
        testContact.AccountId = testMobileAccount.Id;
        testContacts.add(testContact);
        
        testContact = new Contact(
            firstname = 'Contact Test First 2',
            lastname = 'TestContactLast2',
            Email = 'testContact2@gmail.com',
            Original_Service_Date__c = system.today().addDays(3),
        	MailingStreet = '2204 Westcrt ln, Apt 213',
        	MailingCity = 'Herndon',
        	MailingStateCode = 'MI',
        	MailingPostalCode = '48420',
            Primary_Phone__c = 'Mobile Phone',
            MobilePhone = '752-781-0091',
            AccountId = testFixedSiteAccount.Id
        );
        testContacts.add(testContact);
        insert testContacts;
        
        // insert Account Service Roles
        List<Account_Service_Role__c> testServiceRoles = new List<Account_Service_Role__c>();
        
        Account_Service_Role__c testServiceRole;
        testServiceRole = new Account_Service_Role__c();
        testServiceRole.Account_Service_Role__c = 'Blood Program Leader';
        testServiceRole.Account__c = testMobileAccount.Id; 
        testServiceRole.Contact__c = testContacts[0].id;
        testServiceRoles.add(testServiceRole);
        
        testServiceRole = new Account_Service_Role__c();
        testServiceRole.Account_Service_Role__c = 'Account Contact';
        testServiceRole.Account__c = testFixedSiteAccount.Id; 
        testServiceRole.Contact__c = testContacts[0].id;
        testServiceRole.Start_Date__c = system.today();
        testServiceRoles.add(testServiceRole);
        
        testServiceRole = new Account_Service_Role__c();
        testServiceRole.Account_Service_Role__c = 'Account Contact';
        testServiceRole.Account__c = testFixedSiteAccount.Id; 
        testServiceRole.Contact__c = testContacts[1].id;
        testServiceRole.Start_Date__c = system.today();
        testServiceRoles.add(testServiceRole);
        insert testServiceRoles;
        
        // insert Mobile Site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite;
    }
    
    static testMethod void getDefaultPrimaryDriveContactBPL_Test() {
        Test.startTest();
        
        Id testAccountId = [SELECT Id FROM Account WHERE Internal_Name__c = 'TEST ACCOUNT 1' LIMIT 1].Id;
        Id testContactId = [SELECT Id FROM Contact LIMIT 1].Id;
        
        TemplateService.TemplateWrapper wrapper = new TemplateService.TemplateWrapper();
        wrapper.accountId = testAccountId;
        
        List<String> result = TemplateService.getDefaultPrimaryDriveContact(new List<TemplateService.TemplateWrapper>{wrapper});
        Test.stopTest();
        
        Assert.isTrue(result[0] == testContactId);
    }
    
    static testMethod void getDefaultPrimaryDriveContactNoBPL_Test() {
        Test.startTest();
        
        Id testAccountId = [SELECT Id FROM Account WHERE Internal_Name__c = 'TEST ACCOUNT 2' LIMIT 1].Id;
        Id testContactId = [SELECT Id FROM Contact WHERE FirstName = 'Contact Test First 2' LIMIT 1].Id;
        
        TemplateService.TemplateWrapper wrapper = new TemplateService.TemplateWrapper();
        wrapper.accountId = testAccountId;
        
        List<String> result = TemplateService.getDefaultPrimaryDriveContact(new List<TemplateService.TemplateWrapper>{wrapper});
        Test.stopTest();
        
        Assert.isTrue(result[0] == testContactId);
    }
    
    static testMethod void createPrimaryContactDriveServiceRole_Test() {
        Test.startTest();
        
        Id testAccountId = [SELECT Id FROM Account WHERE Internal_Name__c = 'TEST ACCOUNT 1' LIMIT 1].Id;
        Id testContactId = [SELECT Id FROM Contact WHERE FirstName = 'Test Contact First 1' LIMIT 1].Id;
        Id testSiteId = [SELECT Id FROM sked__Location__c LIMIT 1].Id;
        
        // insert Template
        Opportunity mobileTemplateOpp = new Opportunity(
            Name = 'Mobile Template Opp',
            RecordTypeId =  Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId(),
            StageName = 'Discovery', 
            CloseDate = System.today(),
            Is_Template__c = TRUE,
            Start_Time__c = Time.newInstance(10, 0, 0, 0),
      		End_Time__c = Time.newInstance(15, 30, 0, 0),
            Anticipated_Registered_Donors__c = 10,
            WB_Projected_Procedures__c = 11,
            X2RBC_Projected_Procedures__c = 12,
            Red_Cross_Volunteer_Required__c = true,
            Red_Cross_Volunteer_Quantity__c = 1,
            AccountId = testAccountId,
            Drive_Site__c = testSiteId,
            Primary_Drive_Contact__c = testContactId
        );
        insert mobileTemplateOpp;
        Test.stopTest();
        
        List<OpportunityContactRole> testDriveContacts = [SELECT Id, Role FROM OpportunityContactRole WHERE OpportunityId = :mobileTemplateOpp.Id];
        Assert.isTrue(testDriveContacts != null && testDriveContacts.size() == 1);
        Assert.isTrue(testDriveContacts[0].Role == 'Primary Contact');
    }
    
    static testMethod void wrapperNull_Test() {
        Test.startTest();        
        List<String> result = TemplateService.getDefaultPrimaryDriveContact(null);
        Test.stopTest();
    }
    
    static testMethod void getDefaultPrimaryDriveContactNoBPLDiffStartDate_Test() {
        Test.startTest();
        
        Id testAccountId = [SELECT Id FROM Account WHERE Internal_Name__c = 'TEST ACCOUNT 2' LIMIT 1].Id;
        
        List<Account_Service_Role__c> testServiceRoles = [SELECT Id, Contact__c, Start_Date__c FROM Account_Service_Role__c WHERE Account__c = :testAccountId];
        testServiceRoles[0].Start_Date__c = system.today().addDays(-1);
        update testServiceRoles[0];
        
        TemplateService.TemplateWrapper wrapper = new TemplateService.TemplateWrapper();
        wrapper.accountId = testAccountId;
        
        List<String> result = TemplateService.getDefaultPrimaryDriveContact(new List<TemplateService.TemplateWrapper>{wrapper});
        Test.stopTest();
        
        Assert.isTrue(result[0] == testServiceRoles[0].Contact__c);
    }
}