force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/National_Name_Status__c.field-meta.xml
<CustomField>
    <fullName>National_Name_Status__c</fullName>
    <label>National Name Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review Pending</fullName>
            </value>
            <value>
                <fullName>Second Review Pending</fullName>
            </value>
            <value>
                <fullName>Review Completed</fullName>
            </value>
            <value>
                <fullName>Initial Review Completed</fullName>
            </value>
            <value>
                <fullName>Second Review Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fixed_Site_Account.recordType-meta.xml
<RecordType>
    <fullName>Fixed_Site_Account</fullName>
    <active>true</active>
    <label>Fixed Site Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Hold_Threshold__c.field-meta.xml
<CustomField>
    <fullName>sked_Hold_Threshold__c</fullName>
    <defaultValue>48</defaultValue>
    <label>Hold Threshold (Hours)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Lunch_Break_Duration_Fixed_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Duration_Fixed_Site__c</fullName>
    <label>Lunch Break Duration (Fixed Site)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Maximum_Lunch_Break_Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Lunch_Break_Duration_Mobile__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Duration_Mobile__c</fullName>
    <label>Lunch Break Duration (Mobile)</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Maximum_Lunch_Break_Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Work_Week_First_Day__c.field-meta.xml
<CustomField>
    <fullName>sked_Work_Week_First_Day__c</fullName>
    <label>Work Week First Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_Week</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Registered_Donors__c</fullName>
    <description>Numeric value that reflects the # of donors expected to be at the drive. Current based on historical drive data (like drive, how many people).</description>
    <label>Anticipated Registered Donors</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Status__c.field-meta.xml
<CustomField>
    <fullName>Drive_Status__c</fullName>
    <description>This field reflects the value from Drive Status on Drives on Calendar as is.When the opportunity is created, this field should be left blank and should be updated once Drive is created .</description>
    <label>Drive Status(Do not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>System Generated</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Pending Action</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Withdrawn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 6 AND (3 OR 4 OR 5)</booleanFilter>
        <errorMessage>Only Templates related to the same Account are eligible and related site must be active.</errorMessage>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Is_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Drive_Site__r.sked_End_Date__c</field>
            <operation>greaterThan</operation>
            <valueField>$Source.Drive_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Cancelled</value>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Withdrawn</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Template_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select the Template for this Opportunity. Only Templates related to the same Account are eligible to be selected.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Whole Blood Procedures Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>X2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Double Red Procedures Projected</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Mobile_Opp.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Opp</fullName>
    <active>true</active>
    <businessProcess>Blood Drive Sales Process</businessProcess>
    <label>Mobile Opp</label>
</RecordType>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/National_Name_Status__c.field-meta.xml
<CustomField>
    <fullName>National_Name_Status__c</fullName>
    <label>National Name Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review Pending</fullName>
            </value>
            <value>
                <fullName>Second Review Pending</fullName>
            </value>
            <value>
                <fullName>Review Completed</fullName>
            </value>
            <value>
                <fullName>Initial Review Completed</fullName>
            </value>
            <value>
                <fullName>Second Review Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Active__c.field-meta.xml
<CustomField>
    <fullName>sked_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>sked_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <defaultValue>IF(
AND(MONTH(TODAY()) = 2, DAY(TODAY()) = 29),
DATE(YEAR(TODAY())+ 50, 3, 1),
DATE(YEAR(TODAY()) + 50, MONTH(TODAY()), DAY(TODAY()))
)</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Account__c.field-meta.xml
<CustomField>
    <fullName>sked_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Drive_Productivity_Planned__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Productivity_Planned__c</fullName>
    <label>Drive Productivity (Planned)</label>
    <precision>8</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sked_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>sked_Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Days_of_Week.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Days of Week</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/sked_Maximum_Lunch_Break_Duration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <masterLabel>Maximum Lunch Break Duration</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BSFPopulateSiteChapterBatchTest.cls
@isTest
private class BSFPopulateSiteChapterBatchTest {
    
	@testSetup
     public static void prepareDataSetup()
     {        
         BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
         Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
         skedHubBase.BypassInsertTriggers = true;
         // insert Mobile Account
         List<Account> accListToInsert = new List<Account>();
         Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
         testMobileAccount.Internal_Name__c =  'TEST ACCOUNT 1';
         
         accListToInsert.add(testMobileAccount);
         
         // insert Fixed Site Account
         Account testFixedSiteAccount = (Account)mapTestData.get('FIXED_SITE_ACCOUNT');
         testFixedSiteAccount.Internal_Name__c = 'TEST FIXED SITE ACC 1';
         accListToInsert.add(testFixedSiteAccount);
         Triggerhandler.bypass('AccountTriggerhandler');
         insert accListToInsert;
         
         TriggerHandler.bypass('SiteTriggerHandler');
         // insert mobile site
         List<sked__Location__c> siteListToInsert = new List<sked__Location__c>();
         sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
         testMobileSite.sked_Active__c = true;
         testMobileSite.sked_Start_Date__c = system.today().addDays(-30);
         testMobileSite.sked_End_Date__c = system.today().addDays(30);
         testMobileSite.National_Name_Status__c = 'Second Review Pending';
         
         testMobileSite.sked_Zip_Code__c = '12344';
         siteListToInsert.add(testMobileSite);
         
         // insert Fixed Site
         sked__Location__c testFixedSite = (sked__Location__c)mapTestData.get('FIXED_SITE');
         testFixedSite.sked_Active__c = true;
         testFixedSite.sked_Start_Date__c = system.today().addDays(-30);
         testFixedSite.sked_End_Date__c = system.today().addDays(30);
         testFixedSite.sked_Zip_Code__c = '12344';
         siteListToInsert.add(testFixedSite);
         insert siteListToInsert;
         
         // insert Fixed Site Opportunity
         List<Opportunity> oppList = new List<Opportunity>();
         Opportunity testFixedSiteOpp = (Opportunity)mapTestData.get('FIXED_OPP');
         testFixedSiteOpp.AccountId = testFixedSiteAccount.Id;
         testFixedSiteOpp.Drive_Site__c = testFixedSite.Id;
         oppList.add(testFixedSiteOpp);
         //insert testFixedSiteOpp;
         
         // insert Mobile Opportunity
         Opportunity optyObj = new Opportunity();
         optyObj.accountId = testMobileAccount.Id;
         optyObj.Drive_Site__c = testMobileSite.Id;
         optyObj.Drive_Date__c = system.today().addDays(-1);
         optyObj.CloseDate = system.today().addDays(-20);
         optyObj.Is_Template__c = true;
         optyObj.Name = 'Test Drive';
         optyObj.StageName = 'Discovery'; 
         optyObj.Drive_Status__c = 'Draft';
         optyObj.WB_Projected_Procedures__c = 1;
         optyObj.X2RBC_Projected_Procedures__c = 1;
         optyObj.Anticipated_Registered_Donors__c = 1;
         skedHubBase.BypassInsertTriggers = true;
         skedHubBase.BypassUpdateTriggers = true;
         TriggerHandler.bypass('OpportunityTriggerHandler');
         oppList.add(optyObj);
         //insert optyObj;
 
         Opportunity testMobileOpp = (Opportunity)mapTestData.get('MOBILE_OPP');
         testMobileOpp.accountId = testMobileAccount.Id;
         testMobileOpp.Drive_Site__c = testMobileSite.Id;
         testMobileOpp.Drive_Date__c = system.today().addDays(-1);
         testMobileOpp.CloseDate = system.today().addDays(-20);
         testMobileOpp.Parent_Template_Id__c = optyObj.id;
         oppList.add(testMobileOpp);
         Triggerhandler.bypass('OpportunityTriggerHandler');
         insert oppList;
 
         Biomed_Collection_Op_Center__c testCollectionOperation1 = new Biomed_Collection_Op_Center__c(Name = 'Collection Operation 1',
                                                                                                         sked_Lunch_Break_Duration_Fixed_Site__c = '30',
                                                                                                         sked_Lunch_Break_Duration_Mobile__c = '30',
                                                                                                         sked_Hold_Threshold__c = 100,
                                                                                                         Staging_Location_Geolocation__Latitude__s = 37.7450046,
                                                                                                         Staging_Location_Geolocation__Longitude__s = -122.4816244,
                                                                                                         sked_Work_Week_First_Day__c = 'Sunday');
         insert testCollectionOperation1;
 
         sked_Drive__c testDrive1 = new sked_Drive__c(Name = 'Test Drive',
                                                         sked_Collection_Operation__c = testCollectionOperation1.Id,
                                                         sked_Drive_Date__c = System.today().addDays(-1),
                                                         sked_Drive_Site__c = testFixedSite.Id,
                                                         sked_Opportunity__c = testFixedSiteOpp.Id,
                                                         sked_Type_of_Drive__c = 'Fixed Site',
                                                         sked_Account__c = testFixedSiteAccount.Id,
                                                         sked_Start_Time__c = Time.newInstance(7, 0, 0, 0),
                                                         sked_End_Time__c = Time.newInstance(17, 0, 0, 0),
                                                         sked_Drive_Productivity_Planned__c = 0.8,
                                                         sked_Projected_Registered_Donors__c = 100,
                                                      	 sked_2RBC_Projected_Procedures__c = 20,
                                                      	 sked_WB_Projected_Procedures__c = 20,
                                                         sked_Status__c = BSF_Constants.DOC_STATUS_DRAFT);
         skedHubBase.BypassInsertTriggers = true;
         skedHubBase.BypassUpdateTriggers = true;
         TriggerHandler.bypass('DriveTriggerHandler');
         insert testDrive1;
         
         Chapter__c ojdih = new Chapter__c();
         ojdih.Name = 'ARC';
         ojdih.Type__c = 'Chapter';
         insert ojdih;
         Chapter_Blood_Region_Zip_Match__c dededf = new Chapter_Blood_Region_Zip_Match__c();
         dededf.Chapter__c = ojdih.Id;
         dededf.Zip__c = '12344';
         insert dededf;
         
     }
    @isTest
    static void testmethod1() {
        Test.startTest();
        Database.executeBatch(new BSFPopulateSiteChapterBatch(system.today().addDays(-30),system.today().addDays(30)),200);
        Test.stopTest();
    }
}