force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/Coverage_Reason__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Reason__c</fullName>
    <description>Field to capture the vacancy reason on Account Team Member level.</description>
    <label>Coverage Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leave of Absence (LOA)</fullName>
            </value>
            <value>
                <fullName>Vacant Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Original_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Service_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Original Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Calendar Build</fullName>
            </value>
            <value>
                <fullName>Business Planning</fullName>
            </value>
            <value>
                <fullName>Adhoc Calendar Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityTeamMember/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Address__c.field-meta.xml
<CustomField>
    <fullName>sked__Address__c</fullName>
    <description>The address of the location</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Site</fullName>
            </value>
            <value>
                <fullName>Mobile Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Address_1__c.field-meta.xml
<CustomField>
    <fullName>sked_Address_1__c</fullName>
    <label>Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_ARC_Vehicle_Parking_Directions__c.field-meta.xml
<CustomField>
    <fullName>sked_ARC_Vehicle_Parking_Directions__c</fullName>
    <label>ARC Vehicle Parking Directions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Automation_Suitability__c.field-meta.xml
<CustomField>
    <fullName>sked_Automation_Suitability__c</fullName>
    <inlineHelpText>Indicates if the Site is Suitable or Unsuitable for Double Red Blood Cells.</inlineHelpText>
    <label>Automation Suitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Suitable</fullName>
            </value>
            <value>
                <fullName>Unsuitable</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Base_Description__c.field-meta.xml
<CustomField>
    <fullName>sked_Base_Description__c</fullName>
    <label>Base Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_City__c.field-meta.xml
<CustomField>
    <fullName>sked_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_County__c.field-meta.xml
<CustomField>
    <fullName>sked_County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Directions_From_CollectionOperation__c.field-meta.xml
<CustomField>
    <fullName>sked_Directions_From_CollectionOperation__c</fullName>
    <label>Directions From Collection Operation</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Floor_Description__c.field-meta.xml
<CustomField>
    <fullName>sked_Floor_Description__c</fullName>
    <label>Floor Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Inside_stairs__c.field-meta.xml
<CustomField>
    <fullName>sked_Inside_stairs__c</fullName>
    <label>Inside stairs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_National_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_National_Name__c</fullName>
    <label>National Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Outside_stairs__c.field-meta.xml
<CustomField>
    <fullName>sked_Outside_stairs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outside Stairs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Pay_for_Parking__c.field-meta.xml
<CustomField>
    <fullName>sked_Pay_for_Parking__c</fullName>
    <label>Pay for Parking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None Required – Open parking​</fullName>
            </value>
            <value>
                <fullName>Validated by Sponsor​</fullName>
            </value>
            <value>
                <fullName>Staff Responsible​</fullName>
            </value>
            <value>
                <fullName>Capped Meters​</fullName>
            </value>
            <value>
                <fullName>Prepaid Parking Voucher​</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Pay_for_Parking_Details__c.field-meta.xml
<CustomField>
    <fullName>sked_Pay_for_Parking_Details__c</fullName>
    <inlineHelpText>Provide details if &#39;Other&#39; option was selected for Pay for Parking.</inlineHelpText>
    <label>Pay for Parking Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Physical_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Physical_Location_Type__c</fullName>
    <label>Physical Location Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
            <value>
                <fullName>Inside/Outside</fullName>
                <isActive>false</isActive>
                <label>Inside/Outside</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Room_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Room_Name__c</fullName>
    <label>Room Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Building_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Building_Name__c</fullName>
    <label>Site/Building Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Locations (Site Contact)</relationshipLabel>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Inspection_Completed_By__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Inspection_Completed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site is deemed suitable and as applicable concerns are documented and approved.</inlineHelpText>
    <label>Site Inspection Completed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Site_Main_Phone__c.field-meta.xml
<CustomField>
    <fullName>sked_Site_Main_Phone__c</fullName>
    <label>Site Main Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Staff_Personal_Parking_Directions__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Personal_Parking_Directions__c</fullName>
    <label>Staff Personal Parking Directions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_State__c.field-meta.xml
<CustomField>
    <fullName>sked_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Travel_Time_to_Staging_Location__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_to_Staging_Location__c</fullName>
    <label>Travel Time to Staging Location</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Wireless_Policy__c.field-meta.xml
<CustomField>
    <fullName>sked_Wireless_Policy__c</fullName>
    <inlineHelpText>Accepted  
Connectivity Wired Only: allowed but not functional 
Sponsor Wired Only: wireless not allowed to be used  
Prohibited: not allowed on site</inlineHelpText>
    <label>Wireless Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Prohibited</fullName>
            </value>
            <value>
                <fullName>Connectivity Wired Only</fullName>
            </value>
            <value>
                <fullName>Sponsor Wired Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&quot;Standard New Form&quot;</defaultValue>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard New Form</fullName>
            </value>
            <value>
                <fullName>Custom New Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Tag__c/sked__Tag__c.object-meta.xml
<CustomObject>
    <description>string metadata to be associated  with any other object</description>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Tag__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Asset Type</fullName>
            </value>
            <value>
                <fullName>Physical Location Type</fullName>
            </value>
            <value>
                <fullName>Drive Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BSF_Batch_OpportunitySplitDelete_Test.cls
@isTest
public class BSF_Batch_OpportunitySplitDelete_Test {
    
    public static String rolename = 'West_BDM';
    public static String mobileOppRecType = 'Mobile Opp';
    public static String mobileAccRecType = 'Mobile Account';
    public static String mobileSiteRecType = 'Mobile Site';    
    public static Map<String,Id> recordTypeMap  = new Map<String,Id>();
    
    @testSetup 
    public static void prepareDataset(){
        recordTypeMap = recordTypeMap( 'Opportunity' );
        Id optyRecTypeId = recordTypeMap.get(mobileOppRecType);
        
        recordTypeMap = recordTypeMap( 'Account' );
        Id accRecTypeId = recordTypeMap.get(mobileAccRecType);
        
        recordTypeMap = recordTypeMap( 'sked__Location__c' );
        Id siteRecTypeId = recordTypeMap.get(mobileSiteRecType);
        
        User AdminUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'adminuser000@amamama.com',
            Username = 'adminuser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            
        );
        
        UserRole urole  = [select id from userrole where developername =: rolename ];
        
        User DRDAMUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'DRD Profile'].Id,
            LastName = 'last',
            Email = 'DRDProfile000@amamama.com',
            Username = 'drduser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = urole.Id
        );
        
        System.runAs( AdminUser ){
            insert DRDAMUser;
        }
        System.runAs( AdminUser ){
            
            //create account
            List<Account> mobileAccList = new List<Account>();
        	Account accObj;
        	accObj = new Account();
        	accObj.RecordTypeId = accRecTypeId;
        	accObj.Name = 'Exavalu';
            accobj.Internal_Name__c = 'Exavalu';
        	accObj.BillingPostalCode = '30622';            
        	mobileAccList.add(accobj); 
        
        	accObj = new Account();
        	accObj.RecordTypeId = accRecTypeId;
        	accObj.Name = 'Exavalu2';
            accobj.Internal_Name__c = 'Exavalu2';
        	accObj.BillingPostalCode = '30623';            
        	mobileAccList.add(accobj);
            
        	insert mobileAccList;
            
            // create account team member
            List<AccountTeammember> atmList = new List<AccountTeammember>();
      		AccountTeammember atm;
      		atm = new AccountTeammember();
      		atm.AccountAccessLevel = 'Edit';
      		atm.CaseAccessLevel = 'Edit';
      		atm.OpportunityAccessLevel = 'Edit';
      		atm.userId = DRDAMUser.Id ;
      		atm.AccountId = mobileAccList[0].Id ;
      		atm.TeamMemberRole = 'Account Specialist';
            atm.Coverage_Reason__c = 'Leave of Absence (LOA)';
      		atm.End_Date__c = Date.Today().addDays(10);
	  		atm.Start_Date__c = Date.Today().addDays(-10);
      		atmList.add(atm);      
      		insert atmList;
            
            // create contact
            Contact conObj = new Contact();
            conObj.AccountId = mobileAccList[0].Id;
            conObj.FirstName = 'Test';
            conObj.LastName = 'Contact';
            conObj.Email = 'testContact@gmail.com';
        	conObj.Original_Service_Date__c = system.today().addDays(3);
        	conObj.Primary_Phone__c = 'Mobile Phone';
        	conObj.MobilePhone = '752-781-0090';
            conObj.MailingCity = 'Ashburn';
            conObj.MailingCountryCode ='US';
            conObj.MailingPostalCode = '20148';
            conObj.MailingStateCode = 'VA';
            conObj.MailingStreet = '23070 Learning Cir';
            insert conObj;
            
            sked__Tag__c skedTag = new sked__Tag__c();
            skedTag.Name = 'Outside';
            skedTag.sked__Type__c = 'Physical Location Type';            
            insert skedTag; 
            
            //create sked_Location__c
            sked__Location__c siteObj = new sked__Location__c();
            siteObj.RecordTypeId = siteRecTypeId;
            siteObj.Name = 'Test Site';
            siteObj.sked__Address__c = 'Test Site Address';
            siteObj.sked_Site_Building_Name__c = 'Test Site Building';
            siteObj.sked_Floor_Description__c = 'Test Site Floor Description';
            siteObj.sked_Room_Name__c = 'Room 15';
            siteObj.sked_National_Name__c = 'AMERICA';
            siteObj.sked_Physical_Location_Type__c = 'Outside';
            siteObj.sked_Site_Inspection_Completed_By__c = [SELECT Id FROM USER WHERE Email = 'DRDProfile000@amamama.com' ].Id;
            siteObj.sked_Automation_Suitability__c = 'Suitable';
            siteObj.sked_Outside_stairs__c = 1;
            siteObj.sked_Inside_stairs__c = 2;
            siteObj.sked_Base_Description__c = 'test base description';
            siteObj.sked_Travel_Time_to_Staging_Location__c = 45;
            siteObj.sked_ARC_Vehicle_Parking_Directions__c = 'Test Direction';
            siteObj.sked_Staff_Personal_Parking_Directions__c = 'Test Direction';
            siteObj.sked_Site_Contact__c = [SELECT Id FROM Contact WHERE FirstName = 'Test' AND LastName = 'Contact' ].Id;
            siteObj.sked_Site_Main_Phone__c = '758-771-0091';
            siteObj.sked_Directions_From_CollectionOperation__c = 'Test Direction';
            siteObj.sked_Pay_for_Parking__c = 'Other';
            siteObj.sked_Pay_for_Parking_Details__c = 'Test Pay';
            siteObj.sked_Wireless_Policy__c = 'Accepted';            
            siteObj.sked_Address_1__c = 'Test Site Address 1';  
        	siteObj.sked_County__c = 'USA';
        	siteObj.sked_City__c = 'Aubum';
        	siteObj.sked_State__c = 'Alabama';
        	siteObj.sked_Zip_Code__c = '36801';
        	siteObj.sked_Wireless_Policy__c = 'Accepted';
        	siteObj.Source__c = 'Custom New Form';
            insert siteObj;
            
            //create opportunity
            List<Opportunity> oppsobjlist = new List<Opportunity>();
            Opportunity optyObj  = new Opportunity();          
            optyObj.RecordTypeId = optyRecTypeId;
            optyObj.AccountId = mobileAccList[0].Id;
            optyObj.Drive_Site__c = siteObj.Id;
            optyObj.Name = 'Test Drive';
            optyObj.StageName = 'Discovery';
            optyObj.Drive_Date__c = System.today();
            optyObj.CloseDate = System.today();
            optyObj.Start_Time__c = System.now().Time();
            optyObj.End_Time__c = System.now().Time()+1;
            optyObj.WB_Projected_Procedures__c = 1;
            optyObj.X2RBC_Projected_Procedures__c = 1;
            optyObj.Anticipated_Registered_Donors__c = 1;            
            oppsobjlist.add( optyObj );
            insert oppsobjlist;    
        }
    }
        
        @isTest static void oppSplitDelete() { 
            
            Id adminprofileid = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id ;
	  		User adminuser = [ select Id from User where ProfileId =: adminprofileid and isActive = true limit 1];
            
            Id drdprofileid = [SELECT Id FROM Profile WHERE Name = 'DRD Profile'].Id ;
			User drduser = [ select Id from User where ProfileId =: drdprofileid and isActive = true limit 1];
            
            System.runAs( adminuser ){
                List<Opportunity> opps = new List<Opportunity>();
        		opps = [ select Id from Opportunity limit 20];
  				
                //create opportunity split
                List<OpportunitySplit> opsplits = new List<OpportunitySplit>();                
        		OpportunitySplit opsplit;
                opsplit = new OpportunitySplit();
       			opsplit.OpportunityId = opps[0].Id;
        		opsplit.Is_Covering_Incentive__c = false;
        		opsplit.SplitNote = 'test';
        		opsplit.Split_Amount__c = 20;
        		opsplit.Split_Reason__c = 'Coverage Vacancy';
                opsplit.SplitOwnerId = drduser.Id ;
        		opsplits.add( opsplit );
                insert opsplits;
                
                // create opportunity team member
                List<OpportunityTeamMember> otmList = new List<OpportunityTeamMember>();
                OpportunityTeamMember otm = new OpportunityTeamMember();
                otm.OpportunityId = opps[0].Id;
                otm.TeamMemberRole = 'District Manager';
                otm.UserId = drduser.Id;
                otm.Start_Date__c = system.today();
                otmList.add(otm);
                insert otmList;
                
                Test.startTest();
                
                BSF_Batch_OpportunitySplitDelete batchDelete = new BSF_Batch_OpportunitySplitDelete(opsplits , otmList);
                database.executeBatch(batchDelete);
                
                Test.stopTest();       
            }
            
        }
   
    //Method to get the map of recordType Name as key and recordTypeId as value 
    public static Map<String,Id> recordTypeMap(string obj){
        Map<String,Id> recTypeNameWithIdMap = new Map<String,Id>();
        if(obj!= null){
            for(Schema.RecordTypeInfo recInfo : Schema.getGlobalDescribe().get(obj).getDescribe().getRecordTypeInfosByName().values()){
                recTypeNameWithIdMap.put(recInfo.getName(),recInfo.getRecordTypeId());
            }
        }
        return recTypeNameWithIdMap;
    } 

}