force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Open_to_Public__c.field-meta.xml
<CustomField>
    <fullName>Open_to_Public__c</fullName>
    <label>Open to Public?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 6 AND (3 OR 4 OR 5)</booleanFilter>
        <errorMessage>Only Templates related to the same Account are eligible and related site must be active.</errorMessage>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Is_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Drive_Site__r.sked_End_Date__c</field>
            <operation>greaterThan</operation>
            <valueField>$Source.Drive_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Cancelled</value>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Withdrawn</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Template_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select the Template for this Opportunity. Only Templates related to the same Account are eligible to be selected.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Security_Escort_Name__c.field-meta.xml
<CustomField>
    <fullName>Security_Escort_Name__c</fullName>
    <label>Security Escort Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Web_Sched_Offset_from_CO_Global_Settings__c.field-meta.xml
<CustomField>
    <fullName>Web_Sched_Offset_from_CO_Global_Settings__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Web Sched Offset from CO/Global Settings</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Mobile_Opp.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Opp</fullName>
    <active>true</active>
    <businessProcess>Blood Drive Sales Process</businessProcess>
    <label>Mobile Opp</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <formula>Opportunity.Drive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Order_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Due_Date__c</fullName>
    <inlineHelpText>This is a auto populated field, do not put any value here.</inlineHelpText>
    <label>Order Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Publicity_Approved__c.field-meta.xml
<CustomField>
    <fullName>Publicity_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicity Approved &amp; Submitted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Publicity_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Publicity_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicity Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2RBC Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Account__c.field-meta.xml
<CustomField>
    <fullName>sked_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sked_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WB Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateTaskDriveDateBatchTest.cls
@isTest(SeeAllData = FALSE)
public class UpdateTaskDriveDateBatchTest {
    @TestSetup
    static void updateTaskDrive() { 
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects();
        
        // insert Mobile Account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c =  'TEST ACCOUNT 1';
        insert testMobileAccount;
        
        // insert Mobile Site 1
        sked__Location__c testMobileSite1 = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite1;
        
        Test.startTest();
        // insert template 1 - PLT - Inside
        Opportunity testTemplate1 = (Opportunity)mapTestData.get('MOBILE_TEMPLATE_OPP');
        testTemplate1.AccountId = testMobileAccount.Id;
        testTemplate1.Drive_Site__c = testMobileSite1.Id;
        testTemplate1.Type = 'Inside';
        insert testTemplate1;
        
        // insert mobile opp
        TriggerHandler.bypass('OpportunityTeamMemberTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity testMobileOpp = (Opportunity)mapTestData.get('MOBILE_OPP');
        testMobileOpp.AccountId = testMobileAccount.Id;
        testMobileOpp.Drive_Site__c = testMobileSite1.Id;
        testMobileOpp.Parent_Template_Id__c = testTemplate1.Id;
        testMobileOpp.Open_to_Public__c = 'Yes';
        testMobileOpp.Security_Escort_Name__c = 'TEST';
        //testMobileOpp.Web_Sched_Offset_from_CO_Global_Settings__c = True;
        oppList.add(testMobileOpp);
        triggerHandler.bypass('OpportunityTriggerHandler');
        insert oppList;
        
        sked_Drive__c drives = new sked_Drive__c();
        drives.sked_Opportunity__c = oppList[0].Id;
        drives.sked_Account__c = testMobileAccount.Id;
        drives.sked_Drive_Date__c=oppList[0].Drive_Date__c;
        drives.sked_2RBC_Projected_Procedures__c = 20;
        drives.sked_WB_Projected_Procedures__c = 20;
        insert drives;
        
         Order testOrder = new Order(
            AccountId = testMobileAccount.ID,
            Name = 'Test Order',
            Status = 'Draft',
            EffectiveDate = Date.today(),
            Order_Due_Date__c = Date.today().addDays(15), // Order Due Date is 15 days from today
            Publicity_Approved__c = false,
            Publicity_Submitted__c = false,
            OpportunityId = oppList[0].Id
        );
        triggerHandler.bypass('OrderTriggerHandler');
        insert testOrder;
        
        List<Task> allTask = new List<Task>();
        Task task1 = new Task(Subject = 'Test Task 1', WhatId = oppList[0].Id, Drive_Date__c = null);
        Task task2 = new Task(Subject = 'Test Task 2', WhatId = testOrder.Id, Drive_Date__c = null);
        Task task3 = new Task(Subject = 'Test Task 3', WhatId = drives.Id, Drive_Date__c = null);
        allTask.add(task1);
        allTask.add(task2);
        allTask.add(task3);
        
        insert allTask;   
    }
     @IsTest
    static void testBatchExecution1() {
        
        Test.startTest();
        UpdateTaskDriveDateBatch batch = new UpdateTaskDriveDateBatch();
        Database.executeBatch(batch,200);        
        Test.stopTest();
        
        Task updatedTask1 = [SELECT WhatId, Drive_Date__c FROM Task WHERE Subject = 'Test Task 1' LIMIT 1];
        Task updatedTask2 = [SELECT WhatId, Drive_Date__c FROM Task WHERE Subject = 'Test Task 2' LIMIT 1];
        Task updatedTask3 = [SELECT WhatId, Drive_Date__c FROM Task WHERE Subject = 'Test Task 3' LIMIT 1];
        
        System.assertEquals(updatedTask1.Drive_Date__c, [SELECT Drive_Date__c FROM Opportunity WHERE Id = :updatedTask1.WhatId].Drive_Date__c);
        System.assertEquals(updatedTask2.Drive_Date__c, [SELECT Drive_Date__c FROM Order WHERE Id = :updatedTask2.WhatId].Drive_Date__c);
        System.assertEquals(updatedTask3.Drive_Date__c, [SELECT sked_Drive_Date__c FROM sked_Drive__c WHERE Id = :updatedTask3.WhatId].sked_Drive_Date__c);
    }
}