force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Mobile_Account.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Account</fullName>
    <active>true</active>
    <label>Mobile Account</label>
</RecordType>

unpackaged/main/default/objects/BSF_Task_Checklist__c/BSF_Task_Checklist__c.object-meta.xml
<CustomObject>
    <label>BSF Task Checklist</label>
    <nameField>
        <displayFormat>TCS-{00000}</displayFormat>
        <label>BSF Task Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSF Task Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BSF_Task_Checklist__c/fields/OpportunityLookup__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Lookup</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>BSF Task Checklists</relationshipLabel>
    <relationshipName>BSF_Task_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BSF_Task_Checklist__c/fields/Picklist_Input_2__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Input_2__c</fullName>
    <label>Picklist Input 2</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/BSF_Task_Checklist__c/fields/TaskLookup__c.field-meta.xml
<CustomField>
    <fullName>TaskLookup__c</fullName>
    <label>Task Lookup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Task_Checklist__c/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <label>TaskType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Task_Checklist__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Anticipated_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Registered_Donors__c</fullName>
    <description>Numeric value that reflects the # of donors expected to be at the drive. Current based on historical drive data (like drive, how many people).</description>
    <label>Anticipated Registered Donors</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Template Id</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 6 AND (3 OR 4 OR 5)</booleanFilter>
        <errorMessage>Only Templates related to the same Account are eligible and related site must be active.</errorMessage>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Is_Template__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Drive_Site__r.sked_End_Date__c</field>
            <operation>greaterThan</operation>
            <valueField>$Source.Drive_Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Cancelled</value>
        </filterItems>
        <filterItems>
            <field>$Source.StageName</field>
            <operation>equals</operation>
            <value>Withdrawn</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Template_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select the Template for this Opportunity. Only Templates related to the same Account are eligible to be selected.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Procedure_Projections_Template__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Projections_Template__c</fullName>
    <label>Procedure Projections Template</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Slot_Generator__c.field-meta.xml
<CustomField>
    <fullName>Slot_Generator__c</fullName>
    <description>Field has been added as part of HRP-12011</description>
    <label>Slot Generator</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Slot_Generator_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Slot_Generator_Change_Reason__c</fullName>
    <description>Field has been added as part of HRP-12011</description>
    <label>Slot Generator Change Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>Calendar Build</fullName>
            </value>
            <value>
                <fullName>Business Planning</fullName>
            </value>
            <value>
                <fullName>Adhoc Calendar Build</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Whole Blood Procedures Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>X2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Double Red Procedures Projected</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Mobile_Opp.recordType-meta.xml
<RecordType>
    <fullName>Mobile_Opp</fullName>
    <active>true</active>
    <businessProcess>Blood Drive Sales Process</businessProcess>
    <label>Mobile Opp</label>
</RecordType>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&quot;Standard New Form&quot;</defaultValue>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard New Form</fullName>
            </value>
            <value>
                <fullName>Custom New Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskChecklistController_Test.cls
/* Description : This test class covers TaskChecklistController 
 * Current Test Coverage : 94%
   
 * Modification Log 
 * Date					     Developer Name			     Comments
 * ***********************************************************************************************************************************************
 * 10/30/2024				  Priti Jana				Created for HRP-?
 *************************************************************************************************************************************************
*/

@isTest
public class TaskChecklistController_Test {
    
    @testSetup static void prepareTestData() {
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        // insert Mobile Account
        Account testMobileAccount = (Account)mapTestData.get('MOBILE_ACCOUNT');
        testMobileAccount.Internal_Name__c =  'TEST ACCOUNT 1';
        insert testMobileAccount;
        
        // insert Mobile Site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite;
        
        // insert templates
        Opportunity testTemplate = (Opportunity)mapTestData.get('MOBILE_TEMPLATE_OPP');
        testTemplate.AccountId = testMobileAccount.Id;
        testTemplate.Drive_Site__c = testMobileSite.Id;
        insert testTemplate;
        
        // insert Mobile Opp
        Opportunity mobileOpportunityRecord = (Opportunity)mapTestData.get('MOBILE_OPP');
        mobileOpportunityRecord.StageName = 'Discovery';
        mobileOpportunityRecord.AccountId = testMobileAccount.Id;
        mobileOpportunityRecord.Drive_Site__c = testMobileSite.Id;
        mobileOpportunityRecord.Parent_Template_Id__c = testTemplate.Id;
        mobileOpportunityRecord.Procedure_Projections_Template__c = 10;
        mobileOpportunityRecord.Drive_Date__c = Date.Today().addDays(30);
        mobileOpportunityRecord.CloseDate = System.today();
        mobileOpportunityRecord.Start_Time__c = System.now().Time();
        mobileOpportunityRecord.End_Time__c = System.now().Time() + 1;
        mobileOpportunityRecord.Anticipated_Registered_Donors__c = 1;  
        mobileOpportunityRecord.X2RBC_Projected_Procedures__c = 1;
        mobileOpportunityRecord.WB_Projected_Procedures__c = 2;
        mobileOpportunityRecord.Source__c = 'Adhoc';
        mobileOpportunityRecord.Slot_Generator__c = 130;
        mobileOpportunityRecord.Slot_Generator_Change_Reason__c = 'System Generated Value';
        TriggerHandler.bypass('OpportunityTriggerHandler');
        insert mobileOpportunityRecord;
        TriggerHandler.clearAllBypasses();
        
        // Create Tasks
        List<Task> oppTasks = new List<Task>();
        Task recruitmentTask = new Task(
        	Subject = BSF_Constants.RECRUITMENT_PLANNING_TASK,
        	WhatId = mobileOpportunityRecord.Id,
        	ActivityDate = System.Today(),
        	Status = 'Not Started',
        	Priority = 'Normal'
        );
        oppTasks.add(recruitmentTask);
        
        Task pdaTask = new Task(
        	Subject = BSF_Constants.POST_DRIVE_ANALYSIS_TASK,
        	WhatId = mobileOpportunityRecord.Id,
        	ActivityDate = System.Today(),
        	Status = 'Not Started',
        	Priority = 'Normal'
        );
        oppTasks.add(pdaTask);
        
        insert oppTasks;
        
        // insert BSF_Task_Checklist__c
        List<BSF_Task_Checklist__c> taskCheckList = new List<BSF_Task_Checklist__c>();
        BSF_Task_Checklist__c taskCheckList1 = new BSF_Task_Checklist__c(
        	TaskLookup__c = (String) oppTasks[0].Id,
        	TaskType__c = BSF_Constants.RECRUITMENT_PLANNING_TASK,
        	Unique_Name__c = 'Inform_BPL_Checklist'
        );
        BSF_Task_Checklist__c taskCheckList2 = new BSF_Task_Checklist__c(
        	OpportunityLookup__c = (String) mobileOpportunityRecord.Id,
        	TaskType__c = BSF_Constants.POST_DRIVE_ANALYSIS_TASK,
        	Unique_Name__c = 'Review_Data'
        );
        taskCheckList.add(taskCheckList1);
        taskCheckList.add(taskCheckList2);
        insert taskCheckList;  
    }

    static testMethod void testCheckEditAccess() {
        Test.startTest();
        Boolean hasEditAccess = TaskChecklistController.checkEditAccess();
        Assert.areEqual(TRUE, hasEditAccess);
        Test.stopTest();
    }
    
    static testmethod void testGetRelatedCheckistRecordsForOpp() {
        Test.startTest();
        Opportunity mobileOpp = [SELECT Id FROM Opportunity WHERE Is_Template__c = FALSE LIMIT 1];
        Map<String, TaskChecklistController.CheckListWrapper> map_chklstUniqueName_checklistWrapper;
        try{
            map_chklstUniqueName_checklistWrapper = TaskChecklistController.getRelatedCheckistRecords((String) mobileOpp.Id);
        } catch (Exception e) {
            System.debug('Error occurred while fetching checklist records for opportunity: ' + e.getMessage());
            System.debug('Stack Trace: ' + e.getStackTraceString());
        }
        Test.stopTest();
        Assert.isNotNull(map_chklstUniqueName_checklistWrapper);
    }
    
    static testmethod void testGetRelatedCheckistRecordsForTask() {
        Test.startTest();
        Task recruitmentTask = [SELECT Id FROM Task WHERE Subject = :BSF_Constants.POST_DRIVE_ANALYSIS_TASK LIMIT 1];
        Map<String, TaskChecklistController.CheckListWrapper> map_chklstUniqueName_checklistWrapper = TaskChecklistController.getRelatedCheckistRecords((String) recruitmentTask.Id);
        Test.stopTest();
        Assert.isNotNull(map_chklstUniqueName_checklistWrapper);
    }
    
    static testMethod void testUpdateTaskChecklist() {
        Test.startTest();
        BSF_Task_Checklist__c taskCheckList = [SELECT Id, Picklist_Input_2__c FROM BSF_Task_Checklist__c WHERE TaskType__c = :BSF_Constants.POST_DRIVE_ANALYSIS_TASK LIMIT 1];
        String jsonString = '[{"Id":"'+(String) taskCheckList.Id+'","Picklist_Input_2__c":"Do Not Roll"}]';
        Map<String, String> map_successMsg_successDetails = TaskChecklistController.updateTaskChecklist(jsonString);
        Test.stopTest();
        Assert.areEqual('Checklist has been successfully saved.', map_successMsg_successDetails.get('message'));
    }
}