force-app/main/default/objects/Account/fields/Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>Operation_Type__c</fullName>
    <label>Operation Type (Not in use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Non Integrated WB</fullName>
            </value>
            <value>
                <fullName>Non Integrated APH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/skedJobHandler_Test.cls
@isTest
private class skedJobHandler_Test {
    @isTest
    static void generateDriveTypeTag_FixedSite_WB_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Account testAccount = (Account) mapTestData.get('testAccount1');
        testAccount.Operation_Type__c = skedConstants.OPERATION_TYPE_WB;
        update testAccount;

        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        sked_Drive__c fixedSiteTestDrive = testDrive.clone(false, false, false, false);
        fixedSiteTestDrive.sked_Type_Of_Drive__c = 'Fixed Site';


        Test.startTest();
            insert fixedSiteTestDrive;
        Test.stopTest();
    }

    @isTest
    static void generateDriveTypeTag_FixedSite_APH_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Account testAccount = (Account) mapTestData.get('testAccount1');
        testAccount.Operation_Type__c = skedConstants.OPERATION_TYPE_APH;
        update testAccount;

        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        sked_Drive__c fixedSiteTestDrive = testDrive.clone(false, false, false, false);
        fixedSiteTestDrive.sked_Type_Of_Drive__c = 'Fixed Site';


        Test.startTest();
            insert fixedSiteTestDrive;
        Test.stopTest();
    }
}