force-app/main/default/objects/sked__Holiday__c/sked__Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Holiday__c/fields/sked__End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked__End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Holiday__c/fields/sked__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked__Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Holiday_Region__c/sked__Holiday_Region__c.object-meta.xml
<CustomObject>
    <label>Holiday Region</label>
    <nameField>
        <displayFormat>HR-{0}</displayFormat>
        <label>Holiday Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holiday Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Holiday_Region__c/fields/sked__Holiday__c.field-meta.xml
<CustomField>
    <fullName>sked__Holiday__c</fullName>
    <label>Holiday</label>
    <referenceTo>sked__Holiday__c</referenceTo>
    <relationshipLabel>Holiday Regions</relationshipLabel>
    <relationshipName>Holiday_Regions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Holiday_Region__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Holiday Regions</relationshipLabel>
    <relationshipName>Holiday_Regions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Event_Type_Setting__c/sked_Event_Type_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Skedulo Event Type Setting</label>
</CustomObject>

unpackaged/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Available_End__c.field-meta.xml
<CustomField>
    <fullName>sked_Available_End__c</fullName>
    <defaultValue>1900</defaultValue>
    <label>Available End</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Available_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Available_Start__c</fullName>
    <defaultValue>800</defaultValue>
    <label>Available Start</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Background_Color__c.field-meta.xml
<CustomField>
    <fullName>sked_Background_Color__c</fullName>
    <defaultValue>&#39;#0ea7cc&#39;</defaultValue>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Can_Be_Pre_dated__c.field-meta.xml
<CustomField>
    <fullName>sked_Can_Be_Pre_dated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Be Pre-dated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Color__c.field-meta.xml
<CustomField>
    <fullName>sked_Color__c</fullName>
    <defaultValue>&#39;#fff&#39;</defaultValue>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>sked_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Item__c.field-meta.xml
<CustomField>
    <fullName>sked_Item__c</fullName>
    <label>Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Short_Name__c</fullName>
    <label>Short Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Show_Legend__c.field-meta.xml
<CustomField>
    <fullName>sked_Show_Legend__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Legend</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Event_Type_Setting__c/fields/sked_Step__c.field-meta.xml
<CustomField>
    <fullName>sked_Step__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Step</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/skedSetting_Test.cls
@isTest
private class skedSetting_Test {

    @isTest
    static void skedSetting_Test() {
        skedSetting.skedAppSetting appSetting = skedSetting.instance.App;
        skedSetting.skedBookingGridSetting bookingGridSetting = skedSetting.instance.BG;
        skedSetting.skedEcSetting ecSetting = skedSetting.instance.EC;
        skedSetting.skedLacSetting lacSetting = skedSetting.instance.LAC;
        skedSetting.skedPacSetting pacSetting = skedSetting.instance.PAC;
        skedSetting.skedRacSetting racSetting = skedSetting.instance.RAC;
        Map<String, Set<Date>> holidays = appSetting.mapHoliday;
    }

    @TestSetup
    static void makeData() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject>  mapTestData = testDataFactory.setupCommonTestData();

        sked__Region__c testRegion = (sked__Region__c) mapTestData.get('testRegion1');

        sked__Holiday__c testGlobalHoliday = new sked__Holiday__c(
            Name = 'Test',
            sked__Start_Date__c = System.today().addDays(100),
            sked__End_Date__c = System.today().addDays(100)
        );
        insert testGlobalHoliday;

        sked__Holiday_Region__c testHolidayRegion = new sked__Holiday_Region__c(
            sked__Holiday__c = testGlobalHoliday.Id,
            sked__Region__c = testRegion.Id
        );
        insert testHolidayRegion;

        sked_Event_Type_Setting__c testEventTypeSetting = new sked_Event_Type_Setting__c(
            Name = 'Test',
            sked_Is_Active__c = true,
            sked_Item__c = 'Test Item',
            sked_Available_Start__c = 800,
            sked_Available_End__c = 1900,
            sked_Background_Color__c = '#fff',
            sked_Can_Be_Pre_dated__c = true,
            sked_Color__c = '#666',
            sked_Short_Name__c = 'Test',
            sked_Step__c = 1,
            sked_Is_Available__c = true,
            sked_Show_Legend__c = true,
            sked_Category__c = 'job'
        );
        insert testEventTypeSetting;
    }
}