unpackaged/main/default/objects/sked_Staffing_Budget__c/sked_Staffing_Budget__c.object-meta.xml
<CustomObject>
    <label>Staffing Budget</label>
    <nameField>
        <displayFormat>SB-{000000}</displayFormat>
        <label>Staffing Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Staffing_Budget__c/fields/sked_Convert_to_Standard_On__c.field-meta.xml
<CustomField>
    <fullName>sked_Convert_to_Standard_On__c</fullName>
    <label>Convert to Standard On</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Staffing_Budget__c/fields/sked_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bidding Period</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Unavailability Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/skedConvertBiddingToStandardBatch.cls
global class skedConvertBiddingToStandardBatch implements Database.Batchable<sked_Staffing_Budget__c> {
    
    global skedConvertBiddingToStandardBatch() {}
     
    global List<sked_Staffing_Budget__c> start(Database.BatchableContext BC) {
        return [SELECT Id, sked_Request_Type__c
                FROM sked_Staffing_Budget__c
                WHERE sked_Convert_to_Standard_On__c = :system.today()];
    }
    
    global void execute(Database.BatchableContext BC, List<sked_Staffing_Budget__c> records) {
        for (sked_Staffing_Budget__c record : records) {
            record.sked_Request_Type__c = skedConstants.STAFFING_BUDGET_REQUEST_TYPE_STANDARD;
        }
        update records;
    }
    
    global void finish(Database.BatchableContext BC) {}

}