unpackaged/main/default/objects/sked_Notification_Format__mdt/sked_Notification_Format__mdt.object-meta.xml
<CustomObject>
    <label>Skedulo Notification Format</label>
    <pluralLabel>Skedulo Notification Formats</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/sked_Notification_Format__mdt/fields/sked_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Date_Time_Field__c</fullName>
    <label>Date Time Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Format__mdt/fields/sked_Format_For_Token__c.field-meta.xml
<CustomField>
    <fullName>sked_Format_For_Token__c</fullName>
    <label>Format For Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Format__mdt/fields/sked_Format_String__c.field-meta.xml
<CustomField>
    <fullName>sked_Format_String__c</fullName>
    <label>Format String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Format__mdt/fields/sked_Notification_Setting__c.field-meta.xml
<CustomField>
    <fullName>sked_Notification_Setting__c</fullName>
    <label>Skedulo Notification Setting</label>
    <referenceTo>sked_Notification_Setting__mdt</referenceTo>
    <relationshipLabel>Skedulo Notification Formats</relationshipLabel>
    <relationshipName>sked_Notification_Formats</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Format__mdt/fields/sked_Timezone_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone_Field__c</fullName>
    <label>Timezone Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Setting__mdt/sked_Notification_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Skedulo Notification Setting</label>
    <pluralLabel>Skedulo Notification Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Content_Renderer__c.field-meta.xml
<CustomField>
    <fullName>sked_Content_Renderer__c</fullName>
    <label>Content Renderer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Custom_Target_Destination__c.field-meta.xml
<CustomField>
    <fullName>sked_Custom_Target_Destination__c</fullName>
    <label>Custom Target Destination</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Destination_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Destination_Field__c</fullName>
    <inlineHelpText>Custom field that is used to store destination&#39;s email address or phone number</inlineHelpText>
    <label>Destination Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Email_From_Address_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Email_From_Address_Field__c</fullName>
    <label>Email From Address Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Filter__c.field-meta.xml
<CustomField>
    <fullName>sked_Filter__c</fullName>
    <label>Filter</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Notification_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Notification_Target_Field__c</fullName>
    <inlineHelpText>This must be User, Contact or Lead, required by Salesforce.</inlineHelpText>
    <label>Notification Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Notification_Type__c</fullName>
    <label>Notification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>oneoff</fullName>
                <default>true</default>
                <label>oneoff</label>
            </value>
            <value>
                <fullName>customsms</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>salesforcepush</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Oneoff_Protocol_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Oneoff_Protocol_Field__c</fullName>
    <label>Oneoff Protocol Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Sending_From_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>sked_Sending_From_Email_Address__c</fullName>
    <label>Sending From Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Subject__c.field-meta.xml
<CustomField>
    <fullName>sked_Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Target_Field__c.field-meta.xml
<CustomField>
    <fullName>sked_Target_Field__c</fullName>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Target_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>sked_Target_Field_Value__c</fullName>
    <label>Target Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Target_SObject__c.field-meta.xml
<CustomField>
    <fullName>sked_Target_SObject__c</fullName>
    <label>Target SObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Notification_Setting__mdt/fields/sked_Template__c.field-meta.xml
<CustomField>
    <fullName>sked_Template__c</fullName>
    <label>Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/skedSendNotificationBatch.cls
global class skedSendNotificationBatch extends skedNotificationBatchBase implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    protected List<notificationSettingModel> notificationSettings;
    
    global skedSendNotificationBatch(Map<Id, Set<Id>> map_settingId_recordIds) {
        this.notificationSettings = getNotificationSettings(map_settingId_recordIds);
        initialize();
    }
    
    global skedSendNotificationBatch(Map<Id, Set<Id>> map_settingId_recordIds, List<SObject> newRecords, Map<Id, SObject> oldMap) {
        this.notificationSettings = getNotificationSettings(map_settingId_recordIds);
        initialize();

        this.newRecords = newRecords;
        this.oldMap = oldMap;
    }
    
    global skedSendNotificationBatch(List<notificationSettingModel> settings) {
        this.notificationSettings = settings;
        initialize();
    }

    global skedSendNotificationBatch(List<notificationSettingModel> settings, List<SObject> newRecords, Map<Id, SObject> oldMap) {
        this.notificationSettings = settings;
        initialize();

        this.newRecords = newRecords;
        this.oldMap = oldMap;
    }
    
    global List<sObject> start(Database.BatchableContext BC) {
        return this.retrieveTargetRecords();
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> records) {
        if (string.isNotBlank(this.notificationSetting.contentRenderer)) {
            Set<Id> inputRecordIds = new Set<Id>();
            for (sObject record : records) {
                inputRecordIds.add(record.Id);
            }
            this.contentRenderer.process(inputRecordIds, newRecords, oldMap);
        }
        if(!string.isBlank(this.notificationSetting.customTargetDestination)) {
            Set<Id> inputRecordIds = new Set<Id>();
            for (sObject record : records) {
                inputRecordIds.add(record.Id);
            }
            this.customTargetDestination.process(inputRecordIds, records);
        }
        this.sendNotification(this.notificationSetting.notificationType, records);
    }
    
    global void finish(Database.BatchableContext BC) {
        this.notificationSettings.remove(0);
        if (!this.notificationSettings.isEmpty()) {
            skedSendNotificationBatch nextBatchJob = new skedSendNotificationBatch(this.notificationSettings, this.newRecords, this.oldMap);
            Database.executeBatch(nextBatchJob, 20);
        }
    }
    
    /************************************************* Private methods *******************************************************/
    private List<notificationSettingModel> getNotificationSettings(Map<Id, Set<Id>> map_settingId_recordIds) {
        List<notificationSettingModel> notificationSettings = new List<notificationSettingModel>();
        List<sked_Notification_Setting__mdt> skedNotificationSettings = [SELECT Id, DeveloperName, sked_Target_SObject__c, sked_Target_Field__c, 
                                                                         sked_Target_Field_Value__c, sked_Notification_Type__c, sked_Filter__c,
                                                                         sked_Destination_Field__c, sked_Notification_Target_Field__c, 
                                                                         sked_Email_From_Address_Field__c, sked_Template__c, 
                                                                         sked_Sending_From_Email_Address__c, sked_Custom_Target_Destination__c,
                                                                         sked_Content_Renderer__c, sked_Oneoff_Protocol_Field__c, sked_Subject__c,
                                                                         (SELECT Id, sked_Date_Time_Field__c, sked_Format_For_Token__c, 
                                                                          sked_Format_String__c, sked_Timezone_Field__c
                                                                          FROM sked_Notification_Formats__r)
                                                                         FROM sked_Notification_Setting__mdt
                                                                         WHERE Id IN :map_settingId_recordIds.keySet()];
        for (sked_Notification_Setting__mdt skedNotificationSetting : skedNotificationSettings) {
            Set<Id> recordIds = map_settingId_recordIds.get(skedNotificationSetting.Id);
            skedSendNotificationBatch.notificationSettingModel setting = new skedSendNotificationBatch.notificationSettingModel(skedNotificationSetting, recordIds);
            notificationSettings.add(setting);
        }
        return notificationSettings;
    }
    
    private void initialize() {
        this.notificationSetting = this.notificationSettings.get(0);
        this.recordIds = this.notificationSetting.recordIds;

		this.baseInitialize();
    }

}