unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/AccTeamFromPortfolioAssignmentService__e.object-meta.xml
<CustomObject>
    <description>Used in  &quot;PortfolioAssignmentService&quot;  Apex Class</description>
    <label>AccTeamFromPortfolioAssignmentService</label>
    <pluralLabel>AccTeamFromPortfolioAssignmentService</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/AccountAccessLevel__c.field-meta.xml
<CustomField>
    <fullName>AccountAccessLevel__c</fullName>
    <label>AccountAccessLevel</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>AccountTeam Accountid</description>
    <label>AccountId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/BSF_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>BSF_Portfolio__c</fullName>
    <label>BSF_Portfolio__c</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/CaseAccessLevel__c.field-meta.xml
<CustomField>
    <fullName>CaseAccessLevel__c</fullName>
    <label>CaseAccessLevel</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>AccountTeam End_Date__c</description>
    <label>End_Date__c</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/OpportunityAccessLevel__c.field-meta.xml
<CustomField>
    <fullName>OpportunityAccessLevel__c</fullName>
    <label>OpportunityAccessLevel</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>AccountTeam Start date</description>
    <label>Start_Date__c</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>TeamMemberRole</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccTeamFromPortfolioAssignmentService__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>AccountTeam UserId</description>
    <label>UserId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/BSF_Portfolio__c.object-meta.xml
<CustomObject>
    <label>BSF Portfolio</label>
    <nameField>
        <label>BSF Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSFPortfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Account_Based_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Account_Based_Portfolio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Based Portfolio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BSF_Portfolio__c/fields/Portfolio_Type__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Type__c</fullName>
    <label>Portfolio Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Portfolio_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Portfolio__c/fields/Taxonomy_Type__c.field-meta.xml
<CustomField>
    <fullName>Taxonomy_Type__c</fullName>
    <label>Taxonomy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bio Recruitment CD</fullName>
            </value>
            <value>
                <fullName>Bio Collection BSF</fullName>
            </value>
            <value>
                <fullName>Bio Account Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Fixed Sites</fullName>
            </value>
            <value>
                <fullName>Bio Sickle Cell Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Relationship Manager Portfolio</fullName>
            </value>
            <value>
                <fullName>National Account Manager Portfolio</fullName>
            </value>
            <value>
                <fullName>Bio Recruitment Supervisor</fullName>
            </value>
            <value>
                <fullName>Bio Booking Support</fullName>
            </value>
            <value>
                <fullName>Account Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Portfolio_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Account Portfolio</fullName>
    </customValue>
    <customValue>
        <fullName>Account Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Area Booking Manager</fullName>
        <label>Strategic Business Planning Manager</label>
    </customValue>
    <customValue>
        <fullName>Collection Operation</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRICT</fullName>
    </customValue>
    <customValue>
        <fullName>District Manager</fullName>
    </customValue>
    <customValue>
        <fullName>DSVP</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>National Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Power Booker</fullName>
    </customValue>
    <customValue>
        <fullName>RDSE</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sickle Cell Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Support</fullName>
    </customValue>
    <masterLabel>Portfolio Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AccountTeamInsert_Test.cls
@isTest
public class AccountTeamInsert_Test 
{
    @isTest
    public static void testAccountTeamInsert(){
        
        Map <String,Schema.RecordTypeInfo> recordTypesAccount = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        Id mobileRecTypeId = recordTypesAccount.get('Mobile Account').getRecordTypeId();
        List<Account> accList = new List<Account>();
        Account mobileAcc1 = new Account(
            name = 'Test Account 1',
        	RecordTypeId = MobileRecTypeId,
            BillingStreet = '2204 Westcrt ln, Apt 213', 
        	BillingCity = 'Herndon',
        	BillingStateCode = 'MI',
        	BillingPostalCode = '48420'
        );
        
        insert mobileAcc1;
        
   Bsf_portfolio__c bsf = new Bsf_Portfolio__c();
        bsf.Account_Based_Portfolio__c=true;
        bsf.Portfolio_Type__c='Account Manager';
        bsf.Taxonomy_Type__c='Bio Recruitment CD';
        bsf.Start_Date__c = system.today()-1;
        bsf.End_Date__c = system.today()+3;
        
        insert bsf;
  AccTeamFromPortfolioAssignmentService__e accTeamEve = new AccTeamFromPortfolioAssignmentService__e();
  List<AccTeamFromPortfolioAssignmentService__e> accTeamEveList = new List<AccTeamFromPortfolioAssignmentService__e>();

     						accTeamEve.UserId__c=userinfo.getUserId();
                            accTeamEve.AccountId__c=mobileAcc1.Id;
                            accTeamEve.BSF_Portfolio__c=bsf.id;
                            accTeamEve.Start_Date__c=system.today();
                            accTeamEve.End_Date__c=system.today()+3;
                            accTeamEve.AccountAccessLevel__c='Edit';
                            accTeamEve.CaseAccessLevel__c='Edit';
                            accTeamEve.OpportunityAccessLevel__c='Edit';
                            accTeamEve.TeamMemberRole__c='Account Manager';
                            accTeamEveList.add(accTeamEve);
        
        test.startTest();
        try{
        EventBus.publish(accTeamEveList);
        }
        catch(exception e)
        {
            system.debug('exception'+e);
        }
        test.stopTest();
    }
}