unpackaged/main/default/objects/Collections_Territory__c/Collections_Territory__c.object-meta.xml
<CustomObject>
    <description>***API name is different because of reference in code.  Please do not change API name without update to code</description>
    <label>Collections Zipcode</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections Zipcodes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Collections_Territory__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Updated field label for Oct 2019 geographic realignment</description>
    <label>Donor Services Region</label>
    <referenceTo>Collections_Region__c</referenceTo>
    <relationshipLabel>Collections Zip Codes (Region)</relationshipLabel>
    <relationshipName>Collections_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Collections_Territory__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates blood collection services are provided by the Red Cross in this Zip Code</description>
    <inlineHelpText>Indicates blood collection services are provided by the Red Cross in this Zip Code</inlineHelpText>
    <label>Service Area</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collections_Territory__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collections_Territory__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Atlantic</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Eastern</fullName>
            </value>
            <value>
                <fullName>Hawaii-Aleutian</fullName>
            </value>
            <value>
                <fullName>Mountain</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collections_Territory__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <description>The zip code.</description>
    <externalId>true</externalId>
    <inlineHelpText>The zip code.</inlineHelpText>
    <label>Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Collections_Territory__c.field-meta.xml
<CustomField>
    <fullName>Collections_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collections Territory</label>
    <referenceTo>Collections_Territory__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Church/Faith-Based Group</fullName>
            </value>
            <value>
                <fullName>Civic/Community</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Media Outlet</fullName>
            </value>
            <value>
                <fullName>Military/Government/NGO</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Amusement/Recreational</fullName>
                <isActive>false</isActive>
                <label>Amusement/Recreational</label>
            </value>
            <value>
                <fullName>Corporate/Business/Retail Business/Manufacturing</fullName>
                <isActive>false</isActive>
                <label>Corporate/Business/Retail Business/Manufacturing</label>
            </value>
            <value>
                <fullName>Education, University Greek System</fullName>
                <isActive>false</isActive>
                <label>Education, University Greek System</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>Government</label>
            </value>
            <value>
                <fullName>Hospital, Medical, Health and Wellness</fullName>
                <isActive>false</isActive>
                <label>Hospital, Medical, Health and Wellness</label>
            </value>
            <value>
                <fullName>Media</fullName>
                <isActive>false</isActive>
                <label>Media</label>
            </value>
            <value>
                <fullName>Membership/Community Organization/Alumni Greek System</fullName>
                <isActive>false</isActive>
                <label>Membership/Community Organization/Alumni Greek System</label>
            </value>
            <value>
                <fullName>Military</fullName>
                <isActive>false</isActive>
                <label>Military</label>
            </value>
            <value>
                <fullName>Religious</fullName>
                <isActive>false</isActive>
                <label>Religious</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Biomed Lead Process Master</businessProcess>
    <description>Default lead record type</description>
    <label>Lead</label>
</RecordType>

unpackaged/main/default/objects/Lead/recordTypes/LSL.recordType-meta.xml
<RecordType>
    <fullName>LSL</fullName>
    <active>true</active>
    <businessProcess>Biomed Lead Process Master</businessProcess>
    <description>Leaders Save Lives (LSL) program lead record type.</description>
    <label>LSL</label>
</RecordType>

unpackaged/main/default/objects/Taxonomy__c/Taxonomy__c.object-meta.xml
<CustomObject>
    <description>Taxonomy data from GOATS is imported in this object</description>
    <label>Taxonomy</label>
    <nameField>
        <displayFormat>TAX-{0000000000}</displayFormat>
        <label>Taxonomy</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxonomies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxonomy__c/fields/ABM_Code__c.field-meta.xml
<CustomField>
    <fullName>ABM_Code__c</fullName>
    <label>ABM Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/ABM_Key__c.field-meta.xml
<CustomField>
    <fullName>ABM_Key__c</fullName>
    <label>ABM Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/ABM_Name__c.field-meta.xml
<CustomField>
    <fullName>ABM_Name__c</fullName>
    <label>ABM Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City name</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Code__c.field-meta.xml
<CustomField>
    <fullName>Division_Code__c</fullName>
    <label>Division Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Key__c.field-meta.xml
<CustomField>
    <fullName>Division_Key__c</fullName>
    <label>Division Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <label>Division Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DRD_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Code__c</fullName>
    <label>DRD Territory Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DRD_Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Key__c</fullName>
    <label>DRD Territory Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/DRD_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>DRD_Territory_Name__c</fullName>
    <label>DRD Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/DS_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Code__c</fullName>
    <label>DS Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DS_Region_Key__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Key__c</fullName>
    <label>DS Region Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/DS_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>DS_Region_Name__c</fullName>
    <label>DS Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Code__c.field-meta.xml
<CustomField>
    <fullName>Team_Code__c</fullName>
    <label>Team Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Key__c.field-meta.xml
<CustomField>
    <fullName>Team_Key__c</fullName>
    <label>Team Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Stores Custom Time Zone Information</description>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Type_Key__c.field-meta.xml
<CustomField>
    <fullName>Type_Key__c</fullName>
    <label>Type Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Version_Key__c.field-meta.xml
<CustomField>
    <fullName>Version_Key__c</fullName>
    <label>Version Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Taxonomy__c/fields/Zip_Code_Key__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Key__c</fullName>
    <label>Zip Code Key</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Taxonomy__c/fields/Zip_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Name__c</fullName>
    <label>Zip Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/LeadFormLSLConTests.cls
@isTest
public class LeadFormLSLConTests {
    
    @testSetup
    static void setup(){
        
        Collections_Region__c testRegion = new Collections_Region__c(Name = 'Test Region');
        insert(testRegion);

        Collections_Territory__c goodTerritory = new Collections_Territory__c(
            Zip__c = '02770', 
            City__c = 'Rochester',
            State_Code__c = 'MA',
            Service_Area__c = true,
            Region__c = testRegion.Id
        );
        insert(goodTerritory);



        Collections_Territory__c badTerritory = new Collections_Territory__c(
            Zip__c = '27587', 
            City__c = 'Wake Forest',
            State_Code__c = 'NC',
            Service_Area__c = false,
            Region__c = testRegion.Id
        );
        insert(badTerritory);
        
         Collections_Territory__c badTerritory2 = new Collections_Territory__c(
            Zip__c = '20105', 
            City__c = 'Aldie',
            State_Code__c = 'NC',
            Service_Area__c = false,
            Region__c = testRegion.Id
        );
        insert(badTerritory2);
        
        Date startDate = system.today().addDays(30);
        Date endDate = system.today().addDays(-30);
        
        String taxonomyBioSFRecordType = Schema.SObjectType.Taxonomy__c.getRecordTypeInfosByName().get(BSF_Constants.BIO_COLLECTION_RECORD_TYPE).getRecordTypeId();

        Taxonomy__c taxonomy = new Taxonomy__c(ABM_Code__c='GEOR_S Georgia Coastal_ABM', ABM_Key__c=115960, ABM_Name__c='Georgia Coastal ABM', Division_Code__c='BD33', Division_Key__c=42263, Division_Name__c='Southeast and Caribbean', DRD_Territory_Code__c='HProdSED_755', DRD_Territory_Key__c=115893, DRD_Territory_Name__c='GA South 02', DS_Region_Code__c='03E', DS_Region_Key__c=42058, DS_Region_Name__c='Georgia', End_Date__c=System.today()+180, RecordTypeId=taxonomyBioSFRecordType,Start_Date__c=System.today()-10,Team_Code__c='GEOR_S Georgia Coastal', Team_Key__c=42878, Team_Name__c='GEOR_S Georgia Coastal', Time_Zone__c='America/New_York', Type_Key__c=169, Type__c=BSF_Constants.BIO_RECRUITMENT_RECORD_TYPE, Zip_Code_Key__c=20105, Zip_Code__c='20105', Zip_Code_Name__c='20105',Version_Key__c=1000,City__c='Aldie',State__c='VA');

        //Taxonomy__c taxonomy = new Taxonomy__c(Zip_Code__c='20105',Start_Date__c=startDate,End_Date__c=endDate,City__c = 'Wake Forest',State__c = 'NC');
        insert taxonomy;
    }

    
    
    
    static testMethod void pageLoadTest() {
        // Make sure certain properties are set when a page loads
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);
        

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con;

        Test.startTest();
            con = new LeadFormLSLCon();
        Test.stopTest();

        // Test: did the controller create a new Lead object?
        System.assert(con.newLead != null);

    }
    
     static testMethod void formValid1() {
        // Make sure certain properties are set when a page loads
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        
        
        con.firstName = '';
        con.lastName = '';
        con.companyName = '';
        con.email = '';
        con.phone = '';
        con.newLead.Company_Type__c = null;
        //con.setCompanyType();   

        Test.startTest();
         
            con.formIsValid();
            
        Test.stopTest();

        // Test: did the controller create a new Lead object?
        System.assert(con.newLead != null);
        System.assertEquals(false, con.validFirstName);
        System.assertEquals(false, con.validLastName);
        System.assertEquals(false, con.validCompanyName);
        System.assertEquals(false, con.validEmail);
        System.assertEquals(false, con.validPhone);
    }
    
    
    
     
    
    
  
    static testMethod void stateOpts() {
        
        // Validates that the Lead Form's State picklist has some options 
        // 
        
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        List<SelectOption> opts = new List<SelectOption>();
        
        Test.startTest();
           con.getStateOpts();
        Test.stopTest();
        
        System.assertEquals(0,opts.size());
    }
    
    
    static testMethod void validZipTest() {

        // A valid zip code results in the form being displayed
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = true];
        

        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        //con.did = '';
        Lead l = con.newLead;
        l.PostalCode = t.Zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        l.Company_Type__c = 'Church/Faith-Based Group';


        Test.startTest();
            con.validateZipcode();
            //con.setCompanyType();
        Test.stopTest();

		//Update 12024- we are removing territory dependency and moved to taxonomy completely
        System.assertEquals(null,con.territory); 
        //System.assertEquals(true, con.showRel); // because the Company_Type__c = 'Church/Faith-Based Group', the "showRel" property should be true

    }

    static testMethod void invalidZipTest(){
        // A bad zip code results in an error

        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        //con.did = '';
        Lead l = con.newLead;
        l.PostalCode = 'FRANK'; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        

        Test.startTest();
            con.validateZipcode();
        Test.stopTest();


        System.assertEquals(false, con.areaServed);
        System.assertEquals(false, con.validZip);
        System.assertEquals(null,con.territory);    
        
    }

    static testMethod void unknownZipTest(){
        // if the zip code isn't in the Collections Region table, we still want to show 
        // the lead form and capture their information

        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        //con.did = '';
        Lead l = con.newLead;
        l.PostalCode = '99999'; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        

        Test.startTest();
            con.validateZipcode();
        Test.stopTest();


        System.assertEquals(false, con.areaServed);
        System.assertEquals(false, con.validZip);
        System.assertEquals(null,con.territory);
    }


    static testMethod void nonServiceZipTest(){
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false and Zip__c = '27587' limit 1];
        List<Taxonomy__c> taxonomyList =[select id, Zip_Code__c from Taxonomy__c where Zip_code__c = '27587'];

        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadForm;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        
        con.did = '';

        Test.startTest();
            con.validateZipcode();
        Test.stopTest();


        System.assertEquals(false, con.areaServed);//this will be false, on lack of taxonomy record 
        System.assert(taxonomyList.size() == 0);
        
    }

    static testMethod void nonServiceZipTestWithValidTaxonomy(){
        // if the zip code isn't in the ARC blood collections service area, we want to stop the user from seeing the form and wasting their time.

        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false and Zip__c = '20105' limit 1];
        Taxonomy__c taxonomy =[select id, Zip_Code__c from Taxonomy__c where Zip_Code__c = '20105' limit 1];
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadForm;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        
        con.did = '';

        Test.startTest();
            con.validateZipcode();
        Test.stopTest();


        System.assertEquals(true, con.areaServed);//this will be true, because of presence of taxonomy record
        System.Assert(taxonomy != null);
        System.assertEquals(true, con.validZip);
        
    }

    static testMethod void invalidFormTest(){

        // If an invalid phone and/or email is provided, the lead record will not be saved and
        // validation messages will be presented to the user
        
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        //con.did = '';
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        l.Company_Type__c = 'Business';
        //con.setCompanyType();
        
        l.Company_Sub_Type__c = 'Corporation';
        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        l.Company_Size__c = '501 - 1000';
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.title = 'President';
        con.email = 'test@here.org.test'; // Important for this test: an invalid email
        con.phone = '888-7878'; // Important for this test: an invalid phone format
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Testinghouse Inc.';


        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertNotEquals(null, con.validationErrors);
        

    }



    static testMethod void leadSaveTest(){

        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadForm;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormCon con = new LeadFormCon();
        //con.did = '';
        String siteKey = con.siteKey;
        System.assert(siteKey != null);
        
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        

        l.Company_Type__c = 'Education';
        con.setCompanyType();
        l.Company_Type__c = 'Civic/Community';
        con.setCompanyType();
        l.Company_Type__c = 'Media Outlet';
        con.setCompanyType();
        l.Company_Type__c = 'Healthcare';
        con.setCompanyType();
        l.Company_Type__c = 'Military/Government/NGO';
        con.setCompanyType();
        l.Company_Type__c = 'Other';
        con.setCompanyType();
        l.Company_Type__c = 'Business';
        con.setCompanyType();
        
        l.Company_Sub_Type__c = 'Corporation';
        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        l.Company_Size__c = '501 - 1000';
        l.Phone_Type__c = 'Mobile phone';
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.title = 'President';
        con.email = 'test@here.org';
        con.phone = '999-888-7878';
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Testinghouse Inc.';


        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertEquals(0, con.validationErrors.size());

        Lead[] leadResult = [select id, Collections_Territory__c from Lead where Email = :con.email];
        System.assertNotEquals(null, leadResult[0]);
        //System.assertEquals(t.Id, leadResult[0].Collections_Territory__c);

    }
    
    
        
        
    static testMethod void LslSaveTest(){

        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);

        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        //con.did = '';
        String siteKey = con.siteKey;
        System.assert(siteKey != null);
        
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        

        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.email = 'test.lsl.lead@here.org';
        con.phone = '999-888-7878';
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Test High School';
        l.Age_Group__c = '16 - 18';
        l.Current_Blood_Donor__c = 'No';
        l.Student_Type__c = 'High School';
        l.Phone_Type__c = 'Mobile phone';
        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertEquals(0, con.validationErrors.size(), con.validationErrors);

        Lead[] leadResult = [select id, Company_Type__c, RecordType.Name, Collections_Territory__c from Lead where Email = :con.email];
        //System.assertNotEquals(null, leadResult);
        //System.assertEquals(t.Id, leadResult.Collections_Zipcode__c);
        //System.assertEquals('Education', leadResult.Company_Type__c);
        System.assertEquals('LSL', leadResult[0].RecordType.Name);

    }
    
    
    static testMethod void validCampaignIdTest(){
        
        // A valid campaignId is passed in the url/querystring
        
        final string DID_VAL = 'LSL_4848484';
        
        Campaign testCampaign = new Campaign(
            Name = 'Test LSL Campaign', 
            IsActive = true, 
            External_Campaign_Id__c = 'ABC123',
            External_Cid__c='cid123',
            External_Med__c='med123',	
            External_Source__c='source123',
        	External_Did__c = DID_VAL
        );
        insert(testCampaign);
        
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);


		
        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();


        // Critical for this test
        /*con.cmpId = testCampaign.External_Campaign_Id__c; // normally the ext campaign id will be passed into the form via javascript, but this will have to do.
        con.cidId = testCampaign.External_Cid__c;
        con.medId = testCampaign.External_Med__c;
        con.sourceId = testCampaign.External_Source__c;*/
        //con.did = DID_VAL;
        con.validateZipcode();


        
        String siteKey = con.siteKey;
        System.assert(siteKey != null);
        
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        

        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.email = 'test.lsl.lead@here.org';
        con.phone = '999-888-7878';
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Test High School';
        l.Age_Group__c = '16 - 18';
        l.Current_Blood_Donor__c = 'No';
        l.Student_Type__c = 'High School';
	    l.Phone_Type__c = 'Mobile phone';
        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertEquals(0, con.validationErrors.size(), con.validationErrors);

        Lead[] leadResult = [select id, Company_Type__c, RecordType.Name, Collections_Territory__c from Lead where Email = :con.email];
        
    	// Verify a CampaignMember record was created.
        //CampaignMember cmTest = [select Id, LeadId from CampaignMember where CampaignId = :testCampaign.Id];
        //System.assertEquals(cmTest.LeadId, leadResult.Id);
    
    }
    
    static testMethod void invalidCampaignIdTest(){
        
        // An INvalid campaignId is passed in the url/querystring
        
        
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadFormLSL;
        Test.setCurrentPage(leadFormPgRef);
		ApexPages.currentPage().getParameters().put('cid','bogus_campaign_id'); // IMPORTANT FOR THIS TEST
        
        // Create an instance of our page's controller for testing
        LeadFormLSLCon con = new LeadFormLSLCon();
        String siteKey = con.siteKey;
        System.assert(siteKey != null);
        
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.
        

        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.email = 'test.lsl.lead@here.org';
        con.phone = '999-888-7878';
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Test High School';
        l.Age_Group__c = '16 - 18';
        l.Current_Blood_Donor__c = 'No';
        l.Student_Type__c = 'High School';
        l.Phone_Type__c = 'Mobile phone';
        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertEquals(0, con.validationErrors.size(), con.validationErrors);

        
        // Verify the lead was created
        Lead[] leadResult = [select id, Company_Type__c, RecordType.Name, Collections_Territory__c from Lead where Email = :con.email];
        System.assert(leadResult[0].Id != null);
        
    	// Verify a CampaignMember record NOT was created.
        List<CampaignMember> cmResults = [select Id, LeadId from CampaignMember where LeadId = :leadResult[0].Id];
        System.assertEquals(0, cmResults.size());
    
    }
    
    /*
    static testMethod void validCampaignIdTest(){

        // A valid campaign id is passed via the url, the new lead should be added to the campaign
        // 
        
        
        Campaign testCampaign = new Campaign(Name = 'Test Campaign', IsActive = true);
        insert(testCampaign);
        
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadForm;
        Test.setCurrentPage(leadFormPgRef);
		ApexPages.currentPage().getParameters().put('cid',testCampaign.Id); // IMPORTANT FOR THIS TEST
        
        // Create an instance of our page's controller for testing
        LeadFormCon con = new LeadFormCon();
        String siteKey = con.siteKey;
        System.assert(siteKey != null);
        
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.l.Company_Type__c = 'Education';
        l.Company_Type__c = 'Business';
        con.setCompanyType();
        
        l.Company_Sub_Type__c = 'Corporation';
        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        l.Company_Size__c = '501 - 1000';
        
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.title = 'President';
        con.email = 'test@here.org';
        con.phone = '999-888-7878';
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Testinghouse Inc.';


        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertEquals(0, con.validationErrors.size());

        Lead leadResult = [select id, Collections_Territory__c from Lead where Email = :con.email];
        System.assertNotEquals(null, leadResult);
        System.assertEquals(t.Id, leadResult.Collections_Territory__c);
        
        // Verify a CampaignMember record was created.
        CampaignMember cmTest = [select Id, LeadId from CampaignMember where CampaignId = :testCampaign.Id];
        System.assertEquals(cmTest.LeadId, leadResult.Id);

    }

    
    
    
    static testMethod void invalidCampaignIdTest(){

        // An INvalid campaign id is passed via the url, the new lead should NOT be added to a campaign
        // 
        
        
        Collections_Territory__c t = [select id, zip__c from Collections_Territory__c where Service_Area__c = false limit 1];
        
        // Set up the leadForm page for testing
        PageReference leadFormPgRef = Page.LeadForm;
        Test.setCurrentPage(leadFormPgRef);
		ApexPages.currentPage().getParameters().put('cid','bogus_campaign_id'); // IMPORTANT FOR THIS TEST
        
        // Create an instance of our page's controller for testing
        LeadFormCon con = new LeadFormCon();
        String siteKey = con.siteKey;
        System.assert(siteKey != null);
        
        Lead l = con.newLead;
        l.PostalCode = t.zip__c; // we'll use the zip code from the test Territory we created in the Setup() section so we know it exists and is valid.l.Company_Type__c = 'Education';
        l.Company_Type__c = 'Business';
        con.setCompanyType();
        
        l.Company_Sub_Type__c = 'Corporation';
        l.Hosted_Before__c = 'No';
        l.Has_Personal_Story__c = 'No';
        l.Company_Size__c = '501 - 1000';
        
        con.firstName = 'Testerly';
        con.lastName = 'Testinghouse';
        con.title = 'President';
        con.email = 'test@here.org';
        con.phone = '999-888-7878';
        con.street = '12 TEsting Way';
        con.city = 'Testingham';
        con.companyName = 'Testinghouse Inc.';


        Test.startTest();
            con.saveLead();
        Test.stopTest();

        System.assertEquals(0, con.validationErrors.size());

        Lead leadResult = [select id, Collections_Territory__c from Lead where Email = :con.email];
        System.assertNotEquals(null, leadResult);
        System.assertEquals(t.Id, leadResult.Collections_Territory__c);
        
        // Verify a CampaignMember record was created.
        List<CampaignMember> cmResults = [select Id, LeadId from CampaignMember where LeadId = :l.Id];
        System.assertEquals(0, cmResults.size());

    }
    */
}