force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__End1__c.field-meta.xml
<CustomField>
    <fullName>sked__End1__c</fullName>
    <formula>sked__Start__c  +  sked__Duration__c  / 1440</formula>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_CDL__c.field-meta.xml
<CustomField>
    <fullName>sked_CDL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_DOT__c.field-meta.xml
<CustomField>
    <fullName>sked_DOT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DOT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <label>Timezone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Category__c.field-meta.xml
<CustomField>
    <fullName>sked__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked__Resource_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Cargo Van</fullName>
            </value>
            <value>
                <fullName>ProMaster</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <label>Region Timezone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/sked_Operation_Record__c.object-meta.xml
<CustomObject>
    <label>Operation Record</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Operation Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Operation_Record__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <formula>sked_Drive__r.sked_Timezone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_Workday_Submission_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Workday_Submission_Status__c</fullName>
    <description>Draft = waiting for batch. Processed = all staff submitted. Partial = some staff succeeded, some failed. Failed = technical failure.</description>
    <label>Workday Submission Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/sked_Operation_Record_Staff__c.object-meta.xml
<CustomObject>
    <label>Operation Record Staff</label>
    <nameField>
        <displayFormat>ORS-{000000}</displayFormat>
        <label>Operation Staff Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Record Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/Scheduled_Shift_End__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Shift_End__c</fullName>
    <description>Added this field as part of HRP-12929</description>
    <label>Scheduled Shift End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/Scheduled_Shift_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Shift_End_Date__c</fullName>
    <description>This field is created as part of HRP-12929</description>
    <label>Scheduled Shift End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/Scheduled_Shift_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Shift_End_Time__c</fullName>
    <description>This field is created as part of HRP-12929</description>
    <label>Scheduled Shift End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/Scheduled_Shift_Start__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Shift_Start__c</fullName>
    <description>Added this field as part of HRP-12929</description>
    <label>Scheduled Shift Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/Scheduled_Shift_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Shift_Start_Date__c</fullName>
    <description>This field is created as part of HRP-12929</description>
    <label>Scheduled Shift Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/Scheduled_Shift_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Shift_Start_Time__c</fullName>
    <description>This field is created as part of HRP-12929</description>
    <label>Scheduled Shift Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Actual_Shift_End__c.field-meta.xml
<CustomField>
    <fullName>sked_Actual_Shift_End__c</fullName>
    <label>Actual Shift End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Actual_Shift_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Actual_Shift_End_Date__c</fullName>
    <label>Actual Shift End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Actual_Shift_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Actual_Shift_End_Time__c</fullName>
    <label>Actual Shift End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Actual_Shift_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Actual_Shift_Start__c</fullName>
    <label>Actual Shift Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Actual_Shift_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Actual_Shift_Start_Date__c</fullName>
    <label>Actual Shift Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Actual_Shift_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Actual_Shift_Start_Time__c</fullName>
    <label>Actual Shift Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Early_Departure_Date_Received__c.field-meta.xml
<CustomField>
    <fullName>sked_Early_Departure_Date_Received__c</fullName>
    <label>Early Departure Date Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Early_Departure_DateTime_Received__c.field-meta.xml
<CustomField>
    <fullName>sked_Early_Departure_DateTime_Received__c</fullName>
    <label>Early Departure DateTime Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Early_Departure_Time_Received__c.field-meta.xml
<CustomField>
    <fullName>sked_Early_Departure_Time_Received__c</fullName>
    <label>Early Departure Time Received</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Job_Allocation__c.field-meta.xml
<CustomField>
    <fullName>sked_Job_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Allocation</label>
    <referenceTo>sked__Job_Allocation__c</referenceTo>
    <relationshipLabel>Operation Record Staff</relationshipLabel>
    <relationshipName>sked_Operation_Record_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Late_Arrival_Date_Received__c.field-meta.xml
<CustomField>
    <fullName>sked_Late_Arrival_Date_Received__c</fullName>
    <label>Late Arrival Date Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Late_Arrival_DateTime_Received__c.field-meta.xml
<CustomField>
    <fullName>sked_Late_Arrival_DateTime_Received__c</fullName>
    <label>DateTime Late Arrival Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Late_Arrival_Time_Received__c.field-meta.xml
<CustomField>
    <fullName>sked_Late_Arrival_Time_Received__c</fullName>
    <label>Time Late Arrival Received</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Resource__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Operation Record Staff</relationshipLabel>
    <relationshipName>sked_Operation_Record_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <formula>sked_Operation_Record__r.sked_Timezone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Workday_Submission_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Workday_Submission_Status__c</fullName>
    <description>Per-staff Workday submission status. Retries only select staff with Failed and attempt count below max.</description>
    <label>Workday Submission Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Staff_Meal_Rest_Break_Setting__c/sked_Staff_Meal_Rest_Break_Setting__c.object-meta.xml
<CustomObject>
    <label>Staff Meal &amp; Rest Break Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Meal &amp; Rest Break Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Staff_Meal_Rest_Break_Setting__c/fields/sked_Operation_Record_Staff__c.field-meta.xml
<CustomField>
    <fullName>sked_Operation_Record_Staff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Operation Record Staff</label>
    <referenceTo>sked_Operation_Record_Staff__c</referenceTo>
    <relationshipLabel>Staff Meal &amp; Rest Break Settings</relationshipLabel>
    <relationshipName>Staff_Meal_Rest_Break_Settings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/skedOperationRecordStaffHandler.cls
public class skedOperationRecordStaffHandler extends skedTriggerHub {
    
    public override void onBeforeInsert() {
        populateData(this.context.newRecords);
        applyWorkdayIgnoreForVolunteers(this.context.newRecords);
        if (skedSetting.instance.Admin.dateTimeConversion) {
            doDateTimeConversion(this.context.newRecords);
        }
    }
    
    public override void onBeforeUpdate() {
        applyWorkdayIgnoreForVolunteers(this.context.newRecords);
        if (skedSetting.instance.Admin.dateTimeConversion) {
            doDateTimeConversion(this.context.newRecords, (Map<Id, sked_Operation_Record_Staff__c>)this.context.oldMap);
            populateData(this.context.newRecords, (Map<Id, sked_Operation_Record_Staff__c>)this.context.oldMap);
        }
    }
    
    public override void onBeforeDelete() {
       deleteRelatedStaffAndMealBreakRecords((Map<Id, sked_Operation_Record_Staff__c>)this.context.oldMap);
    }
    
    /*********************************************************** Privated Methods ***********************************************************/

    /**
     * Volunteers (Resource Category) are not submitted to Workday — stamp staff status Ignore.
     */
    private void applyWorkdayIgnoreForVolunteers(List<sked_Operation_Record_Staff__c> newRecords) {
        if (newRecords == null || newRecords.isEmpty()) {
            return;
        }
        Set<Id> resourceIds = new Set<Id>();
        for (sked_Operation_Record_Staff__c staff : newRecords) {
            if (staff.sked_Resource__c != null) {
                resourceIds.add(staff.sked_Resource__c);
            }
        }
        if (resourceIds.isEmpty()) {
            return;
        }
        Map<Id, sked__Resource__c> resourceById = new Map<Id, sked__Resource__c>([
            SELECT Id, sked__Category__c
            FROM sked__Resource__c
            WHERE Id IN :resourceIds
        ]);
        for (sked_Operation_Record_Staff__c staff : newRecords) {
            sked__Resource__c resource = resourceById.get(staff.sked_Resource__c);
            if (resource != null
                && resource.sked__Category__c == BSF_WorkdayDirectSubmissionConfig.RESOURCE_CATEGORY_VOLUNTEER) {
                staff.sked_Workday_Submission_Status__c = BSF_WorkdayDirectSubmissionConfig.STAFF_STATUS_IGNORE;
            }
        }
    }

	private void doDateTimeConversion(List<sked_Operation_Record_Staff__c> newRecords) {
        for (sked_Operation_Record_Staff__c newRecord : newRecords) {
            skedTriggerUtils.maintainDateTimeField(newRecord, 'sked_Actual_Shift_Start__c', 'sked_Actual_Shift_Start_Date__c', 'sked_Actual_Shift_Start_Time__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, 'sked_Actual_Shift_End__c', 'sked_Actual_Shift_End_Date__c', 'sked_Actual_Shift_End_Time__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, 'sked_Early_Departure_DateTime_Received__c', 'sked_Early_Departure_Date_Received__c', 'sked_Early_Departure_Time_Received__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, 'sked_Late_Arrival_DateTime_Received__c', 'sked_Late_Arrival_Date_Received__c', 'sked_Late_Arrival_Time_Received__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, 'Scheduled_Shift_Start__c', 'Scheduled_Shift_Start_Date__c', 'Scheduled_Shift_Start_Time__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, 'Scheduled_Shift_End__c', 'Scheduled_Shift_End_Date__c', 'Scheduled_Shift_End_Time__c', 'sked_Timezone__c');
        }
    }
    
    private void doDateTimeConversion(List<sked_Operation_Record_Staff__c> newRecords, Map<Id, sked_Operation_Record_Staff__c> oldMap) {
        for (sked_Operation_Record_Staff__c newRecord : newRecords) {
            sked_Operation_Record_Staff__c oldData = oldMap.get(newRecord.Id);
            skedTriggerUtils.maintainDateTimeField(newRecord, oldData, 'sked_Actual_Shift_Start__c', 'sked_Actual_Shift_Start_Date__c', 'sked_Actual_Shift_Start_Time__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, oldData, 'sked_Actual_Shift_End__c', 'sked_Actual_Shift_End_Date__c', 'sked_Actual_Shift_End_Time__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, oldData, 'sked_Early_Departure_DateTime_Received__c', 'sked_Early_Departure_Date_Received__c', 'sked_Early_Departure_Time_Received__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, oldData, 'sked_Late_Arrival_DateTime_Received__c', 'sked_Late_Arrival_Date_Received__c', 'sked_Late_Arrival_Time_Received__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, oldData, 'Scheduled_Shift_Start__c', 'Scheduled_Shift_Start_Date__c', 'Scheduled_Shift_Start_Time__c', 'sked_Timezone__c');
            skedTriggerUtils.maintainDateTimeField(newRecord, oldData, 'Scheduled_Shift_End__c', 'Scheduled_Shift_End_Date__c', 'Scheduled_Shift_End_Time__c', 'sked_Timezone__c');
        }
    }

    private void populateData(List<sked_Operation_Record_Staff__c> newRecords) {
        Set<Id> jobAllocationIds = new Set<Id>();
        for (sked_Operation_Record_Staff__c opRecordStaff : newRecords) {
            jobAllocationIds.add(opRecordStaff.sked_Job_Allocation__c);
        }

        Map<Id, sked__Job_Allocation__c> jobAllocationsById = new Map<Id, sked__Job_Allocation__c>([
            SELECT Id, sked_CDL__c, sked_DOT__c, sked__Start__c, sked__End1__c,
            sked_Start_Date__c, sked_Start_Time__c, sked_Set_End_Date__c, sked_Set_End_Time__c
            FROM sked__Job_Allocation__c
            WHERE Id IN :jobAllocationIds
        ]);

        for (sked_Operation_Record_Staff__c newRecord : newRecords) {
            sked__Job_Allocation__c jobAllocation = jobAllocationsById.get(newRecord.sked_Job_Allocation__c);
            if(jobAllocation != NULL) {
                newRecord.Scheduled_Shift_Start_Date__c = jobAllocation.sked_Start_Date__c;
                newRecord.Scheduled_Shift_Start_Time__c = jobAllocation.sked_Start_Time__c;
                newRecord.Scheduled_Shift_End_Date__c = jobAllocation.sked_Set_End_Date__c;
                newRecord.Scheduled_Shift_End_Time__c = jobAllocation.sked_Set_End_Time__c;
            }
            if (newRecord.sked_Role__c != NULL && newRecord.sked_Actual_Roles__c == NULL) {
                List<String> roles = newRecord.sked_Role__c.split(',');
                List<String> newRolesStr = new List<String>();
                for (String role : roles) {
                    if (role == skedConstants.JOB_RESOURCE_ROLE_DRIVER) {
                        if (jobAllocation.sked_CDL__c) {
                            newRolesStr.add('Driver CDL B');
                        } else if (jobAllocation.sked_DOT__c) {
                            newRolesStr.add('Driver - DOT');
                        } else {
                            newRolesStr.add('Driver');
                        }
                    } else {
                        newRolesStr.add(role);
                    }
                }
                newRecord.sked_Actual_Roles__c = string.join(newRolesStr, ';');
            }
        }
    }
    
    private void deleteRelatedStaffAndMealBreakRecords(Map<Id, sked_Operation_Record_Staff__c> oldRecordsMap) {
        List<sked_Staff_Meal_Rest_Break_Setting__c> existingBreakTimeRecords = new List<sked_Staff_Meal_Rest_Break_Setting__c>();
        if(!oldRecordsMap.keyset().isEmpty()) {
            existingBreakTimeRecords = [SELECT Id FROM sked_Staff_Meal_Rest_Break_Setting__c WHERE sked_Operation_Record_Staff__c IN :oldRecordsMap.keySet()];
            if(!existingBreakTimeRecords.isEmpty()) {
                delete existingBreakTimeRecords;
            }
        }
    }
    
    private void populateData(List<sked_Operation_Record_Staff__c> newRecords, Map<Id, sked_Operation_Record_Staff__c> oldMap) {
        for (sked_Operation_Record_Staff__c newRecord : newRecords) {
            if(newRecords != NULL && oldMap != NULL) {
                sked_Operation_Record_Staff__c oldData = oldMap.get(newRecord.Id);
                if((newRecord.sked_Actual_Shift_Start_Time__c != NULL && newRecord.sked_Actual_Shift_End_Time__c != NULL) && (oldData.sked_Actual_Shift_Start_Time__c != newRecord.sked_Actual_Shift_Start_Time__c || oldData.sked_Actual_Shift_End_Time__c != newRecord.sked_Actual_Shift_End_Time__c)) {
                    compareAndPopulateMealAndRestBreaksRelatedData(new Set<Id>{oldData.sked_Operation_Record__c}, newRecords);
                }
            }
        }
    }
    
    private static void compareAndPopulateMealAndRestBreaksRelatedData(Set<Id> OpRecIds, List<sked_Operation_Record_Staff__c> newRecords) {
        Integer calculateInterval;
        Boolean isTimeDiffGreaterThanStartingRange;
        Boolean isTimeDiffLesserThanEndingRange;
        String StateCode;
        Set<String> stateCodeSet = new Set<String>();
        Map<String,List<Operation_Meals_And_Rest_Calculation__mdt>> map_stateCode_mealAndRestBreakmetadata = new Map<String,List<Operation_Meals_And_Rest_Calculation__mdt>>();
        List<Operation_Meals_And_Rest_Calculation__mdt> getMealAndRestCalcuationList = new List<Operation_Meals_And_Rest_Calculation__mdt>();
        Map<Id,sked_Operation_Record__c> getOpRecords = new Map<Id,sked_Operation_Record__c>();
        
       	getOpRecords = new Map<Id,sked_Operation_Record__c>([SELECT Id,sked_Drive_Site__r.sked_State__c FROM sked_Operation_Record__c WHERE Id IN :OpRecIds]);
        for(sked_Operation_Record__c getOpRecord : getOpRecords.values()) {
            stateCodeSet.add(getOpRecord.sked_Drive_Site__r.sked_State__c);
        }
       getMealAndRestCalcuationList = Operation_Meals_And_Rest_Calculation__mdt.getAll().values();
        
        for(Operation_Meals_And_Rest_Calculation__mdt getMetadataInfo: getMealAndRestCalcuationList) {
            if(stateCodeSet.contains(getMetadataInfo.StateCode__c)){
                if(!map_stateCode_mealAndRestBreakmetadata.containsKey(getMetadataInfo.StateCode__c)) {
                   map_stateCode_mealAndRestBreakmetadata.put(getMetadataInfo.StateCode__c, new List<Operation_Meals_And_Rest_Calculation__mdt>());
                    }
                map_stateCode_mealAndRestBreakmetadata.get(getMetadataInfo.StateCode__c).add(getMetadataInfo);
            }
        }
        for(sked_Operation_Record_Staff__c updateOpRecStaff: newRecords) {
            sked_Operation_Record__c getOpRecordStateCode = getOpRecords.get(updateOpRecStaff.sked_Operation_Record__c);
            StateCode = getOpRecordStateCode.sked_Drive_Site__r.sked_State__c;
            if(updateOpRecStaff.sked_Actual_Shift_Start__c != NULL && updateOpRecStaff.sked_Actual_Shift_End__c != NULL) {
                calculateInterval = skedDateTimeUtils.getDifferentMinutes(updateOpRecStaff.sked_Actual_Shift_Start__c, updateOpRecStaff.sked_Actual_Shift_End__c);
            }
            if(calculateInterval != NULL && map_stateCode_mealAndRestBreakmetadata.get(StateCode) != NULL) { 
                for(Operation_Meals_And_Rest_Calculation__mdt populateMetadataonRecord: map_stateCode_mealAndRestBreakmetadata.get(StateCode)) {
                    isTimeDiffGreaterThanStartingRange = calculateInterval >= skedDateTimeUtils.convertTimeStrToMinutes(populateMetadataonRecord.Starting_Hour__c);
                    isTimeDiffLesserThanEndingRange = calculateInterval <= skedDateTimeUtils.convertTimeStrToMinutes(populateMetadataonRecord.Ending_Hour__c);
                    if((populateMetadataonRecord.Break_Type__c).contains(skedConstants.OP_RECORD_STAFF_BREAK_TYPE_REST) && isTimeDiffGreaterThanStartingRange && isTimeDiffLesserThanEndingRange) {
                        updateOpRecStaff.sked_Rest_Breaks_Earned__c = populateMetadataonRecord.Breaks_Required__c;
                    }
                    if((populateMetadataonRecord.Break_Type__c).contains(skedConstants.OP_RECORD_STAFF_BREAK_TYPE_MEAL) && isTimeDiffGreaterThanStartingRange && isTimeDiffLesserThanEndingRange) {
                        updateOpRecStaff.sked_Meal_Breaks_Earned__c = populateMetadataonRecord.Breaks_Required__c;
                    }
                }
            }
        }
    }
}