force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>sked__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__User__c.field-meta.xml
<CustomField>
    <fullName>sked__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/skedResourceCalendarController.cls
global class skedResourceCalendarController extends skedRacController {
    
    public string resourceId {get;set;}
    
    public skedResourceCalendarController() {
        List<sked__Resource__c> resourceQuery = [SELECT Id
                                                 FROM sked__Resource__c
                                                 WHERE sked__User__c = :UserInfo.getUserId()
                                                 AND sked__Is_Active__c = TRUE];
        this.resourceId = (resourceQuery != NULL && resourceQuery.size() == 1) ? resourceQuery.get(0).Id : NULL;
    }

}