unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_ARC_Region_ID__c.field-meta.xml
<CustomField>
    <fullName>sked_ARC_Region_ID__c</fullName>
    <formula>sked_District__r.sked_Parent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARC Region ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Linked_Drives__c.field-meta.xml
<CustomField>
    <fullName>sked_Linked_Drives__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Drives</label>
    <referenceTo>sked_Linked_Drives__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Linked_Drives__c/sked_Linked_Drives__c.object-meta.xml
<CustomObject>
    <label>Linked Drives</label>
    <nameField>
        <displayFormat>Linked Drive-{0000000}</displayFormat>
        <label>Linked Drives Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Drives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Linked_Drives__c/fields/sked_ARC_Region__c.field-meta.xml
<CustomField>
    <fullName>sked_ARC_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipLabel>Linked Drives</relationshipLabel>
    <relationshipName>Linked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Linked_Drives__c/fields/sked_Earliest_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Earliest_Drive_Date__c</fullName>
    <label>Earliest Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Linked_Drives__c/fields/sked_Latest_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Latest_Drive_Date__c</fullName>
    <label>Latest Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/skedLinkedDrivesHandler.cls
public class skedLinkedDrivesHandler implements Callable {
    
    public static Object call(String methodName, Map<String, Object> params) {
        skedProcessEventResult result = new skedProcessEventResult();
        try {
            switch on methodName {
                when 'updateLinkedDriveDetails' {
                    updateLinkedDriveDetails((Set<Id>) JSON.deserialize((String) params.get('param1'), Set<Id>.class));

                }
                when else {
                    throw new skedException('Unable to locate Method: ' + methodName + ' in Class: ' + skedLinkedDrivesHandler.class.getName());
                }
            }
        } catch (skedException ex) {
            result.addError(ex);
        }

        return result;
    }

    private static void updateLinkedDriveDetails(Set<Id> linkedDriveIds) {
        List<sked_Linked_Drives__c> linkedDrives = [
            SELECT Id, sked_Earliest_Drive_Date__c, sked_Latest_Drive_Date__c,
            (SELECT Id, sked_Drive_Date__c, sked_ARC_Region_ID__c FROM sked_Drives__r)
            FROM sked_Linked_Drives__c
            WHERE Id IN :linkedDriveIds
        ];

        for (sked_Linked_Drives__c linkedDrive : linkedDrives) {
            if (linkedDrive.sked_Drives__r != null && !linkedDrive.sked_Drives__r.isEmpty()) {
                linkedDrive.sked_ARC_Region__c = (Id) linkedDrive.sked_Drives__r[0].sked_ARC_Region_ID__c;
                for (sked_Drive__c drive : linkedDrive.sked_Drives__r) {
                    if (linkedDrive.sked_Earliest_Drive_Date__c == null || linkedDrive.sked_Earliest_Drive_Date__c > drive.sked_Drive_Date__c) {
                        linkedDrive.sked_Earliest_Drive_Date__c = drive.sked_Drive_Date__c;
                    }

                    if (linkedDrive.sked_Latest_Drive_Date__c == null || linkedDrive.sked_Latest_Drive_Date__c < drive.sked_Drive_Date__c) {
                        linkedDrive.sked_Latest_Drive_Date__c = drive.sked_Drive_Date__c;
                    }
                }
            }
        }

        update linkedDrives;
    }
}