unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2RBC Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2RBC Projected Procedures</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Donors_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>sked_Donors_Scheduled__c</fullName>
    <label>Donors Scheduled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>Draw End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Equipment__c.field-meta.xml
<CustomField>
    <fullName>sked_Equipment__c</fullName>
    <label>Equipment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Finish__c.field-meta.xml
<CustomField>
    <fullName>sked_Finish__c</fullName>
    <label>Max Shift End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Before_Draw_Hours__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Before_Draw_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunch Break Before Draw Hours?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Duration__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Duration__c</fullName>
    <label>Lunch Break Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_End_Time__c</fullName>
    <label>Lunch Break End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Lunch_Break_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Lunch_Break_Start_Time__c</fullName>
    <label>Lunch Break Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Order__c.field-meta.xml
<CustomField>
    <fullName>sked_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Sign_Up_Reduction__c.field-meta.xml
<CustomField>
    <fullName>sked_Sign_Up_Reduction__c</fullName>
    <label>Sign-Up Reduction %</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Staff_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Staff_Setup__c</fullName>
    <label>Staff Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Start__c.field-meta.xml
<CustomField>
    <fullName>sked_Start__c</fullName>
    <label>Min Shift Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Draw Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Vehicles_Needed__c.field-meta.xml
<CustomField>
    <fullName>sked_Vehicles_Needed__c</fullName>
    <label>Vehicles Needed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Volunteer_Setup__c.field-meta.xml
<CustomField>
    <fullName>sked_Volunteer_Setup__c</fullName>
    <label>Volunteer Setup</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/skedCreateRegenerateDriveDCR_Test.cls
@isTest
private class skedCreateRegenerateDriveDCR_Test {
    @isTest
    static void skedCreateRegenerateDriveDCR_Test() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<String, Object> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();

        Test.startTest();
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');

        sked_Drive_Shift__c testDriveShift = new sked_Drive_Shift__c(
            sked_Donors_Scheduled__c = 1,
            sked_End_Time__c = Time.newInstance(20,0,0,0),
            sked_Start_Time__c = Time.newInstance(14,0,0,0),
            sked_Drive__c = testDrive.Id,
            sked_Drive_Date__c = testDrive.sked_Drive_Date__c,
            sked_Equipment__c = 1,
            sked_Lunch_Break__c = FALSE,
            sked_Lunch_Break_Before_Draw_Hours__c = FALSE,
            sked_Lunch_Break_Duration__c = 0,
            sked_Lunch_Break_End_Time__c = NULL,
            sked_Lunch_Break_Start_Time__c = NULL,
            sked_Finish__c = DateTime.newInstance(System.today(), Time.newInstance(20,0,0,0)),
            sked_Start__c = DateTime.newInstance(System.today(), Time.newInstance(14,0,0,0)),
            sked_Order__c = 1,
            sked_Sign_Up_Reduction__c = 0,
            sked_Staff_Setup__c = 1,
            sked_Vehicles_Needed__c = 1,
            sked_Volunteer_Setup__c = 1,
            sked_2RBC_Projected_Procedures__c = 50
        );
        insert testDriveShift;

        testDrive.sked_2RBC_Projected_Procedures__c = 40;
        update testDrive;
        
        Database.executeBatch(new skedCreateRegenerateDriveDCRBatch(), 1);
        Test.stopTest();
    }
}