unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive__c/fields/sked_2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2RBC Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Drive_Shift_Count__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift_Count__c</fullName>
    <label>Drive Shift Count</label>
    <summaryForeignKey>sked_Drive_Shift__c.sked_Drive__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>sked_Operation_Type__c</fullName>
    <formula>TEXT(sked_Drive_Site__r.Operation_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Operation Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sked_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Plasma_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_Plasma_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plasma Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Platelet_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_Platelet_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Platelet Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Platelet_Rounds__c.field-meta.xml
<CustomField>
    <fullName>sked_Platelet_Rounds__c</fullName>
    <label>Platelet Rounds</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Total_Procedures_Projected__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Procedures_Projected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Procedures Projected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Total_Products_Projected__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Products_Projected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Products Projected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Drive_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WB Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>2RBC Projected Procedures</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_End_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Time__c</fullName>
    <label>Draw End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Plasma_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_Plasma_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plasma Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Platelet_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_Platelet_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Platelet Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Platelet_Rounds__c.field-meta.xml
<CustomField>
    <fullName>sked_Platelet_Rounds__c</fullName>
    <label>Platelet Rounds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Time__c</fullName>
    <label>Draw Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Total_Procedures_Projected__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Procedures_Projected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Procedures Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Total_Products_Projected__c.field-meta.xml
<CustomField>
    <fullName>sked_Total_Products_Projected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Products Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>sked_WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WB Projected Procedures</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/sked_Drive_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fixed Site</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>RSMO</fullName>
        <isActive>false</isActive>
        <label>RSMO</label>
    </customValue>
    <masterLabel>Drive Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/UpdateDriveShiftProjectedProcTest.cls
@isTest
public class UpdateDriveShiftProjectedProcTest {

    @istest
    public static void updateDriveShiftForFixedSiteDriveTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.setupData();
        Opportunity fixOpportunity = (Opportunity)mapTestData.get('fixedSiteOpportunity');
     
        Test.startTest();
        AccountTeamMemberHelper.skipAccountTrigger = true;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        
        CreateSkedDrive.createDrives(new List<Opportunity>{fixOpportunity});
                
        List<sked_Drive__c> fixedSiteDriveCreated = [Select Id , sked_Opportunity__c from sked_Drive__c where sked_Opportunity__c =:fixOpportunity.Id];
        Assert.areEqual(1, fixedSiteDriveCreated.size()); // NEW Assert Class
        
        Set<Id> docId = new Set<Id>();        
        for(sked_Drive__c doc : fixedSiteDriveCreated) {
            docId.add(doc.Id);
        } 
        
        List<sked_Drive__c> driveList = [SELECT Id, sked_Type_of_Drive__c, sked_Operation_Type__c,
        sked_Platelet_Rounds__c, sked_WB_Projected_Procedures__c, 
        sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
        sked_2RBC_Projected_Procedures__c, sked_Drive_Shift_Count__c,
        sked_Start_Time__c, sked_End_Time__c,sked_Drive_Date__c,
        (
            SELECT Id, Name, sked_WB_Projected_Procedures__c, sked_2RBC_Projected_Procedures__c, 
            sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
            sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c
            FROM sked_Drive_Shifts__r ORDER BY Name
        ) 
        FROM sked_Drive__c
        WHERE Id IN: docId];
        
        
        
        List<sked_Drive_Shift__c> driveshiftList = [select Id, sked_Drive__c, Name, sked_WB_Projected_Procedures__c, sked_2RBC_Projected_Procedures__c, 
            sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
            sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c from sked_Drive_Shift__c where sked_Drive__c IN : docId];
        for(sked_Drive_Shift__c driveShift : driveshiftList){
            driveShift.sked_WB_Projected_Procedures__c = 2;
            driveShift.sked_2RBC_Projected_Procedures__c = 2;
            driveShift.sked_Total_Procedures_Projected__c = 2;
            driveShift.sked_Total_Products_Projected__c = 2;
            driveShift.sked_Platelet_Projected_Procedures__c = 2;
            driveShift.sked_Plasma_Projected_Procedures__c = 2;
        }
        update driveshiftList;
        AccountTeamMemberHelper.skipAccountTrigger = false;
        Triggerhandler.clearAllBypasses();
        
        Date date1 = driveList[0].sked_Drive_Date__c;
        Date date2 = driveList[0].sked_Drive_Date__c;
        String typeOfDrive = 'Fixed Site';
        Boolean driveShiftUpdate = true;
        Boolean onlyTotalProcedureUpdate = false;

        UpdateDriveShiftProjProc_ProductAndProc batchObject = new UpdateDriveShiftProjProc_ProductAndProc(date1, date2, typeOfDrive, driveShiftUpdate);
        Database.executeBatch(batchObject,100);
        Test.stopTest();
    }
    
    @istest
    public static void updateDriveShiftForMobileDriveTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.testSetupForMobileDriveV2();
        Opportunity mobileOpportunity = (Opportunity)mapTestData.get('mobileOpportunity');
        
        MobileDriveGeneratorDMLService.driveGeneratorConfig config = new MobileDriveGeneratorDMLService.driveGeneratorConfig();
        config.oppIds = new Set<Id>();
        config.oppIds.add(mobileOpportunity.Id);
        
        Test.startTest();
        
        AccountTeamMemberHelper.skipAccountTrigger = true;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        GenerateMobileDrive.generateDrives(config);
        
        List<sked_Drive__c> driveList = [SELECT Id, sked_Type_of_Drive__c, sked_Operation_Type__c,
        sked_Platelet_Rounds__c, sked_WB_Projected_Procedures__c, 
        sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
        sked_2RBC_Projected_Procedures__c, sked_Drive_Shift_Count__c,
        sked_Start_Time__c, sked_End_Time__c,sked_Drive_Date__c,
        (
            SELECT Id, Name, sked_WB_Projected_Procedures__c, sked_2RBC_Projected_Procedures__c, 
            sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
            sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c
            FROM sked_Drive_Shifts__r ORDER BY Name
        ) 
        FROM sked_Drive__c
        WHERE sked_Opportunity__c IN: config.oppIds];
        
        
        
        List<sked_Drive_Shift__c> driveshiftList = [select Id, sked_Drive__c, Name, sked_WB_Projected_Procedures__c, sked_2RBC_Projected_Procedures__c, 
            sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
            sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c from sked_Drive_Shift__c where sked_Drive__r.sked_Opportunity__c IN : config.oppIds];
        for(sked_Drive_Shift__c driveShift : driveshiftList){
            driveShift.sked_WB_Projected_Procedures__c = 2;
            driveShift.sked_2RBC_Projected_Procedures__c = 2;
            driveShift.sked_Total_Procedures_Projected__c = 2;
            driveShift.sked_Total_Products_Projected__c = 2;
        }
        update driveshiftList;
        Date date1 = driveList[0].sked_Drive_Date__c;
        Date date2 = driveList[0].sked_Drive_Date__c;
        String typeOfDrive = 'Mobile';
        Boolean driveShiftUpdate = true;
        Boolean onlyTotalProcedureUpdate = false;

        UpdateDriveShiftProjProc_ProductAndProc batchObject = new UpdateDriveShiftProjProc_ProductAndProc(date1, date2, typeOfDrive, driveShiftUpdate);
        Database.executeBatch(batchObject,100);
        
        Test.stopTest();
    }
    
    @istest
    public static void updateDriveShiftTotalProjectedAndTotalProductForFixedSiteDriveTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.setupData();
        Opportunity fixOpportunity = (Opportunity)mapTestData.get('fixedSiteOpportunity');
     
        Test.startTest();
        AccountTeamMemberHelper.skipAccountTrigger = true;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        
        CreateSkedDrive.createDrives(new List<Opportunity>{fixOpportunity});
                
        List<sked_Drive__c> fixedSiteDriveCreated = [Select Id , sked_Opportunity__c from sked_Drive__c where sked_Opportunity__c =:fixOpportunity.Id];
        Assert.areEqual(1, fixedSiteDriveCreated.size()); // NEW Assert Class
        
        Set<Id> docId = new Set<Id>();        
        for(sked_Drive__c doc : fixedSiteDriveCreated) {
            docId.add(doc.Id);
        } 
        
        List<sked_Drive__c> driveList = [SELECT Id, sked_Type_of_Drive__c, sked_Operation_Type__c,
        sked_Platelet_Rounds__c, sked_WB_Projected_Procedures__c, 
        sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
        sked_2RBC_Projected_Procedures__c, sked_Drive_Shift_Count__c,
        sked_Start_Time__c, sked_End_Time__c,sked_Drive_Date__c,
        (
            SELECT Id, Name, sked_WB_Projected_Procedures__c, sked_2RBC_Projected_Procedures__c, 
            sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
            sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c
            FROM sked_Drive_Shifts__r ORDER BY Name
        ) 
        FROM sked_Drive__c
        WHERE Id IN: docId];
        
        
        
        List<sked_Drive_Shift__c> driveshiftList = [select Id, sked_Drive__c, Name, sked_WB_Projected_Procedures__c, sked_2RBC_Projected_Procedures__c, 
            sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
            sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c from sked_Drive_Shift__c where sked_Drive__c IN : docId];
        for(sked_Drive_Shift__c driveShift : driveshiftList){
            driveShift.sked_WB_Projected_Procedures__c = 2;
            driveShift.sked_2RBC_Projected_Procedures__c = 2;
            driveShift.sked_Total_Procedures_Projected__c = 2;
            driveShift.sked_Total_Products_Projected__c = 2;
            driveShift.sked_Platelet_Projected_Procedures__c = 2;
            driveShift.sked_Plasma_Projected_Procedures__c = 2;
        }
        update driveshiftList;
        AccountTeamMemberHelper.skipAccountTrigger = false;
        Triggerhandler.clearAllBypasses();
        
        Date date1 = driveList[0].sked_Drive_Date__c;
        Date date2 = driveList[0].sked_Drive_Date__c;
        String typeOfDrive = 'Fixed Site';
        Boolean driveShiftUpdate = false;
        Boolean onlyTotalProcedureUpdate = true;

        UpdateDriveShiftProjProc_ProductAndProc batchObject = new UpdateDriveShiftProjProc_ProductAndProc(date1, date2, typeOfDrive, driveShiftUpdate, onlyTotalProcedureUpdate);
        Database.executeBatch(batchObject,100);
        Test.stopTest();
    }
    
    @istest
    public static void updateDriveTotalProjectedAndTotalProductForFixedSiteDriveTest() {        
        Map<string, sObject> mapTestData = GenerateDriveTestData.setupData();
        Opportunity fixOpportunity = (Opportunity)mapTestData.get('fixedSiteOpportunity');
     
        Test.startTest();
        AccountTeamMemberHelper.skipAccountTrigger = true;
        TriggerHandler.bypass('AccountTriggerHandler');
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('OpportunitySplitTriggerHandler');
        
        CreateSkedDrive.createDrives(new List<Opportunity>{fixOpportunity});
                
        List<sked_Drive__c> fixedSiteDriveCreated = [Select Id , sked_Opportunity__c from sked_Drive__c where sked_Opportunity__c =:fixOpportunity.Id];
        Assert.areEqual(1, fixedSiteDriveCreated.size()); // NEW Assert Class
        
        Set<Id> docId = new Set<Id>();        
        for(sked_Drive__c doc : fixedSiteDriveCreated) {
            docId.add(doc.Id);
        } 
        
        List<sked_Drive__c> driveList = [SELECT Id, sked_Type_of_Drive__c, sked_Operation_Type__c,
        sked_Platelet_Rounds__c, sked_WB_Projected_Procedures__c, 
        sked_Platelet_Projected_Procedures__c, sked_Plasma_Projected_Procedures__c,
        sked_2RBC_Projected_Procedures__c, sked_Drive_Shift_Count__c,
        sked_Start_Time__c, sked_End_Time__c,sked_Drive_Date__c, sked_Total_Procedures_Projected__c, sked_Total_Products_Projected__c
        FROM sked_Drive__c
        WHERE Id IN: docId];
        driveList[0].sked_Total_Procedures_Projected__c = 20;
        driveList[0].sked_Total_Products_Projected__c = 20;
        update driveList;
        AccountTeamMemberHelper.skipAccountTrigger = false;
        Triggerhandler.clearAllBypasses();
        
        Date date1 = driveList[0].sked_Drive_Date__c;
        Date date2 = driveList[0].sked_Drive_Date__c;
        String typeOfDrive = 'Fixed Site';
        Boolean driveShiftUpdate = false;
        Boolean onlyTotalProcedureUpdate = false;
        Boolean onlyTotalProcedureUpdateForDrive = true;

        UpdateDriveShiftProjProc_ProductAndProc batchObject = new UpdateDriveShiftProjProc_ProductAndProc(date1, date2, typeOfDrive, driveShiftUpdate, onlyTotalProcedureUpdate, onlyTotalProcedureUpdateForDrive);
        Database.executeBatch(batchObject,100);
        Test.stopTest();
    }
}