force-app/main/default/objects/Opportunity/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Manager of the related Account</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Blood_Drive_Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Template__c.field-meta.xml
<CustomField>
    <fullName>Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this field is template or real opportunity object</description>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BSF_TaskCreationBatch.cls
global class BSF_TaskCreationBatch implements Schedulable, Database.Batchable<sObject>{
    Date nextNDays = Date.today().addDays(Integer.ValueOf(label.SponsorPlanningMeetingTaskThresholdDays));
    Id MOBILE_OPP_RECTYPEID = SObjectType.Opportunity.getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId();
	public String query = 'SELECT Id, Drive_Date__c, Is_Template__c, RecordTypeId, RecordType.Name, Account_Manager__c, OwnerId, StageName FROM Opportunity'+
    ' WHERE Drive_Date__c <=: nextNDays AND Drive_Date__c >= TODAY AND StageName != \'Cancel\' AND Is_Template__c = false AND RecordTypeId =:MOBILE_OPP_RECTYPEID';
    global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}
	global void execute(Database.BatchableContext BC, List<Opportunity> scope){
        system.debug('scope '+scope);
		OpportunityService.createSponsorPlanningMeetingTask(scope,null);
	}
	global void execute(SchedulableContext scon){
		Database.executeBatch(new BSF_TaskCreationBatch(),200);
	}
	global void finish(Database.BatchableContext BC){}
}