force-app/main/default/objects/Opportunity/fields/Anticipated_Registered_Donors__c.field-meta.xml
<CustomField>
    <fullName>Anticipated_Registered_Donors__c</fullName>
    <description>Numeric value that reflects the # of donors expected to be at the drive. Current based on historical drive data (like drive, how many people).</description>
    <label>Anticipated Registered Donors</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drive_Name__c.field-meta.xml
<CustomField>
    <fullName>Drive_Name__c</fullName>
    <label>Blood Drive Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Drive_Site__c.field-meta.xml
<CustomField>
    <fullName>Drive_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_End_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_End_Time_Field__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>1530</fullName>
                <label>3:30 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flow_Start_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Flow_Start_Time_Field__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>0015</fullName>
                <label>12:15 AM</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>12:30 AM</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>12:45 AM</label>
            </value>
            <value>
                <fullName>0100</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>0115</fullName>
                <label>1:15 AM</label>
            </value>
            <value>
                <fullName>0130</fullName>
                <label>1:30 AM</label>
            </value>
            <value>
                <fullName>0145</fullName>
                <label>1:45 AM</label>
            </value>
            <value>
                <fullName>0200</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>0215</fullName>
                <label>2:15 AM</label>
            </value>
            <value>
                <fullName>0230</fullName>
                <label>2:30 AM</label>
            </value>
            <value>
                <fullName>0245</fullName>
                <label>2:45 AM</label>
            </value>
            <value>
                <fullName>0300</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>0315</fullName>
                <label>3:15 AM</label>
            </value>
            <value>
                <fullName>0330</fullName>
                <label>3:30 AM</label>
            </value>
            <value>
                <fullName>0345</fullName>
                <label>3:45 AM</label>
            </value>
            <value>
                <fullName>0400</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>0415</fullName>
                <label>4:15 AM</label>
            </value>
            <value>
                <fullName>0430</fullName>
                <label>4:30 AM</label>
            </value>
            <value>
                <fullName>0445</fullName>
                <label>4:45 AM</label>
            </value>
            <value>
                <fullName>0500</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>0515</fullName>
                <label>5:15 AM</label>
            </value>
            <value>
                <fullName>0530</fullName>
                <label>5:30 AM</label>
            </value>
            <value>
                <fullName>0545</fullName>
                <label>5:45 AM</label>
            </value>
            <value>
                <fullName>0600</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>0615</fullName>
                <label>6:15 AM</label>
            </value>
            <value>
                <fullName>0630</fullName>
                <label>6:30 AM</label>
            </value>
            <value>
                <fullName>0645</fullName>
                <label>6:45 AM</label>
            </value>
            <value>
                <fullName>0700</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>0715</fullName>
                <label>7:15 AM</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>1530</fullName>
                <label>3:30 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Online_Scheduling_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Online_Scheduling_Enabled__c</fullName>
    <label>Online Scheduling Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Drive__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Drive__c</fullName>
    <label>Type of Drive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Fixed Site</fullName>
            </value>
            <value>
                <fullName>RSMO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/WB_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>WB_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Whole Blood Procedures Projected</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X2RBC_Projected_Procedures__c.field-meta.xml
<CustomField>
    <fullName>X2RBC_Projected_Procedures__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Double Red Procedures Projected</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OppLookupCorrectionBatch_Test.cls
@isTest
public class OppLookupCorrectionBatch_Test 
{
	@testSetup
    public static void setup()
    {
        Map <String,Schema.RecordTypeInfo> recordTypesAccount = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        Id mobileRecTypeId = recordTypesAccount.get('Mobile Account').getRecordTypeId();
        List<Account> accList = new List<Account>();
        Account mobileAcc1 = new Account(
            name = 'Test Account 1',
        	RecordTypeId = MobileRecTypeId,
            BillingStreet = '2204 Westcrt ln, Apt 213', 
        	BillingCity = 'Herndon',
        	BillingStateCode = 'MI',
        	BillingPostalCode = '48420'
        );
        Account mobileAcc2 = new Account(
            name = 'Test Account 2',
        	RecordTypeId = MobileRecTypeId,
            BillingStreet = 'PO BOX 1', 
        	BillingCity = 'COLUMBIAVILLE',
        	BillingStateCode = 'MI',
        	BillingPostalCode = '48421'
        );
        accList.add(mobileAcc1);
        accList.add(mobileAcc2);
        insert accList;
        
        }
    @isTest static void OppLookupCorrectionBatchAll()
    {
        Account acc =[select Id from Account Limit 1];
    opportunity opp = new opportunity(
        Name = 'Test Opportunity',
        	StageName = 'Draft',
           	Type_of_Drive__c = 'Mobile',
        	RecordTypeId =  Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId(),
        	Drive_Name__c = 'Test Drive',
        	Drive_Date__c = system.today().addDays(22),
        	CloseDate = System.today().addDays(18),
        	Start_Time__c = Time.newInstance(10, 0, 0, 0),
      		End_Time__c = Time.newInstance(15, 30, 0, 0),
        	Flow_Start_Time_Field__c = '1000',
        	Flow_End_Time_Field__c = '1530',
        	WB_Projected_Procedures__c = 4,
        	X2RBC_Projected_Procedures__c = 2,
        	Anticipated_Registered_Donors__c = 25,
            Online_Scheduling_Enabled__c = 'No',
            //Drive_Site__c = mobileSite.id,
            accountid= acc.id);
        //Database.executeBatch(new BSF_Batch_CreateDefaultPortfolioAssign(system.today()));
         //delete apaExcep;
        TriggerHandler.bypass('OpportunityTriggerHandler');
        Insert opp;
        TriggerHandler.clearbypass('OpportunityTriggerHandler');
        
        test.startTest();
        BSF_Batch_OppLookupCorrection batch = new BSF_Batch_OppLookupCorrection();
        Database.executeBatch(Batch);
        test.StopTest();
        Opportunity opty = [select id,Owner.Name from Opportunity where Id =:opp.Id];
        assert.isTrue(opty.Owner.Name=='Drd System User');
    }
    
    @isTest static void OppLookupCorrectionBatchSpecificOpp()
    {
        Account acc =[select Id from Account Limit 1];
    opportunity opp = new opportunity(
        Name = 'Test Opportunity',
        	StageName = 'Draft',
           	Type_of_Drive__c = 'Mobile',
        	RecordTypeId =  Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId(),
        	Drive_Name__c = 'Test Drive',
        	Drive_Date__c = system.today().addDays(22),
        	CloseDate = System.today().addDays(18),
        	Start_Time__c = Time.newInstance(10, 0, 0, 0),
      		End_Time__c = Time.newInstance(15, 30, 0, 0),
        	Flow_Start_Time_Field__c = '1000',
        	Flow_End_Time_Field__c = '1530',
        	WB_Projected_Procedures__c = 4,
        	X2RBC_Projected_Procedures__c = 2,
        	Anticipated_Registered_Donors__c = 25,
            Online_Scheduling_Enabled__c = 'No',
            //Drive_Site__c = mobileSite.id,
            accountid= acc.id);
        //Database.executeBatch(new BSF_Batch_CreateDefaultPortfolioAssign(system.today()));
         //delete apaExcep;
        TriggerHandler.bypass('OpportunityTriggerHandler');
        Insert opp;
        TriggerHandler.clearbypass('OpportunityTriggerHandler');
        
        test.startTest();
        BSF_Batch_OppLookupCorrection batch = new BSF_Batch_OppLookupCorrection(new Set<Id>{opp.Id});
        Database.executeBatch(Batch);
        test.StopTest();
    }
    
    @isTest static void OppLookupCorrectionBatchSpecificDriveDate()
    {
        Account acc =[select Id from Account Limit 1];
    opportunity opp = new opportunity(
        Name = 'Test Opportunity',
        	StageName = 'Draft',
           	Type_of_Drive__c = 'Mobile',
        	RecordTypeId =  Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName().get('Mobile Opp').getRecordTypeId(),
        	Drive_Name__c = 'Test Drive',
        	Drive_Date__c = system.today().addDays(22),
        	CloseDate = System.today().addDays(18),
        	Start_Time__c = Time.newInstance(10, 0, 0, 0),
      		End_Time__c = Time.newInstance(15, 30, 0, 0),
        	Flow_Start_Time_Field__c = '1000',
        	Flow_End_Time_Field__c = '1530',
        	WB_Projected_Procedures__c = 4,
        	X2RBC_Projected_Procedures__c = 2,
        	Anticipated_Registered_Donors__c = 25,
            Online_Scheduling_Enabled__c = 'No',
            //Drive_Site__c = mobileSite.id,
            accountid= acc.id);
        //Database.executeBatch(new BSF_Batch_CreateDefaultPortfolioAssign(system.today()));
         //delete apaExcep;
        TriggerHandler.bypass('OpportunityTriggerHandler');
        Insert opp;
        TriggerHandler.clearbypass('OpportunityTriggerHandler');
        
        test.startTest();
        BSF_Batch_OppLookupCorrection batch = new BSF_Batch_OppLookupCorrection(opp.Drive_Date__c-1,opp.Drive_Date__c+1);
        Database.executeBatch(Batch);
        test.StopTest();
    }
}