force-app/main/default/objects/Opportunity/fields/Number_of_2RBC_Assets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_2RBC_Assets__c</fullName>
    <label># Of 2RBC Assets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_Number_of_2RBC_Assets__c.field-meta.xml
<CustomField>
    <fullName>sked_Number_of_2RBC_Assets__c</fullName>
    <label>Number of 2RBC Assets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sked_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpptyDOCSyncInvocableTest.cls
@isTest
private class OpptyDOCSyncInvocableTest {
	@testSetup 
    static void prepareTestData() {
        skedTestDataFactory testDataFactory = new skedTestDataFactory('us', 14);
        Map<string, sObject> mapTestData = testDataFactory.setupCommonTestData();
        mapTestData = testDataFactory.setupDriveData();
        
        sked_Drive__c testDrive = (sked_Drive__c) mapTestData.get('testDrive1');
        Opportunity testOpp = (Opportunity) mapTestData.get('testOpportunity');
        
        testDrive.sked_Number_of_2RBC_Assets__c = 1;
        
        skedHubBase.BypassUpdateTriggers = true;
        TriggerHandler.bypass('DriveTriggerHandler');
        update testDrive;
        skedHubBase.BypassUpdateTriggers = false;
        triggerHandler.clearAllBypasses();
    }
    
    @isTest
    private static void updateOpptyTest(){
        sked_Drive__c testDrive = [Select Id, sked_Number_of_2RBC_Assets__c, sked_Opportunity__c FROM sked_Drive__c WHERE Name = 'Test Drive' LIMIT 1];
        
        OpptyDOCSyncInvocable.InputWrapper syncInputs = new OpptyDOCSyncInvocable.InputWrapper();
        syncInputs.Id = testDrive.sked_Opportunity__c;
        syncInputs.X2RBCAssets = String.valueOf(testDrive.sked_Number_of_2RBC_Assets__c);
        
        Test.startTest();
        OpptyDOCSyncInvocable.updateOppty(new List<OpptyDOCSyncInvocable.InputWrapper>{syncInputs});
        Test.stopTest();
        
        Opportunity testOpp = [Select Id, Number_of_2RBC_Assets__c FROM Opportunity WHERE Id =: testDrive.sked_Opportunity__c LIMIT 1];
        
        Assert.areEqual(testDrive.sked_Number_of_2RBC_Assets__c, testOpp.Number_of_2RBC_Assets__c);
        
    }
    
    @isTest
    private static void updateOpptyUpdateExceptionTest(){
        sked_Drive__c testDrive = [Select Id, sked_Number_of_2RBC_Assets__c, sked_Opportunity__c FROM sked_Drive__c WHERE Name = 'Test Drive' LIMIT 1];
        
        OpptyDOCSyncInvocable.InputWrapper syncInputs = new OpptyDOCSyncInvocable.InputWrapper();
        //syncInputs.Id = testDrive.sked_Opportunity__c;
        syncInputs.X2RBCAssets = String.valueOf(testDrive.sked_Number_of_2RBC_Assets__c);
        
        Test.startTest();
        OpptyDOCSyncInvocable.updateOppty(new List<OpptyDOCSyncInvocable.InputWrapper>{syncInputs});
        Test.stopTest();
    }
    
    @isTest
    private static void updateOpptyRunTimeExceptionTest(){
        sked_Drive__c testDrive = [Select Id, sked_Number_of_2RBC_Assets__c, sked_Opportunity__c FROM sked_Drive__c WHERE Name = 'Test Drive' LIMIT 1];
        
        OpptyDOCSyncInvocable.InputWrapper syncInputs = new OpptyDOCSyncInvocable.InputWrapper();
        syncInputs.Id = testDrive.sked_Opportunity__c;
        syncInputs.X2RBCAssets = String.valueOf(testDrive.sked_Number_of_2RBC_Assets__c);
        BSF_Utilities.IS_SET_TO_GENERATE_EXCEPTION = true;
        
        Test.startTest();
        OpptyDOCSyncInvocable.updateOppty(new List<OpptyDOCSyncInvocable.InputWrapper>{syncInputs});
        Test.stopTest();
    }
}