force-app/main/default/objects/Contact/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked_Biomed_Collection_Op_Center__c.field-meta.xml
<CustomField>
    <fullName>sked_Biomed_Collection_Op_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biomed Collection Op (Center)</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Collection Operations Timezones (Skedulo Regions)</relationshipLabel>
    <relationshipName>sked_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/fields/sked_Territory__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>sked_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/sked__Resource_Override__c.object-meta.xml
<CustomObject>
    <label>Resource Override</label>
    <nameField>
        <displayFormat>RO-{000}</displayFormat>
        <label>Resource Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Resource Overrides</relationshipLabel>
    <relationshipName>Resource_Overrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Resource Overrides</relationshipLabel>
    <relationshipName>sked_Resource_Overrides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Override_Region__c/sked__Resource_Override_Region__c.object-meta.xml
<CustomObject>
    <label>Resource Override Region</label>
    <nameField>
        <displayFormat>ROR-{0000}</displayFormat>
        <label>Resource Override Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Override Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Override_Region__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Resource Override Regions</relationshipLabel>
    <relationshipName>Resource_Override_Regions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Resource_Override_Region__c/fields/sked__Resource_Override__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource_Override__c</fullName>
    <label>Resource Override</label>
    <referenceTo>sked__Resource_Override__c</referenceTo>
    <relationshipLabel>Resource Override Regions</relationshipLabel>
    <relationshipName>Resource_Override_Regions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Resource_Tag__c/sked__Resource_Tag__c.object-meta.xml
<CustomObject>
    <label>Resource Tag</label>
    <nameField>
        <displayFormat>RT-{0}</displayFormat>
        <label>ResourceTag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource_Tag__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipName>ResourceTags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive__c/sked_Drive__c.object-meta.xml
<CustomObject>
    <label>Drives on Calendar</label>
    <nameField>
        <label>Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drives on Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Drive__c/fields/sked_ARC_Region_ID__c.field-meta.xml
<CustomField>
    <fullName>sked_ARC_Region_ID__c</fullName>
    <formula>sked_District__r.sked_Parent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARC Region ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Drives on Calendar</relationshipLabel>
    <relationshipName>sked_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Drive__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked_Drive_Shift__c/sked_Drive_Shift__c.object-meta.xml
<CustomObject>
    <label>Drive Shift</label>
    <nameField>
        <label>Drive Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drive Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Drive Shifts</relationshipLabel>
    <relationshipName>sked_Drive_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Drive_Shift__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Operation_Record__c/sked_Operation_Record__c.object-meta.xml
<CustomObject>
    <label>Operation Record</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Operation Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Operation_Record__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipName>sked_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Operation_Record__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Operation Records</relationshipLabel>
    <relationshipName>sked_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record__c/fields/sked_Drive_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Date__c</fullName>
    <formula>sked_Drive__r.sked_Drive_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Operation_Record__c/fields/sked_Drive_Shift__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive_Shift__c</fullName>
    <label>Drive Shift</label>
    <referenceTo>sked_Drive_Shift__c</referenceTo>
    <relationshipLabel>Operation Records</relationshipLabel>
    <relationshipName>sked_Operation_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Operation_Record_Staff__c/sked_Operation_Record_Staff__c.object-meta.xml
<CustomObject>
    <label>Operation Record Staff</label>
    <nameField>
        <displayFormat>ORS-{000000}</displayFormat>
        <label>Operation Staff Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Record Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Operation_Record_Staff__c/fields/sked_Operation_Record__c.field-meta.xml
<CustomField>
    <fullName>sked_Operation_Record__c</fullName>
    <label>Operation Record</label>
    <referenceTo>sked_Operation_Record__c</referenceTo>
    <relationshipLabel>Operation Record Staff</relationshipLabel>
    <relationshipName>sked_Operation_Record_Staff</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Resource_Biomed_Collection_Op__c/sked_Resource_Biomed_Collection_Op__c.object-meta.xml
<CustomObject>
    <label>Secondary Collection Operation</label>
    <nameField>
        <displayFormat>RBCO-{0000}</displayFormat>
        <label>Secondary Collection Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secondary Collection Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Resource_Biomed_Collection_Op__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Territory__c/sked_Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Territory__c/fields/sked_Parent__c.field-meta.xml
<CustomField>
    <fullName>sked_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipName>sked_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Territory_Collection_Operation__c/sked_Territory_Collection_Operation__c.object-meta.xml
<CustomObject>
    <label>Territory Collection Operation</label>
    <nameField>
        <displayFormat>TCO-{000000}</displayFormat>
        <label>Territory Collection Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Collection Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Territory_Collection_Operation__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Territory Collection Operations</relationshipLabel>
    <relationshipName>sked_Territory_Collection_Operations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sked_Territory_Collection_Operation__c/fields/sked_Territory__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory__c</fullName>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipLabel>Territory Collection Operations</relationshipLabel>
    <relationshipName>sked_Territory_Collection_Operations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/slwcOperationRecordService.cls
global without sharing class slwcOperationRecordService {
    
    //public static final string errorMessage400_499 = 'Op Record submission failed due to problem with Op Record or Staff. Check to make sure Op Record and Staffing is complete and correct, and retry. Contact BSF support or system administrator with the Op Record Name or Drive ID for assistance.';
    //public static final string errorMessage500_599 = 'Op Record submission failed due to problem with Azure server or database. Please contact BSF support or system administrator Op Record Name or Drive ID for assistance, and wait a few minutes before retrying.';
    //public static final string errorMessageNoRecord = 'Op Record submission failed due to no record found on database.';
    //public static final string errorMessageSubmitted = 'Op Record already submitted.'; 

    @AuraEnabled
    public static void generateOperationRecords(generateOperationRecordsRequest request) {
        skedTriggerUtils.CHANGES_INITIATED_FROM_SERVICE = true;
        Set<Id> driveIds = new Set<Id>{request.driveId};

        skedOperationRecordService.regenerateOperationRecords(driveIds);
    }
    
    @AuraEnabled
    public static slwcAuraResult populateExternalIds(populateExternalIdsRequest request) {
        skedTriggerUtils.CHANGES_INITIATED_FROM_SERVICE = true;
        slwcAuraResult result = new slwcAuraResult();
        
        Set<Id> operationRecordIds = new Set<Id>{request.recordId};

        List<sked_Operation_Record__c> operationRecords = skedOperationRecordService.populateExternalIds(operationRecordIds);
        result.returnedData = operationRecords;
        
        return result;
    }
    
    @AuraEnabled
    public static slwcAuraResult getResourceData(getResourceDataRequestModel request) {
        slwcAuraResult result = new slwcAuraResult();

        sked_Drive_Shift__c driveShift = [
            SELECT Id, sked_Drive__r.sked_ARC_Region_ID__c, sked_Drive__r.sked_Drive_Date__c
            FROM sked_Drive_Shift__c
            WHERE Id = :request.driveShiftId
        ];

        List<sked_Territory_Collection_Operation__c> tcos = [
            SELECT Id, sked_Collection_Operation__c
            FROM sked_Territory_Collection_Operation__c
            WHERE sked_Territory__r.sked_Parent__c = :driveShift.sked_Drive__r.sked_ARC_Region_ID__c
            AND sked_Start_Date__c <= :driveShift.sked_Drive__r.sked_Drive_Date__c
            AND sked_End_Date__c >= :driveShift.sked_Drive__r.sked_Drive_Date__c
        ];

        Set<Id> collectionOperationIds = new Set<Id>();
        if (tcos != null && !tcos.isEmpty()) {
            for (sked_Territory_Collection_Operation__C tco : tcos) {
                collectionOperationIds.add(tco.sked_Collection_Operation__c);
            }
        }

        Date inputDate = skedDateTimeUtils.getDateFromIsoString(request.inputDate);
        List<String> additionalResourceIds = new List<string>();
        List<sked__Resource__c> resources;
        List<sked__Resource__c> filteredResources;
        if (collectionOperationIds != NULL && !collectionOperationIds.isEmpty()) {
            List<sked__Resource_Override_Region__c> resourceOverrideRegions = [
                SELECT Id, sked__Resource_Override__r.sked__Resource__c 
                FROM sked__Resource_Override_Region__c 
                WHERE sked__Region__r.sked_Biomed_Collection_Op_Center__c IN :collectionOperationIds
                AND (sked__Resource_Override__r.sked_Start_Date__c <= :inputDate 
                    AND sked__Resource_Override__r.sked_End_Date__c >= :inputDate)
            ];
            if (resourceOverrideRegions != NULL && !resourceOverrideRegions.isEmpty()) {
                for (sked__Resource_Override_Region__c resourceOverrideRegion : resourceOverrideRegions) {
                    additionalResourceIds.add(resourceOverrideRegion.sked__Resource_Override__r.sked__Resource__c);
                }
            }
            
            List<sked_Resource_Biomed_Collection_Op__c> resourceCollectionOperations = [
                SELECT Id, sked_Resource__c
                FROM sked_Resource_Biomed_Collection_Op__c
                WHERE sked_Biomed_Collection_Op_Center__c IN :collectionOperationIds
                AND (sked_Start_Date__c = NULL OR sked_Start_Date__c <= :inputDate) 
                AND (sked_End_Date__c = NULL OR sked_End_Date__c  >= :inputDate)
            ];
            if (resourceCollectionOperations != NULL && !resourceCollectionOperations.isEmpty()) {
                for (sked_Resource_Biomed_Collection_Op__c resourceCollectionOperation : resourceCollectionOperations) {
                    additionalResourceIds.add(resourceCollectionOperation.sked_Resource__c);
                }
            }

            string queryTextPadded = '%' + request.queryText + '%';
            resources = [
                SELECT Id, Name, sked__User__c, sked__User__r.SmallPhotoUrl, sked__Primary_Region__r.sked__Timezone__c, 
                sked__Primary_Region__r.sked_Biomed_Collection_Op_Center__c, sked_Biomed_Collection_Op_Center_Name__c
                FROM sked__Resource__c
                WHERE Name LIKE :queryTextPadded
                AND (sked__Primary_Region__r.sked_Biomed_Collection_Op_Center__c IN :collectionOperationIds 
                    OR Id IN :additionalResourceIds)
                AND sked__Resource_Type__c = :skedConstants.RESOURCE_TYPE_PERSON
                AND sked__Is_Active__c = TRUE
                ORDER BY Name
            ];
            
            
            if (request.roles != NULL && !request.roles.isEmpty()) {
                List<sked__Resource_Tag__c> resourceTags = [
                    SELECT Id, sked__Resource__c
                    FROM sked__Resource_Tag__c
                    WHERE sked__Tag__r.Name IN :request.roles
                    AND sked_Start_Date__c <= :inputDate
                    AND sked__Resource__r.Name LIKE :queryTextPadded
                    AND (sked__Resource__r.sked__Primary_Region__r.sked_Biomed_Collection_Op_Center__c IN :collectionOperationIds 
                            OR sked__Resource__c IN :additionalResourceIds)
                    AND sked__Tag__r.sked__Type__c = :skedConstants.TAG_TYPE_ROLE
                    AND sked__Resource__r.sked__Resource_Type__c = :skedConstants.RESOURCE_TYPE_PERSON
                    AND sked__Resource__r.sked__Is_Active__c = TRUE
                ];
                Set<Id> resourceIdsThatHaveRoles = new Set<Id>();
                for (sked__Resource_Tag__c resourceTag : resourceTags) {
                    resourceIdsThatHaveRoles.add(resourceTag.sked__Resource__c);
                }
                
                filteredResources = new List<sked__Resource__c>();
                for (sked__Resource__c resource : resources) {
                    if (resourceIdsThatHaveRoles.contains(resource.Id)) {
                        filteredResources.add(resource);
                    }
                }
            }
        }
        
        resourceDataModel data = new resourceDataModel();
        data.resources = filteredResources != NULL ? filteredResources : resources;
        result.returnedData = data;
        
        return result;
    }

    @AuraEnabled
    public static slwcAuraResult submitOperationRecord(submitOpsRecordRequest request) {
        Boolean isSuccess = false;
        String logMessage = Custom_Messages__mdt.getInstance('OpRecordMessage_SomethingWrong').value__c;
        String logSummary = '';

        sked_Operation_Record__c opRecord;

        skedTriggerUtils.CHANGES_INITIATED_FROM_SERVICE = true;

        try{
            if(request == null || String.isBlank(request.operationRecordId)){
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_NoDataFound').value__c);
            }

            List<sked_Operation_Record__c> opRecordList = skedOperationRecordUtils.getOpsRecords(new Set<Id>{request.operationRecordId});

            if(opRecordList.isEmpty()){
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_NoDataFound').value__c);
            }

            if (opRecordList[0].sked_Drive__c == null) {
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_DriveIdNull').value__c);
            }

            opRecord = opRecordList[0];
            String driveStatus = opRecord.sked_Drive__r.sked_Status__c;

            if(String.isNotBlank(opRecord.sked_Status__c) && opRecord.sked_Status__c.equals(skedConstants.OPERATION_STATUS_SUBMITTED)){
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_AlreadySubmitted').value__c);
            }

            if(opRecord.sked_Operation_Record_Staff__r == null || opRecord.sked_Operation_Record_Staff__r.isEmpty()){
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_staffNull').value__c);
            }

            skedOpsRecordApiData.opsRecordRequest opsRecordRequest = skedOperationRecordUtils.getOpsRecordRequest(opRecord);

            if (opsRecordRequest == null) {
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_RequestNull').value__c);
            }

            skedOpsRecordApiManager apiManager = new skedOpsRecordApiManager();
            skedOpsRecordApiData.resultBase opsRecordResult = apiManager.updateStaffRecord(opsRecordRequest);

            logSummary = 'Submission Details: ' + 
                        '\n\nRequest: ' + JSON.serialize(opsRecordRequest) +
                        '\n\nResponse: ' + JSON.serialize(opsRecordResult);

            if (opsRecordResult == null) {
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_RequestNull').value__c);
            }

            logSummary += '\n\nSuccess: ' + opsRecordResult.success +
                            '\nStatus Code: ' + opsRecordResult.statusCode +
                            '\nStatus: ' + opsRecordResult.status + 
                            '\nMessage: ' + opsRecordResult.message;
            
            if (opsRecordResult.success == false && (opsRecordResult.statusCode == null || opsRecordResult.statusCode >= 500)) {
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_500_599').value__c);
            }
            else if (!opsRecordResult.success) {
                throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_400_499').value__c);
            }

            if (opsRecordResult.success == true) {
                opRecord.sked_Submitted_By__c = skedTriggerHub_Cache.getCurrentUserResource().Id;
                opRecord.sked_Locked__c = true;
                opRecord.sked_Status__c = skedConstants.OPERATION_STATUS_SUBMITTED;
                Database.SaveResult[] srList = Database.update(new List<sked_Operation_Record__c>{opRecord}, false);
                for (Database.SaveResult sr : srList){
                    if(!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            logSummary += 'Error Details: ' +
                            '\n\nMessage: ' + err.getMessage() +
                            '\nField: ' + err.getFields();
                        }
                        throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_SubmittedButSFRecordFail').value__c);
                    }
                }

                List<sked_Drive__c> drivesList = [SELECT Id, 
                                                        sked_Status__c, 
                                                        (SELECT Id
                                                        FROM sked_Drive_Shifts__r) 
                                                    FROM sked_Drive__c 
                                                    WHERE Id = :opRecord.sked_Drive__c];
                if (!drivesList.isEmpty()) {
                    sked_Drive__c drive = drivesList[0];
                    if ((drive.sked_Status__c != skedConstants.DRIVE_STATUS_COMPLETE)) {
                        driveStatus = drive.sked_Status__c;
                        Boolean isAllOpRecordsSubmitted = true;
                        Map<Id, Boolean> opRecordSumbmittedMap =new Map<Id, Boolean>();
                        if (drive.sked_Drive_Shifts__r != null) {
                            for (sked_Drive_Shift__c drvShift : drive.sked_Drive_Shifts__r) {
                                opRecordSumbmittedMap.put(drvShift.Id,false);
                            }
                            List<sked_Operation_Record__c> opRecordSumbmittedList = [SELECT Id, 
                                                                                            sked_Status__c,
                                                                                            sked_Drive_Shift__c
                                                                                    FROM sked_Operation_Record__c
                                                                                    WHERE sked_Drive_Shift__c IN :opRecordSumbmittedMap.keySet()
                                                                                    AND sked_Status__c = :skedConstants.OPERATION_STATUS_SUBMITTED];
                            for (sked_Operation_Record__c opRecSub : opRecordSumbmittedList) {
                                opRecordSumbmittedMap.put(opRecSub.sked_Drive_Shift__c,true);
                            }
                            for (Id shiftId : opRecordSumbmittedMap.keySet()) {
                                if (!opRecordSumbmittedMap.get(shiftId)) {
                                    isAllOpRecordsSubmitted = false;
                                }
                            }
                        }
                        else {
                            isAllOpRecordsSubmitted = false;
                        }

                        if (!isAllOpRecordsSubmitted) {
                            isSuccess = true;
                            logMessage = Custom_Messages__mdt.getInstance('OpRecordMessage_SubmittedButDOCFailed').value__c;
                        }
                        else {
                            drive.sked_Status__c = skedConstants.DRIVE_STATUS_COMPLETE;
                            Database.SaveResult[] srListDOC = Database.update(new List<sked_Drive__c>{drive}, false);
                            for (Database.SaveResult sr : srListDOC) {
                                if (!sr.isSuccess()) {
                                    String expMessage = '';
                                    for (Database.Error err : sr.getErrors()) {
                                        logSummary += 'Error Details: ' +
                                                    '\n\nMessage: ' + err.getMessage() +
                                                    '\nField: ' + err.getFields();
                                        expMessage +=' Field: ' + err.getFields()+
                                                    ' Message: ' + err.getMessage();
                                    }
                                    throw new OperationRecordServiceException(Custom_Messages__mdt.getInstance('OpRecordMessage_SubmittedButDOCFailedExp').value__c+expMessage);
                                }
                                else {
                                    driveStatus = skedConstants.DRIVE_STATUS_COMPLETE;
                                    isSuccess = true;
                                    logMessage = Custom_Messages__mdt.getInstance('OpRecordMessage_Submitted').value__c;
                                }
                            }
                        }
                    }
                    else {
                        isSuccess = true;
                        logMessage = Custom_Messages__mdt.getInstance('OpRecordMessage_Submitted').value__c;
                    }
                }
            }

            logSummary += '\n\nOperation Record: ' + opRecord.Id +
                            '\nOperation Status: ' + opRecord.sked_Status__c +
                            '\nDrive: ' + opRecord.sked_Drive__c + 
                            '\nDrive Status: ' + driveStatus;

        }catch(OperationRecordServiceException opEx){
            logMessage = opEx.getMessage();
            logSummary += '\n'+ opEx.getMessage();
        }catch(Exception exp){
            logMessage = Custom_Messages__mdt.getInstance('OpRecordMessage_Exception').value__c +' '+ exp.getMessage();
            logSummary += 'Exception Details: ' +
                            '\n\nMessage: ' + exp.getMessage() +
                            '\nStack Trace: ' + exp.getStackTraceString() +
                            '\nCause: ' + exp.getCause();
        }

        String logId = insertDebugLog(logMessage,logSummary);

        if ((opRecord != null && !isSuccess && String.isNotBlank(logId)) || Test.isRunningTest()) {
            sendOpRecordAPIFailureEmail(opRecord,logId);
        }

        slwcAuraResult result = new slwcAuraResult();
        result.message = logMessage;
        result.returnedData = logMessage;
        result.success = isSuccess;
        return result;
    }
    public static String insertDebugLog(String logMessage, String logSummary){
        String logId = '';
        sked__Debug_Log__c submissionLog;
        if (skedSetting.instance.Admin.enableOperationRecordLog) {
            submissionLog = new sked__Debug_Log__c(
                sked__Type__c = 'Operation Record Submission',
                sked__User__c = UserInfo.getUserId(),
                sked__Summary__c = logSummary,
                sked__Message__c = logMessage
            );
            Database.insert(new List<sked__Debug_Log__c>{submissionLog}, false);
        }
        if (submissionLog != null && submissionLog.Id != null) {
            logId = submissionLog.Id;
        }
        return logId;
    }
    public static void sendOpRecordAPIFailureEmail(sked_Operation_Record__c opRecord, String logId){
        try{
            List<string> toList = new List<string>();
            if (!string.isBlank(skedSetting.instance.Email.bitTechnicalSupport)) {
                toList.add(skedSetting.instance.Email.bitTechnicalSupport);
            }
            if (!string.isBlank(skedSetting.instance.Email.bhqApsStaffSchedulingManagers)) {
                toList.add(skedSetting.instance.Email.bhqApsStaffSchedulingManagers);
            }
            if (!string.isBlank(skedSetting.instance.Email.bhqApsStaffSchedulingTimekeeping)) {
                toList.add(skedSetting.instance.Email.bhqApsStaffSchedulingTimekeeping);
            }
            if (!string.isBlank(skedSetting.instance.Email.apsDirectors)) {
                toList.add(skedSetting.instance.Email.apsDirectors);
            }
            if (!string.isBlank(skedSetting.instance.Email.bhqCollectionsPlanningScheduling)) {
                toList.add(skedSetting.instance.Email.bhqCollectionsPlanningScheduling);
            }

            string content = 'Failure information: Op Record API failure - open E-Z Vista ticket routed to [BIT support] <br />'
                                + 'Affected Op Record: '+opRecord.Name+' <br/>'
                                + 'Affected Drive: '+opRecord.sked_Drive__r.sked_UFID__c+' <br/>';
            if (String.isNotBlank(logId)) {
                content += 'Op Record Debug Log ID: '+logId+' <br/>';
            }

            List<skedEmailService.emailModel> emails = new List<skedEmailService.emailModel>();
            skedEmailService.emailModel emailItem = new skedEmailService.emailModel();
            emailItem.subject = 'Alert: Op Record API failure';
            emailItem.htmlBody = content;
            emailItem.whatId = opRecord.Id;
            emailItem.targetObjId = UserInfo.getUserId();
            emailItem.toList = toList;
            emails.add(emailItem);
            
            skedEmailService emailService = new skedEmailService();
            emailService.sendEmails(emails);
        }catch(Exception ex){/*no action*/}
    }

    /*********************************************************** Nested Classes ***********************************************************/
    public class getResourceDataRequestModel {
        @AuraEnabled public string queryText {get;set;}
        @AuraEnabled public string driveShiftId {get;set;}
        @AuraEnabled public List<string> roles {get;set;}
        @AuraEnabled public string inputDate {get;set;}
    }

    public class generateOperationRecordsRequest {
        @AuraEnabled public string driveId {get;set;}
    }
    
    public class populateExternalIdsRequest {
        @AuraEnabled public string recordId {get;set;}
    }
    
    public class resourceDataModel {
        @AuraEnabled public object resources {get;set;}
    }

    public class submitOpsRecordRequest {
        @AuraEnabled public string operationRecordId {get;set;}
    }

    public class OperationRecordServiceException extends Exception {}
}