unpackaged/main/default/objects/sked_Resource_Hours_Record__c/sked_Resource_Hours_Record__c.object-meta.xml
<CustomObject>
    <label>Resource Hours Record</label>
    <nameField>
        <displayFormat>RHR-{00000000}</displayFormat>
        <label>Resource Hours Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Hours Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Resource_Hours_Record_Detail__c/sked_Resource_Hours_Record_Detail__c.object-meta.xml
<CustomObject>
    <label>Resource Hours Record	Detail</label>
    <nameField>
        <displayFormat>RHRD-{0000000}</displayFormat>
        <label>Resource Hours Record	Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Hours Record	Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Resource_Hours_Record_Detail__c/fields/sked_Resource_Hours_Record__c.field-meta.xml
<CustomField>
    <fullName>sked_Resource_Hours_Record__c</fullName>
    <label>Resource Hours Record</label>
    <referenceTo>sked_Resource_Hours_Record__c</referenceTo>
    <relationshipLabel>Resource Hours Record	Details</relationshipLabel>
    <relationshipName>sked_Resource_Hours_Record_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/skedResourceHoursRecordDetailHandler.cls
public class skedResourceHoursRecordDetailHandler extends skedTriggerHub {
    public override void onAfterInsert() {
        calculateResourceHoursRecordTotalWorkingDays(this.context.newRecords);
    }

    public override void onAfterDelete() {
        calculateResoruceHoursRecordTotalWorkingDays(this.context.oldRecords);
    }

    /*********************************************************** Privated Methods ***********************************************************/
    private void calculateResourceHoursRecordTotalWorkingDays(List<sked_Resource_Hours_Record_Detail__c> newRecords) {
        skedResourceHoursRecordUtils.countTotalWorkingDays(new List<Id>(getResourceHoursRecordIds(newRecords)));
    }

    private void calculateResoruceHoursRecordTotalWorkingDays(List<sked_Resource_Hours_Record_Detail__c> oldRecords) {
        skedResourceHoursRecordUtils.countTotalWorkingDays(new List<Id>(getResourceHoursRecordIds(oldRecords)));
    }

    private Set<Id> getResourceHoursRecordIds(List<sked_Resource_Hours_Record_Detail__c> records) {
        Set<Id> resourceHoursRecordIds = new Set<Id>();

        for (sked_Resource_Hours_Record_Detail__c record : records) {
            resourceHoursRecordIds.add(record.sked_Resource_Hours_Record__c);
        }

        return resourceHoursRecordIds;
    }
}