unpackaged/main/default/objects/sked_Travel_Time_Index_Item__c/sked_Travel_Time_Index_Item__c.object-meta.xml
<CustomObject>
    <label>Travel Time Index Item</label>
    <nameField>
        <label>Travel Time Index Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Time Index Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Travel_Time_Index_Item__c/fields/sked_Ordering_Key__c.field-meta.xml
<CustomField>
    <fullName>sked_Ordering_Key__c</fullName>
    <label>Ordering Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/sked_Travel_Time_Index_Item__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <label>Timezone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked_Travel_Time_Index_Refresh_Group__c/sked_Travel_Time_Index_Refresh_Group__c.object-meta.xml
<CustomObject>
    <label>Travel Time Index Refresh Group</label>
    <nameField>
        <displayFormat>TTIRG-{000000}</displayFormat>
        <label>Travel Time Index Refresh Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Time Index Refresh Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Travel_Time_Index_Refresh_Group__c/fields/sked_Collection_Operations_To_Refresh__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operations_To_Refresh__c</fullName>
    <label>Collection Operations To Refresh</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>sked_Collection_Operations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Travel_Time_Index_Refresh_Group__c/fields/sked_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generating Refresh Request</fullName>
                <default>true</default>
                <label>Generating Refresh Request</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Travel_Time_Index_Refresh_Request__c/sked_Travel_Time_Index_Refresh_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Time Index Refresh Request</label>
    <nameField>
        <displayFormat>TTIRR-{000000}</displayFormat>
        <label>Travel Time Index Refresh Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Time Index Refresh Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sked_Travel_Time_Index_Refresh_Request__c/fields/sked_Destinations__c.field-meta.xml
<CustomField>
    <fullName>sked_Destinations__c</fullName>
    <label>Destinations</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sked_Travel_Time_Index_Refresh_Request__c/fields/sked_Origins__c.field-meta.xml
<CustomField>
    <fullName>sked_Origins__c</fullName>
    <label>Origins</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/sked_Travel_Time_Index_Refresh_Request__c/fields/sked_Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>sked_Record_Ids__c</fullName>
    <label>Record Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/sked_Travel_Time_Index_Refresh_Request__c/fields/sked_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked_Travel_Time_Index_Refresh_Request__c/fields/sked_Travel_Time_Index_Refresh_Group__c.field-meta.xml
<CustomField>
    <fullName>sked_Travel_Time_Index_Refresh_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Travel Time Index Refresh Group</label>
    <referenceTo>sked_Travel_Time_Index_Refresh_Group__c</referenceTo>
    <relationshipLabel>Travel Time Index Refresh Requests</relationshipLabel>
    <relationshipName>Travel_Time_Index_Refresh_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/sked_Collection_Operations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>San Jose CA cloned</fullName>
    </customValue>
    <customValue>
        <fullName>Adrian MI</fullName>
    </customValue>
    <customValue>
        <fullName>Alameda CA</fullName>
    </customValue>
    <customValue>
        <fullName>Albany NY</fullName>
    </customValue>
    <customValue>
        <fullName>Altoona PA</fullName>
    </customValue>
    <customValue>
        <fullName>Anaheim CA</fullName>
    </customValue>
    <customValue>
        <fullName>Arlington TX</fullName>
    </customValue>
    <customValue>
        <fullName>Asheville NC</fullName>
    </customValue>
    <customValue>
        <fullName>Athens GA</fullName>
    </customValue>
    <customValue>
        <fullName>Atlanta GA</fullName>
    </customValue>
    <customValue>
        <fullName>Austin TX</fullName>
    </customValue>
    <customValue>
        <fullName>Baltimore MD</fullName>
    </customValue>
    <customValue>
        <fullName>Bangor ME</fullName>
    </customValue>
    <customValue>
        <fullName>Beaver PA</fullName>
    </customValue>
    <customValue>
        <fullName>Beckley WV</fullName>
    </customValue>
    <customValue>
        <fullName>Bend OR</fullName>
    </customValue>
    <customValue>
        <fullName>Binghamton NY</fullName>
    </customValue>
    <customValue>
        <fullName>Birmingham AL</fullName>
    </customValue>
    <customValue>
        <fullName>Bloomington IL</fullName>
    </customValue>
    <customValue>
        <fullName>Boise ID</fullName>
    </customValue>
    <customValue>
        <fullName>Bozeman MT</fullName>
    </customValue>
    <customValue>
        <fullName>Buffalo NY</fullName>
    </customValue>
    <customValue>
        <fullName>Burbank CA</fullName>
    </customValue>
    <customValue>
        <fullName>Burlington VT</fullName>
    </customValue>
    <customValue>
        <fullName>Camden NJ</fullName>
    </customValue>
    <customValue>
        <fullName>Cape Girardeau MO</fullName>
    </customValue>
    <customValue>
        <fullName>Charleston SC</fullName>
    </customValue>
    <customValue>
        <fullName>Charlotte NC</fullName>
    </customValue>
    <customValue>
        <fullName>Chicago IL</fullName>
    </customValue>
    <customValue>
        <fullName>Cleveland OH East</fullName>
    </customValue>
    <masterLabel>Collection Operations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/skedTTIndexRefreshRequestTrigger_Test.cls
/* Description: This test class covers skedTravelTimeIndexRefreshRequestTrigger and related handler class */

@isTest
private class skedTTIndexRefreshRequestTrigger_Test {
    
    @isTest
    static void afterInsertUpdateContext_Test() {
        List<sked_Travel_Time_Index_Item__c> testTravelTimeIndexItems = new List<sked_Travel_Time_Index_Item__c>();
        sked_Travel_Time_Index_Item__c testTtii1;
        testTtii1 = new sked_Travel_Time_Index_Item__c(
            sked_From__Latitude__s = 36.7450046,
            sked_From__Longitude__s = -120.4816244,
            sked_To__Latitude__s = 38.7450046,
            sked_To__Longitude__s = -122.4816244,
            sked_Ordering_Key__c = skedConstants.TTII_DIRECTION_SITE_TO_CO + 36.7450046 + ':' + -120.4816244,
            sked_Timezone__c = 'America/New_York'
        );
        testTravelTimeIndexItems.add(testTtii1);
        
        testTtii1 = new sked_Travel_Time_Index_Item__c(
            sked_From__Latitude__s = 36.74500455,
            sked_From__Longitude__s = -120.4816344,
            sked_To__Latitude__s = 38.7450146,
            sked_To__Longitude__s = -122.4826244,
            sked_Ordering_Key__c = skedConstants.TTII_DIRECTION_SITE_TO_CO + 36.74500455 + ':' + -120.4816344,
            sked_Timezone__c = 'America/New_York'
        );
        testTravelTimeIndexItems.add(testTtii1);
        
        insert testTravelTimeIndexItems;

        Location fromLoc1 = Location.newInstance(testTravelTimeIndexItems[0].sked_From__Latitude__s, testTtii1.sked_From__Longitude__s);
        Location toLoc1 = Location.newInstance(testTravelTimeIndexItems[0].sked_To__Latitude__s, testTtii1.sked_To__Longitude__s);
        Location fromLoc2 = Location.newInstance(testTravelTimeIndexItems[1].sked_From__Latitude__s, testTtii1.sked_From__Longitude__s);
        Location toLoc2 = Location.newInstance(testTravelTimeIndexItems[1].sked_To__Latitude__s, testTtii1.sked_To__Longitude__s);
        
        List<sked_Travel_Time_Index_Refresh_Group__c> testTTIRefreshGroupList = new List<sked_Travel_Time_Index_Refresh_Group__c>();
        
        sked_Travel_Time_Index_Refresh_Group__c testTTIRefreshGroup;
        testTTIRefreshGroup = new sked_Travel_Time_Index_Refresh_Group__c(
        	sked_Collection_Operations_To_Refresh__c = 'Adrian MI;Anaheim CA;Baltimore MD'
        );
        testTTIRefreshGroupList.add(testTTIRefreshGroup);
        
        testTTIRefreshGroup = new sked_Travel_Time_Index_Refresh_Group__c(
        	sked_Collection_Operations_To_Refresh__c = 'Boise ID',
            sked_Status__c = skedConstants.TRAVEL_TIME_INDEX_REFRESH_GROUP_STATUS_PENDING
        );
        testTTIRefreshGroupList.add(testTTIRefreshGroup);
        insert testTTIRefreshGroupList;
		
        Test.startTest();
        
        List<sked_Travel_Time_Index_Refresh_Request__c> testItems = new List<sked_Travel_Time_Index_Refresh_Request__c>();
        sked_Travel_Time_Index_Refresh_Request__c testTtirr;
        
        testTtirr = new sked_Travel_Time_Index_Refresh_Request__c(  
            sked_Record_Ids__c = testTravelTimeIndexItems[0].Id,
            sked_Origins__c = skedTravelTimeIndexItemUtils.getKey(fromLoc1),
            sked_Destinations__c = skedTravelTimeIndexItemUtils.getKey(toLoc1),
            sked_Request_Type__c = 'Travel Time',
            sked_Status__c = 'Pending',
            sked_Run_Id__c = '1'
        );
        testItems.add(testTtirr);
        
        testTtirr = new sked_Travel_Time_Index_Refresh_Request__c(  
            sked_Record_Ids__c = testTravelTimeIndexItems[1].Id,
            sked_Origins__c = skedTravelTimeIndexItemUtils.getKey(fromLoc2),
            sked_Destinations__c = skedTravelTimeIndexItemUtils.getKey(toLoc2),
            sked_Travel_Time_Index_Refresh_Group__c = testTTIRefreshGroupList[1].Id,
            sked_Request_Type__c = 'Travel Time',
            sked_Status__c = 'Pending',
            sked_Run_Id__c = '2'
        );
        testItems.add(testTtirr);
        
        insert testItems;
        
        testItems[0].sked_Status__c = 'Completed';
        testItems[1].sked_Status__c = 'In Progress';
        testItems[0].sked_Travel_Time_Index_Refresh_Group__c = testTTIRefreshGroupList[0].Id;
        update testItems;
        
        Test.stopTest();
    }

}