unpackaged/main/default/objects/sked_Travel_Time_Index_Item__c/sked_Travel_Time_Index_Item__c.object-meta.xml
<CustomObject>
    <label>Travel Time Index Item</label>
    <nameField>
        <label>Travel Time Index Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Time Index Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Travel_Time_Index_Item__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Travel Time Index Items</relationshipLabel>
    <relationshipName>sked_Travel_Time_Index_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/skedTtiiCoPopulationOneTimeBatch.cls
public class skedTtiiCoPopulationOneTimeBatch implements Database.Batchable<SObject>, Database.Stateful {

    protected String lastId = '';

    public skedTtiiCoPopulationOneTimeBatch() {
        this.lastId = '';
    }

    public skedTtiiCoPopulationOneTimeBatch(String lastId) {
        this.lastId = lastId;
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id
            FROM sked_Travel_Time_Index_Item__c
            WHERE sked_Collection_Operation__c = NULL
            AND Id > :this.lastId
            ORDER BY Id ASC
            LIMIT 50000
        ]);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        Set<Id> ttiiIds = new Set<Id>();
        for (SObject record : scope) {
            ttiiIds.add((Id) record.get('Id'));
        }
        skedTravelTimeIndexItemHandler.populateTTILokkupFieldsOnSiteCO(ttiiIds);
        this.lastId = (Id) scope.get(scope.size() - 1).get('Id');
    }

    public void finish(Database.BatchableContext BC) {
        List<sked_Travel_Time_Index_Item__c> remainRecordQuery = [
            SELECT Id
            FROM sked_Travel_Time_Index_Item__c
            WHERE sked_Collection_Operation__c = NULL
            AND Id > :this.lastId
            ORDER BY Id ASC
            LIMIT 1
        ];

        if (!remainRecordQuery.isEmpty()) {
            if (!Test.isRunningTest()) {
                Database.executeBatch(new skedTtiiCoPopulationOneTimeBatch(this.lastId), 200);
            }
        }
    }
}