force-app/main/default/objects/sked__Activity__c/sked__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity__c/fields/sked__End__c.field-meta.xml
<CustomField>
    <fullName>sked__End__c</fullName>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/sked__Availability__c.object-meta.xml
<CustomObject>
    <description>Exceptions to the standard availability template for this user</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Availability__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Availabilities1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Exception_Code__c.field-meta.xml
<CustomField>
    <fullName>sked_Exception_Code__c</fullName>
    <label>Exception Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Finish__c.field-meta.xml
<CustomField>
    <fullName>sked__Finish__c</fullName>
    <label>Finish</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>sked_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Set_End__c.field-meta.xml
<CustomField>
    <fullName>sked__Set_End__c</fullName>
    <description>An editable version of the End field. This may be null for historical records. For new records, there are triggers in place to ensure that this will always have the same value as the formula End field.</description>
    <label>Set End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/skedHC__Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/skedHC__Exception__c/fields/sked_Conflicted_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Conflicted_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conflicted Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Exception Log (Conflicted Drive)</relationshipLabel>
    <relationshipName>Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/sked_Conflicted_Job__c.field-meta.xml
<CustomField>
    <fullName>sked_Conflicted_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conflicted Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Exception Log (Conflicted Job)</relationshipLabel>
    <relationshipName>sked_Exception_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/sked_Conflicted_Job_Allocation__c.field-meta.xml
<CustomField>
    <fullName>sked_Conflicted_Job_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conflicted Job Allocation</label>
    <referenceTo>sked__Job_Allocation__c</referenceTo>
    <relationshipLabel>Exception Log (Conflicted Job Allocation)</relationshipLabel>
    <relationshipName>sked_Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/sked_Drive__c.field-meta.xml
<CustomField>
    <fullName>sked_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drive</label>
    <referenceTo>sked_Drive__c</referenceTo>
    <relationshipLabel>Exception Log</relationshipLabel>
    <relationshipName>sked_Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Activity__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Exception Log</relationshipLabel>
    <relationshipName>Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Availability__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Availability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unavailability</label>
    <referenceTo>sked__Availability__c</referenceTo>
    <relationshipLabel>Exception Log</relationshipLabel>
    <relationshipName>Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Exception__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Exception__c</fullName>
    <label>Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Job__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Exception Log</relationshipLabel>
    <relationshipName>Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Job_Allocation__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Job_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Allocation</label>
    <referenceTo>sked__Job_Allocation__c</referenceTo>
    <relationshipLabel>Exception Log</relationshipLabel>
    <relationshipName>Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Resource__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Exception Log</relationshipLabel>
    <relationshipName>Exception_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/skedHC__Exception__c/fields/skedHC__Status__c.field-meta.xml
<CustomField>
    <fullName>skedHC__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/skedExceptionLogService.cls
global class skedExceptionLogService extends skedDataService {
    
    public override void initialize() {
        this.sObjectApiName = 'skedHC__Exception__c';
        this.objectType = 'exceptionLog';
        this.domainType = Type.forName('skedModels.exceptionLog');
    }
    
    /*********************************************************** Public methods ***********************************************************/
    public List<skedHC__Exception__c> captureExceptionLogs(List<resourceUnavailabilityModel> unavailabilityList) {
        Set<Id> resourceIds = new Set<Id>();
        Set<Id> sourceRecordIds = new Set<Id>();
        Set<Id> excludedIds = new Set<Id>();
        DateTime minDt, maxDt;
        boolean hasTermination = false;
        for (resourceUnavailabilityModel unavailability : unavailabilityList) {
            resourceIds.add(unavailability.resourceId);
            
            if (unavailability.recordId != NULL) {
            	sourceRecordIds.add(unavailability.recordId);
            }
            
            if (unavailability.relatedEventFieldApi == 'skedHC__Job_Allocation__c') {
                excludedIds.add(unavailability.recordId);
            }
            if (minDt == NULL || unavailability.startTime < minDt) {
                minDt = unavailability.startTime;
            }
            if (unavailability.endTime != NULL) {
                if (maxDt == NULL || unavailability.endTime > maxDt) {
                    maxDt = unavailability.endTime;
                }
            }
            else {
                hasTermination = true;
            }
        }
        if (hasTermination) {
            maxDt = NULL;
        }
        
        List<sked__Job_Allocation__c> conflictedAllocations = getConflictedAllocations(resourceIds, minDt, maxDt, excludedIds);
        
        List<skedHC__Exception__c> existingExceptionLogs = [
            SELECT Id, skedHC__Job_Allocation__c, skedHC__Exception__c,
            skedHC__Job__r.sked__Start__c, skedHC__Job__r.sked__Finish__c,
            skedHC__Availability__c, skedHC__Availability__r.sked__Start__c, 
            skedHC__Availability__r.sked__Finish__c, skedHC__Activity__c,
            skedHC__Activity__r.sked__Start__c, skedHC__Activity__r.sked__End__c
            FROM skedHC__Exception__c
            WHERE (skedHC__Availability__c IN :sourceRecordIds 
                    OR skedHC__Activity__c IN :sourceRecordIds
                    OR skedHC__Job_Allocation__c IN :sourceRecordIds)
            AND skedHC__Status__c = :skedConstants.EXCEPTION_LOG_STATUS_OPEN
        ];
        Map<string, skedHC__Exception__c> mapExistingExceptionLog = new Map<string, skedHC__Exception__c>();
        List<skedHC__Exception__c> exceptionLogsToUpdate = new List<skedHC__Exception__c>();
        for (skedHC__Exception__c existingExceptionLog : existingExceptionLogs) {
            if (existingExceptionLog.skedHC__Availability__c != NULL 
                && (existingExceptionLog.skedHC__Job__r.sked__Start__c >= existingExceptionLog.skedHC__Availability__r.sked__Finish__c
                    || existingExceptionLog.skedHC__Job__r.sked__Finish__c <= existingExceptionLog.skedHC__Availability__r.sked__Start__c)) {
                        existingExceptionLog.skedHC__Status__c = skedConstants.EXCEPTION_LOG_STATUS_CLOSED;
                        exceptionLogsToUpdate.add(existingExceptionLog);
                    }
            if (existingExceptionLog.skedHC__Activity__c != NULL 
                && (existingExceptionLog.skedHC__Job__r.sked__Start__c >= existingExceptionLog.skedHC__Activity__r.sked__End__c
                    || existingExceptionLog.skedHC__Job__r.sked__Finish__c <= existingExceptionLog.skedHC__Activity__r.sked__Start__c)) {
                        existingExceptionLog.skedHC__Status__c = skedConstants.EXCEPTION_LOG_STATUS_CLOSED;
                        exceptionLogsToUpdate.add(existingExceptionLog);
                    }
            else {
                string key = existingExceptionLog.skedHC__Job_Allocation__c + ':' + existingExceptionLog.skedHC__Exception__c;
                mapExistingExceptionLog.put(key, existingExceptionLog);	
            }
        }
        if (!exceptionLogsToUpdate.isEmpty()) {
            update exceptionLogsToUpdate;
        }
        
        List<skedHC__Exception__c> newExceptionLogs = new List<skedHC__Exception__c>();
        for (resourceUnavailabilityModel unavailability : unavailabilityList) {
            for (sked__Job_Allocation__c conflictedAllocation : conflictedAllocations) {
                if (conflictedAllocation.sked__Resource__c != unavailability.resourceId
                    || conflictedAllocation.sked__Set_End__c < unavailability.startTime) {
                        continue;
                    }
                if (unavailability.endTime != NULL && unavailability.endTime <= conflictedAllocation.sked__Start__c) {
                    break;
                }
                string key = conflictedAllocation.Id + ':' + unavailability.exceptionCode;
                if (mapExistingExceptionLog.containsKey(key)) {
                    continue;
                }

                String jobId = unavailability.jobId != null ? unavailability.jobId : conflictedAllocation.sked__Job__c;
                String jobAllocationId = unavailability.jobAllocationId != null ? unavailability.jobAllocationId : conflictedAllocation.Id;
                String driveId = unavailability.driveId != null ? unavailability.driveId : conflictedAllocation.sked__Job__r.sked_Drive__c;
                
                skedHC__Exception__c newExceptionLog = new skedHC__Exception__c(
                    skedHC__Job__c = jobId,
                    sked_Conflicted_Job__c = conflictedAllocation.sked__Job__c,
                    skedHC__Job_Allocation__c = jobAllocationId,
                    sked_Conflicted_Job_Allocation__c = conflictedAllocation.Id,
                    sked_Drive__c = driveId,
                    sked_Conflicted_Drive__c = conflictedAllocation.sked__Job__r.sked_Drive__c,
                    skedHC__Resource__c = conflictedAllocation.sked__Resource__c,
                    sked_Exception_Code__c = unavailability.exceptionCode,
                    skedHC__Status__c = skedConstants.EXCEPTION_LOG_STATUS_OPEN
                );
                if (!string.isBlank(unavailability.exceptionText)) {
                    newExceptionLog.skedHC__Exception__c = 'Conflict with ' + conflictedAllocation.Name;
                }

                if (!string.isBlank(unavailability.relatedEventFieldApi)) { 
                    newExceptionLog.put(unavailability.relatedEventFieldApi, unavailability.recordId);
                }
                newExceptionLogs.add(newExceptionLog);
            }
        }
        if (!newExceptionLogs.isEmpty()) {
            insert newExceptionLogs;
        }
        
        return newExceptionLogs;
    }
    
    public void removeExceptionLogs(Set<Id> relatedRecordIds) {
        Id firstRecordId;
        for (Id relatedRecordId : relatedRecordIds) {
            firstRecordId = relatedRecordId;
            break;
        }
        string relatedObjApiName = firstRecordId.getSobjectType().getDescribe().getName();
        string relatedFieldApi;
        if (relatedObjApiName == sked__Availability__c.getSobjectType().getDescribe().getName()) {
            relatedFieldApi = 'skedHC__Availability__c';
        }
        else if (relatedObjApiName == sked__Activity__c.getSobjectType().getDescribe().getName()) {
            relatedFieldApi = 'skedHC__Activity__c';
        }
        else if (relatedObjApiName == sked__Job_Allocation__c.getSobjectType().getDescribe().getName()) {
            relatedFieldApi = 'skedHC__Job_Allocation__c';
        }
        queryModel query = new queryModel();
        skedQueryBuilder queryBuilder = query.getQueryBuilder('skedHC__Exception__c');
        string recordIdsCondition = queryBuilder.generateCondition(relatedFieldApi + ' IN {0}', relatedRecordIds);
        if (relatedObjApiName == sked__Job_Allocation__c.getSobjectType().getDescribe().getName()) {
            string subCondition1 = queryBuilder.generateCondition('skedHC__Job_Allocation__c IN {0}', relatedRecordIds);
            string subCondition2 = queryBuilder.generateCondition('sked_Conflicted_Job_Allocation__c IN {0}', relatedRecordIds);
            recordIdsCondition = '(' + subCondition1 + ' OR ' + subCondition2 + ')';
        }
        queryBuilder.addCondition(recordIdsCondition);
        queryBuilder.addCondition('skedHC__Status__c != {0}', skedConstants.EXCEPTION_LOG_STATUS_CLOSED);
        List<sObject> records = query(query);
        if (!records.isEmpty()) {
            for (sObject record : records) {
                record.put('skedHC__Status__c', skedConstants.EXCEPTION_LOG_STATUS_CLOSED);
            }
            update records;
        }
    }
    
    public void removeExceptionLogsWhenCancellingJobs(Set<Id> jobIds) {
        List<skedHC__Exception__c> skedExceptionLogs = [SELECT Id, skedHC__Status__c
                                                        FROM skedHC__Exception__c
                                                        WHERE (skedHC__Job__c IN :jobIds OR sked_Conflicted_Job__c IN :jobIds)
                                                        AND skedHC__Status__c = :skedConstants.EXCEPTION_LOG_STATUS_OPEN];
        if (!skedExceptionLogs.isEmpty()) {
            for (skedHC__Exception__c skedExceptionLog : skedExceptionLogs) {
                skedExceptionLog.skedHC__Status__c = skedConstants.EXCEPTION_LOG_STATUS_CLOSED;
            }
            update skedExceptionLogs;
        }
    }
    
    /*********************************************************** Private methods ***********************************************************/
    private List<sked__Job_Allocation__c> getConflictedAllocations(Set<Id> resourceIds, DateTime startTime, DateTime endTime, Set<Id> excludedIds) {
        skedQueryBuilder jobAllocationBuilder = new skedQueryBuilder();
        jobAllocationBuilder.setFromClause('sked__Job_Allocation__c');
        jobAllocationBuilder.addField('Id');
        jobAllocationBuilder.addField('Name');
        jobAllocationBuilder.addField('sked__Job__c');
        jobAllocationBuilder.addField('sked__Resource__c');
        jobAllocationBuilder.addField('sked__Start__c');
        jobAllocationBuilder.addField('sked__Set_End__c');
        jobAllocationBuilder.addField('sked__Job__r.sked__Type__c');
        jobAllocationBuilder.addField('sked__Job__r.sked_Drive__c');
        
        jobAllocationBuilder.addCondition('sked__Resource__c IN {0}', resourceIds);
        if (startTime != NULL && endTime != NULL) {
            jobAllocationBuilder.addCondition('sked__Start__c < {0}', endTime);
            jobAllocationBuilder.addCondition('sked__Set_End__c > {0}', startTime);
        }
        else if (startTime != NULL) {
            jobAllocationBuilder.addCondition('sked__Start__c >= {0}', startTime);			
        }
        List<string> jobAllocationDeletedStatuses = new List<string>();
        jobAllocationDeletedStatuses.add(skedConstants.JOB_ALLOCATION_STATUS_DELETED);
        jobAllocationDeletedStatuses.add(skedConstants.JOB_ALLOCATION_STATUS_DECLINED);
        jobAllocationBuilder.addCondition('sked__Status__c NOT IN {0}', jobAllocationDeletedStatuses);
        if (excludedIds != NULL && !excludedIds.isEmpty()) {
            jobAllocationBuilder.addCondition('Id NOT IN {0}', excludedIds);
        }
        jobAllocationBuilder.orderClause = 'ORDER BY sked__Start__c ASC';
        
        string queryString = jobAllocationBuilder.toString();
        system.debug('#queryString#' + queryString);
        return (List<sked__Job_Allocation__c>)Database.query(queryString);
    }
    
    /*********************************************************** Nested classes ***********************************************************/
    public class resourceUnavailabilityModel {
        public string resourceId;
        public string relatedEventFieldApi;
        public string recordId;
        public DateTime startTime;
        public DateTime endTime;
        public string exceptionCode;
        public string exceptionText;
        public string jobId;
        public string jobAllocationId;
        public string driveId;
    }

    global class queryModel extends skedDataService.queryModelBase {}
    
}