unpackaged/main/default/objects/BSF_Custom_Notification__c/BSF_Custom_Notification__c.object-meta.xml
<CustomObject>
    <description>Object to store custom notifications data to be processed by an asynchronous process.</description>
    <label>BSF Custom Notification</label>
    <nameField>
        <displayFormat>CNN-{0000000000}</displayFormat>
        <label>BSF Custom Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSF Custom Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Final body text of the notification</description>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BSF_Custom_Notification__c/fields/BSF_Custom_Notification__c.field-meta.xml
<CustomField>
    <fullName>BSF_Custom_Notification__c</fullName>
    <label>Notification Type(Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SalesforcePush</fullName>
            </value>
            <value>
                <fullName>Oneoff</fullName>
            </value>
            <value>
                <fullName>CustomSMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Functional Type of the Notification Being Sent. The Purpose of this to club notifications being sent.</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Custom_Notification_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Custom_Notification_Type_Id__c</fullName>
    <description>This field is used by Salesforce push</description>
    <label>Custom Notification Type Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Destination_Email__c.field-meta.xml
<CustomField>
    <fullName>Destination_Email__c</fullName>
    <description>This field is populated for email notifications</description>
    <label>Destination Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BSF_Custom_Notification__c/fields/Destination_Id__c.field-meta.xml
<CustomField>
    <fullName>Destination_Id__c</fullName>
    <description>This is populated for all notification types.
Email: User, Contact, Lead record Id
Oneoff: Resource Id
CustomSMS: phone number
SalesforcePush: User Id</description>
    <label>Destination Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Template__c</fullName>
    <description>This field is populated for email notifications. This is the id value of email template.</description>
    <label>Email Template</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BSF_Custom_Notification__c/fields/Expiry_TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>Expiry_TimeStamp__c</fullName>
    <label>Expiry TimeStamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SalesforcePush</fullName>
            </value>
            <value>
                <fullName>Oneoff</fullName>
            </value>
            <value>
                <fullName>CustomSMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority of the Notification of all the records which has the same 
Proposed Time. It should be looked it at a system as a whole. Default value/LOW priority is 10,000 and high priority is 1 , medium is 5000</description>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Scheduled_TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_TimeStamp__c</fullName>
    <label>Scheduled TimeStamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Sender_Email__c.field-meta.xml
<CustomField>
    <fullName>Sender_Email__c</fullName>
    <description>This field is populated for email notifications</description>
    <label>Sender Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/BSF_Custom_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Completed with Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This field is populated for Email and Salesforce Push (Bell) notifications.</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BSF_Custom_Notification__c/fields/Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Id__c</fullName>
    <description>This field is used by Salesforce push</description>
    <label>Target Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BSF_Error_Log__c/BSF_Error_Log__c.object-meta.xml
<CustomObject>
    <label>BSF Error Log</label>
    <nameField>
        <displayFormat>BEL-{0000000000}</displayFormat>
        <label>BSF Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSF Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BSF_General_Notification.cls
public class BSF_General_Notification {
    public static List<BSF_Custom_Notification__c> getBellNotificationRecord(Id notificationTypeId, Set<String> recipientIds, String notificationTitle, 
                                                                        String notificationBody, Id targetId, Integer priority, String category, DateTime notificationExpiry){
        List<BSF_Custom_Notification__c> notificationList = new List<BSF_Custom_Notification__c>();
        if(notificationTypeId == null || recipientIds == null || recipientIds.isEmpty() || targetId == null || priority == null 
                || String.isBlank(category) || String.isBlank(notificationTitle) || String.isBlank(notificationBody)){
                    throw new BSF_General_Notification_Exception('Missing required fields.');
        }
        for(String recipientId : recipientIds){
            BSF_Custom_Notification__c notfRec = new BSF_Custom_Notification__c();
            notfRec.Notification_Type__c = 'SalesforcePush';
            notfRec.Status__c = 'Queued';
            notfRec.Category__c = category;
            notfRec.Custom_Notification_Type_Id__c = notificationTypeId;
            notfRec.Subject__c = notificationTitle;
            notfRec.Body__c = notificationBody;
            notfRec.Target_Record_Id__c = targetId;
            notfRec.Destination_Id__c = recipientId;
            notfRec.Priority__c = priority;
            notfRec.Scheduled_TimeStamp__c = System.now();
            notfRec.Expiry_TimeStamp__c = notificationExpiry;
            notificationList.add(notfRec);
        }
        return notificationList;
    }
    public static List<BSF_Custom_Notification__c> getEmailNotificationRecord(List<Messaging.SingleEmailMessage> emailList, String notificationKey, 
                                                                                Integer priority, DateTime emailExpiry) {
        List<BSF_Custom_Notification__c> notificationList = new List<BSF_Custom_Notification__c>();
        Map<Id,String> OrgWideEmailMap = new Map<Id,String>();
        if(emailList == null || emailList.isEmpty() || priority == null || String.isBlank(notificationKey)){
            throw new BSF_General_Notification_Exception('Missing required fields.');
        }
        for(OrgWideEmailAddress owea : [select Id, Address from OrgWideEmailAddress]){
            OrgWideEmailMap.put(owea.Id,owea.Address);
        }
        for(Messaging.SingleEmailMessage message : emailList){
            BSF_Custom_Notification__c emailRec = new BSF_Custom_Notification__c();
            emailRec.Notification_Type__c = 'Email';
            emailRec.Status__c = 'Queued';
            emailRec.Category__c = notificationKey;
            emailRec.Priority__c = priority;
            emailRec.Expiry_TimeStamp__c = emailExpiry;
            emailRec.Scheduled_TimeStamp__c = System.now();
            if(message.getTemplateId() != null){
                Messaging.SingleEmailMessage tempMessage = Messaging.renderStoredEmailTemplate(message.getTemplateId(),null,message.getTargetObjectId());
                emailRec.Email_Template__c = message.getTemplateId();
                emailRec.Subject__c = tempMessage.getSubject();
                emailRec.Body__c = tempMessage.getHtmlBody() == null ? tempMessage.getPlainTextBody() : tempMessage.getHtmlBody();
            }else{
                emailRec.Subject__c = message.getSubject();
                emailRec.Body__c = message.getHtmlBody() == null ? message.getPlainTextBody() : message.getHtmlBody();
            }
            if(message.treatTargetObjectAsRecipient == true){
                emailRec.Destination_Id__c = message.getTargetObjectId();
            }
            if(message.getOrgWideEmailAddressId() != null && OrgWideEmailMap.containsKey(message.getOrgWideEmailAddressId())){
                emailRec.Sender_Email__c = OrgWideEmailMap.get(message.getOrgWideEmailAddressId());
            }else{
                emailRec.Sender_Email__c = UserInfo.getUserEmail();
            }

            List<String> emailToAddresses = new List<String>();
            if(message.toAddresses != null){
                emailToAddresses.addAll(message.toAddresses);
            }
            if(message.ccAddresses != null){
                emailToAddresses.addAll(message.toAddresses);
            }
            if(message.bccAddresses != null){
                emailToAddresses.addAll(message.toAddresses);
            }
            
            if(emailToAddresses.isEmpty() || (emailToAddresses.size() == 1)){
                emailRec.Destination_Email__c = (!emailToAddresses.isEmpty()) ? emailToAddresses.get(0) : null;
                notificationList.add(emailRec);
            }else if(emailToAddresses.size() > 1){
                for(String destinationEmail : emailToAddresses){
                    BSF_Custom_Notification__c emailRecCloned = emailRec.clone();
                    emailRecCloned.Id = null;
                    emailRecCloned.Destination_Email__c = destinationEmail;
                    notificationList.add(emailRecCloned);
                }
            }
        }
        return notificationList;
    }
    public static void insertNotificationRecord(List<BSF_Custom_Notification__c> notfRecList){
        System.debug('Entering BSF_General_Notification.insertNotificationRecord==>'+notfRecList);
        if(notfRecList == null || notfRecList.isEmpty()){
            return;
        }
        if(Limits.getDMLStatements() < Limits.getLimitDMLStatements()){
            String errMsg = '';
            Database.SaveResult[] srList;
            try{
                srList = Database.insert(notfRecList, false);
            }catch(Exception ex){
                errMsg = errMsg + ex.getMessage();
            }
            if(srList != null){
                for (Integer i=0; i < srList.size(); i++){
                    if(!srList.get(i).isSuccess()) {
                        for(Database.Error err : srList.get(i).getErrors()) {
                            errMsg = errMsg + err.getMessage();
                            System.debug('errMsg==> '+errMsg);
                        }
                    }
                }
            }
            if(String.isNotBlank(errMsg)){
                BSF_Error_Log__c err = BSF_Utilities.getErrorLog(null,'BSF_General_Notification','insertNotificationRecord()','Error','Error Creating notification Record',errMsg);
                try{
                    insert err;
                }catch(Exception excptn){
                    System.debug(excptn.getMessage()+excptn.getStackTraceString()+excptn.getLineNumber());
                }
            }
        }else{
            System.debug('Too many DML statements.');
        }
    }
    public class BSF_General_Notification_Exception extends Exception{}
}