force-app/main/default/objects/Activity/fields/sked__Activity__c.field-meta.xml
<CustomField>
    <fullName>sked__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/Biomed_Collection_Op_Center__c.object-meta.xml
<CustomObject>
    <label>Collection Operation</label>
    <nameField>
        <label>Collection Operations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Biomed_Collection_Op_Center__c/fields/sked_Territory__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipName>sked_Biomed_Collection_Ops_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collection_Operation_Time_Block__c/Collection_Operation_Time_Block__c.object-meta.xml
<CustomObject>
    <label>Collection Operation Time Block</label>
    <nameField>
        <displayFormat>COTB-{00000000}</displayFormat>
        <label>CO Time Block ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Operation Time Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Operation_Time_Block__c/fields/Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>Collection_Operation__c</fullName>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Collection Operation Time Blocks</relationshipLabel>
    <relationshipName>Collection_Operation_Time_Blocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collection_Operation_Time_Block__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_Week</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collection_Operation_Time_Block__c/fields/Time_Block__c.field-meta.xml
<CustomField>
    <fullName>Time_Block__c</fullName>
    <label>Time Block</label>
    <referenceTo>Time_Block__c</referenceTo>
    <relationshipLabel>Collection Operation Time Blocks</relationshipLabel>
    <relationshipName>Collection_Operation_Time_Blocks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/sked__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked__Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked__Timezone__c</fullName>
    <label>Timezone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>sked_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Time_Block__c.field-meta.xml
<CustomField>
    <fullName>sked_Time_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Time Block</label>
    <referenceTo>Time_Block__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>sked_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/sked__Activity_Resource__c.object-meta.xml
<CustomObject>
    <description>Allows multiple resources to be attached to an activity</description>
    <label>Activity Resource</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Activity Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked__Activity__c.field-meta.xml
<CustomField>
    <fullName>sked__Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Activity Resources</relationshipLabel>
    <relationshipName>Activity_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activity Resources</relationshipLabel>
    <relationshipName>Activity_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <formula>sked__Resource__r.sked__Primary_Region__r.sked__Timezone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked__Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked__Timezone__c</fullName>
    <inlineHelpText>i.e. &quot;Australia/Brisbane&quot;.</inlineHelpText>
    <label>Timezone</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/fields/sked_Biomed_Collection_Op_Center__c.field-meta.xml
<CustomField>
    <fullName>sked_Biomed_Collection_Op_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biomed Collection Op (Center)</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Collection Operations Timezones (Skedulo Regions)</relationshipLabel>
    <relationshipName>sked_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/fields/sked_Territory__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>sked_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Category__c.field-meta.xml
<CustomField>
    <fullName>sked__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked__Resource_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Cargo Van</fullName>
            </value>
            <value>
                <fullName>ProMaster</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Email__c.field-meta.xml
<CustomField>
    <fullName>sked__Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>sked__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Primary_Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Primary_Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked__Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource_Type__c</fullName>
    <description>Is the resource a human or otherwise</description>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>sked_Employee_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Workday External ID</inlineHelpText>
    <label>Employee ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_First_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Preferred_First_Name__c.field-meta.xml
<CustomField>
    <fullName>sked_Preferred_First_Name__c</fullName>
    <label>Preferred First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <label>Region Timezone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_Title__c.field-meta.xml
<CustomField>
    <fullName>sked_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/fields/sked_ULID__c.field-meta.xml
<CustomField>
    <fullName>sked_ULID__c</fullName>
    <externalId>true</externalId>
    <label>ULID (A #)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/sked_Territory__c/sked_Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Territory__c/fields/sked_Parent__c.field-meta.xml
<CustomField>
    <fullName>sked_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>sked_Territory__c</referenceTo>
    <relationshipName>sked_Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Block__c/Time_Block__c.object-meta.xml
<CustomObject>
    <label>Time Block</label>
    <nameField>
        <label>Time Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Block__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_Week</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Block__c/fields/Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_End_Date__c</fullName>
    <label>Effective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Block__c/fields/Effective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Start_Date__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Days_of_Week.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Days of Week</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BSF_Batch_ActivityTimeBlock_Test.cls
@IsTest
public class BSF_Batch_ActivityTimeBlock_Test {

    @testSetup
    static void setupData() {
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<String, SObject> testData = testDataSetup.createAndInsertCommonObjects();

        Biomed_Collection_Op_Center__c co = (Biomed_Collection_Op_Center__c) testData.get('COLLECTION_OPP');
        co.External_Id__c = 'TEST-ACT-CO-1';
        insert co;

        Biomed_Collection_Op_Center__c co2 = co.clone(false, true, false, false);
        co2.Name = 'Activity Collection Operation 2';
        co2.External_Id__c = 'TEST-ACT-CO-2';
        insert co2;
    }

    @isTest
    static void testExactMatch_AssignsTimeBlock() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Exact',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = activityDate.addDays(-1),
            Effective_End_Date__c = activityDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(tb.Id, act.sked_Time_Block__c, 'An activity whose start/end exactly matches a time block should be assigned to it.');
    }

    @isTest
    static void testFitsWithinWiderTimeBlock_AssignsTimeBlock() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Full Day',
            Start_Time__c = Time.newInstance(7, 0, 0, 0),
            End_Time__c = Time.newInstance(17, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = activityDate.addDays(-1),
            Effective_End_Date__c = activityDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(tb.Id, act.sked_Time_Block__c, 'An activity fully contained within a wider time block should be assigned to it, even without matching its start/end exactly.');
    }

    @isTest
    static void testExtendsBeyondTimeBlock_LeavesTimeBlockBlank() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Morning',
            Start_Time__c = Time.newInstance(9, 0, 0, 0),
            End_Time__c = Time.newInstance(12, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = activityDate.addDays(-1),
            Effective_End_Date__c = activityDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(13, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'An activity extending beyond its only applicable time block on both ends should be left unassigned.');
    }

    @isTest
    static void testNoApplicableTimeBlock_LeavesActivityUnchanged() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'With no Collection Operation Time Block configured, no assignment should occur.');
    }

    @isTest
    static void testFitsMultipleTimeBlocks_LeavesBlank() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tbOne = new Time_Block__c(
            Name = 'TB Narrow',
            Start_Time__c = Time.newInstance(7, 0, 0, 0),
            End_Time__c = Time.newInstance(17, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        Time_Block__c tbTwo = new Time_Block__c(
            Name = 'TB Wide',
            Start_Time__c = Time.newInstance(6, 0, 0, 0),
            End_Time__c = Time.newInstance(18, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert new List<Time_Block__c>{ tbOne, tbTwo };

        insert new List<Collection_Operation_Time_Block__c>{
            new Collection_Operation_Time_Block__c(
                Collection_Operation__c = coId,
                Time_Block__c = tbOne.Id,
                Effective_Start_Date__c = activityDate.addDays(-1),
                Effective_End_Date__c = activityDate.addDays(1)
            ),
            new Collection_Operation_Time_Block__c(
                Collection_Operation__c = coId,
                Time_Block__c = tbTwo.Id,
                Effective_Start_Date__c = activityDate.addDays(-1),
                Effective_End_Date__c = activityDate.addDays(1)
            )
        };

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'When an activity fits inside more than one time block, the assignment is ambiguous and should be left blank.');
    }

    @isTest
    static void testActivityWithResourceAssignment_ExcludedFromProcessing() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Resourced',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = activityDate.addDays(-1),
            Effective_End_Date__c = activityDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Id resourceId = createTestResource(coId);

        skedHubBase.BypassInsertTriggers = true;
        insert new sked__Activity_Resource__c(
            sked__Activity__c = act.Id,
            sked__Resource__c = resourceId
        );
        skedHubBase.BypassInsertTriggers = false;

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'An activity that already has a resource assignment should never be touched by the batch, even with an exact-matching time block available.');
    }

    @isTest
    static void testAlreadyHasTimeBlock_NotProcessedByBatch() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c originalTb = new Time_Block__c(
            Name = 'TB Original',
            Start_Time__c = Time.newInstance(6, 0, 0, 0),
            End_Time__c = Time.newInstance(12, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        Time_Block__c newExactTb = new Time_Block__c(
            Name = 'TB New Exact',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert new List<Time_Block__c>{ originalTb, newExactTb };

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = newExactTb.Id,
            Effective_Start_Date__c = activityDate.addDays(-1),
            Effective_End_Date__c = activityDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        act.sked_Time_Block__c = originalTb.Id;
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(originalTb.Id, act.sked_Time_Block__c, 'An activity that already has a time block assigned should not be reprocessed by the batch.');
    }

    @isTest
    static void testWrongDayOfWeek_LeavesActivityUnchanged() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();
        String otherDay = dayName == 'Monday' ? 'Tuesday' : 'Monday';

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Other Day',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = otherDay
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = activityDate.addDays(-1),
            Effective_End_Date__c = activityDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'A time block that does not apply to the activity day of week should not be assigned.');
    }

    @isTest
    static void testOutsideEffectiveDateRange_LeavesActivityUnchanged() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Expired',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = activityDate.addDays(-30),
            Effective_End_Date__c = activityDate.addDays(-10)
        );

        sked__Activity__c act = buildActivity(coId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'A time block whose effective date range does not cover the activity date should not be assigned.');
    }

    @isTest
    static void testConstructorScopesToProvidedCollectionOperationIds() {
        Id inScopeCoId = collectionOperationId('TEST-ACT-CO-1');
        Id outOfScopeCoId = collectionOperationId('TEST-ACT-CO-2');
        Date activityDate = sharedActivityDate();
        String dayName = sharedDayOfWeek();

        Time_Block__c tbInScope = new Time_Block__c(
            Name = 'TB CO1',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        Time_Block__c tbOutOfScope = new Time_Block__c(
            Name = 'TB CO2',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert new List<Time_Block__c>{ tbInScope, tbOutOfScope };

        insert new List<Collection_Operation_Time_Block__c>{
            new Collection_Operation_Time_Block__c(
                Collection_Operation__c = inScopeCoId,
                Time_Block__c = tbInScope.Id,
                Effective_Start_Date__c = activityDate.addDays(-1),
                Effective_End_Date__c = activityDate.addDays(1)
            ),
            new Collection_Operation_Time_Block__c(
                Collection_Operation__c = outOfScopeCoId,
                Time_Block__c = tbOutOfScope.Id,
                Effective_Start_Date__c = activityDate.addDays(-1),
                Effective_End_Date__c = activityDate.addDays(1)
            )
        };

        sked__Activity__c inScopeAct = buildActivity(inScopeCoId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        sked__Activity__c outOfScopeAct = buildActivity(outOfScopeCoId, activityDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivities(new List<sked__Activity__c>{ inScopeAct, outOfScopeAct });

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(new Set<Id>{ inScopeCoId }), 200);
        Test.stopTest();

        inScopeAct = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :inScopeAct.Id];
        outOfScopeAct = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :outOfScopeAct.Id];

        System.assertEquals(tbInScope.Id, inScopeAct.sked_Time_Block__c, 'Activity under the scoped Collection Operation should be processed.');
        System.assertEquals(null, outOfScopeAct.sked_Time_Block__c, 'Activity under a Collection Operation outside the provided scope should be left untouched.');
    }

    @isTest
    static void testPastStartDate_ExcludedFromProcessing() {
        Id coId = collectionOperationId('TEST-ACT-CO-1');
        Date pastDate = Date.today().addDays(-1);
        String dayName = DateTime.newInstance(pastDate, Time.newInstance(0, 0, 0, 0)).format('EEEE');

        Time_Block__c tb = new Time_Block__c(
            Name = 'TB Past',
            Start_Time__c = Time.newInstance(8, 0, 0, 0),
            End_Time__c = Time.newInstance(10, 0, 0, 0),
            Days_of_Week__c = dayName
        );
        insert tb;

        insert new Collection_Operation_Time_Block__c(
            Collection_Operation__c = coId,
            Time_Block__c = tb.Id,
            Effective_Start_Date__c = pastDate.addDays(-1),
            Effective_End_Date__c = pastDate.addDays(1)
        );

        sked__Activity__c act = buildActivity(coId, pastDate, dayName, Time.newInstance(8, 0, 0, 0), Time.newInstance(10, 0, 0, 0));
        insertActivity(act);

        Test.startTest();
        Database.executeBatch(new BSF_Batch_ActivityTimeBlockAssignment(), 200);
        Test.stopTest();

        act = [SELECT sked_Time_Block__c FROM sked__Activity__c WHERE Id = :act.Id];
        System.assertEquals(null, act.sked_Time_Block__c, 'An activity dated in the past should not be picked up by the batch at all.');
    }

    private static Id createTestResource(Id coId) {
        Map<String, Schema.RecordTypeInfo> territoryRecordTypes = Schema.SObjectType.sked_Territory__c.getRecordTypeInfosByName();

        sked_Territory__c division = new sked_Territory__c(
            RecordTypeId = territoryRecordTypes.get('Division').getRecordTypeId(),
            Name = 'ATB Test Division',
            Start_Date__c = Date.today().addDays(-500),
            End_Date__c = Date.today().addDays(500)
        );
        TriggerHandler.bypass('TerritoryTriggerHandler');
        insert division;

        sked_Territory__c region = new sked_Territory__c(
            RecordTypeId = territoryRecordTypes.get('ARC Region').getRecordTypeId(),
            Name = 'ATB Test ARC Region',
            Start_Date__c = Date.today().addDays(-500),
            End_Date__c = Date.today().addDays(500),
            sked_Parent__c = division.Id
        );
        TriggerHandler.bypass('TerritoryTriggerHandler');
        insert region;

        sked_Territory__c district = new sked_Territory__c(
            RecordTypeId = territoryRecordTypes.get('District').getRecordTypeId(),
            Name = 'ATB Test District',
            Start_Date__c = Date.today().addDays(-500),
            End_Date__c = Date.today().addDays(500),
            sked_Parent__c = region.Id
        );
        TriggerHandler.bypass('TerritoryTriggerHandler');
        insert district;

        sked__Region__c skedRegion = new sked__Region__c(
            Name = 'ATB Test Region',
            sked__Timezone__c = UserInfo.getTimeZone().getID(),
            sked_Biomed_Collection_Op_Center__c = coId,
            sked_Territory__c = district.Id
        );
        insert skedRegion;

        Id staffRecordTypeId = Schema.SObjectType.sked__Resource__c.getRecordTypeInfosByName().get('Staff').getRecordTypeId();
        sked__Resource__c resource = new sked__Resource__c(
            RecordTypeId = staffRecordTypeId,
            sked__Email__c = 'atbtestresource@example.com',
            sked_Employee_ID__c = 'ATB-TEST-001',
            sked__Is_Active__c = true,
            sked_Title__c = 'Test',
            sked_First_Name__c = 'ATB',
            sked_Preferred_First_Name__c = 'ATB',
            sked_Last_Name__c = 'TestResource',
            sked_ULID__c = 'ATB-ULID-001',
            sked__Category__c = 'Employee',
            sked_Employment_Status__c = 'Active',
            sked_Timezone__c = 'America/Los_Angeles',
            sked__Resource_Type__c = 'Person',
            sked__Primary_Region__c = skedRegion.Id
        );

        skedHubBase.BypassInsertTriggers = true;
        skedHubBase.BypassUpdateTriggers = true;
        TriggerHandler.bypass('ResourceTriggerHandler');
        insert resource;
        skedHubBase.BypassInsertTriggers = false;
        skedHubBase.BypassUpdateTriggers = false;

        return resource.Id;
    }

    private static void insertActivity(sked__Activity__c act) {
        insertActivities(new List<sked__Activity__c>{ act });
    }

    private static void insertActivities(List<sked__Activity__c> acts) {
        skedHubBase.BypassInsertTriggers = true;
        insert acts;
        skedHubBase.BypassInsertTriggers = false;
    }

    private static sked__Activity__c buildActivity(Id coId, Date activityDate, String dayName, Time startTime, Time endTime) {
        return new sked__Activity__c(
            sked_Collection_Operation__c = coId,
            sked_Start_Date__c = activityDate,
            sked_Day_of_Week__c = dayName,
            sked_Start_Time__c = startTime,
            sked_End_Time__c = endTime,
            sked__Start__c = DateTime.newInstance(activityDate, startTime),
            sked__End__c = DateTime.newInstance(activityDate, endTime)
        );
    }

    private static Id collectionOperationId(String externalId) {
        return [SELECT Id FROM Biomed_Collection_Op_Center__c WHERE External_Id__c = :externalId LIMIT 1].Id;
    }

    private static Date sharedActivityDate() {
        return Date.today().addDays(14);
    }

    private static String sharedDayOfWeek() {
        return DateTime.newInstance(sharedActivityDate(), Time.newInstance(0, 0, 0, 0)).format('EEEE');
    }
}