force-app/main/default/objects/Activity/fields/sked__Activity__c.field-meta.xml
<CustomField>
    <fullName>sked__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity/fields/sked__Job_Allocation__c.field-meta.xml
<CustomField>
    <fullName>sked__Job_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Allocation</label>
    <referenceTo>sked__Job_Allocation__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/sked__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked__Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked__Timezone__c</fullName>
    <label>Timezone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Duration__c.field-meta.xml
<CustomField>
    <fullName>sked_Duration__c</fullName>
    <formula>ROUND(((sked__End__c - sked__Start__c) * 1440),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Is_Group_Activity__c.field-meta.xml
<CustomField>
    <fullName>sked_Is_Group_Activity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Group Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/sked__Activity_Resource__c.object-meta.xml
<CustomObject>
    <description>Allows multiple resources to be attached to an activity</description>
    <label>Activity Resource</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Activity Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked__Activity__c.field-meta.xml
<CustomField>
    <fullName>sked__Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Activity Resources</relationshipLabel>
    <relationshipName>Activity_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activity Resources</relationshipLabel>
    <relationshipName>Activity_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked_Duration__c.field-meta.xml
<CustomField>
    <fullName>sked_Duration__c</fullName>
    <formula>ROUND(((sked_End__c - sked_Start1__c) * 1440),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked_Start1__c.field-meta.xml
<CustomField>
    <fullName>sked_Start1__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Timezone__c</fullName>
    <formula>sked__Resource__r.sked__Primary_Region__r.sked__Timezone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/sked__Availability__c.object-meta.xml
<CustomObject>
    <description>Exceptions to the standard availability template for this user</description>
    <label>Availability</label>
    <nameField>
        <displayFormat>AVAIL-{0000}</displayFormat>
        <label>Availability Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Availability__c/fields/sked__Is_Available__c.field-meta.xml
<CustomField>
    <fullName>sked__Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, the resources is available for work, if not checked, they are are unavailable</inlineHelpText>
    <label>Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Availabilities1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked__Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked__Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked__Timezone__c</fullName>
    <label>Timezone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Custom_Status__c.field-meta.xml
<CustomField>
    <fullName>sked_Custom_Status__c</fullName>
    <label>Custom Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Expired</fullName>
                <label>Pending - Expired</label>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
                <label>Waitlist - Expired</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved From Waitlist</fullName>
            </value>
            <value>
                <fullName>Approved From Pending</fullName>
            </value>
            <value>
                <fullName>Processing Approval</fullName>
            </value>
            <value>
                <fullName>Processing Adjustment</fullName>
            </value>
            <value>
                <fullName>Processing Cancellation</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
                <isActive>false</isActive>
                <label>Processing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Availability__c/fields/sked_Duration__c.field-meta.xml
<CustomField>
    <fullName>sked_Duration__c</fullName>
    <formula>ROUND(((sked__Finish__c - sked__Start__c) * 1440),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/sked__Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job__c/fields/sked__Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked__Timezone__c</fullName>
    <formula>sked__Region__r.sked__Timezone__c</formula>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/sked__Job_Allocation__c.object-meta.xml
<CustomObject>
    <label>Job Allocation</label>
    <nameField>
        <displayFormat>JA-{0}</displayFormat>
        <label>Job Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Job__c.field-meta.xml
<CustomField>
    <fullName>sked__Job__c</fullName>
    <label>Job</label>
    <referenceTo>sked__Job__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Job Allocations</relationshipLabel>
    <relationshipName>Job_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Start__c.field-meta.xml
<CustomField>
    <fullName>sked__Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked__Status__c.field-meta.xml
<CustomField>
    <fullName>sked__Status__c</fullName>
    <description>Internal Skedulo use only. Do not modify the default Picklist values.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Dispatch</fullName>
                <default>true</default>
                <label>Pending Dispatch</label>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Duration_with_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>sked_Duration_with_Travel_Time__c</fullName>
    <formula>sked__Duration__c +  sked__Estimated_Travel_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration with Travel Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sked__Job_Allocation__c/fields/sked_Job_Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked_Job_Timezone__c</fullName>
    <formula>sked__Job__r.sked__Timezone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked__Timezone__c.field-meta.xml
<CustomField>
    <fullName>sked__Timezone__c</fullName>
    <inlineHelpText>i.e. &quot;Australia/Brisbane&quot;.</inlineHelpText>
    <label>Timezone</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Primary_Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Primary_Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/skedSyncResourceHoursOneTime_Batch.cls
global class skedSyncResourceHoursOneTime_Batch implements Database.Batchable<sObject>, Database.Stateful {
    protected List<String> modes = new List<String>{'JobAllocation', 'Availability', 'Activity', 'ActivityResource'};
    protected String mode = '';
    protected Integer modeIndex;
    protected String lastId = '';

    global skedSyncResourceHoursOneTime_Batch() {
        this.modeIndex = 0;
        this.mode = modes.get(0);
        this.lastId = '';
    }

    global skedSyncResourceHoursOneTime_Batch(Integer modeIndex) {
        this.modeIndex = modeIndex;
        this.mode = modes.get(modeIndex);
        this.lastId = '';
    }

    global skedSyncResourceHoursOneTime_Batch(Integer modeIndex, String lastId) {
        this.modeIndex = modeIndex;
        this.mode = modes.get(modeIndex);
        this.lastId = lastId;
    }

    global List<sObject> start(Database.BatchableContext BC) {
        if (this.mode == 'JobAllocation') {
            return  getJobAllocations(false);
        } else if (this.mode == 'Availability') {
            return getAvailabilities(false);
        } else if (this.mode == 'Activity') { 
            return getActivities(false);
        } else {
            return getActivityResources(false);
        }
    }

    global void execute(Database.BatchableContext BC, List<sObject> records) {
        if (mode == 'JobAllocation') {
            List<sked__Job_Allocation__c> jobAllocations = (List<sked__Job_Allocation__c>)records;
            skedResourceHoursRecordUtils.syncToResourceHoursRecord(jobAllocations);
        }
        else if (mode == 'Availability') {
            List<sked__Availability__c> availabilities = (List<sked__Availability__c>)records;
            for (sked__Availability__c availability : availabilities) {
                if (string.isBlank(availability.sked__Timezone__c)) {
                    availability.sked__Timezone__c = availability.sked__Resource__r.sked__Primary_Region__r.sked__Timezone__c;
                }
            }
            if (!availabilities.isEmpty()) {
                skedResourceHoursRecordUtils.syncToResourceHoursRecord(availabilities);
            }
        }
        else if (mode == 'Activity') {
            List<sked__Activity__c> activities = (List<sked__Activity__c>)records;
            for (sked__Activity__c activity : activities) {
                if (string.isBlank(activity.sked__Timezone__c)) {
                    activity.sked__Timezone__c = activity.sked__Resource__r.sked__Primary_Region__r.sked__Timezone__c;
                }
            }
            if (!activities.isEmpty()) {
                skedResourceHoursRecordUtils.syncToResourceHoursRecord(activities);
            }
        }
        else if (mode == 'ActivityResource') {
            List<sked__Activity_Resource__c> activityResources = (List<sked__Activity_Resource__c>)records;
            skedResourceHoursRecordUtils.syncToResourceHoursRecord(activityResources);
        }

        this.lastId = records.get(records.size()-1).Id;
        System.debug('THIS LAST ID ::: ' + this.lastId);
    }
    
    global void finish(Database.BatchableContext BC) {
        List<SObject> remainingRecords;
        if (this.mode == 'JobAllocation') {
            System.debug('FINISH LAST ID :: ' + this.lastId);
            remainingRecords = getJobAllocations(true);
        } else if (this.mode == 'Availability') {
            remainingRecords = getAvailabilities(true);
        } else if (this.mode == 'Activity') { 
            remainingRecords = getActivities(true);
        } else {
            remainingRecords = getActivityResources(true);
        }

        if (!remainingRecords.isEmpty()) {
            Database.executeBatch(new skedSyncResourceHoursOneTime_Batch(this.modeIndex, this.lastId));
        } else if (this.modeIndex < (this.modes.size()-1)) {
            this.modeIndex++;
            Database.executeBatch(new skedSyncResourceHoursOneTime_Batch(this.modeIndex));
        }
    }

    // Utils
    private List<SObject> getJobAllocations(Boolean isLimitQuery) {
        String query = 'SELECT Id, sked_Duration_with_Travel_Time__c, sked__Start__c, sked_Job_Timezone__c, sked__Status__c, ' +
        ' sked__Resource__c, sked__Job__c' + 
        ' FROM sked__Job_Allocation__c' + 
        ' WHERE sked__Status__c != \'' + skedConstants.JOB_ALLOCATION_STATUS_DECLINED + '\'' +
        ' AND sked__Status__c != \'' + skedConstants.JOB_ALLOCATION_STATUS_DELETED + '\'';
                
        System.debug('GET JA :: LAST ID :: ' + this.lastId);
        query += this.lastId != '' ? ' AND Id > \'' + this.lastId + '\'' : '';
        query += ' ORDER BY Id ASC ';
        query += isLimitQuery ? 'LIMIT 1' : 'LIMIT 50000';

        System.debug('QUERY :: ' + query);
        return Database.query(query);
    }

    private List<SObject> getAvailabilities(Boolean isLimitQuery) {
        String query = 'SELECT Id, sked_Duration__c, sked__Start__c, sked__Timezone__c, sked_Custom_Status__c,' +
        ' sked__Resource__c, sked__Is_Available__c, sked__Resource__r.sked__Primary_Region__r.sked__Timezone__c ' +        
        ' FROM sked__Availability__c' +
        ' WHERE sked__Is_Available__c = FALSE' + 
        ' AND sked_Custom_Status__c =  \'' + skedConstants.AVAILABILITY_STATUS_APPROVED + '\'';
                
        query += this.lastId != '' ? ' AND Id > \'' + this.lastId + '\'' : '';
        query += ' ORDER BY Id ASC ';
        query += isLimitQuery ? 'LIMIT 1' : 'LIMIT 50000';
        return Database.query(query);
    }

    private List<SObject> getActivities(Boolean isLimitQuery) {
        String query = 'SELECT Id, sked_Duration__c, sked__Start__c, sked__Timezone__c,sked_Is_Group_Activity__c,' +
        ' sked__Resource__c, sked__Resource__r.sked__Primary_Region__r.sked__Timezone__c' +
        ' FROM sked__Activity__c' +
        ' WHERE sked_Is_Group_Activity__c = FALSE' + 
        ' AND sked__Resource__c != NULL';
        
        query += this.lastId != '' ? ' AND Id > \'' + this.lastId + '\'' : '';
        query += ' ORDER BY Id ASC ';
        query += isLimitQuery ? 'LIMIT 1' : 'LIMIT 50000';
        return Database.query(query);
    }

    private List<SObject> getActivityResources(Boolean isLimitQuery) {
        String query = 'SELECT Id, sked_Duration__c, sked_Start1__c, sked_Timezone__c, sked__Resource__c' +
        ' FROM sked__Activity_Resource__c';

        query += this.lastId != '' ? ' WHERE Id > \'' + this.lastId + '\'' : '';
        query += ' ORDER BY Id ASC ';
        query += isLimitQuery ? 'LIMIT 1' : 'LIMIT 50000';
        return Database.query(query);
    }
}