force-app/main/default/objects/Activity/fields/sked__Activity__c.field-meta.xml
<CustomField>
    <fullName>sked__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/sked__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity__c/fields/sked__End__c.field-meta.xml
<CustomField>
    <fullName>sked__End__c</fullName>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Blood Drive Support</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Logistics Support</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Special Events</fullName>
            </value>
            <value>
                <fullName>After Hours Call Out Management</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Travel To</fullName>
            </value>
            <value>
                <fullName>Travel Back</fullName>
            </value>
            <value>
                <fullName>On Call</fullName>
            </value>
            <value>
                <fullName>Overnight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Is_Group_Activity__c.field-meta.xml
<CustomField>
    <fullName>sked_Is_Group_Activity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Group Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Recurring_Schedule__c.field-meta.xml
<CustomField>
    <fullName>sked_Recurring_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Schedule</label>
    <referenceTo>sked__Recurring_Schedule__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>sked_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Region__c.field-meta.xml
<CustomField>
    <fullName>sked_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>sked_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Subtype__c.field-meta.xml
<CustomField>
    <fullName>sked_Subtype__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked__Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Culture Initiative</fullName>
            </value>
            <value>
                <fullName>In-Service</fullName>
            </value>
            <value>
                <fullName>Labor Relations</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Modified Duty</fullName>
            </value>
            <value>
                <fullName>National Bargaining</fullName>
            </value>
            <value>
                <fullName>Organizational Day</fullName>
            </value>
            <value>
                <fullName>Physicals</fullName>
            </value>
            <value>
                <fullName>Problem Management</fullName>
            </value>
            <value>
                <fullName>Post-Drive Breakdown</fullName>
            </value>
            <value>
                <fullName>Pre-Drive Setup</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Blood Run</fullName>
            </value>
            <value>
                <fullName>eBDR</fullName>
            </value>
            <value>
                <fullName>Inter-Region Support</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>ORC Beta</fullName>
            </value>
            <value>
                <fullName>After Hours Call Out Management</fullName>
            </value>
            <value>
                <fullName>Holiday Day Off</fullName>
            </value>
            <value>
                <fullName>Donor Outreach</fullName>
            </value>
            <value>
                <fullName>Health Fair</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Parade</fullName>
            </value>
            <value>
                <fullName>BHQ - Annual</fullName>
            </value>
            <value>
                <fullName>BHQ - BioArch R1</fullName>
            </value>
            <value>
                <fullName>BHQ - BioArch R2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Activity__c/fields/sked_Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>sked_Territory_Key__c</fullName>
    <formula>IF(
AND(
NOT(ISBLANK(sked_District__c)),
NOT(ISBLANK(sked_Collection_Operation__c))), CASESAFEID(sked_District__c) + &apos;:&apos; + CASESAFEID(sked_Collection_Operation__c), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/sked__Activity_Resource__c.object-meta.xml
<CustomObject>
    <description>Allows multiple resources to be attached to an activity</description>
    <label>Activity Resource</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Activity Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked__Activity__c.field-meta.xml
<CustomField>
    <fullName>sked__Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>sked__Activity__c</referenceTo>
    <relationshipLabel>Activity Resources</relationshipLabel>
    <relationshipName>Activity_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Activity_Resource__c/fields/sked__Resource__c.field-meta.xml
<CustomField>
    <fullName>sked__Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>sked__Resource__c</referenceTo>
    <relationshipLabel>Activity Resources</relationshipLabel>
    <relationshipName>Activity_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked_Biomed_Collection_Op_Center__c.field-meta.xml
<CustomField>
    <fullName>sked_Biomed_Collection_Op_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biomed Collection Op (Center)</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Collection Operations Timezones (Skedulo Regions)</relationshipLabel>
    <relationshipName>sked_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Resource__c/sked__Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Resource__c/fields/sked__Category__c.field-meta.xml
<CustomField>
    <fullName>sked__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>sked__Resource_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Cargo Van</fullName>
            </value>
            <value>
                <fullName>ProMaster</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/skedActivityService.cls
global class skedActivityService extends skedEventService {

    protected override void initialize() {
        this.sObjectApiName = 'sked__Activity__c';
        this.objectTYpe = 'activity';
        this.domainType = Type.forName('skedModels.activity');
    }

    protected override void doAdditionalMap(sObject sObj, skedModels.modelBase model) {
        sked__Activity__c skedActivity = (sked__Activity__c)sObj;
        skedModels.activity activity = (skedModels.activity)model;
        if (string.isBlank(activity.id)) {
            skedActivity.sked__Resource__c = activity.resourceId;
        }
	}

    public override saveResult saveRecurringSchedule(skedModels.recurringSchedule recurringSchedule) {
        saveResult result = new saveResult();
        if (recurringSchedule.events.size() > 200) {
            Database.executeBatch(new skedCreateBulkActivityBatch(recurringSchedule, UserInfo.getUserId(), 0));
            result.success = true;
            result.message = skedConstants.ACTIVITY_INSERT_BATCH_STARTED;
        } else {
            result = baseSaveRecurringSchedule(recurringSchedule);
        }

        return result;
    }

    protected override void getQueryConditions(skedQueryBuilder queryBuilder, queryModelBase inputModel) {
        queryModel query = (queryModel)inputModel;
        Date startDate, endDate;
        if (!string.isBlank(query.startDate)) {
            startDate = skedDateTimeUtils.getDateFromIsoString(query.startDate);
        }
        if (!string.isBlank(query.endDate)) {
            endDate = skedDateTimeUtils.getDateFromIsoString(query.endDate);
        }
        if (query.territoryKeys != NULL && !query.territoryKeys.isEmpty()) {
            queryBuilder.addCondition('sked_Territory_Key__c IN {0}', query.territoryKeys);
        }
        if (query.biomedCollectionOpIds != NULL && !query.biomedCollectionOpIds.isEmpty()) {
            queryBuilder.addCondition('sked_Region__r.sked_Biomed_Collection_Op_Center__c IN {0}', query.biomedCollectionOpIds);
        }
        if (query.regionIds != NULL && !query.regionIds.isEmpty()) {
            queryBuilder.addCondition('sked_Region__c IN {0}', query.regionIds);
        }
        if (query.resourceIds != NULL && !query.resourceIds.isEmpty()) {
            queryBuilder.addCondition('sked__Resource__c IN {0}', query.resourceIds);
        }
        if (query.activityTypes != NULL && !query.activityTypes.isEmpty()) {
            queryBuilder.addCondition('sked__Type__c IN {0}', query.activityTypes);
        }
        if (query.subTypes != NULL && !query.subTypes.isEmpty()) {
            queryBuilder.addCondition('sked_Subtype__c IN {0}', query.subTypes);
        }
        if (query.resourceCategories != NULL && !query.resourceCategories.isEmpty()) {
            queryBuilder.addCondition('sked__Resource__r.sked__Category__c IN {0}', query.resourceCategories);
        }
        if (query.isGroupActivity != NULL) {
            queryBuilder.addCondition('sked_Is_Group_Activity__c = {0}', query.isGroupActivity);
        }
        if (query.recurringScheduleIds != NULL && !query.recurringScheduleIds.isEmpty()) {
            queryBuilder.addCondition('sked_Recurring_Schedule__c IN {0}', query.recurringScheduleIds);
        }
        if (query.startTime != NULL && query.endTime != NULL) {
            queryBuilder.addCondition('sked__Start__c < {0}', query.endTime);
            queryBuilder.addCondition('sked__End__c > {0}', query.startTime);
        }
        else {
            if (query.startTime != NULL) {
                queryBuilder.addCondition('sked__Start__c >= {0}', query.startTime);
            }
            if (query.endTime != NULL) {
                queryBuilder.addCondition('sked__End__c <= {0}', query.endTime);
            }
        }
        if (startDate != NULL && endDate != NULL) {
            queryBuilder.addCondition('sked_Start_Date__c <= {0}', endDate);
            queryBuilder.addCondition('sked_End_Date__c >= {0}', startDate);
        }
        else {
            if (startDate != NULL) {
                queryBuilder.addCondition('sked_Start_Date__c >= {0}', startDate);
            }
            if (endDate != NULL) {
                queryBuilder.addCondition('sked_End_Date__c <= {0}', endDate);
            }
        }
        if (query.includes(skedSObjectType.ACTIVITY_RESOURCE)) {
            skedQueryBuilder activityResourceBuilder = query.getQueryBuilder('sked__Activity_Resource__c');
            activityResourceBuilder.orderClause = 'ORDER BY sked__Resource__r.Name ASC';
        }

        queryBuilder = query.getQueryBuilder('sked__Activity__c');
        queryBuilder.orderClause = 'ORDER BY sked__Start__c ASC';
    }
    
    /*********************************************************** Nested classes ***********************************************************/
    public class queryModel extends skedEventService.queryModel {
        public List<string> activityTypes;
        public List<string> biomedCollectionOpIds;
        public boolean isGroupActivity;
        public List<string> regionIds;
        public List<string> resourceCategories;
        public List<string> subTypes;
        public List<string> territoryKeys;
    }

}