unpackaged/main/default/objects/Site_Suitability_Checklist__c/Site_Suitability_Checklist__c.object-meta.xml
<CustomObject>
    <description>Created as part of HRP-8137</description>
    <label>Site Suitability Checklist</label>
    <nameField>
        <displayFormat>SSC - {000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Suitability Checklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Suitability_Checklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Site Suitability Checklist</relationshipLabel>
    <relationshipName>Site_Suitability_Checklist</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site_Suitability_Checklist__c/fields/UniqueName__c.field-meta.xml
<CustomField>
    <fullName>UniqueName__c</fullName>
    <description>Unique name of each field</description>
    <label>Unique Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Suitability_Checklist__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SiteSuitabilityController_Test.cls
/* Description : This test class covers SiteSuitabilityController 
 * Current Test Coverage : 90%
   
 * Modification Log 
 * Date					     Developer Name			     Comments
 * ***********************************************************************************************************************************************
 * 10/30/2024				  Priti Jana				Created for HRP-8137
 *************************************************************************************************************************************************
*/

@isTest
public class SiteSuitabilityController_Test {
    
    @testSetup static void prepareTestData() {
        BSF_TestDataSetup testDataSetup = new BSF_TestDataSetup(false);
        Map<string, sObject> mapTestData =  testDataSetup.createAndInsertCommonObjects(); 
        
        // insert Mobile Site
        sked__Location__c testMobileSite = (sked__Location__c)mapTestData.get('MOBILE_SITE');
        insert testMobileSite;
        
        //insert Site Suitability Checklist
        Site_Suitability_Checklist__c siteSuitabilityChecklist = new Site_Suitability_Checklist__c(
        	UniqueName__c = 'A1_Site_Characteristics_Checked',
        	Value__c = TRUE,
        	Site__c = testMobileSite.Id
        );
        insert siteSuitabilityChecklist;
    }
	
    static testMethod void testCheckEditAccess() {
        Test.startTest();
        Boolean hasEditAccess = SiteSuitabilityController.checkEditAccess();
        Assert.areEqual(TRUE, hasEditAccess);
        Test.stopTest();
    }
    
    static testMethod void testGetSiteSuitabilityChecklist() {
        Test.startTest();
        Id testSiteId = [SELECT Id FROM sked__Location__c LIMIT 1].Id;
        Map<String, Map<String, String>> map_mdtLabel_mdtFieldsMap = SiteSuitabilityController.getSiteSuitabilitychecklist((String) testSiteId);
        system.debug('map_mdtLabel_mdtFieldsMap '+map_mdtLabel_mdtFieldsMap);
        Assert.isNotNull(map_mdtLabel_mdtFieldsMap);
        Assert.isNotNull(map_mdtLabel_mdtFieldsMap.get('A1_Site_Characteristics_Checked'));
        Test.stopTest();
    }
}