force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Site</fullName>
            </value>
            <value>
                <fullName>Mobile Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Real_ID_Required__c.field-meta.xml
<CustomField>
    <fullName>sked_Real_ID_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HRP-14700</description>
    <label>Real ID Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sked__Tag__c/sked__Tag__c.object-meta.xml
<CustomObject>
    <description>string metadata to be associated  with any other object</description>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Tag__c/fields/sked__Type__c.field-meta.xml
<CustomField>
    <fullName>sked__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Asset Type</fullName>
            </value>
            <value>
                <fullName>Physical Location Type</fullName>
            </value>
            <value>
                <fullName>Drive Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/sked_Location_Tag__c/sked_Location_Tag__c.object-meta.xml
<CustomObject>
    <label>Location Tag</label>
    <nameField>
        <displayFormat>LT-{000000}</displayFormat>
        <label>Location Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Location_Tag__c/fields/sked_Location__c.field-meta.xml
<CustomField>
    <fullName>sked_Location__c</fullName>
    <label>Location</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Location Tags</relationshipLabel>
    <relationshipName>sked_Location_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Location_Tag__c/fields/sked_Tag__c.field-meta.xml
<CustomField>
    <fullName>sked_Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>sked__Tag__c</referenceTo>
    <relationshipLabel>Location Tags</relationshipLabel>
    <relationshipName>sked_Location_Tags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/skedLocationTagHandler.cls
/*------------------------------------------------------------
Author:        	Jack Kittridge
Company:       	Skedulo
Description:   	Trigger Handler for Location Tag custom object
Test Class:     skedLocationTagHandler_Test
------------------------------------------------------------*/
public class skedLocationTagHandler extends skedTriggerHub {
    public override void onAfterInsert() {
        if (!skedSetting.instance.Admin.migrationMode) {
            addToJobsAndDriveShifts(this.context.newRecords);
            updateRealIDFlagOnLocations(this.context.newRecords, true);
        }
    }

    public override void onAfterUpdate() {
        if (!skedSetting.instance.Admin.migrationMode) {
            updateTagsOnRelatedObjects(this.context.newRecords, (Map<Id, sked_Location_Tag__c>) this.context.oldMap);
        }
    }

    public override void onAfterDelete() {
        if (!skedSetting.instance.Admin.migrationMode) {
            removeTagsFromRelatedObjects(this.context.oldMap.values());
            updateRealIDFlagOnLocations(this.context.oldMap.values(), false);
        }
    }

    /*********************************************************** Privated Methods ***********************************************************/
    private void addToJobsAndDriveShifts(List<sked_Location_Tag__c> newRecords) {
        Database.executeBatch(new skedLocationTagInsertBatch(newRecords), 1);
    }

    private void updateTagsOnRelatedObjects(List<sked_Location_Tag__c> newRecords, Map<Id, sked_Location_Tag__c> oldMap) {
        Database.executeBatch(new skedLocationTagUpdateBatch(newRecords, oldMap), 1);
    }

    private void removeTagsFromRelatedObjects(List<sked_Location_Tag__c> oldValues) {
        Database.executeBatch(new skedLocationTagDeleteBatch(oldValues), 1);
    }

    private void updateRealIDFlagOnLocations(List<sked_Location_Tag__c> locationTags, Boolean isInsert) {        
        Set<Id> locationIdsToProcess = new Set<Id>();
        Map<Id, Boolean> locationIdToRealIDMap = new Map<Id, Boolean>();
        
        for (sked_Location_Tag__c locationTag : locationTags) {            
            if (locationTag.sked_Tag__c != null && getTagName(locationTag.sked_Tag__c) == skedConstants.TAG_REAL_ID) {
                locationIdsToProcess.add(locationTag.sked_Location__c);
                locationIdToRealIDMap.put(locationTag.sked_Location__c, isInsert);
            }
        }        
        List<sked__Location__c> locationsToUpdate = new List<sked__Location__c>();
        for (Id locationId : locationIdToRealIDMap.keySet()) {
            locationsToUpdate.add(new sked__Location__c(
                Id = locationId,
                sked_Real_ID_Required__c = locationIdToRealIDMap.get(locationId)
            ));
        }
        if (!locationsToUpdate.isEmpty()) {
            update locationsToUpdate;
        }
    }

    private String getTagName(Id tagId) {
        try{
            return [SELECT Name FROM sked__Tag__c WHERE Id = :tagId AND sked__Type__c = :skedConstants.TAG_TYPE_CERTIFICATION].Name;
        }
        catch (Exception e) {
            return '';
        }
    }
}