force-app/main/default/objects/sked__Location__c/sked__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Location__c/fields/sked__Region__c.field-meta.xml
<CustomField>
    <fullName>sked__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>sked_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <defaultValue>IF(
AND(MONTH(TODAY()) = 2, DAY(TODAY()) = 29),
DATE(YEAR(TODAY())+ 50, 3, 1),
DATE(YEAR(TODAY()) + 50, MONTH(TODAY()), DAY(TODAY()))
)</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Location__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sked__Region__c/sked__Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/sked__Region__c/fields/sked__Location__c.field-meta.xml
<CustomField>
    <fullName>sked__Location__c</fullName>
    <label>Location</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/sked_Site_Collection_Operation__c.object-meta.xml
<CustomObject>
    <label>Site Collection Operation</label>
    <nameField>
        <displayFormat>SCO-{000000}</displayFormat>
        <label>Site Collection Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Collection Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Collection_Operation__c.field-meta.xml
<CustomField>
    <fullName>sked_Collection_Operation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Operation</label>
    <referenceTo>Biomed_Collection_Op_Center__c</referenceTo>
    <relationshipLabel>Site Collection Operations</relationshipLabel>
    <relationshipName>sked_Site_Collection_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Region__c.field-meta.xml
<CustomField>
    <fullName>sked_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>sked__Region__c</referenceTo>
    <relationshipLabel>Site Collection Operations</relationshipLabel>
    <relationshipName>Site_Collection_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Site__c.field-meta.xml
<CustomField>
    <fullName>sked_Site__c</fullName>
    <label>Site</label>
    <referenceTo>sked__Location__c</referenceTo>
    <relationshipLabel>Site Collection Operations</relationshipLabel>
    <relationshipName>sked_Site_Collection_Operations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sked_Site_Collection_Operation__c/fields/sked_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sked_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/SiteUpdateBatch.cls
global class SiteUpdateBatch implements Schedulable, Database.Batchable<sObject>, Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        Date currDate = System.today();
        String today = String.valueOf(currDate);
        
        //Retrieve site collection operation records that cover the current day
        String query = 'SELECT Id, sked_region__c, sked_Collection_Operation__c, sked_Site__c FROM sked_Site_Collection_Operation__c WHERE sked_Start_Date__c <= ' + today + ' AND sked_End_Date__c >= ' + today;
        
        return Database.getQueryLocator(query);   
    }
    
	global void execute(Database.BatchableContext bc, List<sked_Site_Collection_Operation__c> lstSiteColOp) {
        
        system.debug('### inside execute: ' + lstSiteColOp.size());
        
        Map<Id,sked_Site_Collection_Operation__c> siteColOpMap = new Map<Id,sked_Site_Collection_Operation__c>();
		List<sked__Location__c> sitesToUpdateLst = new List<sked__Location__c>();
        
        if(lstSiteColOp != null && lstSiteColOp.size() > 0) {
			for(sked_Site_Collection_Operation__c scoRec : lstSiteColOp) {
				siteColOpMap.put(scoRec.sked_Site__c, scoRec);
			}
        }
        
		List<sked__Location__c> sitesLst = [SELECT id, sked_Collection_Operation__c, sked__Region__c FROM sked__Location__c WHERE id IN: siteColOpMap.keySet()];
        
        for(sked__Location__c loc : sitesLst){
			if(siteColOpMap.containsKey(loc.id)){
				if(siteColOpMap.get(loc.id).sked_Collection_Operation__c != null){
					loc.sked_Collection_Operation__c = siteColOpMap.get(loc.id).sked_Collection_Operation__c;
				}
				if(siteColOpMap.get(loc.id).sked_Region__c != null){
					loc.sked__Region__c = siteColOpMap.get(loc.id).sked_Region__c;
				}
				sitesToUpdateLst.add(loc);
			}
		}
        
		if(sitesToUpdateLst.size() > 0){
            Database.update(sitesToUpdateLst, false);
		}
    }

    global void finish(Database.BatchableContext bc) {
       
    }
    
	global void execute(SchedulableContext scon) {
		Database.executeBatch(new SiteUpdateBatch(), 200);
   }
}